-- ============================================================================
-- HANES MES Oracle Database Initial Schema
-- TypeORM Migration Script
-- ============================================================================

-- ============================================================================
-- 기준정보 그룹 (Master Data)
-- ============================================================================

-- 공통코드 테이블
CREATE TABLE COM_CODES (
  ID VARCHAR2(36) PRIMARY KEY,
  GROUP_CODE VARCHAR2(50) NOT NULL,
  DETAIL_CODE VARCHAR2(50) NOT NULL,
  PARENT_CODE VARCHAR2(50),
  CODE_NAME VARCHAR2(200) NOT NULL,
  CODE_DESC VARCHAR2(500),
  SORT_ORDER NUMBER DEFAULT 0,
  USE_YN VARCHAR2(1) DEFAULT 'Y',
  ATTR1 VARCHAR2(100),
  ATTR2 VARCHAR2(100),
  ATTR3 VARCHAR2(100),
  COMPANY VARCHAR2(50),
  PLANT_CD VARCHAR2(50),
  CREATED_BY VARCHAR2(50),
  UPDATED_BY VARCHAR2(50),
  CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  UPDATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  DELETED_AT TIMESTAMP WITH TIME ZONE,
  CONSTRAINT UK_COM_CODES UNIQUE (GROUP_CODE, DETAIL_CODE)
);

CREATE INDEX IDX_COM_CODES_GROUP ON COM_CODES(GROUP_CODE);
CREATE INDEX IDX_COM_CODES_PARENT ON COM_CODES(PARENT_CODE);

-- 공장/라인 테이블
CREATE TABLE PLANTS (
  ID VARCHAR2(36) PRIMARY KEY,
  PLANT_CODE VARCHAR2(50) NOT NULL,
  SHOP_CODE VARCHAR2(50),
  LINE_CODE VARCHAR2(50),
  CELL_CODE VARCHAR2(50),
  PLANT_NAME VARCHAR2(200) NOT NULL,
  PLANT_TYPE VARCHAR2(20),
  PARENT_ID VARCHAR2(36),
  SORT_ORDER NUMBER DEFAULT 0,
  USE_YN VARCHAR2(1) DEFAULT 'Y',
  COMPANY VARCHAR2(50),
  PLANT_CD VARCHAR2(50),
  CREATED_BY VARCHAR2(50),
  UPDATED_BY VARCHAR2(50),
  CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  UPDATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  DELETED_AT TIMESTAMP WITH TIME ZONE,
  CONSTRAINT UK_PLANTS UNIQUE (PLANT_CODE, SHOP_CODE, LINE_CODE, CELL_CODE),
  CONSTRAINT FK_PLANTS_PARENT FOREIGN KEY (PARENT_ID) REFERENCES PLANTS(ID)
);

CREATE INDEX IDX_PLANTS_TYPE ON PLANTS(PLANT_TYPE);
CREATE INDEX IDX_PLANTS_PARENT ON PLANTS(PARENT_ID);

-- 회사마스터 테이블
CREATE TABLE COMPANY_MASTERS (
  ID VARCHAR2(36) PRIMARY KEY,
  COMPANY_CODE VARCHAR2(50) UNIQUE NOT NULL,
  COMPANY_NAME VARCHAR2(200) NOT NULL,
  BIZ_NO VARCHAR2(20),
  CEO_NAME VARCHAR2(100),
  ADDRESS VARCHAR2(500),
  TEL VARCHAR2(50),
  FAX VARCHAR2(50),
  EMAIL VARCHAR2(100),
  REMARK VARCHAR2(1000),
  USE_YN VARCHAR2(1) DEFAULT 'Y',
  COMPANY VARCHAR2(50),
  PLANT_CD VARCHAR2(50),
  CREATED_BY VARCHAR2(50),
  UPDATED_BY VARCHAR2(50),
  CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  UPDATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  DELETED_AT TIMESTAMP WITH TIME ZONE
);

-- 품목마스터 테이블
CREATE TABLE PART_MASTERS (
  ID VARCHAR2(36) PRIMARY KEY,
  PART_CODE VARCHAR2(100) UNIQUE NOT NULL,
  PART_NAME VARCHAR2(200) NOT NULL,
  PART_NO VARCHAR2(100),
  CUST_PART_NO VARCHAR2(100),
  PART_TYPE VARCHAR2(20) NOT NULL,
  PRODUCT_TYPE VARCHAR2(50),
  SPEC VARCHAR2(500),
  REV VARCHAR2(20),
  UNIT VARCHAR2(20) DEFAULT 'EA',
  DRAW_NO VARCHAR2(100),
  CUSTOMER VARCHAR2(100),
  VENDOR VARCHAR2(100),
  LEAD_TIME NUMBER DEFAULT 0,
  SAFETY_STOCK NUMBER DEFAULT 0,
  LOT_UNIT_QTY NUMBER,
  BOX_QTY NUMBER DEFAULT 0,
  IQC_FLAG VARCHAR2(1) DEFAULT 'Y',
  TACT_TIME NUMBER DEFAULT 0,
  EXPIRY_DATE NUMBER DEFAULT 0,
  REMARKS VARCHAR2(1000),
  USE_YN VARCHAR2(1) DEFAULT 'Y',
  COMPANY VARCHAR2(50),
  PLANT_CD VARCHAR2(50),
  CREATED_BY VARCHAR2(50),
  UPDATED_BY VARCHAR2(50),
  CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  UPDATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  DELETED_AT TIMESTAMP WITH TIME ZONE
);

CREATE INDEX IDX_PART_MASTERS_TYPE ON PART_MASTERS(PART_TYPE);
CREATE INDEX IDX_PART_MASTERS_CUSTOMER ON PART_MASTERS(CUSTOMER);

-- BOM 테이블
CREATE TABLE BOM_MASTERS (
  ID VARCHAR2(36) PRIMARY KEY,
  PARENT_PART_ID VARCHAR2(36) NOT NULL,
  CHILD_PART_ID VARCHAR2(36) NOT NULL,
  QTY_PER NUMBER(10,4) NOT NULL,
  SEQ NUMBER DEFAULT 0,
  REVISION VARCHAR2(10) DEFAULT 'A',
  BOM_GRP VARCHAR2(50),
  OPER VARCHAR2(50),
  SIDE VARCHAR2(10),
  ECO_NO VARCHAR2(50),
  VALID_FROM DATE,
  VALID_TO DATE,
  REMARK VARCHAR2(1000),
  USE_YN VARCHAR2(1) DEFAULT 'Y',
  COMPANY VARCHAR2(50),
  PLANT_CD VARCHAR2(50),
  CREATED_BY VARCHAR2(50),
  UPDATED_BY VARCHAR2(50),
  CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  UPDATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  DELETED_AT TIMESTAMP WITH TIME ZONE,
  CONSTRAINT UK_BOM_MASTERS UNIQUE (PARENT_PART_ID, CHILD_PART_ID, REVISION)
);

CREATE INDEX IDX_BOM_PARENT ON BOM_MASTERS(PARENT_PART_ID);
CREATE INDEX IDX_BOM_CHILD ON BOM_MASTERS(CHILD_PART_ID);

-- 설비마스터 테이블
CREATE TABLE EQUIP_MASTERS (
  ID VARCHAR2(36) PRIMARY KEY,
  EQUIP_CODE VARCHAR2(50) UNIQUE NOT NULL,
  EQUIP_NAME VARCHAR2(200) NOT NULL,
  EQUIP_TYPE VARCHAR2(50),
  MODEL_NAME VARCHAR2(100),
  MAKER VARCHAR2(100),
  LINE_CODE VARCHAR2(50),
  IP_ADDRESS VARCHAR2(50),
  PORT NUMBER,
  COMM_TYPE VARCHAR2(20),
  COMM_CONFIG CLOB,
  INSTALL_DATE DATE,
  STATUS VARCHAR2(20) DEFAULT 'NORMAL',
  USE_YN VARCHAR2(1) DEFAULT 'Y',
  COMPANY VARCHAR2(50),
  PLANT_CD VARCHAR2(50),
  CREATED_BY VARCHAR2(50),
  UPDATED_BY VARCHAR2(50),
  CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  UPDATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  DELETED_AT TIMESTAMP WITH TIME ZONE
);

CREATE INDEX IDX_EQUIP_TYPE ON EQUIP_MASTERS(EQUIP_TYPE);
CREATE INDEX IDX_EQUIP_LINE ON EQUIP_MASTERS(LINE_CODE);

-- 작업지시 테이블
CREATE TABLE JOB_ORDERS (
  ID VARCHAR2(36) PRIMARY KEY,
  ORDER_NO VARCHAR2(50) UNIQUE NOT NULL,
  PART_ID VARCHAR2(36) NOT NULL,
  LINE_CODE VARCHAR2(50),
  PLAN_QTY NUMBER NOT NULL,
  GOOD_QTY NUMBER DEFAULT 0,
  DEFECT_QTY NUMBER DEFAULT 0,
  PLAN_DATE DATE,
  START_TIME TIMESTAMP WITH TIME ZONE,
  END_TIME TIMESTAMP WITH TIME ZONE,
  STATUS VARCHAR2(20) DEFAULT 'WAITING',
  COMPANY VARCHAR2(50),
  PLANT_CD VARCHAR2(50),
  CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  UPDATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  DELETED_AT TIMESTAMP WITH TIME ZONE
);

CREATE INDEX IDX_JOB_ORDERS_STATUS ON JOB_ORDERS(STATUS);

-- 창고 테이블
CREATE TABLE WAREHOUSES (
  ID VARCHAR2(36) PRIMARY KEY,
  WAREHOUSE_CODE VARCHAR2(50) UNIQUE NOT NULL,
  WAREHOUSE_NAME VARCHAR2(200) NOT NULL,
  WAREHOUSE_TYPE VARCHAR2(20) NOT NULL,
  USE_YN VARCHAR2(1) DEFAULT 'Y',
  COMPANY VARCHAR2(50),
  PLANT_CD VARCHAR2(50),
  CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  UPDATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  DELETED_AT TIMESTAMP WITH TIME ZONE
);

-- LOT 테이블
CREATE TABLE LOTS (
  ID VARCHAR2(36) PRIMARY KEY,
  LOT_NO VARCHAR2(50) UNIQUE NOT NULL,
  PART_ID VARCHAR2(36) NOT NULL,
  PART_TYPE VARCHAR2(20) NOT NULL,
  INIT_QTY NUMBER NOT NULL,
  CURRENT_QTY NUMBER NOT NULL,
  RECV_DATE DATE,
  STATUS VARCHAR2(20) DEFAULT 'NORMAL',
  COMPANY VARCHAR2(50),
  PLANT_CD VARCHAR2(50),
  CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  UPDATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  DELETED_AT TIMESTAMP WITH TIME ZONE
);

-- 재고 테이블
CREATE TABLE STOCKS (
  ID VARCHAR2(36) PRIMARY KEY,
  WAREHOUSE_ID VARCHAR2(36) NOT NULL,
  PART_ID VARCHAR2(36) NOT NULL,
  LOT_ID VARCHAR2(36),
  QTY NUMBER DEFAULT 0,
  RESERVED_QTY NUMBER DEFAULT 0,
  AVAILABLE_QTY NUMBER DEFAULT 0,
  LAST_TRANS_AT TIMESTAMP WITH TIME ZONE,
  COMPANY VARCHAR2(50),
  PLANT_CD VARCHAR2(50),
  CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  UPDATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT UK_STOCKS UNIQUE (WAREHOUSE_ID, PART_ID, LOT_ID)
);

-- 수불이력 테이블
CREATE TABLE STOCK_TRANSACTIONS (
  ID VARCHAR2(36) PRIMARY KEY,
  TRANS_NO VARCHAR2(50) UNIQUE NOT NULL,
  TRANS_TYPE VARCHAR2(50) NOT NULL,
  TRANS_DATE TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  PART_ID VARCHAR2(36) NOT NULL,
  QTY NUMBER NOT NULL,
  STATUS VARCHAR2(20) DEFAULT 'DONE',
  COMPANY VARCHAR2(50),
  PLANT_CD VARCHAR2(50),
  CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- 사용자 테이블
CREATE TABLE USERS (
  ID VARCHAR2(36) PRIMARY KEY,
  EMAIL VARCHAR2(200) UNIQUE NOT NULL,
  PASSWORD VARCHAR2(200) DEFAULT 'admin123',
  NAME VARCHAR2(100),
  ROLE VARCHAR2(20) DEFAULT 'OPERATOR',
  STATUS VARCHAR2(20) DEFAULT 'ACTIVE',
  CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  UPDATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  DELETED_AT TIMESTAMP WITH TIME ZONE
);

COMMIT;
