-- =============================================================================
-- Migration 002: itemType 통일 (WIP → SEMI_PRODUCT, FG → FINISHED)
-- 대상 테이블: PRODUCT_STOCKS, PRODUCT_TRANSACTIONS, PROD_PLANS
-- 실행 전 백업 권장 (SELECT INTO ... FROM ...)
-- =============================================================================

-- 1. PRODUCT_STOCKS
UPDATE PRODUCT_STOCKS SET ITEM_TYPE = 'SEMI_PRODUCT' WHERE ITEM_TYPE = 'WIP';
UPDATE PRODUCT_STOCKS SET ITEM_TYPE = 'FINISHED'     WHERE ITEM_TYPE = 'FG';

-- 2. PRODUCT_TRANSACTIONS
UPDATE PRODUCT_TRANSACTIONS SET ITEM_TYPE = 'SEMI_PRODUCT' WHERE ITEM_TYPE = 'WIP';
UPDATE PRODUCT_TRANSACTIONS SET ITEM_TYPE = 'FINISHED'     WHERE ITEM_TYPE = 'FG';

-- 3. PROD_PLANS
UPDATE PROD_PLANS SET ITEM_TYPE = 'SEMI_PRODUCT' WHERE ITEM_TYPE = 'WIP';
UPDATE PROD_PLANS SET ITEM_TYPE = 'FINISHED'     WHERE ITEM_TYPE = 'FG';

COMMIT;

-- 검증
SELECT 'PRODUCT_STOCKS'    AS tbl, ITEM_TYPE, COUNT(*) AS cnt FROM PRODUCT_STOCKS    GROUP BY ITEM_TYPE
UNION ALL
SELECT 'PRODUCT_TRANSACTIONS', ITEM_TYPE, COUNT(*)            FROM PRODUCT_TRANSACTIONS GROUP BY ITEM_TYPE
UNION ALL
SELECT 'PROD_PLANS',           ITEM_TYPE, COUNT(*)            FROM PROD_PLANS            GROUP BY ITEM_TYPE
ORDER BY 1, 2;
