-- Align IQC master tables with tenant-scoped entity keys.
-- Run after verifying there are no NULL COMPANY / PLANT_CD values in the IQC tables.

DECLARE
  v_count NUMBER;

  PROCEDURE assert_no_null_tenant(p_table_name IN VARCHAR2) IS
  BEGIN
    EXECUTE IMMEDIATE
      'SELECT COUNT(*) FROM ' || p_table_name || ' WHERE COMPANY IS NULL OR PLANT_CD IS NULL'
      INTO v_count;

    IF v_count > 0 THEN
      RAISE_APPLICATION_ERROR(-20001, p_table_name || ' has rows with NULL COMPANY or PLANT_CD');
    END IF;
  END;

  PROCEDURE assert_no_duplicate_key(p_table_name IN VARCHAR2, p_columns IN VARCHAR2) IS
  BEGIN
    EXECUTE IMMEDIATE
      'SELECT COUNT(*) FROM (SELECT ' || p_columns || ', COUNT(*) CNT FROM ' || p_table_name ||
      ' GROUP BY ' || p_columns || ' HAVING COUNT(*) > 1)'
      INTO v_count;

    IF v_count > 0 THEN
      RAISE_APPLICATION_ERROR(-20002, p_table_name || ' has duplicate tenant key: ' || p_columns);
    END IF;
  END;
BEGIN
  assert_no_null_tenant('IQC_ITEM_POOL');
  assert_no_null_tenant('IQC_ITEM_MASTERS');
  assert_no_null_tenant('IQC_GROUPS');
  assert_no_null_tenant('IQC_GROUP_ITEMS');
  assert_no_null_tenant('IQC_PART_LINKS');
  assert_no_null_tenant('IQC_PART_SPECS');
  assert_no_null_tenant('IQC_PART_SPEC_ITEMS');

  assert_no_duplicate_key('IQC_ITEM_POOL', 'COMPANY, PLANT_CD, INSP_ITEM_CODE');
  assert_no_duplicate_key('IQC_ITEM_MASTERS', 'COMPANY, PLANT_CD, ITEM_CODE, SEQ');
  assert_no_duplicate_key('IQC_GROUPS', 'COMPANY, PLANT_CD, GROUP_CODE');
  assert_no_duplicate_key('IQC_GROUP_ITEMS', 'COMPANY, PLANT_CD, GROUP_ID, INSP_ITEM_ID');
  assert_no_duplicate_key('IQC_PART_LINKS', 'COMPANY, PLANT_CD, ITEM_CODE, PARTNER_ID');
  assert_no_duplicate_key('IQC_PART_SPECS', 'COMPANY, PLANT_CD, ITEM_CODE');
  assert_no_duplicate_key('IQC_PART_SPEC_ITEMS', 'COMPANY, PLANT_CD, ITEM_CODE, SEQ');
END;
/

BEGIN
  FOR c IN (
    SELECT child.table_name, child.constraint_name
    FROM user_constraints child
    JOIN user_constraints parent
      ON parent.constraint_name = child.r_constraint_name
    WHERE child.constraint_type = 'R'
      AND parent.table_name IN ('IQC_ITEM_POOL', 'IQC_GROUPS', 'IQC_PART_SPECS')
      AND child.table_name IN ('IQC_GROUP_ITEMS', 'IQC_PART_LINKS', 'IQC_PART_SPEC_ITEMS')
  ) LOOP
    EXECUTE IMMEDIATE 'ALTER TABLE ' || c.table_name || ' DROP CONSTRAINT ' || c.constraint_name;
  END LOOP;
END;
/

BEGIN
  FOR c IN (
    SELECT table_name, constraint_name
    FROM user_constraints
    WHERE constraint_type = 'P'
      AND table_name IN (
        'IQC_ITEM_POOL',
        'IQC_ITEM_MASTERS',
        'IQC_GROUPS',
        'IQC_GROUP_ITEMS',
        'IQC_PART_LINKS',
        'IQC_PART_SPECS',
        'IQC_PART_SPEC_ITEMS'
      )
  ) LOOP
    EXECUTE IMMEDIATE 'ALTER TABLE ' || c.table_name || ' DROP CONSTRAINT ' || c.constraint_name;
  END LOOP;
END;
/

ALTER TABLE IQC_ITEM_POOL       MODIFY (COMPANY NOT NULL, PLANT_CD NOT NULL);
ALTER TABLE IQC_ITEM_MASTERS    MODIFY (COMPANY NOT NULL, PLANT_CD NOT NULL);
ALTER TABLE IQC_GROUPS          MODIFY (COMPANY NOT NULL, PLANT_CD NOT NULL);
ALTER TABLE IQC_GROUP_ITEMS     MODIFY (COMPANY NOT NULL, PLANT_CD NOT NULL);
ALTER TABLE IQC_PART_LINKS      MODIFY (COMPANY NOT NULL, PLANT_CD NOT NULL);
ALTER TABLE IQC_PART_SPECS      MODIFY (COMPANY NOT NULL, PLANT_CD NOT NULL);
ALTER TABLE IQC_PART_SPEC_ITEMS MODIFY (COMPANY NOT NULL, PLANT_CD NOT NULL);

ALTER TABLE IQC_ITEM_POOL
  ADD CONSTRAINT PK_IQC_ITEM_POOL PRIMARY KEY (COMPANY, PLANT_CD, INSP_ITEM_CODE);

ALTER TABLE IQC_ITEM_MASTERS
  ADD CONSTRAINT PK_IQC_ITEM_MASTERS PRIMARY KEY (COMPANY, PLANT_CD, ITEM_CODE, SEQ);

ALTER TABLE IQC_GROUPS
  ADD CONSTRAINT PK_IQC_GROUPS PRIMARY KEY (COMPANY, PLANT_CD, GROUP_CODE);

ALTER TABLE IQC_GROUP_ITEMS
  ADD CONSTRAINT PK_IQC_GROUP_ITEMS PRIMARY KEY (COMPANY, PLANT_CD, GROUP_ID, INSP_ITEM_ID);

ALTER TABLE IQC_PART_LINKS
  ADD CONSTRAINT PK_IQC_PART_LINKS PRIMARY KEY (COMPANY, PLANT_CD, ITEM_CODE, PARTNER_ID);

ALTER TABLE IQC_PART_SPECS
  ADD CONSTRAINT PK_IQC_PART_SPECS PRIMARY KEY (COMPANY, PLANT_CD, ITEM_CODE);

ALTER TABLE IQC_PART_SPEC_ITEMS
  ADD CONSTRAINT PK_IQC_PART_SPEC_ITEMS PRIMARY KEY (COMPANY, PLANT_CD, ITEM_CODE, SEQ);

ALTER TABLE IQC_GROUP_ITEMS
  ADD CONSTRAINT FK_IQC_GROUP_ITEMS_GROUP
  FOREIGN KEY (COMPANY, PLANT_CD, GROUP_ID)
  REFERENCES IQC_GROUPS (COMPANY, PLANT_CD, GROUP_CODE)
  ON DELETE CASCADE;

ALTER TABLE IQC_GROUP_ITEMS
  ADD CONSTRAINT FK_IQC_GROUP_ITEMS_POOL
  FOREIGN KEY (COMPANY, PLANT_CD, INSP_ITEM_ID)
  REFERENCES IQC_ITEM_POOL (COMPANY, PLANT_CD, INSP_ITEM_CODE);

ALTER TABLE IQC_PART_LINKS
  ADD CONSTRAINT FK_IQC_PART_LINKS_GROUP
  FOREIGN KEY (COMPANY, PLANT_CD, GROUP_ID)
  REFERENCES IQC_GROUPS (COMPANY, PLANT_CD, GROUP_CODE);

ALTER TABLE IQC_PART_SPEC_ITEMS
  ADD CONSTRAINT FK_IQC_PART_SPEC_ITEMS_SPEC
  FOREIGN KEY (COMPANY, PLANT_CD, ITEM_CODE)
  REFERENCES IQC_PART_SPECS (COMPANY, PLANT_CD, ITEM_CODE)
  ON DELETE CASCADE;

ALTER TABLE IQC_PART_SPEC_ITEMS
  ADD CONSTRAINT FK_IQC_PART_SPEC_ITEMS_POOL
  FOREIGN KEY (COMPANY, PLANT_CD, INSP_ITEM_CODE)
  REFERENCES IQC_ITEM_POOL (COMPANY, PLANT_CD, INSP_ITEM_CODE);

COMMIT;
