-- 2026-05-22: ROUTING_PROCESSES에 자주검사 설정 컬럼 추가
-- 실행 전 반드시 JSHANES 사이트에서 실행할 것

ALTER TABLE ROUTING_PROCESSES ADD QC_SELF_YN VARCHAR2(1) DEFAULT 'N';
ALTER TABLE ROUTING_PROCESSES ADD INSPECT_METHOD VARCHAR2(20) DEFAULT 'DIRECT';
ALTER TABLE ROUTING_PROCESSES ADD DESTRUCTIVE_YN VARCHAR2(1) DEFAULT 'N';
ALTER TABLE ROUTING_PROCESSES ADD SAMPLE_QTY NUMBER DEFAULT 1;

COMMENT ON COLUMN ROUTING_PROCESSES.QC_SELF_YN IS '자주검사 수행 여부 (Y/N)';
COMMENT ON COLUMN ROUTING_PROCESSES.INSPECT_METHOD IS '기본 검사방법 (DIRECT/DELEGATE)';
COMMENT ON COLUMN ROUTING_PROCESSES.DESTRUCTIVE_YN IS '파괴검사 여부 (Y/N)';
COMMENT ON COLUMN ROUTING_PROCESSES.SAMPLE_QTY IS '기본 샘플 수량';

COMMIT;
