-- 2026-05-21: 설비점검·자주검사 MEASURE/VISUAL 구분 컬럼 추가

-- 1. EQUIP_INSPECT_ITEM_MASTERS: 점검 유형, 측정단위, LSL/USL, 작업자QR
ALTER TABLE EQUIP_INSPECT_ITEM_MASTERS ADD (
  ITEM_TYPE      VARCHAR2(20)  DEFAULT 'VISUAL',
  UNIT           VARCHAR2(20),
  LSL_VALUE      NUMBER,
  USL_VALUE      NUMBER,
  WORKER_QR_CODE VARCHAR2(50)
);

-- 2. SELF_INSPECT_ITEMS: 검사 유형, 측정단위, LSL/USL, 시료수
ALTER TABLE SELF_INSPECT_ITEMS ADD (
  ITEM_TYPE    VARCHAR2(20)  DEFAULT 'VISUAL',
  UNIT         VARCHAR2(20),
  LSL_VALUE    NUMBER,
  USL_VALUE    NUMBER,
  SAMPLE_COUNT NUMBER        DEFAULT 1
);

-- 3. SELF_INSPECT_RESULTS: 시료번호, 측정값
ALTER TABLE SELF_INSPECT_RESULTS ADD (
  SAMPLE_NO     NUMBER  DEFAULT 1,
  MEASURE_VALUE NUMBER
);

COMMIT;
