-- 2026-05-21: 개선요청 등록 테이블 생성

CREATE TABLE IMPR_REQUESTS (
  IMPR_ID        VARCHAR2(36)   NOT NULL,
  PAGE_URL       VARCHAR2(500)  NOT NULL,
  ELEMENT_TEXT   VARCHAR2(1000),
  ELEMENT_TAG    VARCHAR2(100),
  DESCRIPTION    VARCHAR2(2000) NOT NULL,
  SCREENSHOT     CLOB,
  STATUS         VARCHAR2(20)   DEFAULT 'PENDING' NOT NULL,
  REQUESTER_ID   VARCHAR2(100)  NOT NULL,
  REQUESTER_NM   VARCHAR2(200),
  COMPANY        VARCHAR2(10)   NOT NULL,
  PLANT_CD       VARCHAR2(10)   NOT NULL,
  CREATED_AT     TIMESTAMP      DEFAULT SYSDATE NOT NULL,
  UPDATED_AT     TIMESTAMP      DEFAULT SYSDATE NOT NULL,
  CONSTRAINT PK_IMPR_REQUESTS PRIMARY KEY (IMPR_ID)
);

CREATE INDEX IDX_IMPR_REQUESTS_STATUS    ON IMPR_REQUESTS (STATUS);
CREATE INDEX IDX_IMPR_REQUESTS_COMPANY   ON IMPR_REQUESTS (COMPANY, PLANT_CD);
CREATE INDEX IDX_IMPR_REQUESTS_CREATED   ON IMPR_REQUESTS (CREATED_AT DESC);

COMMIT;
