-- Create equipment inspection item pool and link existing equipment assignments.
-- Safe to rerun: creates missing objects, seeds only unmatched pool rows, and backfills null ITEM_CODE values.

DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count FROM USER_TABLES WHERE TABLE_NAME = 'EQUIP_INSPECT_ITEM_POOL';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE '
      CREATE TABLE EQUIP_INSPECT_ITEM_POOL (
        COMPANY      VARCHAR2(50)  NOT NULL,
        PLANT_CD     VARCHAR2(50)  NOT NULL,
        ITEM_CODE    VARCHAR2(30)  NOT NULL,
        ITEM_NAME    VARCHAR2(200) NOT NULL,
        INSPECT_TYPE VARCHAR2(20)  NOT NULL,
        CRITERIA     VARCHAR2(500),
        CYCLE        VARCHAR2(20),
        USE_YN       VARCHAR2(1) DEFAULT ''Y'',
        REMARK       VARCHAR2(500),
        CREATED_BY   VARCHAR2(50),
        UPDATED_BY   VARCHAR2(50),
        CREATED_AT   TIMESTAMP DEFAULT SYSTIMESTAMP,
        UPDATED_AT   TIMESTAMP DEFAULT SYSTIMESTAMP,
        CONSTRAINT PK_EQUIP_INSPECT_ITEM_POOL PRIMARY KEY (COMPANY, PLANT_CD, ITEM_CODE)
      )';
  END IF;
END;
/

DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count FROM USER_SEQUENCES WHERE SEQUENCE_NAME = 'SEQ_EQUIP_INSPECT_ITEM_POOL';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'CREATE SEQUENCE SEQ_EQUIP_INSPECT_ITEM_POOL START WITH 1 INCREMENT BY 1 NOCACHE';
  END IF;
END;
/

DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count
  FROM USER_TAB_COLUMNS
  WHERE TABLE_NAME = 'EQUIP_INSPECT_ITEM_MASTERS'
    AND COLUMN_NAME = 'ITEM_CODE';

  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE EQUIP_INSPECT_ITEM_MASTERS ADD (ITEM_CODE VARCHAR2(30))';
  END IF;
END;
/

INSERT INTO EQUIP_INSPECT_ITEM_POOL (
  COMPANY, PLANT_CD, ITEM_CODE, ITEM_NAME, INSPECT_TYPE, CRITERIA, CYCLE, USE_YN, CREATED_AT, UPDATED_AT
)
SELECT
  src.COMPANY,
  src.PLANT_CD,
  'EIP-' || LPAD(SEQ_EQUIP_INSPECT_ITEM_POOL.NEXTVAL, 6, '0') AS ITEM_CODE,
  src.ITEM_NAME,
  src.INSPECT_TYPE,
  src.CRITERIA,
  src.CYCLE,
  NVL(src.USE_YN, 'Y') AS USE_YN,
  SYSTIMESTAMP,
  SYSTIMESTAMP
FROM (
  SELECT
    COMPANY,
    PLANT_CD,
    ITEM_NAME,
    INSPECT_TYPE,
    CRITERIA,
    CYCLE,
    MAX(USE_YN) AS USE_YN
  FROM EQUIP_INSPECT_ITEM_MASTERS
  GROUP BY COMPANY, PLANT_CD, ITEM_NAME, INSPECT_TYPE, CRITERIA, CYCLE
) src
WHERE NOT EXISTS (
  SELECT 1
  FROM EQUIP_INSPECT_ITEM_POOL pool
  WHERE pool.COMPANY = src.COMPANY
    AND pool.PLANT_CD = src.PLANT_CD
    AND pool.ITEM_NAME = src.ITEM_NAME
    AND pool.INSPECT_TYPE = src.INSPECT_TYPE
    AND NVL(pool.CRITERIA, CHR(0)) = NVL(src.CRITERIA, CHR(0))
    AND NVL(pool.CYCLE, CHR(0)) = NVL(src.CYCLE, CHR(0))
);

MERGE INTO EQUIP_INSPECT_ITEM_MASTERS target
USING (
  SELECT
    pool.COMPANY,
    pool.PLANT_CD,
    pool.ITEM_CODE,
    pool.ITEM_NAME,
    pool.INSPECT_TYPE,
    pool.CRITERIA,
    pool.CYCLE
  FROM EQUIP_INSPECT_ITEM_POOL pool
) src
ON (
  target.COMPANY = src.COMPANY
  AND target.PLANT_CD = src.PLANT_CD
  AND target.ITEM_NAME = src.ITEM_NAME
  AND target.INSPECT_TYPE = src.INSPECT_TYPE
  AND NVL(target.CRITERIA, CHR(0)) = NVL(src.CRITERIA, CHR(0))
  AND NVL(target.CYCLE, CHR(0)) = NVL(src.CYCLE, CHR(0))
)
WHEN MATCHED THEN UPDATE
  SET target.ITEM_CODE = src.ITEM_CODE
  WHERE target.ITEM_CODE IS NULL;

DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count
  FROM USER_CONSTRAINTS
  WHERE CONSTRAINT_NAME = 'FK_EQUIP_INSP_ITEM_POOL'
    AND TABLE_NAME = 'EQUIP_INSPECT_ITEM_MASTERS';

  IF v_count = 0 THEN
    EXECUTE IMMEDIATE '
      ALTER TABLE EQUIP_INSPECT_ITEM_MASTERS ADD CONSTRAINT FK_EQUIP_INSP_ITEM_POOL
      FOREIGN KEY (COMPANY, PLANT_CD, ITEM_CODE)
      REFERENCES EQUIP_INSPECT_ITEM_POOL (COMPANY, PLANT_CD, ITEM_CODE)';
  END IF;
END;
/

COMMENT ON TABLE EQUIP_INSPECT_ITEM_POOL IS '설비 점검항목 공통 Pool';
COMMENT ON COLUMN EQUIP_INSPECT_ITEM_POOL.ITEM_CODE IS '점검항목 Pool 코드';
COMMENT ON COLUMN EQUIP_INSPECT_ITEM_POOL.ITEM_NAME IS '점검항목명';
COMMENT ON COLUMN EQUIP_INSPECT_ITEM_POOL.INSPECT_TYPE IS '점검유형';
COMMENT ON COLUMN EQUIP_INSPECT_ITEM_POOL.CRITERIA IS '판정기준';
COMMENT ON COLUMN EQUIP_INSPECT_ITEM_POOL.CYCLE IS '점검주기';
COMMENT ON COLUMN EQUIP_INSPECT_ITEM_MASTERS.ITEM_CODE IS '설비별 할당 항목의 Pool 코드';

COMMIT;
