-- ============================================================================
-- Phase 3-C: PK가 없는 테이블에 새 PK 추가 + EQUIP_BOM_ITEMS 수정
-- ============================================================================

-- 1. BOM_MASTERS: PK 없음 → 추가
DECLARE
  v_cnt NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_cnt FROM user_constraints
  WHERE table_name = 'BOM_MASTERS' AND constraint_type = 'P';

  IF v_cnt = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE BOM_MASTERS ADD CONSTRAINT PK_BOM_MASTERS PRIMARY KEY (PARENT_ITEM_CODE, CHILD_ITEM_CODE, REVISION)';
    DBMS_OUTPUT.PUT_LINE('OK: BOM_MASTERS PK = (PARENT_ITEM_CODE, CHILD_ITEM_CODE, REVISION)');
  ELSE
    DBMS_OUTPUT.PUT_LINE('SKIP: BOM_MASTERS already has PK');
  END IF;
EXCEPTION
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('ERR: BOM_MASTERS → ' || SQLERRM);
END;
/

-- 2. MAT_STOCKS: PK 없음 → 추가
DECLARE
  v_cnt NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_cnt FROM user_constraints
  WHERE table_name = 'MAT_STOCKS' AND constraint_type = 'P';

  IF v_cnt = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE MAT_STOCKS ADD CONSTRAINT PK_MAT_STOCKS PRIMARY KEY (WAREHOUSE_CODE, ITEM_CODE, LOT_NO)';
    DBMS_OUTPUT.PUT_LINE('OK: MAT_STOCKS PK = (WAREHOUSE_CODE, ITEM_CODE, LOT_NO)');
  ELSE
    DBMS_OUTPUT.PUT_LINE('SKIP: MAT_STOCKS already has PK');
  END IF;
EXCEPTION
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('ERR: MAT_STOCKS → ' || SQLERRM);
END;
/

-- 3. PRODUCT_STOCKS: PK 없음 → 추가
DECLARE
  v_cnt NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_cnt FROM user_constraints
  WHERE table_name = 'PRODUCT_STOCKS' AND constraint_type = 'P';

  IF v_cnt = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE PRODUCT_STOCKS ADD CONSTRAINT PK_PRODUCT_STOCKS PRIMARY KEY (WAREHOUSE_CODE, ITEM_CODE, LOT_NO)';
    DBMS_OUTPUT.PUT_LINE('OK: PRODUCT_STOCKS PK = (WAREHOUSE_CODE, ITEM_CODE, LOT_NO)');
  ELSE
    DBMS_OUTPUT.PUT_LINE('SKIP: PRODUCT_STOCKS already has PK');
  END IF;
EXCEPTION
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('ERR: PRODUCT_STOCKS → ' || SQLERRM);
END;
/

-- 4. EQUIP_BOM_ITEMS: UQ 삭제 → PK 삭제 → 새 PK 추가
DECLARE
  v_cnt NUMBER;
  v_pk_col VARCHAR2(200);
BEGIN
  -- 현재 PK 컬럼 확인
  BEGIN
    SELECT ucc.column_name INTO v_pk_col
    FROM user_constraints uc
    JOIN user_cons_columns ucc ON uc.constraint_name = ucc.constraint_name
    WHERE uc.table_name = 'EQUIP_BOM_ITEMS' AND uc.constraint_type = 'P' AND ROWNUM = 1;
  EXCEPTION
    WHEN NO_DATA_FOUND THEN v_pk_col := 'NONE';
  END;

  IF v_pk_col = 'ID' THEN
    -- UQ 삭제
    EXECUTE IMMEDIATE 'ALTER TABLE EQUIP_BOM_ITEMS DROP CONSTRAINT UQ_8945b239c4dcd27235a2d1db387';
    DBMS_OUTPUT.PUT_LINE('  Dropped UQ');

    -- PK 삭제
    EXECUTE IMMEDIATE 'ALTER TABLE EQUIP_BOM_ITEMS DROP CONSTRAINT PK_28de1e100f9f98cf91d46750ad7';
    DBMS_OUTPUT.PUT_LINE('  Dropped PK');

    -- 새 PK 추가
    EXECUTE IMMEDIATE 'ALTER TABLE EQUIP_BOM_ITEMS ADD CONSTRAINT PK_EQUIP_BOM_ITEMS PRIMARY KEY (BOM_ITEM_CODE)';
    DBMS_OUTPUT.PUT_LINE('OK: EQUIP_BOM_ITEMS PK = BOM_ITEM_CODE');
  ELSIF v_pk_col = 'NONE' THEN
    EXECUTE IMMEDIATE 'ALTER TABLE EQUIP_BOM_ITEMS ADD CONSTRAINT PK_EQUIP_BOM_ITEMS PRIMARY KEY (BOM_ITEM_CODE)';
    DBMS_OUTPUT.PUT_LINE('OK: EQUIP_BOM_ITEMS PK = BOM_ITEM_CODE (no prev PK)');
  ELSE
    DBMS_OUTPUT.PUT_LINE('SKIP: EQUIP_BOM_ITEMS PK already = ' || v_pk_col);
  END IF;
EXCEPTION
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('ERR: EQUIP_BOM_ITEMS → ' || SQLERRM);
END;
/
