-- Phase 3-D: 최종 PK 수정 (PRODUCT_STOCKS + EQUIP_BOM_ITEMS)

-- 1. PRODUCT_STOCKS PK 추가
DECLARE
  v_cnt NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_cnt FROM user_constraints
  WHERE table_name = 'PRODUCT_STOCKS' AND constraint_type = 'P';

  IF v_cnt = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE PRODUCT_STOCKS MODIFY LOT_NO NOT NULL';
    EXECUTE IMMEDIATE 'ALTER TABLE PRODUCT_STOCKS ADD CONSTRAINT PK_PRODUCT_STOCKS PRIMARY KEY (WAREHOUSE_CODE, ITEM_CODE, LOT_NO)';
    DBMS_OUTPUT.PUT_LINE('OK: PRODUCT_STOCKS PK = (WAREHOUSE_CODE, ITEM_CODE, LOT_NO)');
  ELSE
    DBMS_OUTPUT.PUT_LINE('SKIP: PRODUCT_STOCKS already has PK');
  END IF;
EXCEPTION
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('ERR: PRODUCT_STOCKS → ' || SQLERRM);
END;
/

-- 2. EQUIP_BOM_ITEMS: 큰따옴표 필요 (TypeORM이 소문자로 생성)
DECLARE
  v_pk_col VARCHAR2(200);
BEGIN
  BEGIN
    SELECT ucc.column_name INTO v_pk_col
    FROM user_constraints uc
    JOIN user_cons_columns ucc ON uc.constraint_name = ucc.constraint_name
    WHERE uc.table_name = 'EQUIP_BOM_ITEMS' AND uc.constraint_type = 'P' AND ROWNUM = 1;
  EXCEPTION
    WHEN NO_DATA_FOUND THEN v_pk_col := 'NONE';
  END;

  IF v_pk_col = 'ID' THEN
    -- UQ/PK 이름에 소문자 포함 → 큰따옴표 사용
    EXECUTE IMMEDIATE 'ALTER TABLE EQUIP_BOM_ITEMS DROP CONSTRAINT "UQ_8945b239c4dcd27235a2d1db387"';
    DBMS_OUTPUT.PUT_LINE('  Dropped UQ');
    EXECUTE IMMEDIATE 'ALTER TABLE EQUIP_BOM_ITEMS DROP CONSTRAINT "PK_28de1e100f9f98cf91d46750ad7"';
    DBMS_OUTPUT.PUT_LINE('  Dropped PK');
    EXECUTE IMMEDIATE 'ALTER TABLE EQUIP_BOM_ITEMS ADD CONSTRAINT PK_EQUIP_BOM_ITEMS PRIMARY KEY (BOM_ITEM_CODE)';
    DBMS_OUTPUT.PUT_LINE('OK: EQUIP_BOM_ITEMS PK = BOM_ITEM_CODE');
  ELSIF v_pk_col = 'NONE' THEN
    EXECUTE IMMEDIATE 'ALTER TABLE EQUIP_BOM_ITEMS ADD CONSTRAINT PK_EQUIP_BOM_ITEMS PRIMARY KEY (BOM_ITEM_CODE)';
    DBMS_OUTPUT.PUT_LINE('OK: EQUIP_BOM_ITEMS PK = BOM_ITEM_CODE (no prev PK)');
  ELSE
    DBMS_OUTPUT.PUT_LINE('SKIP: EQUIP_BOM_ITEMS PK already = ' || v_pk_col);
  END IF;
EXCEPTION
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('ERR: EQUIP_BOM_ITEMS → ' || SQLERRM);
END;
/
