-- ============================================================
-- THN GAP Phase 1: 엔티티 컬럼 추가 (IQC_LOGS, WAREHOUSES)
-- 실행 대상: JSHANES 사이트
-- ============================================================

-- G4: IQC_LOGS 테이블 — 검사분류, 파괴검사 시료, 검사성적서 경로
ALTER TABLE IQC_LOGS ADD (INSPECT_CLASS VARCHAR2(10));
ALTER TABLE IQC_LOGS ADD (DESTRUCT_SAMPLE_QTY NUMBER(10));
ALTER TABLE IQC_LOGS ADD (CERT_FILE_PATH VARCHAR2(500));

COMMENT ON COLUMN IQC_LOGS.INSPECT_CLASS IS '검사분류: FULL(전수), SAMPLE(선별), NONE(무검사)';
COMMENT ON COLUMN IQC_LOGS.DESTRUCT_SAMPLE_QTY IS '파괴검사 시료 수량';
COMMENT ON COLUMN IQC_LOGS.CERT_FILE_PATH IS '검사성적서 파일 경로';

-- G9: WAREHOUSES 테이블 — 창고 그룹 (Phase 2에서 사용하지만 엔티티와 동기화)
ALTER TABLE WAREHOUSES ADD (WAREHOUSE_GROUP VARCHAR2(20));

COMMENT ON COLUMN WAREHOUSES.WAREHOUSE_GROUP IS '창고 그룹 (동일 그룹: 즉시이동 / 다른 그룹: 매니저 승인)';

-- G6: WAREHOUSES에 DEFECT 타입 불용창고 시드 데이터
INSERT INTO WAREHOUSES (WAREHOUSE_CODE, WAREHOUSE_NAME, WAREHOUSE_TYPE, WAREHOUSE_GROUP, IS_DEFAULT, USE_YN, CREATED_AT, UPDATED_AT)
SELECT 'WH-DEFECT', '불용창고', 'DEFECT', 'DEFECT', 'N', 'Y', SYSDATE, SYSDATE
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM WAREHOUSES WHERE WAREHOUSE_CODE = 'WH-DEFECT');

-- G4/G6: SYS_CONFIGS 사이트설정 시드 데이터
INSERT INTO SYS_CONFIGS (CONFIG_KEY, CONFIG_GROUP, CONFIG_VALUE, CONFIG_TYPE, LABEL, DESCRIPTION, OPTIONS, SORT_ORDER, IS_ACTIVE, CREATED_AT, UPDATED_AT)
SELECT 'IQC_SAMPLE_ISSUE_MODE', 'MATERIAL', 'LOSS_ALLOW', 'SELECT', 'IQC 파괴검사 시료 출고방식',
       'AUTO_ISSUE: 합격시 자동출고 / LOSS_ALLOW: LOSS 허용범위 관리',
       '[{"label":"자동출고","value":"AUTO_ISSUE"},{"label":"LOSS허용","value":"LOSS_ALLOW"}]',
       10, 'Y', SYSDATE, SYSDATE
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM SYS_CONFIGS WHERE CONFIG_KEY = 'IQC_SAMPLE_ISSUE_MODE');

INSERT INTO SYS_CONFIGS (CONFIG_KEY, CONFIG_GROUP, CONFIG_VALUE, CONFIG_TYPE, LABEL, DESCRIPTION, OPTIONS, SORT_ORDER, IS_ACTIVE, CREATED_AT, UPDATED_AT)
SELECT 'RETURN_MODE', 'MATERIAL', 'CANCEL', 'SELECT', '불출자재 반환방식',
       'RETURN: 자재창고 반납 / CANCEL: 불출취소',
       '[{"label":"반납","value":"RETURN"},{"label":"불출취소","value":"CANCEL"}]',
       11, 'Y', SYSDATE, SYSDATE
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM SYS_CONFIGS WHERE CONFIG_KEY = 'RETURN_MODE');

INSERT INTO SYS_CONFIGS (CONFIG_KEY, CONFIG_GROUP, CONFIG_VALUE, CONFIG_TYPE, LABEL, DESCRIPTION, SORT_ORDER, IS_ACTIVE, CREATED_AT, UPDATED_AT)
SELECT 'WMS_ENABLED', 'MATERIAL', 'N', 'BOOLEAN', 'WMS 연동 활성화',
       'Y: WMS에서 불출자재 이관 / N: MES 자체 관리',
       12, 'Y', SYSDATE, SYSDATE
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM SYS_CONFIGS WHERE CONFIG_KEY = 'WMS_ENABLED');

INSERT INTO SYS_CONFIGS (CONFIG_KEY, CONFIG_GROUP, CONFIG_VALUE, CONFIG_TYPE, LABEL, DESCRIPTION, SORT_ORDER, IS_ACTIVE, CREATED_AT, UPDATED_AT)
SELECT 'ERP_EXPORT_ENABLED', 'MATERIAL', 'N', 'BOOLEAN', 'ERP 실적전송 활성화',
       'Y: 입고/반품/출고/보정 실적 ERP 전송 / N: 비활성',
       13, 'Y', SYSDATE, SYSDATE
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM SYS_CONFIGS WHERE CONFIG_KEY = 'ERP_EXPORT_ENABLED');

COMMIT;
