-- ============================================================
-- THN GAP Phase 2: 엔티티 컬럼 추가
-- G9: STOCK_TRANSACTIONS에 승인 컬럼 추가 (별도 테이블 없음)
-- G11: IQC_LOGS inspectType='RETEST'로 재검 (별도 테이블 없음)
-- ============================================================

-- G8: MAT_ISSUES — 불출자/수령인
ALTER TABLE MAT_ISSUES ADD (ISSUER_ID VARCHAR2(20));
ALTER TABLE MAT_ISSUES ADD (ISSUER_NAME VARCHAR2(50));
ALTER TABLE MAT_ISSUES ADD (RECEIVER_ID VARCHAR2(20));
ALTER TABLE MAT_ISSUES ADD (RECEIVER_NAME VARCHAR2(50));

COMMENT ON COLUMN MAT_ISSUES.ISSUER_ID IS '불출자 사번 (바코드 스캔)';
COMMENT ON COLUMN MAT_ISSUES.ISSUER_NAME IS '불출자 이름';
COMMENT ON COLUMN MAT_ISSUES.RECEIVER_ID IS '수령인 사번 (바코드 스캔)';
COMMENT ON COLUMN MAT_ISSUES.RECEIVER_NAME IS '수령인 이름';

-- G7: MAT_ISSUE_REQUEST_ITEMS — BOM 소요량
ALTER TABLE MAT_ISSUE_REQUEST_ITEMS ADD (BOM_REQ_QTY NUMBER(12,3));
ALTER TABLE MAT_ISSUE_REQUEST_ITEMS ADD (PREV_ISSUE_QTY NUMBER(12,3));
ALTER TABLE MAT_ISSUE_REQUEST_ITEMS ADD (FLOOR_STOCK_QTY NUMBER(12,3));

COMMENT ON COLUMN MAT_ISSUE_REQUEST_ITEMS.BOM_REQ_QTY IS 'BOM 소요량 (= BOM * 생산수량)';
COMMENT ON COLUMN MAT_ISSUE_REQUEST_ITEMS.PREV_ISSUE_QTY IS '기 불출수량';
COMMENT ON COLUMN MAT_ISSUE_REQUEST_ITEMS.FLOOR_STOCK_QTY IS '현장재고';

-- Minor: PHYSICAL_INV_COUNT_DETAILS — 실제 로케이션
ALTER TABLE PHYSICAL_INV_COUNT_DETAILS ADD (ACTUAL_LOCATION VARCHAR2(50));

COMMENT ON COLUMN PHYSICAL_INV_COUNT_DETAILS.ACTUAL_LOCATION IS '실사 시 확인된 실제 로케이션 (위치 보정용)';

-- G9: STOCK_TRANSACTIONS — 승인 워크플로우 (status='PENDING_APPROVAL' 활용)
ALTER TABLE STOCK_TRANSACTIONS ADD (APPROVER_ID VARCHAR2(20));
ALTER TABLE STOCK_TRANSACTIONS ADD (APPROVED_AT TIMESTAMP);

COMMENT ON COLUMN STOCK_TRANSACTIONS.APPROVER_ID IS '승인자 ID (기타출고 승인 워크플로우)';
COMMENT ON COLUMN STOCK_TRANSACTIONS.APPROVED_AT IS '승인 일시';

COMMIT;
