-- ============================================================
-- PDA 앱 관련 ComCode 그룹 추가
-- 대상: ADJ_REASON (보정 사유), INSPECT_NG_REASON (설비점검 NG 사유)
-- COM_CODES 테이블: GROUP_CODE + DETAIL_CODE (복합 PK)
-- COMPANY='40', PLANT_CD='1000'
-- ============================================================

-- ADJ_REASON (보정 사유) - PDA 재고 보정 시 사유 선택
INSERT INTO COM_CODES (GROUP_CODE, DETAIL_CODE, CODE_NAME, SORT_ORDER, USE_YN, COMPANY, PLANT_CD)
SELECT 'ADJ_REASON', 'DAMAGE', '파손', 1, 'Y', '40', '1000' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM COM_CODES WHERE GROUP_CODE = 'ADJ_REASON' AND DETAIL_CODE = 'DAMAGE');

INSERT INTO COM_CODES (GROUP_CODE, DETAIL_CODE, CODE_NAME, SORT_ORDER, USE_YN, COMPANY, PLANT_CD)
SELECT 'ADJ_REASON', 'LOST', '분실', 2, 'Y', '40', '1000' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM COM_CODES WHERE GROUP_CODE = 'ADJ_REASON' AND DETAIL_CODE = 'LOST');

INSERT INTO COM_CODES (GROUP_CODE, DETAIL_CODE, CODE_NAME, SORT_ORDER, USE_YN, COMPANY, PLANT_CD)
SELECT 'ADJ_REASON', 'MEASURE_ERR', '계량오차', 3, 'Y', '40', '1000' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM COM_CODES WHERE GROUP_CODE = 'ADJ_REASON' AND DETAIL_CODE = 'MEASURE_ERR');

INSERT INTO COM_CODES (GROUP_CODE, DETAIL_CODE, CODE_NAME, SORT_ORDER, USE_YN, COMPANY, PLANT_CD)
SELECT 'ADJ_REASON', 'ETC', '기타', 99, 'Y', '40', '1000' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM COM_CODES WHERE GROUP_CODE = 'ADJ_REASON' AND DETAIL_CODE = 'ETC');

-- INSPECT_NG_REASON (설비점검 NG 사유) - PDA 설비점검 NG 판정 시 사유 선택
INSERT INTO COM_CODES (GROUP_CODE, DETAIL_CODE, CODE_NAME, SORT_ORDER, USE_YN, COMPANY, PLANT_CD)
SELECT 'INSPECT_NG_REASON', 'DAMAGE', '파손', 1, 'Y', '40', '1000' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM COM_CODES WHERE GROUP_CODE = 'INSPECT_NG_REASON' AND DETAIL_CODE = 'DAMAGE');

INSERT INTO COM_CODES (GROUP_CODE, DETAIL_CODE, CODE_NAME, SORT_ORDER, USE_YN, COMPANY, PLANT_CD)
SELECT 'INSPECT_NG_REASON', 'DETACH', '탈락', 2, 'Y', '40', '1000' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM COM_CODES WHERE GROUP_CODE = 'INSPECT_NG_REASON' AND DETAIL_CODE = 'DETACH');

INSERT INTO COM_CODES (GROUP_CODE, DETAIL_CODE, CODE_NAME, SORT_ORDER, USE_YN, COMPANY, PLANT_CD)
SELECT 'INSPECT_NG_REASON', 'AGING', '노후화', 3, 'Y', '40', '1000' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM COM_CODES WHERE GROUP_CODE = 'INSPECT_NG_REASON' AND DETAIL_CODE = 'AGING');

INSERT INTO COM_CODES (GROUP_CODE, DETAIL_CODE, CODE_NAME, SORT_ORDER, USE_YN, COMPANY, PLANT_CD)
SELECT 'INSPECT_NG_REASON', 'ETC', '기타', 99, 'Y', '40', '1000' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM COM_CODES WHERE GROUP_CODE = 'INSPECT_NG_REASON' AND DETAIL_CODE = 'ETC');

COMMIT;
