-- JOB_ORDERS 테이블에 ROUTING_CODE 컬럼 추가
ALTER TABLE JOB_ORDERS ADD ROUTING_CODE VARCHAR2(50);

-- 인덱스 추가
CREATE INDEX IDX_JOB_ORDERS_ROUTING ON JOB_ORDERS(ROUTING_CODE);

-- 기존 데이터 마이그레이션: itemCode 기반으로 라우팅 코드 매핑
UPDATE JOB_ORDERS jo
SET jo.ROUTING_CODE = (
  SELECT rg.ROUTING_CODE
  FROM ROUTING_GROUPS rg
  WHERE rg.ITEM_CODE = jo.ITEM_CODE
    AND rg.USE_YN = 'Y'
    AND ROWNUM = 1
)
WHERE jo.ROUTING_CODE IS NULL;

COMMIT;
