-- ============================================================
-- IATF 16949 관련 ComCode 그룹 추가
-- 대상: CHANGE_TYPE, CHANGE_STATUS, CHANGE_PRIORITY,
--       CAPA_TYPE, CAPA_STATUS, CAPA_SOURCE_TYPE, CAPA_ACTION_STATUS,
--       COMPLAINT_TYPE, COMPLAINT_STATUS, COMPLAINT_URGENCY,
--       FAI_TRIGGER_TYPE, FAI_STATUS, FAI_RESULT
-- COM_CODES 테이블: GROUP_CODE + DETAIL_CODE (복합 PK)
-- COMPANY='40', PLANT_CD='1000'
-- ============================================================

-- CHANGE_TYPE (4M 변경 유형)
INSERT INTO COM_CODES (GROUP_CODE,DETAIL_CODE,CODE_NAME,SORT_ORDER,USE_YN,COMPANY,PLANT_CD)
SELECT 'CHANGE_TYPE','MAN','인력변경',1,'Y','40','1000' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM COM_CODES WHERE GROUP_CODE='CHANGE_TYPE' AND DETAIL_CODE='MAN');

INSERT INTO COM_CODES (GROUP_CODE,DETAIL_CODE,CODE_NAME,SORT_ORDER,USE_YN,COMPANY,PLANT_CD)
SELECT 'CHANGE_TYPE','MACHINE','설비변경',2,'Y','40','1000' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM COM_CODES WHERE GROUP_CODE='CHANGE_TYPE' AND DETAIL_CODE='MACHINE');

INSERT INTO COM_CODES (GROUP_CODE,DETAIL_CODE,CODE_NAME,SORT_ORDER,USE_YN,COMPANY,PLANT_CD)
SELECT 'CHANGE_TYPE','MATERIAL','자재변경',3,'Y','40','1000' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM COM_CODES WHERE GROUP_CODE='CHANGE_TYPE' AND DETAIL_CODE='MATERIAL');

INSERT INTO COM_CODES (GROUP_CODE,DETAIL_CODE,CODE_NAME,SORT_ORDER,USE_YN,COMPANY,PLANT_CD)
SELECT 'CHANGE_TYPE','METHOD','방법변경',4,'Y','40','1000' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM COM_CODES WHERE GROUP_CODE='CHANGE_TYPE' AND DETAIL_CODE='METHOD');

-- CHANGE_STATUS (변경관리 상태)
INSERT INTO COM_CODES (GROUP_CODE,DETAIL_CODE,CODE_NAME,SORT_ORDER,USE_YN,COMPANY,PLANT_CD)
SELECT 'CHANGE_STATUS','DRAFT','초안',1,'Y','40','1000' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM COM_CODES WHERE GROUP_CODE='CHANGE_STATUS' AND DETAIL_CODE='DRAFT');

INSERT INTO COM_CODES (GROUP_CODE,DETAIL_CODE,CODE_NAME,SORT_ORDER,USE_YN,COMPANY,PLANT_CD)
SELECT 'CHANGE_STATUS','SUBMITTED','제출',2,'Y','40','1000' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM COM_CODES WHERE GROUP_CODE='CHANGE_STATUS' AND DETAIL_CODE='SUBMITTED');

INSERT INTO COM_CODES (GROUP_CODE,DETAIL_CODE,CODE_NAME,SORT_ORDER,USE_YN,COMPANY,PLANT_CD)
SELECT 'CHANGE_STATUS','REVIEWING','검토중',3,'Y','40','1000' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM COM_CODES WHERE GROUP_CODE='CHANGE_STATUS' AND DETAIL_CODE='REVIEWING');

INSERT INTO COM_CODES (GROUP_CODE,DETAIL_CODE,CODE_NAME,SORT_ORDER,USE_YN,COMPANY,PLANT_CD)
SELECT 'CHANGE_STATUS','APPROVED','승인',4,'Y','40','1000' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM COM_CODES WHERE GROUP_CODE='CHANGE_STATUS' AND DETAIL_CODE='APPROVED');

INSERT INTO COM_CODES (GROUP_CODE,DETAIL_CODE,CODE_NAME,SORT_ORDER,USE_YN,COMPANY,PLANT_CD)
SELECT 'CHANGE_STATUS','REJECTED','반려',5,'Y','40','1000' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM COM_CODES WHERE GROUP_CODE='CHANGE_STATUS' AND DETAIL_CODE='REJECTED');

INSERT INTO COM_CODES (GROUP_CODE,DETAIL_CODE,CODE_NAME,SORT_ORDER,USE_YN,COMPANY,PLANT_CD)
SELECT 'CHANGE_STATUS','IN_PROGRESS','진행중',6,'Y','40','1000' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM COM_CODES WHERE GROUP_CODE='CHANGE_STATUS' AND DETAIL_CODE='IN_PROGRESS');

INSERT INTO COM_CODES (GROUP_CODE,DETAIL_CODE,CODE_NAME,SORT_ORDER,USE_YN,COMPANY,PLANT_CD)
SELECT 'CHANGE_STATUS','COMPLETED','완료',7,'Y','40','1000' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM COM_CODES WHERE GROUP_CODE='CHANGE_STATUS' AND DETAIL_CODE='COMPLETED');

INSERT INTO COM_CODES (GROUP_CODE,DETAIL_CODE,CODE_NAME,SORT_ORDER,USE_YN,COMPANY,PLANT_CD)
SELECT 'CHANGE_STATUS','CLOSED','종결',8,'Y','40','1000' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM COM_CODES WHERE GROUP_CODE='CHANGE_STATUS' AND DETAIL_CODE='CLOSED');

-- CHANGE_PRIORITY (변경 우선순위)
INSERT INTO COM_CODES (GROUP_CODE,DETAIL_CODE,CODE_NAME,SORT_ORDER,USE_YN,COMPANY,PLANT_CD)
SELECT 'CHANGE_PRIORITY','HIGH','긴급',1,'Y','40','1000' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM COM_CODES WHERE GROUP_CODE='CHANGE_PRIORITY' AND DETAIL_CODE='HIGH');

INSERT INTO COM_CODES (GROUP_CODE,DETAIL_CODE,CODE_NAME,SORT_ORDER,USE_YN,COMPANY,PLANT_CD)
SELECT 'CHANGE_PRIORITY','MEDIUM','보통',2,'Y','40','1000' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM COM_CODES WHERE GROUP_CODE='CHANGE_PRIORITY' AND DETAIL_CODE='MEDIUM');

INSERT INTO COM_CODES (GROUP_CODE,DETAIL_CODE,CODE_NAME,SORT_ORDER,USE_YN,COMPANY,PLANT_CD)
SELECT 'CHANGE_PRIORITY','LOW','낮음',3,'Y','40','1000' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM COM_CODES WHERE GROUP_CODE='CHANGE_PRIORITY' AND DETAIL_CODE='LOW');

-- CAPA_TYPE (시정/예방조치 유형)
INSERT INTO COM_CODES (GROUP_CODE,DETAIL_CODE,CODE_NAME,SORT_ORDER,USE_YN,COMPANY,PLANT_CD)
SELECT 'CAPA_TYPE','CORRECTIVE','시정조치',1,'Y','40','1000' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM COM_CODES WHERE GROUP_CODE='CAPA_TYPE' AND DETAIL_CODE='CORRECTIVE');

INSERT INTO COM_CODES (GROUP_CODE,DETAIL_CODE,CODE_NAME,SORT_ORDER,USE_YN,COMPANY,PLANT_CD)
SELECT 'CAPA_TYPE','PREVENTIVE','예방조치',2,'Y','40','1000' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM COM_CODES WHERE GROUP_CODE='CAPA_TYPE' AND DETAIL_CODE='PREVENTIVE');

-- CAPA_STATUS (CAPA 상태)
INSERT INTO COM_CODES (GROUP_CODE,DETAIL_CODE,CODE_NAME,SORT_ORDER,USE_YN,COMPANY,PLANT_CD)
SELECT 'CAPA_STATUS','OPEN','접수',1,'Y','40','1000' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM COM_CODES WHERE GROUP_CODE='CAPA_STATUS' AND DETAIL_CODE='OPEN');

INSERT INTO COM_CODES (GROUP_CODE,DETAIL_CODE,CODE_NAME,SORT_ORDER,USE_YN,COMPANY,PLANT_CD)
SELECT 'CAPA_STATUS','ANALYZING','원인분석중',2,'Y','40','1000' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM COM_CODES WHERE GROUP_CODE='CAPA_STATUS' AND DETAIL_CODE='ANALYZING');

INSERT INTO COM_CODES (GROUP_CODE,DETAIL_CODE,CODE_NAME,SORT_ORDER,USE_YN,COMPANY,PLANT_CD)
SELECT 'CAPA_STATUS','ACTION_PLANNED','조치계획',3,'Y','40','1000' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM COM_CODES WHERE GROUP_CODE='CAPA_STATUS' AND DETAIL_CODE='ACTION_PLANNED');

INSERT INTO COM_CODES (GROUP_CODE,DETAIL_CODE,CODE_NAME,SORT_ORDER,USE_YN,COMPANY,PLANT_CD)
SELECT 'CAPA_STATUS','IN_PROGRESS','조치진행',4,'Y','40','1000' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM COM_CODES WHERE GROUP_CODE='CAPA_STATUS' AND DETAIL_CODE='IN_PROGRESS');

INSERT INTO COM_CODES (GROUP_CODE,DETAIL_CODE,CODE_NAME,SORT_ORDER,USE_YN,COMPANY,PLANT_CD)
SELECT 'CAPA_STATUS','VERIFYING','검증중',5,'Y','40','1000' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM COM_CODES WHERE GROUP_CODE='CAPA_STATUS' AND DETAIL_CODE='VERIFYING');

INSERT INTO COM_CODES (GROUP_CODE,DETAIL_CODE,CODE_NAME,SORT_ORDER,USE_YN,COMPANY,PLANT_CD)
SELECT 'CAPA_STATUS','CLOSED','종결',6,'Y','40','1000' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM COM_CODES WHERE GROUP_CODE='CAPA_STATUS' AND DETAIL_CODE='CLOSED');

-- CAPA_SOURCE_TYPE (CAPA 발생원)
INSERT INTO COM_CODES (GROUP_CODE,DETAIL_CODE,CODE_NAME,SORT_ORDER,USE_YN,COMPANY,PLANT_CD)
SELECT 'CAPA_SOURCE_TYPE','DEFECT','불량',1,'Y','40','1000' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM COM_CODES WHERE GROUP_CODE='CAPA_SOURCE_TYPE' AND DETAIL_CODE='DEFECT');

INSERT INTO COM_CODES (GROUP_CODE,DETAIL_CODE,CODE_NAME,SORT_ORDER,USE_YN,COMPANY,PLANT_CD)
SELECT 'CAPA_SOURCE_TYPE','COMPLAINT','고객클레임',2,'Y','40','1000' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM COM_CODES WHERE GROUP_CODE='CAPA_SOURCE_TYPE' AND DETAIL_CODE='COMPLAINT');

INSERT INTO COM_CODES (GROUP_CODE,DETAIL_CODE,CODE_NAME,SORT_ORDER,USE_YN,COMPANY,PLANT_CD)
SELECT 'CAPA_SOURCE_TYPE','AUDIT','감사',3,'Y','40','1000' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM COM_CODES WHERE GROUP_CODE='CAPA_SOURCE_TYPE' AND DETAIL_CODE='AUDIT');

INSERT INTO COM_CODES (GROUP_CODE,DETAIL_CODE,CODE_NAME,SORT_ORDER,USE_YN,COMPANY,PLANT_CD)
SELECT 'CAPA_SOURCE_TYPE','REWORK','재작업',4,'Y','40','1000' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM COM_CODES WHERE GROUP_CODE='CAPA_SOURCE_TYPE' AND DETAIL_CODE='REWORK');

-- CAPA_ACTION_STATUS (CAPA 조치항목 상태)
INSERT INTO COM_CODES (GROUP_CODE,DETAIL_CODE,CODE_NAME,SORT_ORDER,USE_YN,COMPANY,PLANT_CD)
SELECT 'CAPA_ACTION_STATUS','PENDING','대기',1,'Y','40','1000' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM COM_CODES WHERE GROUP_CODE='CAPA_ACTION_STATUS' AND DETAIL_CODE='PENDING');

INSERT INTO COM_CODES (GROUP_CODE,DETAIL_CODE,CODE_NAME,SORT_ORDER,USE_YN,COMPANY,PLANT_CD)
SELECT 'CAPA_ACTION_STATUS','IN_PROGRESS','진행중',2,'Y','40','1000' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM COM_CODES WHERE GROUP_CODE='CAPA_ACTION_STATUS' AND DETAIL_CODE='IN_PROGRESS');

INSERT INTO COM_CODES (GROUP_CODE,DETAIL_CODE,CODE_NAME,SORT_ORDER,USE_YN,COMPANY,PLANT_CD)
SELECT 'CAPA_ACTION_STATUS','DONE','완료',3,'Y','40','1000' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM COM_CODES WHERE GROUP_CODE='CAPA_ACTION_STATUS' AND DETAIL_CODE='DONE');

-- COMPLAINT_TYPE (고객불만 유형)
INSERT INTO COM_CODES (GROUP_CODE,DETAIL_CODE,CODE_NAME,SORT_ORDER,USE_YN,COMPANY,PLANT_CD)
SELECT 'COMPLAINT_TYPE','QUALITY','품질불량',1,'Y','40','1000' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM COM_CODES WHERE GROUP_CODE='COMPLAINT_TYPE' AND DETAIL_CODE='QUALITY');

INSERT INTO COM_CODES (GROUP_CODE,DETAIL_CODE,CODE_NAME,SORT_ORDER,USE_YN,COMPANY,PLANT_CD)
SELECT 'COMPLAINT_TYPE','DELIVERY','납기지연',2,'Y','40','1000' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM COM_CODES WHERE GROUP_CODE='COMPLAINT_TYPE' AND DETAIL_CODE='DELIVERY');

INSERT INTO COM_CODES (GROUP_CODE,DETAIL_CODE,CODE_NAME,SORT_ORDER,USE_YN,COMPANY,PLANT_CD)
SELECT 'COMPLAINT_TYPE','DAMAGE','파손',3,'Y','40','1000' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM COM_CODES WHERE GROUP_CODE='COMPLAINT_TYPE' AND DETAIL_CODE='DAMAGE');

-- COMPLAINT_STATUS (고객불만 상태)
INSERT INTO COM_CODES (GROUP_CODE,DETAIL_CODE,CODE_NAME,SORT_ORDER,USE_YN,COMPANY,PLANT_CD)
SELECT 'COMPLAINT_STATUS','RECEIVED','접수',1,'Y','40','1000' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM COM_CODES WHERE GROUP_CODE='COMPLAINT_STATUS' AND DETAIL_CODE='RECEIVED');

INSERT INTO COM_CODES (GROUP_CODE,DETAIL_CODE,CODE_NAME,SORT_ORDER,USE_YN,COMPANY,PLANT_CD)
SELECT 'COMPLAINT_STATUS','INVESTIGATING','조사중',2,'Y','40','1000' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM COM_CODES WHERE GROUP_CODE='COMPLAINT_STATUS' AND DETAIL_CODE='INVESTIGATING');

INSERT INTO COM_CODES (GROUP_CODE,DETAIL_CODE,CODE_NAME,SORT_ORDER,USE_YN,COMPANY,PLANT_CD)
SELECT 'COMPLAINT_STATUS','RESPONDING','대응중',3,'Y','40','1000' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM COM_CODES WHERE GROUP_CODE='COMPLAINT_STATUS' AND DETAIL_CODE='RESPONDING');

INSERT INTO COM_CODES (GROUP_CODE,DETAIL_CODE,CODE_NAME,SORT_ORDER,USE_YN,COMPANY,PLANT_CD)
SELECT 'COMPLAINT_STATUS','RESOLVED','해결',4,'Y','40','1000' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM COM_CODES WHERE GROUP_CODE='COMPLAINT_STATUS' AND DETAIL_CODE='RESOLVED');

INSERT INTO COM_CODES (GROUP_CODE,DETAIL_CODE,CODE_NAME,SORT_ORDER,USE_YN,COMPANY,PLANT_CD)
SELECT 'COMPLAINT_STATUS','CLOSED','종결',5,'Y','40','1000' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM COM_CODES WHERE GROUP_CODE='COMPLAINT_STATUS' AND DETAIL_CODE='CLOSED');

-- COMPLAINT_URGENCY (고객불만 긴급도)
INSERT INTO COM_CODES (GROUP_CODE,DETAIL_CODE,CODE_NAME,SORT_ORDER,USE_YN,COMPANY,PLANT_CD)
SELECT 'COMPLAINT_URGENCY','CRITICAL','긴급',1,'Y','40','1000' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM COM_CODES WHERE GROUP_CODE='COMPLAINT_URGENCY' AND DETAIL_CODE='CRITICAL');

INSERT INTO COM_CODES (GROUP_CODE,DETAIL_CODE,CODE_NAME,SORT_ORDER,USE_YN,COMPANY,PLANT_CD)
SELECT 'COMPLAINT_URGENCY','HIGH','높음',2,'Y','40','1000' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM COM_CODES WHERE GROUP_CODE='COMPLAINT_URGENCY' AND DETAIL_CODE='HIGH');

INSERT INTO COM_CODES (GROUP_CODE,DETAIL_CODE,CODE_NAME,SORT_ORDER,USE_YN,COMPANY,PLANT_CD)
SELECT 'COMPLAINT_URGENCY','MEDIUM','보통',3,'Y','40','1000' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM COM_CODES WHERE GROUP_CODE='COMPLAINT_URGENCY' AND DETAIL_CODE='MEDIUM');

INSERT INTO COM_CODES (GROUP_CODE,DETAIL_CODE,CODE_NAME,SORT_ORDER,USE_YN,COMPANY,PLANT_CD)
SELECT 'COMPLAINT_URGENCY','LOW','낮음',4,'Y','40','1000' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM COM_CODES WHERE GROUP_CODE='COMPLAINT_URGENCY' AND DETAIL_CODE='LOW');

-- FAI_TRIGGER_TYPE (초도품검사 발생사유)
INSERT INTO COM_CODES (GROUP_CODE,DETAIL_CODE,CODE_NAME,SORT_ORDER,USE_YN,COMPANY,PLANT_CD)
SELECT 'FAI_TRIGGER_TYPE','NEW_PART','신규품목',1,'Y','40','1000' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM COM_CODES WHERE GROUP_CODE='FAI_TRIGGER_TYPE' AND DETAIL_CODE='NEW_PART');

INSERT INTO COM_CODES (GROUP_CODE,DETAIL_CODE,CODE_NAME,SORT_ORDER,USE_YN,COMPANY,PLANT_CD)
SELECT 'FAI_TRIGGER_TYPE','ECN','설계변경',2,'Y','40','1000' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM COM_CODES WHERE GROUP_CODE='FAI_TRIGGER_TYPE' AND DETAIL_CODE='ECN');

INSERT INTO COM_CODES (GROUP_CODE,DETAIL_CODE,CODE_NAME,SORT_ORDER,USE_YN,COMPANY,PLANT_CD)
SELECT 'FAI_TRIGGER_TYPE','PROCESS_CHANGE','공정변경',3,'Y','40','1000' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM COM_CODES WHERE GROUP_CODE='FAI_TRIGGER_TYPE' AND DETAIL_CODE='PROCESS_CHANGE');

INSERT INTO COM_CODES (GROUP_CODE,DETAIL_CODE,CODE_NAME,SORT_ORDER,USE_YN,COMPANY,PLANT_CD)
SELECT 'FAI_TRIGGER_TYPE','LONG_STOP','장기중단',4,'Y','40','1000' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM COM_CODES WHERE GROUP_CODE='FAI_TRIGGER_TYPE' AND DETAIL_CODE='LONG_STOP');

-- FAI_STATUS (초도품검사 상태)
INSERT INTO COM_CODES (GROUP_CODE,DETAIL_CODE,CODE_NAME,SORT_ORDER,USE_YN,COMPANY,PLANT_CD)
SELECT 'FAI_STATUS','REQUESTED','요청',1,'Y','40','1000' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM COM_CODES WHERE GROUP_CODE='FAI_STATUS' AND DETAIL_CODE='REQUESTED');

INSERT INTO COM_CODES (GROUP_CODE,DETAIL_CODE,CODE_NAME,SORT_ORDER,USE_YN,COMPANY,PLANT_CD)
SELECT 'FAI_STATUS','SAMPLING','샘플채취',2,'Y','40','1000' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM COM_CODES WHERE GROUP_CODE='FAI_STATUS' AND DETAIL_CODE='SAMPLING');

INSERT INTO COM_CODES (GROUP_CODE,DETAIL_CODE,CODE_NAME,SORT_ORDER,USE_YN,COMPANY,PLANT_CD)
SELECT 'FAI_STATUS','INSPECTING','검사중',3,'Y','40','1000' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM COM_CODES WHERE GROUP_CODE='FAI_STATUS' AND DETAIL_CODE='INSPECTING');

INSERT INTO COM_CODES (GROUP_CODE,DETAIL_CODE,CODE_NAME,SORT_ORDER,USE_YN,COMPANY,PLANT_CD)
SELECT 'FAI_STATUS','PASS','합격',4,'Y','40','1000' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM COM_CODES WHERE GROUP_CODE='FAI_STATUS' AND DETAIL_CODE='PASS');

INSERT INTO COM_CODES (GROUP_CODE,DETAIL_CODE,CODE_NAME,SORT_ORDER,USE_YN,COMPANY,PLANT_CD)
SELECT 'FAI_STATUS','FAIL','불합격',5,'Y','40','1000' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM COM_CODES WHERE GROUP_CODE='FAI_STATUS' AND DETAIL_CODE='FAIL');

INSERT INTO COM_CODES (GROUP_CODE,DETAIL_CODE,CODE_NAME,SORT_ORDER,USE_YN,COMPANY,PLANT_CD)
SELECT 'FAI_STATUS','CONDITIONAL','조건부합격',6,'Y','40','1000' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM COM_CODES WHERE GROUP_CODE='FAI_STATUS' AND DETAIL_CODE='CONDITIONAL');

-- FAI_RESULT (초도품검사 결과)
INSERT INTO COM_CODES (GROUP_CODE,DETAIL_CODE,CODE_NAME,SORT_ORDER,USE_YN,COMPANY,PLANT_CD)
SELECT 'FAI_RESULT','PASS','합격',1,'Y','40','1000' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM COM_CODES WHERE GROUP_CODE='FAI_RESULT' AND DETAIL_CODE='PASS');

INSERT INTO COM_CODES (GROUP_CODE,DETAIL_CODE,CODE_NAME,SORT_ORDER,USE_YN,COMPANY,PLANT_CD)
SELECT 'FAI_RESULT','FAIL','불합격',2,'Y','40','1000' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM COM_CODES WHERE GROUP_CODE='FAI_RESULT' AND DETAIL_CODE='FAIL');

INSERT INTO COM_CODES (GROUP_CODE,DETAIL_CODE,CODE_NAME,SORT_ORDER,USE_YN,COMPANY,PLANT_CD)
SELECT 'FAI_RESULT','CONDITIONAL','조건부',3,'Y','40','1000' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM COM_CODES WHERE GROUP_CODE='FAI_RESULT' AND DETAIL_CODE='CONDITIONAL');

COMMIT;
