-- ============================================================
-- 필터 Select 공용화를 위한 누락 ComCode 그룹 추가
-- 실행 전 해당 그룹/코드 존재 여부 확인 후 없는 것만 INSERT
-- ============================================================

-- PO_STATUS (발주 상태) - material/po/page.tsx에서 하드코딩 중
INSERT INTO COM_CODES (GROUP_CODE,CODE,CODE_NAME,SORT_ORDER,USE_YN,COMPANY)
SELECT 'PO_STATUS','DRAFT','임시저장',1,'Y','40' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM COM_CODES WHERE GROUP_CODE='PO_STATUS' AND CODE='DRAFT');

INSERT INTO COM_CODES (GROUP_CODE,CODE,CODE_NAME,SORT_ORDER,USE_YN,COMPANY)
SELECT 'PO_STATUS','CONFIRMED','확정',2,'Y','40' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM COM_CODES WHERE GROUP_CODE='PO_STATUS' AND CODE='CONFIRMED');

INSERT INTO COM_CODES (GROUP_CODE,CODE,CODE_NAME,SORT_ORDER,USE_YN,COMPANY)
SELECT 'PO_STATUS','PARTIAL','부분입고',3,'Y','40' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM COM_CODES WHERE GROUP_CODE='PO_STATUS' AND CODE='PARTIAL');

INSERT INTO COM_CODES (GROUP_CODE,CODE,CODE_NAME,SORT_ORDER,USE_YN,COMPANY)
SELECT 'PO_STATUS','RECEIVED','입고완료',4,'Y','40' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM COM_CODES WHERE GROUP_CODE='PO_STATUS' AND CODE='RECEIVED');

INSERT INTO COM_CODES (GROUP_CODE,CODE,CODE_NAME,SORT_ORDER,USE_YN,COMPANY)
SELECT 'PO_STATUS','CLOSED','마감',5,'Y','40' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM COM_CODES WHERE GROUP_CODE='PO_STATUS' AND CODE='CLOSED');

-- ITEM_TYPE (품목 유형) - master/part/page.tsx에서 하드코딩 중
INSERT INTO COM_CODES (GROUP_CODE,CODE,CODE_NAME,SORT_ORDER,USE_YN,COMPANY)
SELECT 'ITEM_TYPE','RAW','원자재',1,'Y','40' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM COM_CODES WHERE GROUP_CODE='ITEM_TYPE' AND CODE='RAW');

INSERT INTO COM_CODES (GROUP_CODE,CODE,CODE_NAME,SORT_ORDER,USE_YN,COMPANY)
SELECT 'ITEM_TYPE','WIP','반제품',2,'Y','40' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM COM_CODES WHERE GROUP_CODE='ITEM_TYPE' AND CODE='WIP');

INSERT INTO COM_CODES (GROUP_CODE,CODE,CODE_NAME,SORT_ORDER,USE_YN,COMPANY)
SELECT 'ITEM_TYPE','FG','완제품',3,'Y','40' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM COM_CODES WHERE GROUP_CODE='ITEM_TYPE' AND CODE='FG');

-- PARTNER_TYPE (거래처 유형) - master/partner/page.tsx에서 하드코딩 중
INSERT INTO COM_CODES (GROUP_CODE,CODE,CODE_NAME,SORT_ORDER,USE_YN,COMPANY)
SELECT 'PARTNER_TYPE','SUPPLIER','공급사',1,'Y','40' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM COM_CODES WHERE GROUP_CODE='PARTNER_TYPE' AND CODE='SUPPLIER');

INSERT INTO COM_CODES (GROUP_CODE,CODE,CODE_NAME,SORT_ORDER,USE_YN,COMPANY)
SELECT 'PARTNER_TYPE','CUSTOMER','고객사',2,'Y','40' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM COM_CODES WHERE GROUP_CODE='PARTNER_TYPE' AND CODE='CUSTOMER');

-- USE_YN (사용여부) - master/worker/page.tsx에서 하드코딩 중
INSERT INTO COM_CODES (GROUP_CODE,CODE,CODE_NAME,SORT_ORDER,USE_YN,COMPANY)
SELECT 'USE_YN','Y','사용',1,'Y','40' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM COM_CODES WHERE GROUP_CODE='USE_YN' AND CODE='Y');

INSERT INTO COM_CODES (GROUP_CODE,CODE,CODE_NAME,SORT_ORDER,USE_YN,COMPANY)
SELECT 'USE_YN','N','미사용',2,'Y','40' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM COM_CODES WHERE GROUP_CODE='USE_YN' AND CODE='N');

-- COMM_TYPE (통신방식) - EquipMasterTab에서 하드코딩 중
INSERT INTO COM_CODES (GROUP_CODE,CODE,CODE_NAME,SORT_ORDER,USE_YN,COMPANY)
SELECT 'COMM_TYPE','NONE','없음',1,'Y','40' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM COM_CODES WHERE GROUP_CODE='COMM_TYPE' AND CODE='NONE');

INSERT INTO COM_CODES (GROUP_CODE,CODE,CODE_NAME,SORT_ORDER,USE_YN,COMPANY)
SELECT 'COMM_TYPE','TCP','TCP/IP',2,'Y','40' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM COM_CODES WHERE GROUP_CODE='COMM_TYPE' AND CODE='TCP');

INSERT INTO COM_CODES (GROUP_CODE,CODE,CODE_NAME,SORT_ORDER,USE_YN,COMPANY)
SELECT 'COMM_TYPE','SERIAL','Serial',3,'Y','40' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM COM_CODES WHERE GROUP_CODE='COMM_TYPE' AND CODE='SERIAL');

INSERT INTO COM_CODES (GROUP_CODE,CODE,CODE_NAME,SORT_ORDER,USE_YN,COMPANY)
SELECT 'COMM_TYPE','MQTT','MQTT',4,'Y','40' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM COM_CODES WHERE GROUP_CODE='COMM_TYPE' AND CODE='MQTT');

-- CONSUMABLE_LIFE_STATUS (소모품 수명 상태) - consumables/life/page.tsx에서 하드코딩 중
INSERT INTO COM_CODES (GROUP_CODE,CODE,CODE_NAME,SORT_ORDER,USE_YN,COMPANY)
SELECT 'CONSUMABLE_LIFE_STATUS','NORMAL','정상',1,'Y','40' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM COM_CODES WHERE GROUP_CODE='CONSUMABLE_LIFE_STATUS' AND CODE='NORMAL');

INSERT INTO COM_CODES (GROUP_CODE,CODE,CODE_NAME,SORT_ORDER,USE_YN,COMPANY)
SELECT 'CONSUMABLE_LIFE_STATUS','WARNING','주의',2,'Y','40' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM COM_CODES WHERE GROUP_CODE='CONSUMABLE_LIFE_STATUS' AND CODE='WARNING');

INSERT INTO COM_CODES (GROUP_CODE,CODE,CODE_NAME,SORT_ORDER,USE_YN,COMPANY)
SELECT 'CONSUMABLE_LIFE_STATUS','REPLACE','교체필요',3,'Y','40' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM COM_CODES WHERE GROUP_CODE='CONSUMABLE_LIFE_STATUS' AND CODE='REPLACE');

-- CON_STOCK_STATUS (소모품 재고 상태) - consumables/stock/page.tsx에서 하드코딩 중
INSERT INTO COM_CODES (GROUP_CODE,CODE,CODE_NAME,SORT_ORDER,USE_YN,COMPANY)
SELECT 'CON_STOCK_STATUS','PENDING','미입고',1,'Y','40' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM COM_CODES WHERE GROUP_CODE='CON_STOCK_STATUS' AND CODE='PENDING');

INSERT INTO COM_CODES (GROUP_CODE,CODE,CODE_NAME,SORT_ORDER,USE_YN,COMPANY)
SELECT 'CON_STOCK_STATUS','ACTIVE','사용가능',2,'Y','40' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM COM_CODES WHERE GROUP_CODE='CON_STOCK_STATUS' AND CODE='ACTIVE');

INSERT INTO COM_CODES (GROUP_CODE,CODE,CODE_NAME,SORT_ORDER,USE_YN,COMPANY)
SELECT 'CON_STOCK_STATUS','MOUNTED','장착중',3,'Y','40' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM COM_CODES WHERE GROUP_CODE='CON_STOCK_STATUS' AND CODE='MOUNTED');

INSERT INTO COM_CODES (GROUP_CODE,CODE,CODE_NAME,SORT_ORDER,USE_YN,COMPANY)
SELECT 'CON_STOCK_STATUS','REPAIR','수리중',4,'Y','40' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM COM_CODES WHERE GROUP_CODE='CON_STOCK_STATUS' AND CODE='REPAIR');

INSERT INTO COM_CODES (GROUP_CODE,CODE,CODE_NAME,SORT_ORDER,USE_YN,COMPANY)
SELECT 'CON_STOCK_STATUS','SCRAPPED','폐기',5,'Y','40' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM COM_CODES WHERE GROUP_CODE='CON_STOCK_STATUS' AND CODE='SCRAPPED');

COMMIT;
