-- ============================================================
-- HANES MES: TypeORM Entity → Oracle DB 스키마 정렬 마이그레이션
-- 생성일: 2026-03-16
-- 목적: DB 스키마를 TypeORM 엔티티 정의에 맞게 일치시킨다.
-- 실행환경: Oracle (JSHANES 스키마)
-- 실행순서: Phase 0 → 1 → 2 → 3 → 4 → 5 → 6
-- 주의: 테스트 데이터 환경 — 데이터 충돌 시 TRUNCATE 후 구조 변경
-- ============================================================

-- ============================================================
-- Phase 0: FK 제약조건 사전 DROP
--   (PK 변경 대상 테이블을 참조하는 FK를 먼저 제거)
-- ============================================================

-- FK_CAPA_ACTION_REQ: CAPA_ACTIONS.CAPA_ID → CAPA_REQUESTS.ID
ALTER TABLE CAPA_ACTIONS DROP CONSTRAINT FK_CAPA_ACTION_REQ;

-- FK_FAI_ITEM_REQ: FAI_ITEMS.FAI_ID → FAI_REQUESTS.ID
ALTER TABLE FAI_ITEMS DROP CONSTRAINT FK_FAI_ITEM_REQ;

-- FK_REWORK_INSP_ORDER: REWORK_INSPECTS.REWORK_ORDER_ID → REWORK_ORDERS.ID
ALTER TABLE REWORK_INSPECTS DROP CONSTRAINT FK_REWORK_INSP_ORDER;

-- FK_REWORK_PROC_ORDER: REWORK_PROCESSES.REWORK_ORDER_ID → REWORK_ORDERS.ID
ALTER TABLE REWORK_PROCESSES DROP CONSTRAINT FK_REWORK_PROC_ORDER;

-- FK_REWORK_RES_PROC: REWORK_RESULTS.REWORK_PROCESS_ID → REWORK_PROCESSES.ID
ALTER TABLE REWORK_RESULTS DROP CONSTRAINT FK_REWORK_RES_PROC;


-- ============================================================
-- Phase 1: PK 구조 변경이 필요한 테이블 TRUNCATE
--   (테스트 데이터 제거 — PK 변경 전 데이터 무결성 해제)
-- ============================================================

-- ACTIVITY_LOGS는 Phase 4에서 CREATE하므로 TRUNCATE 생략
TRUNCATE TABLE AUDIT_FINDINGS;
TRUNCATE TABLE AUDIT_PLANS;
TRUNCATE TABLE CALIBRATION_LOGS;
TRUNCATE TABLE CAPA_ACTIONS;
TRUNCATE TABLE CAPA_REQUESTS;
TRUNCATE TABLE CHANGE_ORDERS;
TRUNCATE TABLE CONSUMABLE_LOGS;
TRUNCATE TABLE CONSUMABLE_MOUNT_LOGS;
TRUNCATE TABLE CONTROL_PLAN_ITEMS;
TRUNCATE TABLE CONTROL_PLANS;
TRUNCATE TABLE CUSTOMER_COMPLAINTS;
TRUNCATE TABLE CUSTOMER_ORDER_ITEMS;
TRUNCATE TABLE CUSTOMS_ENTRIES;
TRUNCATE TABLE CUSTOMS_LOTS;
TRUNCATE TABLE CUSTOMS_USAGE_REPORTS;
TRUNCATE TABLE DEFECT_LOGS;
TRUNCATE TABLE DOCUMENT_MASTERS;
TRUNCATE TABLE EQUIP_BOM_RELS;
TRUNCATE TABLE FAI_ITEMS;
TRUNCATE TABLE FAI_REQUESTS;
TRUNCATE TABLE GAUGE_MASTERS;
TRUNCATE TABLE INSPECT_RESULTS;
TRUNCATE TABLE INTER_LOGS;
TRUNCATE TABLE INV_ADJ_LOGS;
TRUNCATE TABLE IQC_GROUP_ITEMS;
TRUNCATE TABLE IQC_GROUPS;
TRUNCATE TABLE IQC_ITEM_MASTERS;
TRUNCATE TABLE IQC_ITEM_POOL;
TRUNCATE TABLE IQC_LOGS;
TRUNCATE TABLE IQC_PART_LINKS;
TRUNCATE TABLE LABEL_PRINT_LOGS;
TRUNCATE TABLE LABEL_TEMPLATES;
TRUNCATE TABLE MAT_ARRIVALS;
TRUNCATE TABLE MAT_ISSUE_REQUEST_ITEMS;
TRUNCATE TABLE MAT_ISSUE_REQUESTS;
TRUNCATE TABLE MAT_ISSUES;
TRUNCATE TABLE MAT_RECEIVINGS;
TRUNCATE TABLE MODEL_SUFFIXES;
TRUNCATE TABLE MOLD_MASTERS;
TRUNCATE TABLE MOLD_USAGE_LOGS;
TRUNCATE TABLE OQC_REQUEST_BOXES;
TRUNCATE TABLE PDA_ROLE_MENU;
TRUNCATE TABLE PHYSICAL_INV_SESSIONS;
TRUNCATE TABLE PM_PLAN_ITEMS;
TRUNCATE TABLE PM_WO_RESULTS;
TRUNCATE TABLE PM_WORK_ORDERS;
TRUNCATE TABLE PPAP_SUBMISSIONS;
TRUNCATE TABLE PROD_PLANS;
TRUNCATE TABLE PROD_RESULTS;
TRUNCATE TABLE PRODUCT_TRANSACTIONS;
TRUNCATE TABLE PURCHASE_ORDER_ITEMS;
TRUNCATE TABLE REPAIR_LOGS;
TRUNCATE TABLE REWORK_INSPECTS;
TRUNCATE TABLE REWORK_ORDERS;
TRUNCATE TABLE REWORK_PROCESSES;
TRUNCATE TABLE REWORK_RESULTS;
TRUNCATE TABLE ROLE_MENU_PERMISSIONS;
TRUNCATE TABLE SAMPLE_INSPECT_RESULTS;
TRUNCATE TABLE SHIPMENT_LOGS;
TRUNCATE TABLE SHIPMENT_ORDER_ITEMS;
TRUNCATE TABLE SHIPMENT_RETURN_ITEMS;
TRUNCATE TABLE SHIPMENT_RETURNS;
TRUNCATE TABLE SPC_CHARTS;
TRUNCATE TABLE SPC_DATA;
TRUNCATE TABLE STOCK_TRANSACTIONS;
TRUNCATE TABLE SUBCON_DELIVERIES;
TRUNCATE TABLE SUBCON_RECEIVES;
TRUNCATE TABLE TRACE_LOGS;
TRUNCATE TABLE TRAINING_PLANS;
TRUNCATE TABLE TRAINING_RESULTS;
TRUNCATE TABLE USER_AUTHS;
TRUNCATE TABLE VENDOR_BARCODE_MAPPINGS;
TRUNCATE TABLE VENDOR_MASTERS;
TRUNCATE TABLE WAREHOUSE_TRANSFER_RULES;
TRUNCATE TABLE WORK_INSTRUCTIONS;

-- DELETED_AT만 드롭하는 테이블들 (데이터 보존 가능하지만 일관성을 위해 TRUNCATE)
TRUNCATE TABLE BOX_MASTERS;
TRUNCATE TABLE EQUIP_BOM_ITEMS;


-- ============================================================
-- Phase 2: PK 변경 + 컬럼 변경 (테이블별 순서 정렬)
-- ============================================================

-- ------------------------------------------------------------
-- 2-A. AUDIT_FINDINGS: ID 제거, 복합 PK (AUDIT_ID, FINDING_NO)
-- ------------------------------------------------------------
ALTER TABLE AUDIT_FINDINGS DROP PRIMARY KEY;
ALTER TABLE AUDIT_FINDINGS DROP COLUMN ID;
-- AUDIT_ID, FINDING_NO 는 이미 존재 — NOT NULL 확인
ALTER TABLE AUDIT_FINDINGS MODIFY (AUDIT_ID NOT NULL);
ALTER TABLE AUDIT_FINDINGS MODIFY (FINDING_NO NOT NULL);
ALTER TABLE AUDIT_FINDINGS ADD CONSTRAINT PK_AUDIT_FINDINGS PRIMARY KEY (AUDIT_ID, FINDING_NO);

-- ------------------------------------------------------------
-- 2-B. AUDIT_PLANS: PK=ID → AUDIT_NO
-- ------------------------------------------------------------
ALTER TABLE AUDIT_PLANS DROP PRIMARY KEY;
-- ID 컬럼은 엔티티에서 generated @Column으로 유지 → DROP 하지 않음
ALTER TABLE AUDIT_PLANS MODIFY (AUDIT_NO NOT NULL);
ALTER TABLE AUDIT_PLANS ADD CONSTRAINT PK_AUDIT_PLANS PRIMARY KEY (AUDIT_NO);

-- ------------------------------------------------------------
-- 2-C. BOX_MASTERS: PALLET_ID → PALLET_NO 컬럼 이름 변경, DELETED_AT 제거
-- ------------------------------------------------------------
ALTER TABLE BOX_MASTERS RENAME COLUMN PALLET_ID TO PALLET_NO;
ALTER TABLE BOX_MASTERS DROP COLUMN DELETED_AT;

-- ------------------------------------------------------------
-- 2-D. CALIBRATION_LOGS: PK=ID → CALIBRATION_NO
-- ------------------------------------------------------------
ALTER TABLE CALIBRATION_LOGS DROP PRIMARY KEY;
ALTER TABLE CALIBRATION_LOGS DROP COLUMN ID;
ALTER TABLE CALIBRATION_LOGS MODIFY (CALIBRATION_NO NOT NULL);
ALTER TABLE CALIBRATION_LOGS ADD CONSTRAINT PK_CALIBRATION_LOGS PRIMARY KEY (CALIBRATION_NO);

-- ------------------------------------------------------------
-- 2-E. CAPA_ACTIONS: ID 제거, 복합 PK (CAPA_ID, SEQ)
-- ------------------------------------------------------------
ALTER TABLE CAPA_ACTIONS DROP PRIMARY KEY;
ALTER TABLE CAPA_ACTIONS DROP COLUMN ID;
ALTER TABLE CAPA_ACTIONS MODIFY (CAPA_ID NOT NULL);
ALTER TABLE CAPA_ACTIONS MODIFY (SEQ NOT NULL);
ALTER TABLE CAPA_ACTIONS ADD CONSTRAINT PK_CAPA_ACTIONS PRIMARY KEY (CAPA_ID, SEQ);

-- ------------------------------------------------------------
-- 2-F. CAPA_REQUESTS: PK=ID → CAPA_NO
-- ------------------------------------------------------------
ALTER TABLE CAPA_REQUESTS DROP PRIMARY KEY;
-- ID: generated @Column 유지
ALTER TABLE CAPA_REQUESTS MODIFY (CAPA_NO NOT NULL);
ALTER TABLE CAPA_REQUESTS ADD CONSTRAINT PK_CAPA_REQUESTS PRIMARY KEY (CAPA_NO);

-- ------------------------------------------------------------
-- 2-G. CHANGE_ORDERS: PK=ID → CHANGE_NO
-- ------------------------------------------------------------
ALTER TABLE CHANGE_ORDERS DROP PRIMARY KEY;
ALTER TABLE CHANGE_ORDERS DROP COLUMN ID;
ALTER TABLE CHANGE_ORDERS MODIFY (CHANGE_NO NOT NULL);
ALTER TABLE CHANGE_ORDERS ADD CONSTRAINT PK_CHANGE_ORDERS PRIMARY KEY (CHANGE_NO);

-- ------------------------------------------------------------
-- 2-H. CONSUMABLE_LOGS: 컬럼 이름 변경 + PK 재설정
--      CONSUMABLE_ID → CONSUMABLE_CODE
--      EQUIPMENT_ID  → EQUIP_CODE
--      LINE_ID       → LINE_CODE
--      PK: (USAGE_DATE, SEQ) — SEQ 및 USAGE_DATE 이미 존재 가정
-- ------------------------------------------------------------
ALTER TABLE CONSUMABLE_LOGS DROP PRIMARY KEY;
ALTER TABLE CONSUMABLE_LOGS RENAME COLUMN CONSUMABLE_ID TO CONSUMABLE_CODE;
ALTER TABLE CONSUMABLE_LOGS RENAME COLUMN EQUIPMENT_ID  TO EQUIP_CODE;
ALTER TABLE CONSUMABLE_LOGS RENAME COLUMN LINE_ID       TO LINE_CODE;
-- ID: generated @Column 유지
ALTER TABLE CONSUMABLE_LOGS MODIFY (TRANS_DATE NOT NULL);
ALTER TABLE CONSUMABLE_LOGS MODIFY (SEQ NOT NULL);
ALTER TABLE CONSUMABLE_LOGS ADD CONSTRAINT PK_CONSUMABLE_LOGS PRIMARY KEY (TRANS_DATE, SEQ);

-- ------------------------------------------------------------
-- 2-I. CONSUMABLE_MOUNT_LOGS: CONSUMABLE_ID → CONSUMABLE_CODE + PK 재설정
--      PK: (MOUNT_DATE, SEQ) — 이미 존재 가정
-- ------------------------------------------------------------
ALTER TABLE CONSUMABLE_MOUNT_LOGS DROP PRIMARY KEY;
ALTER TABLE CONSUMABLE_MOUNT_LOGS RENAME COLUMN CONSUMABLE_ID TO CONSUMABLE_CODE;
-- ID: generated @Column 유지
ALTER TABLE CONSUMABLE_MOUNT_LOGS MODIFY (MOUNT_DATE NOT NULL);
ALTER TABLE CONSUMABLE_MOUNT_LOGS MODIFY (SEQ NOT NULL);
ALTER TABLE CONSUMABLE_MOUNT_LOGS ADD CONSTRAINT PK_CONSUMABLE_MOUNT_LOGS PRIMARY KEY (MOUNT_DATE, SEQ);

-- ------------------------------------------------------------
-- 2-J. CONTROL_PLAN_ITEMS: ID 제거, 복합 PK (CONTROL_PLAN_ID, SEQ)
-- ------------------------------------------------------------
ALTER TABLE CONTROL_PLAN_ITEMS DROP PRIMARY KEY;
ALTER TABLE CONTROL_PLAN_ITEMS DROP COLUMN ID;
ALTER TABLE CONTROL_PLAN_ITEMS MODIFY (CONTROL_PLAN_ID NOT NULL);
ALTER TABLE CONTROL_PLAN_ITEMS MODIFY (SEQ NOT NULL);
ALTER TABLE CONTROL_PLAN_ITEMS ADD CONSTRAINT PK_CONTROL_PLAN_ITEMS PRIMARY KEY (CONTROL_PLAN_ID, SEQ);

-- ------------------------------------------------------------
-- 2-K. CONTROL_PLANS: PK=ID → PLAN_NO
-- ------------------------------------------------------------
ALTER TABLE CONTROL_PLANS DROP PRIMARY KEY;
-- ID: generated @Column 유지
ALTER TABLE CONTROL_PLANS MODIFY (PLAN_NO NOT NULL);
ALTER TABLE CONTROL_PLANS ADD CONSTRAINT PK_CONTROL_PLANS PRIMARY KEY (PLAN_NO);

-- ------------------------------------------------------------
-- 2-L. CUSTOMER_COMPLAINTS: PK=ID → COMPLAINT_NO
-- ------------------------------------------------------------
ALTER TABLE CUSTOMER_COMPLAINTS DROP PRIMARY KEY;
ALTER TABLE CUSTOMER_COMPLAINTS DROP COLUMN ID;
ALTER TABLE CUSTOMER_COMPLAINTS MODIFY (COMPLAINT_NO NOT NULL);
ALTER TABLE CUSTOMER_COMPLAINTS ADD CONSTRAINT PK_CUSTOMER_COMPLAINTS PRIMARY KEY (COMPLAINT_NO);

-- ------------------------------------------------------------
-- 2-M. CUSTOMER_ORDER_ITEMS: ID → SEQ 이름 변경, 복합 PK (ORDER_ID, SEQ)
-- ------------------------------------------------------------
ALTER TABLE CUSTOMER_ORDER_ITEMS DROP PRIMARY KEY;
ALTER TABLE CUSTOMER_ORDER_ITEMS RENAME COLUMN ID TO SEQ;
ALTER TABLE CUSTOMER_ORDER_ITEMS MODIFY (ORDER_ID NOT NULL);
ALTER TABLE CUSTOMER_ORDER_ITEMS MODIFY (SEQ NOT NULL);
ALTER TABLE CUSTOMER_ORDER_ITEMS ADD CONSTRAINT PK_CUSTOMER_ORDER_ITEMS PRIMARY KEY (ORDER_ID, SEQ);

-- ------------------------------------------------------------
-- 2-N. CUSTOMS_ENTRIES: PK=ID → ENTRY_NO, DELETED_AT 제거
-- ------------------------------------------------------------
ALTER TABLE CUSTOMS_ENTRIES DROP PRIMARY KEY;
ALTER TABLE CUSTOMS_ENTRIES DROP COLUMN ID;
ALTER TABLE CUSTOMS_ENTRIES DROP COLUMN DELETED_AT;
ALTER TABLE CUSTOMS_ENTRIES MODIFY (ENTRY_NO NOT NULL);
ALTER TABLE CUSTOMS_ENTRIES ADD CONSTRAINT PK_CUSTOMS_ENTRIES PRIMARY KEY (ENTRY_NO);

-- ------------------------------------------------------------
-- 2-O. CUSTOMS_LOTS: ENTRY_ID → ENTRY_NO, ID 제거, 복합 PK (ENTRY_NO, MAT_UID)
-- ------------------------------------------------------------
ALTER TABLE CUSTOMS_LOTS DROP PRIMARY KEY;
ALTER TABLE CUSTOMS_LOTS RENAME COLUMN ENTRY_ID TO ENTRY_NO;
ALTER TABLE CUSTOMS_LOTS DROP COLUMN ID;
ALTER TABLE CUSTOMS_LOTS MODIFY (ENTRY_NO NOT NULL);
ALTER TABLE CUSTOMS_LOTS MODIFY (MAT_UID NOT NULL);
ALTER TABLE CUSTOMS_LOTS ADD CONSTRAINT PK_CUSTOMS_LOTS PRIMARY KEY (ENTRY_NO, MAT_UID);

-- ------------------------------------------------------------
-- 2-P. CUSTOMS_USAGE_REPORTS: CUSTOMS_LOT_ID 제거, LOT_ENTRY_NO + LOT_MAT_UID 추가,
--      PK=ID → REPORT_NO
-- ------------------------------------------------------------
ALTER TABLE CUSTOMS_USAGE_REPORTS DROP PRIMARY KEY;
ALTER TABLE CUSTOMS_USAGE_REPORTS DROP COLUMN ID;
ALTER TABLE CUSTOMS_USAGE_REPORTS DROP COLUMN CUSTOMS_LOT_ID;
ALTER TABLE CUSTOMS_USAGE_REPORTS ADD (
    LOT_ENTRY_NO  VARCHAR2(50)  NOT NULL,
    LOT_MAT_UID   VARCHAR2(100) NOT NULL
);
ALTER TABLE CUSTOMS_USAGE_REPORTS MODIFY (REPORT_NO NOT NULL);
ALTER TABLE CUSTOMS_USAGE_REPORTS ADD CONSTRAINT PK_CUSTOMS_USAGE_REPORTS PRIMARY KEY (REPORT_NO);

-- ------------------------------------------------------------
-- 2-Q. DEFECT_LOGS: PK=ID → (OCCUR_TIME, SEQ), DELETED_AT 제거
--      ID 컬럼은 엔티티에서 generated @Column으로 유지 → DB 컬럼 그대로 둠
-- ------------------------------------------------------------
ALTER TABLE DEFECT_LOGS DROP PRIMARY KEY;
ALTER TABLE DEFECT_LOGS DROP COLUMN DELETED_AT;
ALTER TABLE DEFECT_LOGS MODIFY (OCCUR_TIME NOT NULL);
ALTER TABLE DEFECT_LOGS MODIFY (SEQ NOT NULL);
ALTER TABLE DEFECT_LOGS ADD CONSTRAINT PK_DEFECT_LOGS PRIMARY KEY (OCCUR_TIME, SEQ);

-- ------------------------------------------------------------
-- 2-R. DOCUMENT_MASTERS: PK=ID → DOC_NO
-- ------------------------------------------------------------
ALTER TABLE DOCUMENT_MASTERS DROP PRIMARY KEY;
ALTER TABLE DOCUMENT_MASTERS DROP COLUMN ID;
ALTER TABLE DOCUMENT_MASTERS MODIFY (DOC_NO NOT NULL);
ALTER TABLE DOCUMENT_MASTERS ADD CONSTRAINT PK_DOCUMENT_MASTERS PRIMARY KEY (DOC_NO);

-- ------------------------------------------------------------
-- 2-S. EQUIP_BOM_RELS: PK=ID → (EQUIP_CODE, BOM_ITEM_CODE), DELETED_AT 제거
-- ------------------------------------------------------------
ALTER TABLE EQUIP_BOM_RELS DROP PRIMARY KEY;
ALTER TABLE EQUIP_BOM_RELS DROP COLUMN ID;
ALTER TABLE EQUIP_BOM_RELS DROP COLUMN DELETED_AT;
ALTER TABLE EQUIP_BOM_RELS MODIFY (EQUIP_CODE NOT NULL);
ALTER TABLE EQUIP_BOM_RELS MODIFY (BOM_ITEM_CODE NOT NULL);
ALTER TABLE EQUIP_BOM_RELS ADD CONSTRAINT PK_EQUIP_BOM_RELS PRIMARY KEY (EQUIP_CODE, BOM_ITEM_CODE);

-- ------------------------------------------------------------
-- 2-T. FAI_ITEMS: ID 제거, 복합 PK (FAI_ID, SEQ)
-- ------------------------------------------------------------
ALTER TABLE FAI_ITEMS DROP PRIMARY KEY;
ALTER TABLE FAI_ITEMS DROP COLUMN ID;
ALTER TABLE FAI_ITEMS MODIFY (FAI_ID NOT NULL);
ALTER TABLE FAI_ITEMS MODIFY (SEQ NOT NULL);
ALTER TABLE FAI_ITEMS ADD CONSTRAINT PK_FAI_ITEMS PRIMARY KEY (FAI_ID, SEQ);

-- ------------------------------------------------------------
-- 2-U. FAI_REQUESTS: PK=ID → FAI_NO
-- ------------------------------------------------------------
ALTER TABLE FAI_REQUESTS DROP PRIMARY KEY;
-- ID: generated @Column 유지
ALTER TABLE FAI_REQUESTS MODIFY (FAI_NO NOT NULL);
ALTER TABLE FAI_REQUESTS ADD CONSTRAINT PK_FAI_REQUESTS PRIMARY KEY (FAI_NO);

-- ------------------------------------------------------------
-- 2-V. GAUGE_MASTERS: PK=ID → GAUGE_CODE
-- ------------------------------------------------------------
ALTER TABLE GAUGE_MASTERS DROP PRIMARY KEY;
ALTER TABLE GAUGE_MASTERS DROP COLUMN ID;
ALTER TABLE GAUGE_MASTERS MODIFY (GAUGE_CODE NOT NULL);
ALTER TABLE GAUGE_MASTERS ADD CONSTRAINT PK_GAUGE_MASTERS PRIMARY KEY (GAUGE_CODE);

-- ------------------------------------------------------------
-- 2-W. INSPECT_RESULTS: PK=ID → RESULT_NO
-- ------------------------------------------------------------
ALTER TABLE INSPECT_RESULTS DROP PRIMARY KEY;
-- ID: generated @Column 유지
ALTER TABLE INSPECT_RESULTS MODIFY (RESULT_NO NOT NULL);
ALTER TABLE INSPECT_RESULTS ADD CONSTRAINT PK_INSPECT_RESULTS PRIMARY KEY (RESULT_NO);

-- ------------------------------------------------------------
-- 2-X. INTER_LOGS: PK=ID → (TRANS_DATE, SEQ), TRANS_DATE 컬럼 추가
--      ID 컬럼은 엔티티에서 generated @Column으로 유지 → DB 컬럼 그대로 둠
-- ------------------------------------------------------------
ALTER TABLE INTER_LOGS DROP PRIMARY KEY;
ALTER TABLE INTER_LOGS ADD (TRANS_DATE DATE);
UPDATE INTER_LOGS SET TRANS_DATE = TRUNC(SYSDATE);
ALTER TABLE INTER_LOGS MODIFY (TRANS_DATE NOT NULL);
ALTER TABLE INTER_LOGS MODIFY (SEQ NOT NULL);
ALTER TABLE INTER_LOGS ADD CONSTRAINT PK_INTER_LOGS PRIMARY KEY (TRANS_DATE, SEQ);

-- ------------------------------------------------------------
-- 2-Y. INV_ADJ_LOGS: ID 제거, 복합 PK (ADJ_DATE, SEQ)
-- ------------------------------------------------------------
ALTER TABLE INV_ADJ_LOGS DROP PRIMARY KEY;
ALTER TABLE INV_ADJ_LOGS DROP COLUMN ID;
ALTER TABLE INV_ADJ_LOGS MODIFY (ADJ_DATE NOT NULL);
ALTER TABLE INV_ADJ_LOGS MODIFY (SEQ NOT NULL);
ALTER TABLE INV_ADJ_LOGS ADD CONSTRAINT PK_INV_ADJ_LOGS PRIMARY KEY (ADJ_DATE, SEQ);

-- ------------------------------------------------------------
-- 2-Z. IQC_GROUP_ITEMS: ITEM_ID → INSP_ITEM_ID, ID 제거, 복합 PK (GROUP_ID, INSP_ITEM_ID)
-- ------------------------------------------------------------
ALTER TABLE IQC_GROUP_ITEMS DROP PRIMARY KEY;
ALTER TABLE IQC_GROUP_ITEMS RENAME COLUMN ITEM_ID TO INSP_ITEM_ID;
ALTER TABLE IQC_GROUP_ITEMS DROP COLUMN ID;
ALTER TABLE IQC_GROUP_ITEMS MODIFY (GROUP_ID NOT NULL);
ALTER TABLE IQC_GROUP_ITEMS MODIFY (INSP_ITEM_ID NOT NULL);
ALTER TABLE IQC_GROUP_ITEMS ADD CONSTRAINT PK_IQC_GROUP_ITEMS PRIMARY KEY (GROUP_ID, INSP_ITEM_ID);

-- ------------------------------------------------------------
-- 2-AA. IQC_GROUPS: PK=ID → GROUP_CODE, DELETED_AT 제거
-- ------------------------------------------------------------
ALTER TABLE IQC_GROUPS DROP PRIMARY KEY;
-- ID: generated @Column 유지
ALTER TABLE IQC_GROUPS DROP COLUMN DELETED_AT;
ALTER TABLE IQC_GROUPS MODIFY (GROUP_CODE NOT NULL);
ALTER TABLE IQC_GROUPS ADD CONSTRAINT PK_IQC_GROUPS PRIMARY KEY (GROUP_CODE);

-- ------------------------------------------------------------
-- 2-AB. IQC_ITEM_MASTERS: PK=ID → (ITEM_CODE, SEQ), DELETED_AT 제거
-- ------------------------------------------------------------
ALTER TABLE IQC_ITEM_MASTERS DROP PRIMARY KEY;
ALTER TABLE IQC_ITEM_MASTERS DROP COLUMN ID;
ALTER TABLE IQC_ITEM_MASTERS DROP COLUMN DELETED_AT;
ALTER TABLE IQC_ITEM_MASTERS MODIFY (ITEM_CODE NOT NULL);
ALTER TABLE IQC_ITEM_MASTERS MODIFY (SEQ NOT NULL);
ALTER TABLE IQC_ITEM_MASTERS ADD CONSTRAINT PK_IQC_ITEM_MASTERS PRIMARY KEY (ITEM_CODE, SEQ);

-- ------------------------------------------------------------
-- 2-AC. IQC_ITEM_POOL: PK=ID → INSP_ITEM_CODE, DELETED_AT 제거
-- ------------------------------------------------------------
ALTER TABLE IQC_ITEM_POOL DROP PRIMARY KEY;
-- ID: generated @Column 유지
ALTER TABLE IQC_ITEM_POOL DROP COLUMN DELETED_AT;
ALTER TABLE IQC_ITEM_POOL MODIFY (INSP_ITEM_CODE NOT NULL);
ALTER TABLE IQC_ITEM_POOL ADD CONSTRAINT PK_IQC_ITEM_POOL PRIMARY KEY (INSP_ITEM_CODE);

-- ------------------------------------------------------------
-- 2-AD. IQC_LOGS: PK=ID → (INSPECT_DATE, SEQ), LOT_ID 제거
-- ------------------------------------------------------------
ALTER TABLE IQC_LOGS DROP PRIMARY KEY;
ALTER TABLE IQC_LOGS DROP COLUMN ID;
ALTER TABLE IQC_LOGS DROP COLUMN LOT_ID;
ALTER TABLE IQC_LOGS MODIFY (INSPECT_DATE NOT NULL);
ALTER TABLE IQC_LOGS MODIFY (SEQ NOT NULL);
ALTER TABLE IQC_LOGS ADD CONSTRAINT PK_IQC_LOGS PRIMARY KEY (INSPECT_DATE, SEQ);

-- ------------------------------------------------------------
-- 2-AE. IQC_PART_LINKS: PK=ID → (ITEM_CODE, PARTNER_ID), DELETED_AT 제거
-- ------------------------------------------------------------
ALTER TABLE IQC_PART_LINKS DROP PRIMARY KEY;
ALTER TABLE IQC_PART_LINKS DROP COLUMN ID;
ALTER TABLE IQC_PART_LINKS DROP COLUMN DELETED_AT;
ALTER TABLE IQC_PART_LINKS MODIFY (ITEM_CODE NOT NULL);
ALTER TABLE IQC_PART_LINKS MODIFY (PARTNER_ID NOT NULL);
ALTER TABLE IQC_PART_LINKS ADD CONSTRAINT PK_IQC_PART_LINKS PRIMARY KEY (ITEM_CODE, PARTNER_ID);

-- ------------------------------------------------------------
-- 2-AF. LABEL_PRINT_LOGS: ID 제거, 복합 PK (PRINTED_AT, SEQ)
-- ------------------------------------------------------------
ALTER TABLE LABEL_PRINT_LOGS DROP PRIMARY KEY;
ALTER TABLE LABEL_PRINT_LOGS DROP COLUMN ID;
ALTER TABLE LABEL_PRINT_LOGS MODIFY (PRINTED_AT NOT NULL);
ALTER TABLE LABEL_PRINT_LOGS MODIFY (SEQ NOT NULL);
ALTER TABLE LABEL_PRINT_LOGS ADD CONSTRAINT PK_LABEL_PRINT_LOGS PRIMARY KEY (PRINTED_AT, SEQ);

-- ------------------------------------------------------------
-- 2-AG. LABEL_TEMPLATES: PK=ID → (TEMPLATE_NAME, CATEGORY), DELETED_AT 제거
-- ------------------------------------------------------------
ALTER TABLE LABEL_TEMPLATES DROP PRIMARY KEY;
ALTER TABLE LABEL_TEMPLATES DROP COLUMN ID;
ALTER TABLE LABEL_TEMPLATES DROP COLUMN DELETED_AT;
ALTER TABLE LABEL_TEMPLATES MODIFY (TEMPLATE_NAME NOT NULL);
ALTER TABLE LABEL_TEMPLATES MODIFY (CATEGORY NOT NULL);
ALTER TABLE LABEL_TEMPLATES ADD CONSTRAINT PK_LABEL_TEMPLATES PRIMARY KEY (TEMPLATE_NAME, CATEGORY);

-- ------------------------------------------------------------
-- 2-AH. MAT_ARRIVALS: ID → SEQ 이름 변경, 복합 PK (ARRIVAL_NO, SEQ)
-- ------------------------------------------------------------
ALTER TABLE MAT_ARRIVALS DROP PRIMARY KEY;
ALTER TABLE MAT_ARRIVALS RENAME COLUMN ID TO SEQ;
ALTER TABLE MAT_ARRIVALS MODIFY (ARRIVAL_NO NOT NULL);
ALTER TABLE MAT_ARRIVALS MODIFY (SEQ NOT NULL);
ALTER TABLE MAT_ARRIVALS ADD CONSTRAINT PK_MAT_ARRIVALS PRIMARY KEY (ARRIVAL_NO, SEQ);

-- ------------------------------------------------------------
-- 2-AI. MAT_ISSUE_REQUEST_ITEMS: ID → SEQ 이름 변경, 복합 PK (REQUEST_ID, SEQ)
-- ------------------------------------------------------------
ALTER TABLE MAT_ISSUE_REQUEST_ITEMS DROP PRIMARY KEY;
ALTER TABLE MAT_ISSUE_REQUEST_ITEMS RENAME COLUMN ID TO SEQ;
ALTER TABLE MAT_ISSUE_REQUEST_ITEMS MODIFY (REQUEST_ID NOT NULL);
ALTER TABLE MAT_ISSUE_REQUEST_ITEMS MODIFY (SEQ NOT NULL);
ALTER TABLE MAT_ISSUE_REQUEST_ITEMS ADD CONSTRAINT PK_MAT_ISSUE_REQUEST_ITEMS PRIMARY KEY (REQUEST_ID, SEQ);

-- ------------------------------------------------------------
-- 2-AJ. MAT_ISSUE_REQUESTS: PK=ID → REQUEST_NO, DELETED_AT 제거
-- ------------------------------------------------------------
ALTER TABLE MAT_ISSUE_REQUESTS DROP PRIMARY KEY;
-- ID: generated @Column 유지
ALTER TABLE MAT_ISSUE_REQUESTS DROP COLUMN DELETED_AT;
ALTER TABLE MAT_ISSUE_REQUESTS MODIFY (REQUEST_NO NOT NULL);
ALTER TABLE MAT_ISSUE_REQUESTS ADD CONSTRAINT PK_MAT_ISSUE_REQUESTS PRIMARY KEY (REQUEST_NO);

-- ------------------------------------------------------------
-- 2-AK. MAT_ISSUES: ID → SEQ 이름 변경, 복합 PK (ISSUE_NO, SEQ)
-- ------------------------------------------------------------
ALTER TABLE MAT_ISSUES DROP PRIMARY KEY;
ALTER TABLE MAT_ISSUES RENAME COLUMN ID TO SEQ;
ALTER TABLE MAT_ISSUES MODIFY (ISSUE_NO NOT NULL);
ALTER TABLE MAT_ISSUES MODIFY (SEQ NOT NULL);
ALTER TABLE MAT_ISSUES ADD CONSTRAINT PK_MAT_ISSUES PRIMARY KEY (ISSUE_NO, SEQ);

-- ------------------------------------------------------------
-- 2-AL. MAT_RECEIVINGS: ID → SEQ 이름 변경, 복합 PK (RECEIVE_NO, SEQ)
-- ------------------------------------------------------------
ALTER TABLE MAT_RECEIVINGS DROP PRIMARY KEY;
ALTER TABLE MAT_RECEIVINGS RENAME COLUMN ID TO SEQ;
ALTER TABLE MAT_RECEIVINGS MODIFY (RECEIVE_NO NOT NULL);
ALTER TABLE MAT_RECEIVINGS MODIFY (SEQ NOT NULL);
ALTER TABLE MAT_RECEIVINGS ADD CONSTRAINT PK_MAT_RECEIVINGS PRIMARY KEY (RECEIVE_NO, SEQ);

-- ------------------------------------------------------------
-- 2-AM. MODEL_SUFFIXES: PK=ID → (MODEL_CODE, SUFFIX_CODE), DELETED_AT 제거
-- ------------------------------------------------------------
ALTER TABLE MODEL_SUFFIXES DROP PRIMARY KEY;
ALTER TABLE MODEL_SUFFIXES DROP COLUMN ID;
ALTER TABLE MODEL_SUFFIXES DROP COLUMN DELETED_AT;
ALTER TABLE MODEL_SUFFIXES MODIFY (MODEL_CODE NOT NULL);
ALTER TABLE MODEL_SUFFIXES MODIFY (SUFFIX_CODE NOT NULL);
ALTER TABLE MODEL_SUFFIXES ADD CONSTRAINT PK_MODEL_SUFFIXES PRIMARY KEY (MODEL_CODE, SUFFIX_CODE);

-- ------------------------------------------------------------
-- 2-AN. MOLD_MASTERS: PK=ID → MOLD_CODE
-- ------------------------------------------------------------
ALTER TABLE MOLD_MASTERS DROP PRIMARY KEY;
ALTER TABLE MOLD_MASTERS DROP COLUMN ID;
ALTER TABLE MOLD_MASTERS MODIFY (MOLD_CODE NOT NULL);
ALTER TABLE MOLD_MASTERS ADD CONSTRAINT PK_MOLD_MASTERS PRIMARY KEY (MOLD_CODE);

-- ------------------------------------------------------------
-- 2-AO. MOLD_USAGE_LOGS: MOLD_ID → MOLD_CODE, ID 제거, 복합 PK (USAGE_DATE, SEQ)
-- ------------------------------------------------------------
ALTER TABLE MOLD_USAGE_LOGS DROP PRIMARY KEY;
ALTER TABLE MOLD_USAGE_LOGS RENAME COLUMN MOLD_ID TO MOLD_CODE;
ALTER TABLE MOLD_USAGE_LOGS DROP COLUMN ID;
ALTER TABLE MOLD_USAGE_LOGS MODIFY (USAGE_DATE NOT NULL);
ALTER TABLE MOLD_USAGE_LOGS MODIFY (SEQ NOT NULL);
ALTER TABLE MOLD_USAGE_LOGS ADD CONSTRAINT PK_MOLD_USAGE_LOGS PRIMARY KEY (USAGE_DATE, SEQ);

-- ------------------------------------------------------------
-- 2-AP. OQC_REQUEST_BOXES: BOX_ID + ID 제거, 복합 PK (OQC_REQUEST_ID, BOX_NO)
-- ------------------------------------------------------------
ALTER TABLE OQC_REQUEST_BOXES DROP PRIMARY KEY;
ALTER TABLE OQC_REQUEST_BOXES DROP COLUMN ID;
ALTER TABLE OQC_REQUEST_BOXES DROP COLUMN BOX_ID;
ALTER TABLE OQC_REQUEST_BOXES MODIFY (OQC_REQUEST_ID NOT NULL);
ALTER TABLE OQC_REQUEST_BOXES MODIFY (BOX_NO NOT NULL);
ALTER TABLE OQC_REQUEST_BOXES ADD CONSTRAINT PK_OQC_REQUEST_BOXES PRIMARY KEY (OQC_REQUEST_ID, BOX_NO);

-- ------------------------------------------------------------
-- 2-AQ. PDA_ROLE_MENU: ID 제거, 복합 PK (PDA_ROLE_CODE, MENU_CODE)
-- ------------------------------------------------------------
ALTER TABLE PDA_ROLE_MENU DROP PRIMARY KEY;
ALTER TABLE PDA_ROLE_MENU DROP COLUMN ID;
ALTER TABLE PDA_ROLE_MENU MODIFY (PDA_ROLE_CODE NOT NULL);
ALTER TABLE PDA_ROLE_MENU MODIFY (MENU_CODE NOT NULL);
ALTER TABLE PDA_ROLE_MENU ADD CONSTRAINT PK_PDA_ROLE_MENU PRIMARY KEY (PDA_ROLE_CODE, MENU_CODE);

-- ------------------------------------------------------------
-- 2-AR. PHYSICAL_INV_SESSIONS: ID 제거, 복합 PK (SESSION_DATE, SEQ)
-- ------------------------------------------------------------
ALTER TABLE PHYSICAL_INV_SESSIONS DROP PRIMARY KEY;
ALTER TABLE PHYSICAL_INV_SESSIONS DROP COLUMN ID;
ALTER TABLE PHYSICAL_INV_SESSIONS MODIFY (SESSION_DATE NOT NULL);
ALTER TABLE PHYSICAL_INV_SESSIONS MODIFY (SEQ NOT NULL);
ALTER TABLE PHYSICAL_INV_SESSIONS ADD CONSTRAINT PK_PHYSICAL_INV_SESSIONS PRIMARY KEY (SESSION_DATE, SEQ);

-- ------------------------------------------------------------
-- 2-AS. PM_PLAN_ITEMS: ID 제거, 복합 PK (PM_PLAN_ID, SEQ)
-- ------------------------------------------------------------
ALTER TABLE PM_PLAN_ITEMS DROP PRIMARY KEY;
ALTER TABLE PM_PLAN_ITEMS DROP COLUMN ID;
ALTER TABLE PM_PLAN_ITEMS MODIFY (PM_PLAN_ID NOT NULL);
ALTER TABLE PM_PLAN_ITEMS MODIFY (SEQ NOT NULL);
ALTER TABLE PM_PLAN_ITEMS ADD CONSTRAINT PK_PM_PLAN_ITEMS PRIMARY KEY (PM_PLAN_ID, SEQ);

-- ------------------------------------------------------------
-- 2-AT. PM_WO_RESULTS: ID 제거, 복합 PK (WORK_ORDER_ID, SEQ)
-- ------------------------------------------------------------
ALTER TABLE PM_WO_RESULTS DROP PRIMARY KEY;
ALTER TABLE PM_WO_RESULTS DROP COLUMN ID;
ALTER TABLE PM_WO_RESULTS MODIFY (WORK_ORDER_ID NOT NULL);
ALTER TABLE PM_WO_RESULTS MODIFY (SEQ NOT NULL);
ALTER TABLE PM_WO_RESULTS ADD CONSTRAINT PK_PM_WO_RESULTS PRIMARY KEY (WORK_ORDER_ID, SEQ);

-- ------------------------------------------------------------
-- 2-AU. PM_WORK_ORDERS: PK=ID → WORK_ORDER_NO
-- ------------------------------------------------------------
ALTER TABLE PM_WORK_ORDERS DROP PRIMARY KEY;
-- ID: generated @Column 유지
ALTER TABLE PM_WORK_ORDERS MODIFY (WORK_ORDER_NO NOT NULL);
ALTER TABLE PM_WORK_ORDERS ADD CONSTRAINT PK_PM_WORK_ORDERS PRIMARY KEY (WORK_ORDER_NO);

-- ------------------------------------------------------------
-- 2-AV. PPAP_SUBMISSIONS: PK=ID → PPAP_NO
-- ------------------------------------------------------------
ALTER TABLE PPAP_SUBMISSIONS DROP PRIMARY KEY;
ALTER TABLE PPAP_SUBMISSIONS DROP COLUMN ID;
ALTER TABLE PPAP_SUBMISSIONS MODIFY (PPAP_NO NOT NULL);
ALTER TABLE PPAP_SUBMISSIONS ADD CONSTRAINT PK_PPAP_SUBMISSIONS PRIMARY KEY (PPAP_NO);

-- ------------------------------------------------------------
-- 2-AW. PROD_PLANS: PK=ID → PLAN_NO
-- ------------------------------------------------------------
ALTER TABLE PROD_PLANS DROP PRIMARY KEY;
ALTER TABLE PROD_PLANS DROP COLUMN ID;
ALTER TABLE PROD_PLANS MODIFY (PLAN_NO NOT NULL);
ALTER TABLE PROD_PLANS ADD CONSTRAINT PK_PROD_PLANS PRIMARY KEY (PLAN_NO);

-- ------------------------------------------------------------
-- 2-AX. PROD_RESULTS: PK=ID → RESULT_NO
-- ------------------------------------------------------------
ALTER TABLE PROD_RESULTS DROP PRIMARY KEY;
-- ID: generated @Column 유지
ALTER TABLE PROD_RESULTS DROP COLUMN DELETED_AT;
ALTER TABLE PROD_RESULTS MODIFY (RESULT_NO NOT NULL);
ALTER TABLE PROD_RESULTS ADD CONSTRAINT PK_PROD_RESULTS PRIMARY KEY (RESULT_NO);

-- ------------------------------------------------------------
-- 2-AY. PRODUCT_TRANSACTIONS: PK=ID → TRANS_NO
-- ------------------------------------------------------------
ALTER TABLE PRODUCT_TRANSACTIONS DROP PRIMARY KEY;
ALTER TABLE PRODUCT_TRANSACTIONS DROP COLUMN ID;
ALTER TABLE PRODUCT_TRANSACTIONS MODIFY (TRANS_NO NOT NULL);
ALTER TABLE PRODUCT_TRANSACTIONS ADD CONSTRAINT PK_PRODUCT_TRANSACTIONS PRIMARY KEY (TRANS_NO);

-- ------------------------------------------------------------
-- 2-AZ. PURCHASE_ORDER_ITEMS: ID → SEQ 이름 변경, 복합 PK (PO_ID, SEQ)
-- ------------------------------------------------------------
ALTER TABLE PURCHASE_ORDER_ITEMS DROP PRIMARY KEY;
ALTER TABLE PURCHASE_ORDER_ITEMS RENAME COLUMN ID TO SEQ;
ALTER TABLE PURCHASE_ORDER_ITEMS MODIFY (PO_ID NOT NULL);
ALTER TABLE PURCHASE_ORDER_ITEMS MODIFY (SEQ NOT NULL);
ALTER TABLE PURCHASE_ORDER_ITEMS ADD CONSTRAINT PK_PURCHASE_ORDER_ITEMS PRIMARY KEY (PO_ID, SEQ);

-- ------------------------------------------------------------
-- 2-BA. REPAIR_LOGS: ID 제거, 복합 PK (REPAIR_DATE, SEQ)
-- ------------------------------------------------------------
ALTER TABLE REPAIR_LOGS DROP PRIMARY KEY;
ALTER TABLE REPAIR_LOGS DROP COLUMN ID;
ALTER TABLE REPAIR_LOGS MODIFY (REPAIR_DATE NOT NULL);
ALTER TABLE REPAIR_LOGS MODIFY (SEQ NOT NULL);
ALTER TABLE REPAIR_LOGS ADD CONSTRAINT PK_REPAIR_LOGS PRIMARY KEY (REPAIR_DATE, SEQ);

-- ------------------------------------------------------------
-- 2-BB. REWORK_INSPECTS: ID → SEQ 이름 변경, 복합 PK (REWORK_ORDER_ID, SEQ)
-- ------------------------------------------------------------
ALTER TABLE REWORK_INSPECTS DROP PRIMARY KEY;
ALTER TABLE REWORK_INSPECTS RENAME COLUMN ID TO SEQ;
ALTER TABLE REWORK_INSPECTS MODIFY (REWORK_ORDER_ID NOT NULL);
ALTER TABLE REWORK_INSPECTS MODIFY (SEQ NOT NULL);
ALTER TABLE REWORK_INSPECTS ADD CONSTRAINT PK_REWORK_INSPECTS PRIMARY KEY (REWORK_ORDER_ID, SEQ);

-- ------------------------------------------------------------
-- 2-BC. REWORK_ORDERS: PK=ID → REWORK_NO
-- ------------------------------------------------------------
ALTER TABLE REWORK_ORDERS DROP PRIMARY KEY;
-- ID: generated @Column 유지
ALTER TABLE REWORK_ORDERS MODIFY (REWORK_NO NOT NULL);
ALTER TABLE REWORK_ORDERS ADD CONSTRAINT PK_REWORK_ORDERS PRIMARY KEY (REWORK_NO);

-- ------------------------------------------------------------
-- 2-BD. REWORK_PROCESSES: ID 제거, 복합 PK (REWORK_ORDER_ID, PROCESS_CODE)
-- ------------------------------------------------------------
ALTER TABLE REWORK_PROCESSES DROP PRIMARY KEY;
ALTER TABLE REWORK_PROCESSES DROP COLUMN ID;
ALTER TABLE REWORK_PROCESSES MODIFY (REWORK_ORDER_ID NOT NULL);
ALTER TABLE REWORK_PROCESSES MODIFY (PROCESS_CODE NOT NULL);
ALTER TABLE REWORK_PROCESSES ADD CONSTRAINT PK_REWORK_PROCESSES PRIMARY KEY (REWORK_ORDER_ID, PROCESS_CODE);

-- ------------------------------------------------------------
-- 2-BE. REWORK_RESULTS: REWORK_PROCESS_ID 제거, REWORK_ORDER_ID + PROCESS_CODE + SEQ 추가,
--       ID 제거, 복합 PK (REWORK_ORDER_ID, PROCESS_CODE, SEQ)
-- ------------------------------------------------------------
ALTER TABLE REWORK_RESULTS DROP PRIMARY KEY;
ALTER TABLE REWORK_RESULTS DROP COLUMN ID;
ALTER TABLE REWORK_RESULTS DROP COLUMN REWORK_PROCESS_ID;
ALTER TABLE REWORK_RESULTS ADD (
    REWORK_ORDER_ID NUMBER        NOT NULL,
    PROCESS_CODE    VARCHAR2(50)  NOT NULL,
    SEQ             NUMBER        NOT NULL
);
ALTER TABLE REWORK_RESULTS ADD CONSTRAINT PK_REWORK_RESULTS PRIMARY KEY (REWORK_ORDER_ID, PROCESS_CODE, SEQ);

-- ------------------------------------------------------------
-- 2-BF. ROLE_MENU_PERMISSIONS: ROLE_ID → ROLE_CODE, ID 제거, 복합 PK (ROLE_CODE, MENU_CODE)
-- ------------------------------------------------------------
ALTER TABLE ROLE_MENU_PERMISSIONS DROP PRIMARY KEY;
ALTER TABLE ROLE_MENU_PERMISSIONS RENAME COLUMN ROLE_ID TO ROLE_CODE;
ALTER TABLE ROLE_MENU_PERMISSIONS DROP COLUMN ID;
ALTER TABLE ROLE_MENU_PERMISSIONS MODIFY (ROLE_CODE NOT NULL);
ALTER TABLE ROLE_MENU_PERMISSIONS MODIFY (MENU_CODE NOT NULL);
ALTER TABLE ROLE_MENU_PERMISSIONS ADD CONSTRAINT PK_ROLE_MENU_PERMISSIONS PRIMARY KEY (ROLE_CODE, MENU_CODE);

-- ------------------------------------------------------------
-- 2-BG. SAMPLE_INSPECT_RESULTS: ID 제거, 복합 PK (ORDER_NO, SAMPLE_NO)
-- ------------------------------------------------------------
ALTER TABLE SAMPLE_INSPECT_RESULTS DROP PRIMARY KEY;
ALTER TABLE SAMPLE_INSPECT_RESULTS DROP COLUMN ID;
ALTER TABLE SAMPLE_INSPECT_RESULTS MODIFY (ORDER_NO NOT NULL);
ALTER TABLE SAMPLE_INSPECT_RESULTS MODIFY (SAMPLE_NO NOT NULL);
ALTER TABLE SAMPLE_INSPECT_RESULTS ADD CONSTRAINT PK_SAMPLE_INSPECT_RESULTS PRIMARY KEY (ORDER_NO, SAMPLE_NO);

-- ------------------------------------------------------------
-- 2-BH. SHIPMENT_LOGS: PK=ID → SHIP_NO, DELETED_AT 제거
-- ------------------------------------------------------------
ALTER TABLE SHIPMENT_LOGS DROP PRIMARY KEY;
-- ID: generated @Column 유지
ALTER TABLE SHIPMENT_LOGS DROP COLUMN DELETED_AT;
ALTER TABLE SHIPMENT_LOGS MODIFY (SHIP_NO NOT NULL);
ALTER TABLE SHIPMENT_LOGS ADD CONSTRAINT PK_SHIPMENT_LOGS PRIMARY KEY (SHIP_NO);

-- ------------------------------------------------------------
-- 2-BI. SHIPMENT_ORDER_ITEMS: ID → SEQ 이름 변경, 복합 PK (SHIP_ORDER_ID, SEQ)
-- ------------------------------------------------------------
ALTER TABLE SHIPMENT_ORDER_ITEMS DROP PRIMARY KEY;
ALTER TABLE SHIPMENT_ORDER_ITEMS RENAME COLUMN ID TO SEQ;
ALTER TABLE SHIPMENT_ORDER_ITEMS MODIFY (SHIP_ORDER_ID NOT NULL);
ALTER TABLE SHIPMENT_ORDER_ITEMS MODIFY (SEQ NOT NULL);
ALTER TABLE SHIPMENT_ORDER_ITEMS ADD CONSTRAINT PK_SHIPMENT_ORDER_ITEMS PRIMARY KEY (SHIP_ORDER_ID, SEQ);

-- ------------------------------------------------------------
-- 2-BJ. SHIPMENT_RETURN_ITEMS: ID → SEQ, RETURN_ID → RETURN_NO,
--        복합 PK (RETURN_NO, SEQ)
-- ------------------------------------------------------------
ALTER TABLE SHIPMENT_RETURN_ITEMS DROP PRIMARY KEY;
ALTER TABLE SHIPMENT_RETURN_ITEMS RENAME COLUMN ID TO SEQ;
ALTER TABLE SHIPMENT_RETURN_ITEMS RENAME COLUMN RETURN_ID TO RETURN_NO;
ALTER TABLE SHIPMENT_RETURN_ITEMS MODIFY (RETURN_NO NOT NULL);
ALTER TABLE SHIPMENT_RETURN_ITEMS MODIFY (SEQ NOT NULL);
ALTER TABLE SHIPMENT_RETURN_ITEMS ADD CONSTRAINT PK_SHIPMENT_RETURN_ITEMS PRIMARY KEY (RETURN_NO, SEQ);

-- ------------------------------------------------------------
-- 2-BK. SHIPMENT_RETURNS: PK=ID → RETURN_NO, DELETED_AT 제거
-- ------------------------------------------------------------
ALTER TABLE SHIPMENT_RETURNS DROP PRIMARY KEY;
ALTER TABLE SHIPMENT_RETURNS DROP COLUMN ID;
ALTER TABLE SHIPMENT_RETURNS DROP COLUMN DELETED_AT;
ALTER TABLE SHIPMENT_RETURNS MODIFY (RETURN_NO NOT NULL);
ALTER TABLE SHIPMENT_RETURNS ADD CONSTRAINT PK_SHIPMENT_RETURNS PRIMARY KEY (RETURN_NO);

-- ------------------------------------------------------------
-- 2-BL. SPC_CHARTS: PK=ID → CHART_NO
-- ------------------------------------------------------------
ALTER TABLE SPC_CHARTS DROP PRIMARY KEY;
-- ID: generated @Column 유지
ALTER TABLE SPC_CHARTS MODIFY (CHART_NO NOT NULL);
ALTER TABLE SPC_CHARTS ADD CONSTRAINT PK_SPC_CHARTS PRIMARY KEY (CHART_NO);

-- ------------------------------------------------------------
-- 2-BM. SPC_DATA: PK=ID → (CHART_ID, SAMPLE_DATE, SEQ)
-- ------------------------------------------------------------
ALTER TABLE SPC_DATA DROP PRIMARY KEY;
-- ID: generated @Column 유지
ALTER TABLE SPC_DATA MODIFY (CHART_ID NOT NULL);
ALTER TABLE SPC_DATA MODIFY (SAMPLE_DATE NOT NULL);
ALTER TABLE SPC_DATA MODIFY (SEQ NOT NULL);
ALTER TABLE SPC_DATA ADD CONSTRAINT PK_SPC_DATA PRIMARY KEY (CHART_ID, SAMPLE_DATE, SEQ);

-- ------------------------------------------------------------
-- 2-BN. STOCK_TRANSACTIONS: PK=ID → TRANS_NO
-- ------------------------------------------------------------
ALTER TABLE STOCK_TRANSACTIONS DROP PRIMARY KEY;
ALTER TABLE STOCK_TRANSACTIONS DROP COLUMN ID;
ALTER TABLE STOCK_TRANSACTIONS MODIFY (TRANS_NO NOT NULL);
ALTER TABLE STOCK_TRANSACTIONS ADD CONSTRAINT PK_STOCK_TRANSACTIONS PRIMARY KEY (TRANS_NO);

-- ------------------------------------------------------------
-- 2-BO. SUBCON_DELIVERIES: PK=ID → DELIVERY_NO
-- ------------------------------------------------------------
ALTER TABLE SUBCON_DELIVERIES DROP PRIMARY KEY;
ALTER TABLE SUBCON_DELIVERIES DROP COLUMN ID;
ALTER TABLE SUBCON_DELIVERIES MODIFY (DELIVERY_NO NOT NULL);
ALTER TABLE SUBCON_DELIVERIES ADD CONSTRAINT PK_SUBCON_DELIVERIES PRIMARY KEY (DELIVERY_NO);

-- ------------------------------------------------------------
-- 2-BP. SUBCON_RECEIVES: PK=ID → RECEIVE_NO
-- ------------------------------------------------------------
ALTER TABLE SUBCON_RECEIVES DROP PRIMARY KEY;
ALTER TABLE SUBCON_RECEIVES DROP COLUMN ID;
ALTER TABLE SUBCON_RECEIVES MODIFY (RECEIVE_NO NOT NULL);
ALTER TABLE SUBCON_RECEIVES ADD CONSTRAINT PK_SUBCON_RECEIVES PRIMARY KEY (RECEIVE_NO);

-- ------------------------------------------------------------
-- 2-BQ. TRACE_LOGS: PK=ID → (TRACE_TIME, SEQ)
--        TRACE_TIME, SEQ 컬럼은 이미 존재
-- ------------------------------------------------------------
ALTER TABLE TRACE_LOGS DROP PRIMARY KEY;
-- ID: generated @Column 유지
ALTER TABLE TRACE_LOGS MODIFY (TRACE_TIME NOT NULL);
ALTER TABLE TRACE_LOGS MODIFY (SEQ NOT NULL);
ALTER TABLE TRACE_LOGS ADD CONSTRAINT PK_TRACE_LOGS PRIMARY KEY (TRACE_TIME, SEQ);

-- ------------------------------------------------------------
-- 2-BR. TRAINING_PLANS: PK=ID → PLAN_NO
-- ------------------------------------------------------------
ALTER TABLE TRAINING_PLANS DROP PRIMARY KEY;
ALTER TABLE TRAINING_PLANS DROP COLUMN ID;
ALTER TABLE TRAINING_PLANS MODIFY (PLAN_NO NOT NULL);
ALTER TABLE TRAINING_PLANS ADD CONSTRAINT PK_TRAINING_PLANS PRIMARY KEY (PLAN_NO);

-- ------------------------------------------------------------
-- 2-BS. TRAINING_RESULTS: PK=ID → (PLAN_NO, WORKER_CODE)
-- ------------------------------------------------------------
ALTER TABLE TRAINING_RESULTS DROP PRIMARY KEY;
ALTER TABLE TRAINING_RESULTS DROP COLUMN ID;
ALTER TABLE TRAINING_RESULTS MODIFY (PLAN_NO NOT NULL);
ALTER TABLE TRAINING_RESULTS MODIFY (WORKER_CODE NOT NULL);
ALTER TABLE TRAINING_RESULTS ADD CONSTRAINT PK_TRAINING_RESULTS PRIMARY KEY (PLAN_NO, WORKER_CODE);

-- ------------------------------------------------------------
-- 2-BT. USER_AUTHS: USER_ID → USER_EMAIL, ID 제거, 복합 PK (USER_EMAIL, MENU_CODE)
-- ------------------------------------------------------------
ALTER TABLE USER_AUTHS DROP PRIMARY KEY;
ALTER TABLE USER_AUTHS RENAME COLUMN USER_ID TO USER_EMAIL;
ALTER TABLE USER_AUTHS DROP COLUMN ID;
ALTER TABLE USER_AUTHS MODIFY (USER_EMAIL NOT NULL);
ALTER TABLE USER_AUTHS MODIFY (MENU_CODE NOT NULL);
ALTER TABLE USER_AUTHS ADD CONSTRAINT PK_USER_AUTHS PRIMARY KEY (USER_EMAIL, MENU_CODE);

-- ------------------------------------------------------------
-- 2-BU. VENDOR_BARCODE_MAPPINGS: PK=ID → VENDOR_BARCODE,
--        DELETED_AT + ITEM_ID 제거 (ITEM_CODE 컬럼이 엔티티 PK, ITEM_ID는 레거시)
-- ------------------------------------------------------------
ALTER TABLE VENDOR_BARCODE_MAPPINGS DROP PRIMARY KEY;
ALTER TABLE VENDOR_BARCODE_MAPPINGS DROP COLUMN ID;
ALTER TABLE VENDOR_BARCODE_MAPPINGS DROP COLUMN DELETED_AT;
ALTER TABLE VENDOR_BARCODE_MAPPINGS DROP COLUMN ITEM_ID;
ALTER TABLE VENDOR_BARCODE_MAPPINGS MODIFY (VENDOR_BARCODE NOT NULL);
ALTER TABLE VENDOR_BARCODE_MAPPINGS ADD CONSTRAINT PK_VENDOR_BARCODE_MAPPINGS PRIMARY KEY (VENDOR_BARCODE);

-- ------------------------------------------------------------
-- 2-BV. VENDOR_MASTERS: PK=ID → VENDOR_CODE, DELETED_AT 제거
-- ------------------------------------------------------------
ALTER TABLE VENDOR_MASTERS DROP PRIMARY KEY;
ALTER TABLE VENDOR_MASTERS DROP COLUMN ID;
ALTER TABLE VENDOR_MASTERS DROP COLUMN DELETED_AT;
ALTER TABLE VENDOR_MASTERS MODIFY (VENDOR_CODE NOT NULL);
ALTER TABLE VENDOR_MASTERS ADD CONSTRAINT PK_VENDOR_MASTERS PRIMARY KEY (VENDOR_CODE);

-- ------------------------------------------------------------
-- 2-BW. WAREHOUSE_TRANSFER_RULES: ID 제거, 복합 PK (FROM_WAREHOUSE_ID, TO_WAREHOUSE_ID)
-- ------------------------------------------------------------
ALTER TABLE WAREHOUSE_TRANSFER_RULES DROP PRIMARY KEY;
ALTER TABLE WAREHOUSE_TRANSFER_RULES DROP COLUMN ID;
ALTER TABLE WAREHOUSE_TRANSFER_RULES MODIFY (FROM_WAREHOUSE_ID NOT NULL);
ALTER TABLE WAREHOUSE_TRANSFER_RULES MODIFY (TO_WAREHOUSE_ID NOT NULL);
ALTER TABLE WAREHOUSE_TRANSFER_RULES ADD CONSTRAINT PK_WAREHOUSE_TRANSFER_RULES PRIMARY KEY (FROM_WAREHOUSE_ID, TO_WAREHOUSE_ID);

-- ------------------------------------------------------------
-- 2-BX. WORK_INSTRUCTIONS: PK=ID → (ITEM_CODE, PROCESS_CODE, REVISION), DELETED_AT 제거
-- ------------------------------------------------------------
ALTER TABLE WORK_INSTRUCTIONS DROP PRIMARY KEY;
ALTER TABLE WORK_INSTRUCTIONS DROP COLUMN ID;
ALTER TABLE WORK_INSTRUCTIONS DROP COLUMN DELETED_AT;
ALTER TABLE WORK_INSTRUCTIONS MODIFY (ITEM_CODE NOT NULL);
ALTER TABLE WORK_INSTRUCTIONS MODIFY (PROCESS_CODE NOT NULL);
ALTER TABLE WORK_INSTRUCTIONS MODIFY (REVISION NOT NULL);
ALTER TABLE WORK_INSTRUCTIONS ADD CONSTRAINT PK_WORK_INSTRUCTIONS PRIMARY KEY (ITEM_CODE, PROCESS_CODE, REVISION);


-- ============================================================
-- Phase 3: DELETED_AT 및 불필요 컬럼 제거 (PK 이미 정상인 테이블)
-- ============================================================

-- BOM_MASTERS: DELETED_AT 제거
ALTER TABLE BOM_MASTERS DROP COLUMN DELETED_AT;

-- COM_CODES: DELETED_AT 제거
ALTER TABLE COM_CODES DROP COLUMN DELETED_AT;

-- COMM_CONFIGS: DELETED_AT 제거
ALTER TABLE COMM_CONFIGS DROP COLUMN DELETED_AT;

-- COMPANY_MASTERS: DELETED_AT 제거
ALTER TABLE COMPANY_MASTERS DROP COLUMN DELETED_AT;

-- CONSUMABLE_MASTERS: DELETED_AT 제거
ALTER TABLE CONSUMABLE_MASTERS DROP COLUMN DELETED_AT;

-- CUSTOMER_ORDERS: DELETED_AT 제거
ALTER TABLE CUSTOMER_ORDERS DROP COLUMN DELETED_AT;

-- DEPARTMENT_MASTERS: DELETED_AT 제거
ALTER TABLE DEPARTMENT_MASTERS DROP COLUMN DELETED_AT;

-- EQUIP_BOM_ITEMS: DELETED_AT 제거
ALTER TABLE EQUIP_BOM_ITEMS DROP COLUMN DELETED_AT;

-- EQUIP_MASTERS: DELETED_AT 제거
ALTER TABLE EQUIP_MASTERS DROP COLUMN DELETED_AT;

-- ITEM_MASTERS: DELETED_AT 제거
ALTER TABLE ITEM_MASTERS DROP COLUMN DELETED_AT;

-- JOB_ORDERS: DELETED_AT 제거
ALTER TABLE JOB_ORDERS DROP COLUMN DELETED_AT;

-- MAT_LOTS: DELETED_AT 제거
ALTER TABLE MAT_LOTS DROP COLUMN DELETED_AT;

-- NUM_RULE_MASTERS: DELETED_AT 제거
ALTER TABLE NUM_RULE_MASTERS DROP COLUMN DELETED_AT;

-- OQC_REQUESTS: DELETED_AT 제거
ALTER TABLE OQC_REQUESTS DROP COLUMN DELETED_AT;

-- PALLET_MASTERS: DELETED_AT 제거
ALTER TABLE PALLET_MASTERS DROP COLUMN DELETED_AT;

-- PARTNER_MASTERS: DELETED_AT 제거
ALTER TABLE PARTNER_MASTERS DROP COLUMN DELETED_AT;

-- PLANTS: DELETED_AT + PARENT_ID 제거
ALTER TABLE PLANTS DROP COLUMN DELETED_AT;
ALTER TABLE PLANTS DROP COLUMN PARENT_ID;

-- PM_PLANS: DELETED_AT 제거
ALTER TABLE PM_PLANS DROP COLUMN DELETED_AT;

-- PROCESS_MAPS: DELETED_AT 제거
ALTER TABLE PROCESS_MAPS DROP COLUMN DELETED_AT;

-- PROCESS_MASTERS: DELETED_AT + SAMPLE_INSPECT_YN 제거
ALTER TABLE PROCESS_MASTERS DROP COLUMN DELETED_AT;
ALTER TABLE PROCESS_MASTERS DROP COLUMN SAMPLE_INSPECT_YN;

-- PROD_LINE_MASTERS: DELETED_AT 제거
ALTER TABLE PROD_LINE_MASTERS DROP COLUMN DELETED_AT;

-- PURCHASE_ORDERS: DELETED_AT 제거
ALTER TABLE PURCHASE_ORDERS DROP COLUMN DELETED_AT;

-- ROLES: DELETED_AT 제거
ALTER TABLE ROLES DROP COLUMN DELETED_AT;

-- SHIPMENT_ORDERS: DELETED_AT 제거
ALTER TABLE SHIPMENT_ORDERS DROP COLUMN DELETED_AT;

-- SUBCON_ORDERS: DELETED_AT 제거
ALTER TABLE SUBCON_ORDERS DROP COLUMN DELETED_AT;

-- USERS: DELETED_AT 제거
ALTER TABLE USERS DROP COLUMN DELETED_AT;

-- WAREHOUSES: DELETED_AT 제거
ALTER TABLE WAREHOUSES DROP COLUMN DELETED_AT;

-- WORKER_MASTERS: DELETED_AT 제거
ALTER TABLE WORKER_MASTERS DROP COLUMN DELETED_AT;


-- ============================================================
-- Phase 4: ACTIVITY_LOGS 테이블 신규 생성
-- ============================================================

CREATE TABLE ACTIVITY_LOGS (
    ACTIVITY_DATE   DATE           DEFAULT SYSDATE NOT NULL,
    SEQ             NUMBER         DEFAULT 1       NOT NULL,
    USER_EMAIL      VARCHAR2(255)                  NOT NULL,
    USER_NAME       VARCHAR2(255),
    ACTIVITY_TYPE   VARCHAR2(50)                   NOT NULL,
    PAGE_PATH       VARCHAR2(500),
    PAGE_NAME       VARCHAR2(200),
    IP_ADDRESS      VARCHAR2(50),
    USER_AGENT      VARCHAR2(500),
    DEVICE_TYPE     VARCHAR2(20),
    COMPANY         VARCHAR2(50),
    PLANT_CD        VARCHAR2(50),
    CREATED_AT      TIMESTAMP      DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT PK_ACTIVITY_LOGS PRIMARY KEY (ACTIVITY_DATE, SEQ)
);

-- 인덱스 생성
CREATE INDEX IDX_ACTIVITY_LOGS_EMAIL    ON ACTIVITY_LOGS (USER_EMAIL);
CREATE INDEX IDX_ACTIVITY_LOGS_TYPE     ON ACTIVITY_LOGS (ACTIVITY_TYPE);
CREATE INDEX IDX_ACTIVITY_LOGS_CREATED  ON ACTIVITY_LOGS (CREATED_AT);


-- ============================================================
-- Phase 5: FK 제약조건 재생성
--   (Phase 0에서 드롭한 FK를 변경된 PK 기준으로 재생성)
-- ============================================================

-- FK_CAPA_ACTION_REQ: CAPA_ACTIONS.CAPA_ID → CAPA_REQUESTS.CAPA_NO
ALTER TABLE CAPA_ACTIONS
    ADD CONSTRAINT FK_CAPA_ACTION_REQ
    FOREIGN KEY (CAPA_ID)
    REFERENCES CAPA_REQUESTS (CAPA_NO);

-- FK_FAI_ITEM_REQ: FAI_ITEMS.FAI_ID → FAI_REQUESTS.FAI_NO
ALTER TABLE FAI_ITEMS
    ADD CONSTRAINT FK_FAI_ITEM_REQ
    FOREIGN KEY (FAI_ID)
    REFERENCES FAI_REQUESTS (FAI_NO);

-- FK_REWORK_INSP_ORDER: REWORK_INSPECTS.REWORK_ORDER_ID → REWORK_ORDERS.REWORK_NO
ALTER TABLE REWORK_INSPECTS
    ADD CONSTRAINT FK_REWORK_INSP_ORDER
    FOREIGN KEY (REWORK_ORDER_ID)
    REFERENCES REWORK_ORDERS (REWORK_NO);

-- FK_REWORK_PROC_ORDER: REWORK_PROCESSES.REWORK_ORDER_ID → REWORK_ORDERS.REWORK_NO
ALTER TABLE REWORK_PROCESSES
    ADD CONSTRAINT FK_REWORK_PROC_ORDER
    FOREIGN KEY (REWORK_ORDER_ID)
    REFERENCES REWORK_ORDERS (REWORK_NO);

-- FK_REWORK_RES_PROC: REWORK_RESULTS.(REWORK_ORDER_ID, PROCESS_CODE) → REWORK_PROCESSES.(REWORK_ORDER_ID, PROCESS_CODE)
ALTER TABLE REWORK_RESULTS
    ADD CONSTRAINT FK_REWORK_RES_PROC
    FOREIGN KEY (REWORK_ORDER_ID, PROCESS_CODE)
    REFERENCES REWORK_PROCESSES (REWORK_ORDER_ID, PROCESS_CODE);

-- CUSTOMS_LOTS.ENTRY_NO → CUSTOMS_ENTRIES.ENTRY_NO (ENTRY_ID에서 변경됨)
ALTER TABLE CUSTOMS_LOTS
    ADD CONSTRAINT FK_CUSTOMS_LOT_ENTRY
    FOREIGN KEY (ENTRY_NO)
    REFERENCES CUSTOMS_ENTRIES (ENTRY_NO);


-- ============================================================
-- Phase 6: 최종 확인 쿼리 (실행 후 검증용 — 결과가 0이어야 정상)
-- ============================================================

-- 아래 쿼리를 수동으로 실행하여 마이그레이션 결과를 확인하세요.

/*
-- 1) PK 확인: 주요 테이블 PK 컬럼 목록
SELECT c.TABLE_NAME, c.COLUMN_NAME, c.POSITION
FROM   USER_CONS_COLUMNS c
JOIN   USER_CONSTRAINTS  k ON k.CONSTRAINT_NAME = c.CONSTRAINT_NAME
WHERE  k.CONSTRAINT_TYPE = 'P'
AND    c.TABLE_NAME IN (
    'CAPA_REQUESTS','REWORK_ORDERS','FAI_REQUESTS','CUSTOMS_ENTRIES',
    'REWORK_PROCESSES','REWORK_RESULTS','USER_AUTHS','ROLE_MENU_PERMISSIONS',
    'ACTIVITY_LOGS','CUSTOMS_LOTS','DEFECT_LOGS','INTER_LOGS'
)
ORDER BY c.TABLE_NAME, c.POSITION;

-- 2) DELETED_AT 컬럼이 남아 있는 테이블 확인 (0건이어야 함)
SELECT TABLE_NAME, COLUMN_NAME
FROM   USER_TAB_COLUMNS
WHERE  COLUMN_NAME = 'DELETED_AT'
ORDER BY TABLE_NAME;

-- 3) ID 컬럼이 PK로 남아 있는지 확인 (INTER_LOGS, DEFECT_LOGS는 의도적으로 유지)
SELECT c.TABLE_NAME, c.COLUMN_NAME
FROM   USER_CONS_COLUMNS c
JOIN   USER_CONSTRAINTS  k ON k.CONSTRAINT_NAME = c.CONSTRAINT_NAME
WHERE  k.CONSTRAINT_TYPE = 'P'
AND    c.COLUMN_NAME = 'ID'
ORDER BY c.TABLE_NAME;

-- 4) ACTIVITY_LOGS 테이블 존재 확인
SELECT TABLE_NAME FROM USER_TABLES WHERE TABLE_NAME = 'ACTIVITY_LOGS';

-- 5) FK 유효성 확인 (DISABLED 상태 없어야 함)
SELECT CONSTRAINT_NAME, TABLE_NAME, STATUS
FROM   USER_CONSTRAINTS
WHERE  CONSTRAINT_TYPE = 'R'
AND    STATUS = 'DISABLED';
*/
