-- ================================================================
-- lotNo → matUid/prdUid/supUid 컬럼 리네이밍 마이그레이션
-- 대상: JSHANES (dev/test 환경)
-- 날짜: 2026-02-27
-- ================================================================

-- 1. MAT_LOTS: LOT_NO → MAT_UID (PK)
ALTER TABLE MAT_LOTS RENAME COLUMN LOT_NO TO MAT_UID;

-- 2. MAT_STOCKS: LOT_NO → MAT_UID
ALTER TABLE MAT_STOCKS RENAME COLUMN LOT_NO TO MAT_UID;

-- 3. MAT_ISSUES: LOT_NO → MAT_UID
ALTER TABLE MAT_ISSUES RENAME COLUMN LOT_NO TO MAT_UID;

-- 4. MAT_RECEIVINGS: LOT_NO → MAT_UID
ALTER TABLE MAT_RECEIVINGS RENAME COLUMN LOT_NO TO MAT_UID;

-- 5. MAT_ARRIVALS: DROP LOT_NO, ADD IQC_STATUS + SUP_UID
ALTER TABLE MAT_ARRIVALS DROP COLUMN LOT_NO;
ALTER TABLE MAT_ARRIVALS ADD IQC_STATUS VARCHAR2(20) DEFAULT 'PENDING';
ALTER TABLE MAT_ARRIVALS ADD SUP_UID VARCHAR2(50);

-- 6. TRACE_LOGS: LOT_NO → MAT_UID, ADD PRD_UID
ALTER TABLE TRACE_LOGS RENAME COLUMN LOT_NO TO MAT_UID;
ALTER TABLE TRACE_LOGS ADD PRD_UID VARCHAR2(255);

-- 7. IQC_LOGS: LOT_NO → ARRIVAL_NO
ALTER TABLE IQC_LOGS RENAME COLUMN LOT_NO TO ARRIVAL_NO;

-- 8. LABEL_PRINT_LOGS: LOT_IDS → UID_LIST
ALTER TABLE LABEL_PRINT_LOGS RENAME COLUMN LOT_IDS TO UID_LIST;

-- 9. PROD_RESULTS: LOT_NO → PRD_UID
ALTER TABLE PROD_RESULTS RENAME COLUMN LOT_NO TO PRD_UID;

-- 10. SUBCON_DELIVERIES: LOT_NO → MAT_UID
ALTER TABLE SUBCON_DELIVERIES RENAME COLUMN LOT_NO TO MAT_UID;

-- 11. SUBCON_RECEIVES: LOT_NO → MAT_UID
ALTER TABLE SUBCON_RECEIVES RENAME COLUMN LOT_NO TO MAT_UID;

-- 12. CUSTOMS_LOTS: LOT_NO → MAT_UID
ALTER TABLE CUSTOMS_LOTS RENAME COLUMN LOT_NO TO MAT_UID;

-- 13. INV_ADJ_LOGS: LOT_NO → MAT_UID
ALTER TABLE INV_ADJ_LOGS RENAME COLUMN LOT_NO TO MAT_UID;

-- 14. PRODUCT_STOCKS: LOT_NO → PRD_UID
ALTER TABLE PRODUCT_STOCKS RENAME COLUMN LOT_NO TO PRD_UID;

-- 15. PRODUCT_TRANSACTIONS: LOT_NO → PRD_UID
ALTER TABLE PRODUCT_TRANSACTIONS RENAME COLUMN LOT_NO TO PRD_UID;

-- 16. STOCK_TRANSACTIONS: LOT_NO → MAT_UID
ALTER TABLE STOCK_TRANSACTIONS RENAME COLUMN LOT_NO TO MAT_UID;

-- NOTE: LOTS, STOCKS 테이블은 Entity 매핑 없는 레거시 테이블로 변경 제외
