-- =============================================================================
-- 소모품 UID/바코드 시스템 DDL
-- 대상: CONSUMABLE_STOCKS 테이블, F_GET_CON_UID Function, ComCode 상태값
-- 실행 환경: Oracle DB (JSHANES)
-- =============================================================================

-- 1) 시퀀스
CREATE SEQUENCE CON_UID_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;

-- 2) UID 채번 Function (prefix 'C' + YYMMDD + 5자리)
CREATE OR REPLACE FUNCTION F_GET_CON_UID RETURN VARCHAR2 IS
  v_seq NUMBER;
BEGIN
  SELECT CON_UID_SEQ.NEXTVAL INTO v_seq FROM DUAL;
  RETURN 'C' || TO_CHAR(SYSDATE, 'YYMMDD') || LPAD(v_seq, 5, '0');
END;
/

-- 3) 소모품 개별 인스턴스 테이블
CREATE TABLE CONSUMABLE_STOCKS (
  CON_UID            VARCHAR2(50)  PRIMARY KEY,
  CONSUMABLE_CODE    VARCHAR2(50)  NOT NULL,
  STATUS             VARCHAR2(20)  DEFAULT 'PENDING',
  CURRENT_COUNT      NUMBER(10)    DEFAULT 0,
  LOCATION           VARCHAR2(100),
  MOUNTED_EQUIP_CODE VARCHAR2(50),
  RECV_DATE          TIMESTAMP,
  LABEL_PRINTED_AT   TIMESTAMP,
  VENDOR_CODE        VARCHAR2(50),
  VENDOR_NAME        VARCHAR2(100),
  UNIT_PRICE         NUMBER(12,2),
  REMARK             VARCHAR2(500),
  COMPANY            VARCHAR2(50),
  PLANT_CD           VARCHAR2(50),
  CREATED_BY         VARCHAR2(50),
  UPDATED_BY         VARCHAR2(50),
  CREATED_AT         TIMESTAMP DEFAULT SYSTIMESTAMP,
  UPDATED_AT         TIMESTAMP DEFAULT SYSTIMESTAMP
);

CREATE INDEX IDX_CS_CODE ON CONSUMABLE_STOCKS (CONSUMABLE_CODE);
CREATE INDEX IDX_CS_STATUS ON CONSUMABLE_STOCKS (STATUS);

-- 4) 기존 테이블에 CON_UID 컬럼 추가
ALTER TABLE CONSUMABLE_LOGS ADD (CON_UID VARCHAR2(50));
ALTER TABLE CONSUMABLE_MOUNT_LOGS ADD (CON_UID VARCHAR2(50));

-- 5) ComCode: 소모품 인스턴스 상태
INSERT INTO COM_CODES (GROUP_CODE, CODE, CODE_NAME, SORT_ORDER, USE_YN, COMPANY)
VALUES ('CON_STOCK_STATUS', 'PENDING', '미입고', 1, 'Y', '40');

INSERT INTO COM_CODES (GROUP_CODE, CODE, CODE_NAME, SORT_ORDER, USE_YN, COMPANY)
VALUES ('CON_STOCK_STATUS', 'ACTIVE', '사용가능', 2, 'Y', '40');

INSERT INTO COM_CODES (GROUP_CODE, CODE, CODE_NAME, SORT_ORDER, USE_YN, COMPANY)
VALUES ('CON_STOCK_STATUS', 'MOUNTED', '장착중', 3, 'Y', '40');

INSERT INTO COM_CODES (GROUP_CODE, CODE, CODE_NAME, SORT_ORDER, USE_YN, COMPANY)
VALUES ('CON_STOCK_STATUS', 'REPAIR', '수리중', 4, 'Y', '40');

INSERT INTO COM_CODES (GROUP_CODE, CODE, CODE_NAME, SORT_ORDER, USE_YN, COMPANY)
VALUES ('CON_STOCK_STATUS', 'SCRAPPED', '폐기', 5, 'Y', '40');

COMMIT;
