-- ============================================================
-- 재작업 공정별 작업/실적 테이블 생성
-- 대상: REWORK_PROCESSES, REWORK_RESULTS
-- ============================================================

-- 1) REWORK_PROCESSES (재작업 공정별 작업지시)
CREATE TABLE REWORK_PROCESSES (
  ID            NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  REWORK_ORDER_ID NUMBER NOT NULL,
  PROCESS_CODE  VARCHAR2(50)   NOT NULL,
  PROCESS_NAME  VARCHAR2(200)  NOT NULL,
  SEQ           NUMBER(10)     NOT NULL,
  STATUS        VARCHAR2(30)   DEFAULT 'WAITING' NOT NULL,
  WORKER_CODE   VARCHAR2(50),
  LINE_CODE     VARCHAR2(50),
  EQUIP_CODE    VARCHAR2(50),
  PLAN_QTY      NUMBER(10)     DEFAULT 0,
  RESULT_QTY    NUMBER(10)     DEFAULT 0,
  START_AT      TIMESTAMP WITH TIME ZONE,
  END_AT        TIMESTAMP WITH TIME ZONE,
  REMARKS       VARCHAR2(1000),
  COMPANY       NUMBER         NOT NULL,
  PLANT         VARCHAR2(20)   NOT NULL,
  CREATED_BY    VARCHAR2(50),
  UPDATED_BY    VARCHAR2(50),
  CREATED_AT    TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP,
  UPDATED_AT    TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP,
  CONSTRAINT FK_REWORK_PROC_ORDER FOREIGN KEY (REWORK_ORDER_ID) REFERENCES REWORK_ORDERS(ID)
);

CREATE INDEX IDX_REWORK_PROC_COMP ON REWORK_PROCESSES (COMPANY, PLANT, REWORK_ORDER_ID);

-- 2) REWORK_RESULTS (재작업 공정별 실적)
CREATE TABLE REWORK_RESULTS (
  ID                NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  REWORK_PROCESS_ID NUMBER NOT NULL,
  WORKER_CODE       VARCHAR2(50)   NOT NULL,
  RESULT_QTY        NUMBER(10)     DEFAULT 0,
  GOOD_QTY          NUMBER(10)     DEFAULT 0,
  DEFECT_QTY        NUMBER(10)     DEFAULT 0,
  WORK_DETAIL       VARCHAR2(2000) NOT NULL,
  WORK_TIME_MIN     NUMBER(10),
  START_AT          TIMESTAMP WITH TIME ZONE,
  END_AT            TIMESTAMP WITH TIME ZONE,
  REMARKS           VARCHAR2(1000),
  COMPANY           NUMBER         NOT NULL,
  PLANT             VARCHAR2(20)   NOT NULL,
  CREATED_BY        VARCHAR2(50),
  UPDATED_BY        VARCHAR2(50),
  CREATED_AT        TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP,
  UPDATED_AT        TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP,
  CONSTRAINT FK_REWORK_RES_PROC FOREIGN KEY (REWORK_PROCESS_ID) REFERENCES REWORK_PROCESSES(ID)
);

CREATE INDEX IDX_REWORK_RES_COMP ON REWORK_RESULTS (COMPANY, PLANT, REWORK_PROCESS_ID);

COMMIT;
