-- ============================================================
-- PROCESS_QUALITY_CONDITIONS 테이블 생성
-- 공정별 양품조건(품질 검사 조건) 마스터
-- PK: ITEM_CODE + SEQ + CONDITION_SEQ
-- ============================================================

CREATE TABLE PROCESS_QUALITY_CONDITIONS (
    ITEM_CODE         VARCHAR2(36)    NOT NULL,
    SEQ               NUMBER          NOT NULL,
    CONDITION_SEQ     NUMBER          NOT NULL,
    CONDITION_CODE    VARCHAR2(50),
    MIN_VALUE         NUMBER(10,2),
    MAX_VALUE         NUMBER(10,2),
    UNIT              VARCHAR2(20),
    EQUIP_INTERFACE_YN VARCHAR2(1)    DEFAULT 'N',
    USE_YN            VARCHAR2(1)     DEFAULT 'Y' NOT NULL,
    COMPANY           VARCHAR2(255)   NOT NULL,
    PLANT_CD          VARCHAR2(255)   NOT NULL,
    CREATED_BY        VARCHAR2(255),
    UPDATED_BY        VARCHAR2(255),
    CREATED_AT        TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT        TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_PROCESS_QUALITY_COND PRIMARY KEY (ITEM_CODE, SEQ, CONDITION_SEQ)
);

COMMENT ON TABLE PROCESS_QUALITY_CONDITIONS IS '공정별 양품조건 마스터';
COMMENT ON COLUMN PROCESS_QUALITY_CONDITIONS.ITEM_CODE IS '품번 (PROCESS_MAPS FK)';
COMMENT ON COLUMN PROCESS_QUALITY_CONDITIONS.SEQ IS '공정순서 (PROCESS_MAPS FK)';
COMMENT ON COLUMN PROCESS_QUALITY_CONDITIONS.CONDITION_SEQ IS '조건 순번';
COMMENT ON COLUMN PROCESS_QUALITY_CONDITIONS.CONDITION_CODE IS '양품조건 코드 (ComCode: QUALITY_CONDITION)';
COMMENT ON COLUMN PROCESS_QUALITY_CONDITIONS.MIN_VALUE IS '정상수치 최소값';
COMMENT ON COLUMN PROCESS_QUALITY_CONDITIONS.MAX_VALUE IS '정상수치 최대값';
COMMENT ON COLUMN PROCESS_QUALITY_CONDITIONS.UNIT IS '단위 (ComCode: UNIT)';
COMMENT ON COLUMN PROCESS_QUALITY_CONDITIONS.EQUIP_INTERFACE_YN IS '설비 인터페이스 여부 (Y/N)';
COMMENT ON COLUMN PROCESS_QUALITY_CONDITIONS.USE_YN IS '사용여부';
