-- WORK_CALENDAR_DAYS 테이블 생성
CREATE TABLE WORK_CALENDAR_DAYS (
  CALENDAR_ID   VARCHAR2(50)  NOT NULL,
  WORK_DATE     DATE          NOT NULL,
  DAY_TYPE      VARCHAR2(20)  DEFAULT 'WORK',
  OFF_REASON    VARCHAR2(20),
  SHIFT_COUNT   NUMBER(1)     DEFAULT 1,
  SHIFTS        VARCHAR2(100),
  WORK_MINUTES  NUMBER(5)     DEFAULT 0,
  OT_MINUTES    NUMBER(5)     DEFAULT 0,
  REMARK        VARCHAR2(500),
  COMPANY       VARCHAR2(50),
  PLANT_CD      VARCHAR2(50),
  CREATED_BY    VARCHAR2(50),
  UPDATED_BY    VARCHAR2(50),
  CREATED_AT    TIMESTAMP     DEFAULT SYSTIMESTAMP,
  UPDATED_AT    TIMESTAMP     DEFAULT SYSTIMESTAMP,
  CONSTRAINT PK_WORK_CALENDAR_DAYS PRIMARY KEY (CALENDAR_ID, WORK_DATE)
)
