-- WORK_CALENDARS 테이블 생성
CREATE TABLE WORK_CALENDARS (
  CALENDAR_ID         VARCHAR2(50)  NOT NULL,
  CALENDAR_YEAR       VARCHAR2(4)   NOT NULL,
  PROCESS_CD          VARCHAR2(50),
  DEFAULT_SHIFT_COUNT NUMBER(1)     DEFAULT 1,
  DEFAULT_SHIFTS      VARCHAR2(100),
  STATUS              VARCHAR2(20)  DEFAULT 'DRAFT',
  REMARK              VARCHAR2(500),
  COMPANY             VARCHAR2(50),
  PLANT_CD            VARCHAR2(50),
  CREATED_BY          VARCHAR2(50),
  UPDATED_BY          VARCHAR2(50),
  CREATED_AT          TIMESTAMP     DEFAULT SYSTIMESTAMP,
  UPDATED_AT          TIMESTAMP     DEFAULT SYSTIMESTAMP,
  CONSTRAINT PK_WORK_CALENDARS PRIMARY KEY (CALENDAR_ID),
  CONSTRAINT UQ_WORK_CAL_YEAR_PROC UNIQUE (COMPANY, PLANT_CD, CALENDAR_YEAR, PROCESS_CD)
)
