CREATE TABLE PHYSICAL_INV_COUNT_DETAILS (
    SESSION_DATE     DATE            NOT NULL,
    SEQ              NUMBER(10)      NOT NULL,
    WAREHOUSE_CODE   VARCHAR2(50)    NOT NULL,
    ITEM_CODE        VARCHAR2(50)    NOT NULL,
    MAT_UID          VARCHAR2(50)    NOT NULL,
    LOCATION_CODE    VARCHAR2(50),
    SYSTEM_QTY       NUMBER(10)      DEFAULT 0 NOT NULL,
    COUNTED_QTY      NUMBER(10)      DEFAULT 0 NOT NULL,
    COUNTED_BY       VARCHAR2(50),
    REMARK           VARCHAR2(500),
    CREATED_AT       TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT       TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_PHYS_INV_COUNT_DTL PRIMARY KEY (SESSION_DATE, SEQ, WAREHOUSE_CODE, ITEM_CODE, MAT_UID)
)
