CREATE TABLE SHIFT_PATTERNS (
  COMPANY       VARCHAR2(50)  NOT NULL,
  PLANT_CD      VARCHAR2(50)  NOT NULL,
  SHIFT_CODE    VARCHAR2(20)  NOT NULL,
  SHIFT_NAME    VARCHAR2(100) NOT NULL,
  START_TIME    VARCHAR2(5)   NOT NULL,
  END_TIME      VARCHAR2(5)   NOT NULL,
  BREAK_MINUTES NUMBER(4)     DEFAULT 60,
  WORK_MINUTES  NUMBER(5)     DEFAULT 0,
  SORT_ORDER    NUMBER(3)     DEFAULT 0,
  USE_YN        VARCHAR2(1)   DEFAULT 'Y',
  CREATED_BY    VARCHAR2(50),
  UPDATED_BY    VARCHAR2(50),
  CREATED_AT    TIMESTAMP     DEFAULT SYSTIMESTAMP,
  UPDATED_AT    TIMESTAMP     DEFAULT SYSTIMESTAMP,
  CONSTRAINT PK_SHIFT_PATTERNS PRIMARY KEY (COMPANY, PLANT_CD, SHIFT_CODE)
)
