-- ============================================================
-- 스케줄러 관리 모듈 DDL
-- 실행 대상: Oracle (HNSMES 스키마)
-- ============================================================

-- 1. SCHEDULER_JOBS (스케줄 작업 정의)
CREATE TABLE SCHEDULER_JOBS (
  COMPANY       VARCHAR2(20)    NOT NULL,
  PLANT_CD      VARCHAR2(20)    NOT NULL,
  JOB_CODE      VARCHAR2(50)    NOT NULL,
  JOB_NAME      NVARCHAR2(100)  NOT NULL,
  JOB_GROUP     VARCHAR2(20),
  EXEC_TYPE     VARCHAR2(20),
  EXEC_TARGET   NVARCHAR2(500),
  EXEC_PARAMS   NVARCHAR2(2000),
  CRON_EXPR     VARCHAR2(50),
  IS_ACTIVE     CHAR(1)         DEFAULT 'N',
  MAX_RETRY     NUMBER(3)       DEFAULT 0,
  TIMEOUT_SEC   NUMBER(5)       DEFAULT 300,
  DESCRIPTION   NVARCHAR2(500),
  LAST_RUN_AT   TIMESTAMP,
  LAST_STATUS   VARCHAR2(20),
  LAST_ERROR_AT TIMESTAMP,
  NEXT_RUN_AT   TIMESTAMP,
  CREATED_BY    VARCHAR2(50),
  CREATED_AT    TIMESTAMP       DEFAULT SYSTIMESTAMP,
  UPDATED_BY    VARCHAR2(50),
  UPDATED_AT    TIMESTAMP       DEFAULT SYSTIMESTAMP,
  CONSTRAINT PK_SCHEDULER_JOBS PRIMARY KEY (COMPANY, PLANT_CD, JOB_CODE)
);

COMMENT ON TABLE SCHEDULER_JOBS IS '스케줄러 작업 정의';
COMMENT ON COLUMN SCHEDULER_JOBS.COMPANY IS '회사코드 (멀티테넌시)';
COMMENT ON COLUMN SCHEDULER_JOBS.PLANT_CD IS '사업장코드';
COMMENT ON COLUMN SCHEDULER_JOBS.JOB_CODE IS '작업코드';
COMMENT ON COLUMN SCHEDULER_JOBS.JOB_NAME IS '작업명';
COMMENT ON COLUMN SCHEDULER_JOBS.JOB_GROUP IS '작업그룹 (ComCode SCHED_GROUP)';
COMMENT ON COLUMN SCHEDULER_JOBS.EXEC_TYPE IS '실행유형 (SERVICE/PROCEDURE/SQL/HTTP/SCRIPT)';
COMMENT ON COLUMN SCHEDULER_JOBS.EXEC_TARGET IS '실행대상 (프로시저명, URL 등)';
COMMENT ON COLUMN SCHEDULER_JOBS.EXEC_PARAMS IS 'JSON 파라미터';
COMMENT ON COLUMN SCHEDULER_JOBS.CRON_EXPR IS '크론 표현식';
COMMENT ON COLUMN SCHEDULER_JOBS.IS_ACTIVE IS '활성여부 (Y/N)';
COMMENT ON COLUMN SCHEDULER_JOBS.MAX_RETRY IS '최대 재시도 횟수';
COMMENT ON COLUMN SCHEDULER_JOBS.TIMEOUT_SEC IS '타임아웃 (초)';

-- 2. SCHEDULER_LOGS (실행 이력)
CREATE TABLE SCHEDULER_LOGS (
  COMPANY       VARCHAR2(20)    NOT NULL,
  PLANT_CD      VARCHAR2(20)    NOT NULL,
  LOG_ID        NUMBER          NOT NULL,
  JOB_CODE      VARCHAR2(50),
  START_TIME    TIMESTAMP,
  END_TIME      TIMESTAMP,
  DURATION_MS   NUMBER(10),
  STATUS        VARCHAR2(20),
  RESULT_MSG    NVARCHAR2(2000),
  ERROR_MSG     NVARCHAR2(4000),
  RETRY_COUNT   NUMBER(3)       DEFAULT 0,
  AFFECTED_ROWS NUMBER(10),
  CREATED_AT    TIMESTAMP       DEFAULT SYSTIMESTAMP,
  UPDATED_AT    TIMESTAMP       DEFAULT SYSTIMESTAMP,
  CONSTRAINT PK_SCHEDULER_LOGS PRIMARY KEY (COMPANY, PLANT_CD, LOG_ID),
  CONSTRAINT FK_SCHED_LOGS_JOB FOREIGN KEY (COMPANY, PLANT_CD, JOB_CODE)
    REFERENCES SCHEDULER_JOBS (COMPANY, PLANT_CD, JOB_CODE)
);

CREATE INDEX IDX_SCHED_LOGS_SEARCH ON SCHEDULER_LOGS (COMPANY, PLANT_CD, START_TIME, STATUS);

COMMENT ON TABLE SCHEDULER_LOGS IS '스케줄러 실행 이력';
COMMENT ON COLUMN SCHEDULER_LOGS.LOG_ID IS '로그 ID (시퀀스)';
COMMENT ON COLUMN SCHEDULER_LOGS.STATUS IS '실행상태 (SUCCESS/FAIL/RUNNING/RETRYING/TIMEOUT/SKIPPED)';

-- 3. SCHEDULER_NOTIFICATIONS (알림)
CREATE TABLE SCHEDULER_NOTIFICATIONS (
  COMPANY       VARCHAR2(20)    NOT NULL,
  NOTI_ID       NUMBER          NOT NULL,
  JOB_CODE      VARCHAR2(50),
  PLANT_CD      VARCHAR2(20),
  USER_ID       VARCHAR2(50),
  NOTI_TYPE     VARCHAR2(20),
  MESSAGE       NVARCHAR2(500),
  IS_READ       CHAR(1)         DEFAULT 'N',
  CREATED_AT    TIMESTAMP       DEFAULT SYSTIMESTAMP,
  UPDATED_AT    TIMESTAMP       DEFAULT SYSTIMESTAMP,
  CONSTRAINT PK_SCHEDULER_NOTI PRIMARY KEY (COMPANY, NOTI_ID)
);

COMMENT ON TABLE SCHEDULER_NOTIFICATIONS IS '스케줄러 알림';
COMMENT ON COLUMN SCHEDULER_NOTIFICATIONS.NOTI_TYPE IS '알림유형 (FAIL/TIMEOUT/SUCCESS)';
COMMENT ON COLUMN SCHEDULER_NOTIFICATIONS.IS_READ IS '읽음여부 (Y/N)';
