-- ============================================================
-- PDA 역할 관련 테이블 생성 마이그레이션
-- 파일: scripts/migration/create_pda_role_tables.sql
-- 설명: PDA 단말기 접근 제어를 위한 역할/메뉴 테이블 생성 및 기본 데이터 시드
--
-- 실행 순서:
-- 1. PDA_ROLE 테이블 생성
-- 2. PDA_ROLE_MENU 테이블 생성 + 시퀀스
-- 3. USERS 테이블에 PDA_ROLE_CODE 컬럼 추가
-- 4. 기본 역할 3개 시드 (PDA_ADMIN / PDA_MATERIAL / PDA_SHIPPING)
-- 5. PDA_ADMIN에 모든 메뉴 권한 INSERT
-- ============================================================

-- ============================================================
-- 1. PDA_ROLE 테이블
-- ============================================================
CREATE TABLE PDA_ROLE (
    CODE        VARCHAR2(50)   NOT NULL,
    NAME        VARCHAR2(100)  NOT NULL,
    DESCRIPTION VARCHAR2(500),
    IS_ACTIVE   CHAR(1)        DEFAULT 'Y' NOT NULL,
    COMPANY     VARCHAR2(50),
    PLANT_CD    VARCHAR2(50),
    CREATED_BY  VARCHAR2(50),
    UPDATED_BY  VARCHAR2(50),
    CREATED_AT  TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT  TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_PDA_ROLE PRIMARY KEY (CODE),
    CONSTRAINT CHK_PDA_ROLE_ACTIVE CHECK (IS_ACTIVE IN ('Y', 'N'))
);

COMMENT ON TABLE  PDA_ROLE             IS 'PDA 역할 정의 테이블';
COMMENT ON COLUMN PDA_ROLE.CODE        IS '역할 코드 (PK)';
COMMENT ON COLUMN PDA_ROLE.NAME        IS '역할 이름';
COMMENT ON COLUMN PDA_ROLE.DESCRIPTION IS '역할 설명';
COMMENT ON COLUMN PDA_ROLE.IS_ACTIVE   IS '활성 여부 (Y/N)';
COMMENT ON COLUMN PDA_ROLE.COMPANY     IS '회사 코드';
COMMENT ON COLUMN PDA_ROLE.PLANT_CD    IS '공장 코드';

-- ============================================================
-- 2. PDA_ROLE_MENU 시퀀스 + 테이블
-- ============================================================
CREATE SEQUENCE SEQ_PDA_ROLE_MENU_ID
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE TABLE PDA_ROLE_MENU (
    ID            NUMBER         NOT NULL,
    PDA_ROLE_CODE VARCHAR2(50)   NOT NULL,
    MENU_CODE     VARCHAR2(50)   NOT NULL,
    IS_ACTIVE     CHAR(1)        DEFAULT 'Y' NOT NULL,
    CREATED_AT    TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT    TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_PDA_ROLE_MENU PRIMARY KEY (ID),
    CONSTRAINT UK_PDA_ROLE_MENU UNIQUE (PDA_ROLE_CODE, MENU_CODE),
    CONSTRAINT FK_PDA_ROLE_MENU_ROLE FOREIGN KEY (PDA_ROLE_CODE)
        REFERENCES PDA_ROLE (CODE) ON DELETE CASCADE,
    CONSTRAINT CHK_PDA_ROLE_MENU_ACTIVE CHECK (IS_ACTIVE IN ('Y', 'N'))
);

COMMENT ON TABLE  PDA_ROLE_MENU               IS 'PDA 역할-메뉴 매핑 테이블';
COMMENT ON COLUMN PDA_ROLE_MENU.ID            IS '자동증가 PK (시퀀스)';
COMMENT ON COLUMN PDA_ROLE_MENU.PDA_ROLE_CODE IS 'PDA 역할 코드 (FK)';
COMMENT ON COLUMN PDA_ROLE_MENU.MENU_CODE     IS 'PDA 메뉴 코드';
COMMENT ON COLUMN PDA_ROLE_MENU.IS_ACTIVE     IS '활성 여부 (Y/N)';

-- ============================================================
-- 3. USERS 테이블에 PDA_ROLE_CODE 컬럼 추가
-- ============================================================
ALTER TABLE USERS ADD (
    PDA_ROLE_CODE VARCHAR2(50)
);

COMMENT ON COLUMN USERS.PDA_ROLE_CODE IS 'PDA 역할 코드 (FK → PDA_ROLE.CODE, nullable)';

-- ============================================================
-- 4. 기본 역할 3개 시드
-- ============================================================
INSERT INTO PDA_ROLE (CODE, NAME, DESCRIPTION, IS_ACTIVE, CREATED_AT, UPDATED_AT)
VALUES ('PDA_ADMIN', 'PDA 관리자', 'PDA 전체 메뉴 접근 가능한 관리자 역할', 'Y', SYSTIMESTAMP, SYSTIMESTAMP);

INSERT INTO PDA_ROLE (CODE, NAME, DESCRIPTION, IS_ACTIVE, CREATED_AT, UPDATED_AT)
VALUES ('PDA_MATERIAL', 'PDA 자재담당', '자재 입고/불출/조정/실사 메뉴 접근 가능', 'Y', SYSTIMESTAMP, SYSTIMESTAMP);

INSERT INTO PDA_ROLE (CODE, NAME, DESCRIPTION, IS_ACTIVE, CREATED_AT, UPDATED_AT)
VALUES ('PDA_SHIPPING', 'PDA 출하담당', '출하 메뉴 접근 가능', 'Y', SYSTIMESTAMP, SYSTIMESTAMP);

-- ============================================================
-- 5. PDA_ADMIN에 모든 메뉴 권한 INSERT
-- ============================================================
INSERT INTO PDA_ROLE_MENU (ID, PDA_ROLE_CODE, MENU_CODE, IS_ACTIVE, CREATED_AT, UPDATED_AT)
VALUES (SEQ_PDA_ROLE_MENU_ID.NEXTVAL, 'PDA_ADMIN', 'PDA_MAT_RECEIVING', 'Y', SYSTIMESTAMP, SYSTIMESTAMP);

INSERT INTO PDA_ROLE_MENU (ID, PDA_ROLE_CODE, MENU_CODE, IS_ACTIVE, CREATED_AT, UPDATED_AT)
VALUES (SEQ_PDA_ROLE_MENU_ID.NEXTVAL, 'PDA_ADMIN', 'PDA_MAT_ISSUING', 'Y', SYSTIMESTAMP, SYSTIMESTAMP);

INSERT INTO PDA_ROLE_MENU (ID, PDA_ROLE_CODE, MENU_CODE, IS_ACTIVE, CREATED_AT, UPDATED_AT)
VALUES (SEQ_PDA_ROLE_MENU_ID.NEXTVAL, 'PDA_ADMIN', 'PDA_MAT_ADJUSTMENT', 'Y', SYSTIMESTAMP, SYSTIMESTAMP);

INSERT INTO PDA_ROLE_MENU (ID, PDA_ROLE_CODE, MENU_CODE, IS_ACTIVE, CREATED_AT, UPDATED_AT)
VALUES (SEQ_PDA_ROLE_MENU_ID.NEXTVAL, 'PDA_ADMIN', 'PDA_MAT_INV_COUNT', 'Y', SYSTIMESTAMP, SYSTIMESTAMP);

INSERT INTO PDA_ROLE_MENU (ID, PDA_ROLE_CODE, MENU_CODE, IS_ACTIVE, CREATED_AT, UPDATED_AT)
VALUES (SEQ_PDA_ROLE_MENU_ID.NEXTVAL, 'PDA_ADMIN', 'PDA_SHIPPING', 'Y', SYSTIMESTAMP, SYSTIMESTAMP);

INSERT INTO PDA_ROLE_MENU (ID, PDA_ROLE_CODE, MENU_CODE, IS_ACTIVE, CREATED_AT, UPDATED_AT)
VALUES (SEQ_PDA_ROLE_MENU_ID.NEXTVAL, 'PDA_ADMIN', 'PDA_EQUIP_INSPECT', 'Y', SYSTIMESTAMP, SYSTIMESTAMP);

INSERT INTO PDA_ROLE_MENU (ID, PDA_ROLE_CODE, MENU_CODE, IS_ACTIVE, CREATED_AT, UPDATED_AT)
VALUES (SEQ_PDA_ROLE_MENU_ID.NEXTVAL, 'PDA_ADMIN', 'PDA_PRODUCT_INV_COUNT', 'Y', SYSTIMESTAMP, SYSTIMESTAMP);

COMMIT;
