CREATE OR REPLACE FUNCTION F_GET_CON_UID RETURN VARCHAR2 IS
  v_seq NUMBER;
BEGIN
  SELECT CON_UID_SEQ.NEXTVAL INTO v_seq FROM DUAL;
  RETURN 'C' || TO_CHAR(SYSDATE, 'YYMMDD') || LPAD(v_seq, 5, '0');
END;
