CREATE OR REPLACE FUNCTION F_GET_MAT_UID RETURN VARCHAR2 IS
  v_seq NUMBER;
  v_prefix VARCHAR2(10);
BEGIN
  v_prefix := 'M' || TO_CHAR(SYSDATE, 'YYMMDD');
  SELECT MAT_UID_SEQ.NEXTVAL INTO v_seq FROM DUAL;
  RETURN v_prefix || LPAD(v_seq, 5, '0');
END;
