-- =================================================================
-- PPAP_SUBMISSIONS 시드 데이터
-- 실제 ITEM_MASTERS / PARTNER_MASTERS 품목 기준
-- COMPANY: 40, PLANT: 1000 (HANES)
-- =================================================================

-- 1) 엔진룸 하네스 Assy - 신규부품 PPAP Level 3, 승인완료
INSERT INTO PPAP_SUBMISSIONS (
  PPAP_NO, ITEM_CODE, ITEM_NAME, CUSTOMER_CODE, CUSTOMER_NAME,
  PPAP_LEVEL, REASON, STATUS, SUBMITTED_AT, APPROVED_AT, APPROVED_BY,
  REJECTED_REASON,
  DESIGN_RECORDS, ECN_DOCUMENTS, CUSTOMER_APPROVAL, DFMEA,
  PROCESS_FLOW_DIAGRAM, PFMEA, CONTROL_PLAN, MSA_STUDIES,
  DIMENSIONAL_RESULTS, MATERIAL_TEST_RESULTS, INITIAL_PROCESS_STUDIES,
  QUALIFIED_LAB_DOC, APPEARANCE_APPROVAL, SAMPLE_PRODUCT,
  MASTER_SAMPLE, CHECKING_AIDS, CUSTOMER_SPECIFIC_REQ, PART_SUBMISSION_WARRANT,
  REMARKS, COMPANY, PLANT, CREATED_BY, UPDATED_BY, CREATED_AT, UPDATED_AT
) VALUES (
  'PPAP-20260210-001', 'FG-EH-001', '엔진룸 하네스 Assy', 'CUS-001', '현대자동차',
  3, 'NEW_PART', 'APPROVED', TIMESTAMP '2026-02-12 09:30:00', TIMESTAMP '2026-02-18 14:00:00', 'admin',
  NULL,
  1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
  '신규 양산 승인 완료', '40', '1000', 'admin', 'admin', TIMESTAMP '2026-02-10 10:00:00', TIMESTAMP '2026-02-18 14:00:00'
);

-- 2) 6P 커넥터 하우징 - 금형변경, 제출됨 (Level 2)
INSERT INTO PPAP_SUBMISSIONS (
  PPAP_NO, ITEM_CODE, ITEM_NAME, CUSTOMER_CODE, CUSTOMER_NAME,
  PPAP_LEVEL, REASON, STATUS, SUBMITTED_AT, APPROVED_AT, APPROVED_BY,
  REJECTED_REASON,
  DESIGN_RECORDS, ECN_DOCUMENTS, CUSTOMER_APPROVAL, DFMEA,
  PROCESS_FLOW_DIAGRAM, PFMEA, CONTROL_PLAN, MSA_STUDIES,
  DIMENSIONAL_RESULTS, MATERIAL_TEST_RESULTS, INITIAL_PROCESS_STUDIES,
  QUALIFIED_LAB_DOC, APPEARANCE_APPROVAL, SAMPLE_PRODUCT,
  MASTER_SAMPLE, CHECKING_AIDS, CUSTOMER_SPECIFIC_REQ, PART_SUBMISSION_WARRANT,
  REMARKS, COMPANY, PLANT, CREATED_BY, UPDATED_BY, CREATED_AT, UPDATED_AT
) VALUES (
  'PPAP-20260225-001', 'RAW-C-001', '6P 커넥터 하우징', 'CUS-001', '현대자동차',
  2, 'TOOLING', 'SUBMITTED', TIMESTAMP '2026-02-28 10:00:00', NULL, NULL,
  NULL,
  1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1,
  '금형 2차 개선 후 재제출', '40', '1000', 'admin', 'admin', TIMESTAMP '2026-02-25 09:00:00', TIMESTAMP '2026-02-28 10:00:00'
);

-- 3) 10P 커넥터 하우징 - 설계변경(ECN), 반려 (Level 3)
INSERT INTO PPAP_SUBMISSIONS (
  PPAP_NO, ITEM_CODE, ITEM_NAME, CUSTOMER_CODE, CUSTOMER_NAME,
  PPAP_LEVEL, REASON, STATUS, SUBMITTED_AT, APPROVED_AT, APPROVED_BY,
  REJECTED_REASON,
  DESIGN_RECORDS, ECN_DOCUMENTS, CUSTOMER_APPROVAL, DFMEA,
  PROCESS_FLOW_DIAGRAM, PFMEA, CONTROL_PLAN, MSA_STUDIES,
  DIMENSIONAL_RESULTS, MATERIAL_TEST_RESULTS, INITIAL_PROCESS_STUDIES,
  QUALIFIED_LAB_DOC, APPEARANCE_APPROVAL, SAMPLE_PRODUCT,
  MASTER_SAMPLE, CHECKING_AIDS, CUSTOMER_SPECIFIC_REQ, PART_SUBMISSION_WARRANT,
  REMARKS, COMPANY, PLANT, CREATED_BY, UPDATED_BY, CREATED_AT, UPDATED_AT
) VALUES (
  'PPAP-20260301-001', 'RAW-C-002', '10P 커넥터 하우징', 'CUS-002', '기아자동차',
  3, 'ECN', 'REJECTED', TIMESTAMP '2026-03-03 11:00:00', NULL, NULL,
  '치수 측정결과 불합격 - 핀 간격 공차 초과 (±0.05mm 기준 ±0.12mm)',
  1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1,
  'ECN-2026-0045 도면 변경 반영', '40', '1000', 'admin', 'admin', TIMESTAMP '2026-03-01 08:30:00', TIMESTAMP '2026-03-05 16:00:00'
);

-- 4) 090형 암단자 - 신규부품, 작성중 (Level 1)
INSERT INTO PPAP_SUBMISSIONS (
  PPAP_NO, ITEM_CODE, ITEM_NAME, CUSTOMER_CODE, CUSTOMER_NAME,
  PPAP_LEVEL, REASON, STATUS, SUBMITTED_AT, APPROVED_AT, APPROVED_BY,
  REJECTED_REASON,
  DESIGN_RECORDS, ECN_DOCUMENTS, CUSTOMER_APPROVAL, DFMEA,
  PROCESS_FLOW_DIAGRAM, PFMEA, CONTROL_PLAN, MSA_STUDIES,
  DIMENSIONAL_RESULTS, MATERIAL_TEST_RESULTS, INITIAL_PROCESS_STUDIES,
  QUALIFIED_LAB_DOC, APPEARANCE_APPROVAL, SAMPLE_PRODUCT,
  MASTER_SAMPLE, CHECKING_AIDS, CUSTOMER_SPECIFIC_REQ, PART_SUBMISSION_WARRANT,
  REMARKS, COMPANY, PLANT, CREATED_BY, UPDATED_BY, CREATED_AT, UPDATED_AT
) VALUES (
  'PPAP-20260310-001', 'RAW-T-001', '090형 암단자', 'CUS-001', '현대자동차',
  1, 'NEW_PART', 'DRAFT', NULL, NULL, NULL,
  NULL,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
  'PSW 작성 중', '40', '1000', 'admin', 'admin', TIMESTAMP '2026-03-10 13:00:00', TIMESTAMP '2026-03-10 13:00:00'
);

-- 5) AVS 0.5sq 흑색 전선 - 시정조치, 잠정승인 (Level 3)
INSERT INTO PPAP_SUBMISSIONS (
  PPAP_NO, ITEM_CODE, ITEM_NAME, CUSTOMER_CODE, CUSTOMER_NAME,
  PPAP_LEVEL, REASON, STATUS, SUBMITTED_AT, APPROVED_AT, APPROVED_BY,
  REJECTED_REASON,
  DESIGN_RECORDS, ECN_DOCUMENTS, CUSTOMER_APPROVAL, DFMEA,
  PROCESS_FLOW_DIAGRAM, PFMEA, CONTROL_PLAN, MSA_STUDIES,
  DIMENSIONAL_RESULTS, MATERIAL_TEST_RESULTS, INITIAL_PROCESS_STUDIES,
  QUALIFIED_LAB_DOC, APPEARANCE_APPROVAL, SAMPLE_PRODUCT,
  MASTER_SAMPLE, CHECKING_AIDS, CUSTOMER_SPECIFIC_REQ, PART_SUBMISSION_WARRANT,
  REMARKS, COMPANY, PLANT, CREATED_BY, UPDATED_BY, CREATED_AT, UPDATED_AT
) VALUES (
  'PPAP-20260305-001', 'RAW-W-001', 'AVS 0.5sq 흑색 전선', 'CUS-002', '기아자동차',
  3, 'CORRECTION', 'INTERIM', TIMESTAMP '2026-03-07 09:00:00', TIMESTAMP '2026-03-10 11:30:00', 'admin',
  NULL,
  1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
  '피복 내열 시험 재진행 필요 - 90일 잠정승인', '40', '1000', 'admin', 'admin', TIMESTAMP '2026-03-05 10:00:00', TIMESTAMP '2026-03-10 11:30:00'
);

-- 6) 코루게이트 튜브 10mm - 기타 사유, 작성중 (Level 2)
INSERT INTO PPAP_SUBMISSIONS (
  PPAP_NO, ITEM_CODE, ITEM_NAME, CUSTOMER_CODE, CUSTOMER_NAME,
  PPAP_LEVEL, REASON, STATUS, SUBMITTED_AT, APPROVED_AT, APPROVED_BY,
  REJECTED_REASON,
  DESIGN_RECORDS, ECN_DOCUMENTS, CUSTOMER_APPROVAL, DFMEA,
  PROCESS_FLOW_DIAGRAM, PFMEA, CONTROL_PLAN, MSA_STUDIES,
  DIMENSIONAL_RESULTS, MATERIAL_TEST_RESULTS, INITIAL_PROCESS_STUDIES,
  QUALIFIED_LAB_DOC, APPEARANCE_APPROVAL, SAMPLE_PRODUCT,
  MASTER_SAMPLE, CHECKING_AIDS, CUSTOMER_SPECIFIC_REQ, PART_SUBMISSION_WARRANT,
  REMARKS, COMPANY, PLANT, CREATED_BY, UPDATED_BY, CREATED_AT, UPDATED_AT
) VALUES (
  'PPAP-20260315-001', 'RAW-P-001', '코루게이트 튜브 10mm', 'CUS-001', '현대자동차',
  2, 'OTHER', 'DRAFT', NULL, NULL, NULL,
  NULL,
  1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0,
  '공급업체 변경에 따른 재승인', '40', '1000', 'admin', 'admin', TIMESTAMP '2026-03-15 14:00:00', TIMESTAMP '2026-03-15 14:00:00'
);

-- 7) 250형 암단자 - ECN, 승인완료 (Level 5)
INSERT INTO PPAP_SUBMISSIONS (
  PPAP_NO, ITEM_CODE, ITEM_NAME, CUSTOMER_CODE, CUSTOMER_NAME,
  PPAP_LEVEL, REASON, STATUS, SUBMITTED_AT, APPROVED_AT, APPROVED_BY,
  REJECTED_REASON,
  DESIGN_RECORDS, ECN_DOCUMENTS, CUSTOMER_APPROVAL, DFMEA,
  PROCESS_FLOW_DIAGRAM, PFMEA, CONTROL_PLAN, MSA_STUDIES,
  DIMENSIONAL_RESULTS, MATERIAL_TEST_RESULTS, INITIAL_PROCESS_STUDIES,
  QUALIFIED_LAB_DOC, APPEARANCE_APPROVAL, SAMPLE_PRODUCT,
  MASTER_SAMPLE, CHECKING_AIDS, CUSTOMER_SPECIFIC_REQ, PART_SUBMISSION_WARRANT,
  REMARKS, COMPANY, PLANT, CREATED_BY, UPDATED_BY, CREATED_AT, UPDATED_AT
) VALUES (
  'PPAP-20260220-001', 'RAW-T-003', '250형 암단자', 'CUS-002', '기아자동차',
  5, 'ECN', 'APPROVED', TIMESTAMP '2026-02-22 10:00:00', TIMESTAMP '2026-03-01 15:00:00', 'admin',
  NULL,
  1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
  '고객 최상위 레벨 요구 - 전체 요소 완료', '40', '1000', 'admin', 'admin', TIMESTAMP '2026-02-20 09:00:00', TIMESTAMP '2026-03-01 15:00:00'
);

-- 8) 2P 방수커넥터 - 신규부품, 제출됨 (Level 4)
INSERT INTO PPAP_SUBMISSIONS (
  PPAP_NO, ITEM_CODE, ITEM_NAME, CUSTOMER_CODE, CUSTOMER_NAME,
  PPAP_LEVEL, REASON, STATUS, SUBMITTED_AT, APPROVED_AT, APPROVED_BY,
  REJECTED_REASON,
  DESIGN_RECORDS, ECN_DOCUMENTS, CUSTOMER_APPROVAL, DFMEA,
  PROCESS_FLOW_DIAGRAM, PFMEA, CONTROL_PLAN, MSA_STUDIES,
  DIMENSIONAL_RESULTS, MATERIAL_TEST_RESULTS, INITIAL_PROCESS_STUDIES,
  QUALIFIED_LAB_DOC, APPEARANCE_APPROVAL, SAMPLE_PRODUCT,
  MASTER_SAMPLE, CHECKING_AIDS, CUSTOMER_SPECIFIC_REQ, PART_SUBMISSION_WARRANT,
  REMARKS, COMPANY, PLANT, CREATED_BY, UPDATED_BY, CREATED_AT, UPDATED_AT
) VALUES (
  'PPAP-20260312-001', 'RAW-C-004', '2P 방수커넥터', 'CUS-001', '현대자동차',
  4, 'NEW_PART', 'SUBMITTED', TIMESTAMP '2026-03-14 09:30:00', NULL, NULL,
  NULL,
  1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
  'IP67 방수 성능 검증 포함', '40', '1000', 'admin', 'admin', TIMESTAMP '2026-03-12 11:00:00', TIMESTAMP '2026-03-14 09:30:00'
);

-- 9) 환형단자 M6 - 금형변경, 승인완료 (Level 2)
INSERT INTO PPAP_SUBMISSIONS (
  PPAP_NO, ITEM_CODE, ITEM_NAME, CUSTOMER_CODE, CUSTOMER_NAME,
  PPAP_LEVEL, REASON, STATUS, SUBMITTED_AT, APPROVED_AT, APPROVED_BY,
  REJECTED_REASON,
  DESIGN_RECORDS, ECN_DOCUMENTS, CUSTOMER_APPROVAL, DFMEA,
  PROCESS_FLOW_DIAGRAM, PFMEA, CONTROL_PLAN, MSA_STUDIES,
  DIMENSIONAL_RESULTS, MATERIAL_TEST_RESULTS, INITIAL_PROCESS_STUDIES,
  QUALIFIED_LAB_DOC, APPEARANCE_APPROVAL, SAMPLE_PRODUCT,
  MASTER_SAMPLE, CHECKING_AIDS, CUSTOMER_SPECIFIC_REQ, PART_SUBMISSION_WARRANT,
  REMARKS, COMPANY, PLANT, CREATED_BY, UPDATED_BY, CREATED_AT, UPDATED_AT
) VALUES (
  'PPAP-20260128-001', 'RAW-T-005', '환형단자 M6', 'CUS-002', '기아자동차',
  2, 'TOOLING', 'APPROVED', TIMESTAMP '2026-01-30 10:00:00', TIMESTAMP '2026-02-05 16:00:00', 'admin',
  NULL,
  1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1,
  '금형 이관 완료', '40', '1000', 'admin', 'admin', TIMESTAMP '2026-01-28 09:00:00', TIMESTAMP '2026-02-05 16:00:00'
);

-- 10) 비닐테이프 19mm - 시정조치, 작성중 (Level 1)
INSERT INTO PPAP_SUBMISSIONS (
  PPAP_NO, ITEM_CODE, ITEM_NAME, CUSTOMER_CODE, CUSTOMER_NAME,
  PPAP_LEVEL, REASON, STATUS, SUBMITTED_AT, APPROVED_AT, APPROVED_BY,
  REJECTED_REASON,
  DESIGN_RECORDS, ECN_DOCUMENTS, CUSTOMER_APPROVAL, DFMEA,
  PROCESS_FLOW_DIAGRAM, PFMEA, CONTROL_PLAN, MSA_STUDIES,
  DIMENSIONAL_RESULTS, MATERIAL_TEST_RESULTS, INITIAL_PROCESS_STUDIES,
  QUALIFIED_LAB_DOC, APPEARANCE_APPROVAL, SAMPLE_PRODUCT,
  MASTER_SAMPLE, CHECKING_AIDS, CUSTOMER_SPECIFIC_REQ, PART_SUBMISSION_WARRANT,
  REMARKS, COMPANY, PLANT, CREATED_BY, UPDATED_BY, CREATED_AT, UPDATED_AT
) VALUES (
  'PPAP-20260317-001', 'RAW-P-002', '비닐테이프 19mm', 'CUS-001', '현대자동차',
  1, 'CORRECTION', 'DRAFT', NULL, NULL, NULL,
  NULL,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  '접착력 불량 시정조치 보고서 작성 예정', '40', '1000', 'admin', 'admin', TIMESTAMP '2026-03-17 15:00:00', TIMESTAMP '2026-03-17 15:00:00'
);

COMMIT;
