/**
 * @file seed_audits.sql
 * @description AUDIT_PLANS + AUDIT_FINDINGS 시드 데이터
 *   - IATF 16949 내부심사 샘플 8건 (다양한 상태/유형)
 *   - 발견사항 10건
 *   - FINDING_CATEGORY, FINDING_STATUS ComCode 포함
 *   - COMPANY='40', PLANT='1000' (JSHANES)
 */

-- ============================================================
-- 1) ComCode: FINDING_CATEGORY (발견사항 분류)
-- ============================================================
MERGE INTO "COM_CODES" t
USING (
  SELECT 'FINDING_CATEGORY' AS "GROUP_CODE", 'NC_MAJOR' AS "DETAIL_CODE", '중부적합' AS "CODE_NAME", 1 AS "SORT_ORDER", 'Major NC' AS "ATTR1", '严重不合格' AS "ATTR2", 'NC nghiêm trọng' AS "ATTR3" FROM DUAL UNION ALL
  SELECT 'FINDING_CATEGORY', 'NC_MINOR', '경부적합', 2, 'Minor NC', '轻微不合格', 'NC nhẹ' FROM DUAL UNION ALL
  SELECT 'FINDING_CATEGORY', 'OBSERVATION', '관찰사항', 3, 'Observation', '观察项', 'Quan sát' FROM DUAL UNION ALL
  SELECT 'FINDING_CATEGORY', 'OFI', '개선기회', 4, 'Opportunity for Improvement', '改善机会', 'Cơ hội cải tiến' FROM DUAL
) s ON (t."COMPANY" = '40' AND t."PLANT_CD" = '1000' AND t."GROUP_CODE" = s."GROUP_CODE" AND t."DETAIL_CODE" = s."DETAIL_CODE")
WHEN NOT MATCHED THEN INSERT (
  "COMPANY","PLANT_CD","GROUP_CODE","DETAIL_CODE","CODE_NAME","SORT_ORDER","USE_YN","ATTR1","ATTR2","ATTR3","CREATED_BY","CREATED_AT","UPDATED_AT"
) VALUES (
  '40','1000', s."GROUP_CODE", s."DETAIL_CODE", s."CODE_NAME", s."SORT_ORDER", 'Y', s."ATTR1", s."ATTR2", s."ATTR3", 'SYSTEM', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
);

-- ============================================================
-- 2) ComCode: FINDING_STATUS (발견사항 상태)
-- ============================================================
MERGE INTO "COM_CODES" t
USING (
  SELECT 'FINDING_STATUS' AS "GROUP_CODE", 'OPEN' AS "DETAIL_CODE", '미조치' AS "CODE_NAME", 1 AS "SORT_ORDER", 'Open' AS "ATTR1", '未处理' AS "ATTR2", 'Chưa xử lý' AS "ATTR3" FROM DUAL UNION ALL
  SELECT 'FINDING_STATUS', 'IN_PROGRESS', '조치중', 2, 'In Progress', '处理中', 'Đang xử lý' FROM DUAL UNION ALL
  SELECT 'FINDING_STATUS', 'CLOSED', '종료', 3, 'Closed', '已关闭', 'Đã đóng' FROM DUAL
) s ON (t."COMPANY" = '40' AND t."PLANT_CD" = '1000' AND t."GROUP_CODE" = s."GROUP_CODE" AND t."DETAIL_CODE" = s."DETAIL_CODE")
WHEN NOT MATCHED THEN INSERT (
  "COMPANY","PLANT_CD","GROUP_CODE","DETAIL_CODE","CODE_NAME","SORT_ORDER","USE_YN","ATTR1","ATTR2","ATTR3","CREATED_BY","CREATED_AT","UPDATED_AT"
) VALUES (
  '40','1000', s."GROUP_CODE", s."DETAIL_CODE", s."CODE_NAME", s."SORT_ORDER", 'Y', s."ATTR1", s."ATTR2", s."ATTR3", 'SYSTEM', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
);

-- ============================================================
-- 3) AUDIT_PLANS 시드 데이터 (8건)
-- ============================================================

-- #1 CLOSED — 시스템심사 (전체 조항)
INSERT INTO AUDIT_PLANS (AUDIT_NO, AUDIT_TYPE, AUDIT_SCOPE, TARGET_DEPT, AUDITOR, CO_AUDITOR, SCHEDULED_DATE, ACTUAL_DATE, STATUS, OVERALL_RESULT, SUMMARY, COMPANY, PLANT, CREATED_BY, UPDATED_BY)
VALUES ('AUD-20260115-001', 'SYSTEM', 'IATF 16949 전체 조항 (4~10절) 시스템 적합성 심사', '전체', 'W007', 'W008', TIMESTAMP '2026-01-20 09:00:00', TIMESTAMP '2026-01-20 09:00:00', 'CLOSED', 'MINOR', '경부적합 2건 발견, 시정조치 완료 후 종결', '40', '1000', 'admin', 'admin');

-- #2 CLOSED — 공정심사 (절단공정)
INSERT INTO AUDIT_PLANS (AUDIT_NO, AUDIT_TYPE, AUDIT_SCOPE, TARGET_DEPT, AUDITOR, CO_AUDITOR, SCHEDULED_DATE, ACTUAL_DATE, STATUS, OVERALL_RESULT, SUMMARY, COMPANY, PLANT, CREATED_BY, UPDATED_BY)
VALUES ('AUD-20260201-001', 'PROCESS', '절단 공정 작업표준서 준수 및 공정능력 확인', '생산1팀', 'W007', 'W001', TIMESTAMP '2026-02-05 09:00:00', TIMESTAMP '2026-02-05 09:00:00', 'CLOSED', 'PASS', '전 항목 적합, 공정능력지수 Cpk 1.67 이상 유지 확인', '40', '1000', 'admin', 'admin');

-- #3 COMPLETED — 제품심사 (완제품)
INSERT INTO AUDIT_PLANS (AUDIT_NO, AUDIT_TYPE, AUDIT_SCOPE, TARGET_DEPT, AUDITOR, CO_AUDITOR, SCHEDULED_DATE, ACTUAL_DATE, STATUS, OVERALL_RESULT, SUMMARY, COMPANY, PLANT, CREATED_BY, UPDATED_BY)
VALUES ('AUD-20260215-001', 'PRODUCT', '완제품 치수검사 및 외관검사 기준 적합성', '품질팀', 'W008', NULL, TIMESTAMP '2026-02-20 09:00:00', TIMESTAMP '2026-02-21 09:00:00', 'COMPLETED', 'MINOR', '외관검사 기준 일부 불명확 - 관찰사항 1건', '40', '1000', 'admin', 'admin');

-- #4 COMPLETED — 계층별심사 (2월)
INSERT INTO AUDIT_PLANS (AUDIT_NO, AUDIT_TYPE, AUDIT_SCOPE, TARGET_DEPT, AUDITOR, CO_AUDITOR, SCHEDULED_DATE, ACTUAL_DATE, STATUS, OVERALL_RESULT, SUMMARY, COMPANY, PLANT, CREATED_BY, UPDATED_BY)
VALUES ('AUD-20260228-001', 'LAYERED', '2월 계층별 공정심사 (조장/반장/팀장 단계)', '생산2팀', 'W004', 'W005', TIMESTAMP '2026-02-28 09:00:00', TIMESTAMP '2026-02-28 09:00:00', 'COMPLETED', 'PASS', '전 항목 적합', '40', '1000', 'admin', 'admin');

-- #5 IN_PROGRESS — 시스템심사 (문서관리)
INSERT INTO AUDIT_PLANS (AUDIT_NO, AUDIT_TYPE, AUDIT_SCOPE, TARGET_DEPT, AUDITOR, CO_AUDITOR, SCHEDULED_DATE, ACTUAL_DATE, STATUS, OVERALL_RESULT, SUMMARY, COMPANY, PLANT, CREATED_BY, UPDATED_BY)
VALUES ('AUD-20260310-001', 'SYSTEM', 'IATF 16949 7.5절 문서화된 정보 관리 심사', '전체', 'W007', 'W008', TIMESTAMP '2026-03-10 09:00:00', TIMESTAMP '2026-03-10 09:00:00', 'IN_PROGRESS', NULL, NULL, '40', '1000', 'admin', 'admin');

-- #6 IN_PROGRESS — 공정심사 (봉제공정)
INSERT INTO AUDIT_PLANS (AUDIT_NO, AUDIT_TYPE, AUDIT_SCOPE, TARGET_DEPT, AUDITOR, CO_AUDITOR, SCHEDULED_DATE, ACTUAL_DATE, STATUS, OVERALL_RESULT, SUMMARY, COMPANY, PLANT, CREATED_BY, UPDATED_BY)
VALUES ('AUD-20260312-001', 'PROCESS', '봉제 공정 작업자 숙련도 및 검사 기준 준수 여부', '생산1팀', 'W008', 'W003', TIMESTAMP '2026-03-15 09:00:00', TIMESTAMP '2026-03-15 09:00:00', 'IN_PROGRESS', NULL, NULL, '40', '1000', 'admin', 'admin');

-- #7 PLANNED — 제품심사 (3월 예정)
INSERT INTO AUDIT_PLANS (AUDIT_NO, AUDIT_TYPE, AUDIT_SCOPE, TARGET_DEPT, AUDITOR, CO_AUDITOR, SCHEDULED_DATE, ACTUAL_DATE, STATUS, OVERALL_RESULT, SUMMARY, COMPANY, PLANT, CREATED_BY, UPDATED_BY)
VALUES ('AUD-20260320-001', 'PRODUCT', '반제품 공정검사 기준 및 측정장비 교정 상태 확인', '품질팀', 'W007', NULL, TIMESTAMP '2026-03-25 09:00:00', NULL, 'PLANNED', NULL, NULL, '40', '1000', 'admin', 'admin');

-- #8 PLANNED — 계층별심사 (3월 예정)
INSERT INTO AUDIT_PLANS (AUDIT_NO, AUDIT_TYPE, AUDIT_SCOPE, TARGET_DEPT, AUDITOR, CO_AUDITOR, SCHEDULED_DATE, ACTUAL_DATE, STATUS, OVERALL_RESULT, SUMMARY, COMPANY, PLANT, CREATED_BY, UPDATED_BY)
VALUES ('AUD-20260325-001', 'LAYERED', '3월 계층별 공정심사 (조장/반장/팀장 단계)', '생산1팀', 'W001', 'W009', TIMESTAMP '2026-03-28 09:00:00', NULL, 'PLANNED', NULL, NULL, '40', '1000', 'admin', 'admin');

-- ============================================================
-- 4) AUDIT_FINDINGS 시드 데이터 (10건)
--    AUDIT_ID는 서브쿼리로 참조 (환경에 따라 ID가 다를 수 있음)
-- ============================================================

-- AUD-20260115-001 (CLOSED 시스템심사) — 경부적합 2건
INSERT INTO AUDIT_FINDINGS (AUDIT_ID, FINDING_NO, CLAUSE_REF, CATEGORY, DESCRIPTION, EVIDENCE, DUE_DATE, CLOSED_AT, STATUS, REMARKS, COMPANY, PLANT, CREATED_BY)
VALUES ((SELECT ID FROM AUDIT_PLANS WHERE AUDIT_NO='AUD-20260115-001' AND COMPANY='40'), 1, '7.5.3', 'NC_MINOR', '문서관리 절차서 Rev.3 미승인 상태로 현장 배포됨', '절단 공정 작업표준서 WI-CUT-003 Rev.3 미승인 상태 확인', TIMESTAMP '2026-02-05 00:00:00', TIMESTAMP '2026-01-30 00:00:00', 'CLOSED', '즉시 회수 후 승인 절차 재수행', '40', '1000', 'admin');

INSERT INTO AUDIT_FINDINGS (AUDIT_ID, FINDING_NO, CLAUSE_REF, CATEGORY, DESCRIPTION, EVIDENCE, DUE_DATE, CLOSED_AT, STATUS, REMARKS, COMPANY, PLANT, CREATED_BY)
VALUES ((SELECT ID FROM AUDIT_PLANS WHERE AUDIT_NO='AUD-20260115-001' AND COMPANY='40'), 2, '8.5.1', 'NC_MINOR', '생산 설비 예방보전 계획 대비 실행율 75% (목표 90%)', '2025년 12월 PM 실적 대장 확인: 계획 20건 중 15건 수행', TIMESTAMP '2026-02-15 00:00:00', TIMESTAMP '2026-02-10 00:00:00', 'CLOSED', '미수행 5건 즉시 실시 완료, 일정 재조정', '40', '1000', 'admin');

-- AUD-20260201-001 (CLOSED 공정심사) — 관찰사항 1건
INSERT INTO AUDIT_FINDINGS (AUDIT_ID, FINDING_NO, CLAUSE_REF, CATEGORY, DESCRIPTION, EVIDENCE, DUE_DATE, CLOSED_AT, STATUS, REMARKS, COMPANY, PLANT, CREATED_BY)
VALUES ((SELECT ID FROM AUDIT_PLANS WHERE AUDIT_NO='AUD-20260201-001' AND COMPANY='40'), 1, '8.5.1', 'OBSERVATION', '작업자 교대 시 인수인계 기록이 구두로만 진행됨', '교대 인수인계 대장 미작성 확인 (2026-01-28~02-04)', TIMESTAMP '2026-03-01 00:00:00', TIMESTAMP '2026-02-20 00:00:00', 'CLOSED', '인수인계 체크리스트 양식 도입 완료', '40', '1000', 'admin');

-- AUD-20260215-001 (COMPLETED 제품심사) — 관찰사항 + OFI
INSERT INTO AUDIT_FINDINGS (AUDIT_ID, FINDING_NO, CLAUSE_REF, CATEGORY, DESCRIPTION, EVIDENCE, DUE_DATE, CLOSED_AT, STATUS, REMARKS, COMPANY, PLANT, CREATED_BY)
VALUES ((SELECT ID FROM AUDIT_PLANS WHERE AUDIT_NO='AUD-20260215-001' AND COMPANY='40'), 1, '8.6', 'OBSERVATION', '외관검사 한도견본(Limit Sample) 유효기간 관리 미흡', '한도견본 3건 유효기간 초과 상태로 사용 중 확인', TIMESTAMP '2026-03-15 00:00:00', NULL, 'IN_PROGRESS', '한도견본 갱신 진행 중', '40', '1000', 'admin');

INSERT INTO AUDIT_FINDINGS (AUDIT_ID, FINDING_NO, CLAUSE_REF, CATEGORY, DESCRIPTION, EVIDENCE, DUE_DATE, CLOSED_AT, STATUS, REMARKS, COMPANY, PLANT, CREATED_BY)
VALUES ((SELECT ID FROM AUDIT_PLANS WHERE AUDIT_NO='AUD-20260215-001' AND COMPANY='40'), 2, '7.1.5', 'OFI', '측정장비 교정 이력 관리를 전산화하면 효율 개선 가능', '현재 수기 대장으로 관리 - 누락 위험 존재', TIMESTAMP '2026-04-30 00:00:00', NULL, 'OPEN', NULL, '40', '1000', 'admin');

-- AUD-20260310-001 (IN_PROGRESS 시스템심사) — 경부적합 2건 + 관찰사항 1건
INSERT INTO AUDIT_FINDINGS (AUDIT_ID, FINDING_NO, CLAUSE_REF, CATEGORY, DESCRIPTION, EVIDENCE, DUE_DATE, CLOSED_AT, STATUS, REMARKS, COMPANY, PLANT, CREATED_BY)
VALUES ((SELECT ID FROM AUDIT_PLANS WHERE AUDIT_NO='AUD-20260310-001' AND COMPANY='40'), 1, '7.5.2', 'NC_MINOR', '문서 개정 시 변경이력 미기재 건 발견', '품질매뉴얼 QM-001 Rev.5 변경이력란 공란 확인', TIMESTAMP '2026-04-10 00:00:00', NULL, 'OPEN', NULL, '40', '1000', 'admin');

INSERT INTO AUDIT_FINDINGS (AUDIT_ID, FINDING_NO, CLAUSE_REF, CATEGORY, DESCRIPTION, EVIDENCE, DUE_DATE, CLOSED_AT, STATUS, REMARKS, COMPANY, PLANT, CREATED_BY)
VALUES ((SELECT ID FROM AUDIT_PLANS WHERE AUDIT_NO='AUD-20260310-001' AND COMPANY='40'), 2, '7.5.3', 'NC_MINOR', '폐기 대상 구버전 문서가 현장에 잔존', '생산2팀 현장 Rev.2 작업지시서 3부 확인', TIMESTAMP '2026-04-10 00:00:00', NULL, 'OPEN', NULL, '40', '1000', 'admin');

INSERT INTO AUDIT_FINDINGS (AUDIT_ID, FINDING_NO, CLAUSE_REF, CATEGORY, DESCRIPTION, EVIDENCE, DUE_DATE, CLOSED_AT, STATUS, REMARKS, COMPANY, PLANT, CREATED_BY)
VALUES ((SELECT ID FROM AUDIT_PLANS WHERE AUDIT_NO='AUD-20260310-001' AND COMPANY='40'), 3, '7.5.1', 'OBSERVATION', '문서 분류 체계가 부서별로 상이하여 검색 효율 저하', '품질팀 QP-xxx, 생산팀 SP-xxx 등 코드 체계 불일치', TIMESTAMP '2026-04-30 00:00:00', NULL, 'OPEN', NULL, '40', '1000', 'admin');

-- AUD-20260312-001 (IN_PROGRESS 공정심사) — 중부적합 1건 + 경부적합 1건
INSERT INTO AUDIT_FINDINGS (AUDIT_ID, FINDING_NO, CLAUSE_REF, CATEGORY, DESCRIPTION, EVIDENCE, DUE_DATE, CLOSED_AT, STATUS, REMARKS, COMPANY, PLANT, CREATED_BY)
VALUES ((SELECT ID FROM AUDIT_PLANS WHERE AUDIT_NO='AUD-20260312-001' AND COMPANY='40'), 1, '8.5.1', 'NC_MAJOR', '봉제 공정 신규 작업자 2명 자격인증 미취득 상태로 투입', '작업자 자격인증 대장 확인 - 미인증 작업자 2명', TIMESTAMP '2026-03-30 00:00:00', NULL, 'OPEN', '즉시 작업 배제, 교육 수료 후 재배치 예정', '40', '1000', 'admin');

INSERT INTO AUDIT_FINDINGS (AUDIT_ID, FINDING_NO, CLAUSE_REF, CATEGORY, DESCRIPTION, EVIDENCE, DUE_DATE, CLOSED_AT, STATUS, REMARKS, COMPANY, PLANT, CREATED_BY)
VALUES ((SELECT ID FROM AUDIT_PLANS WHERE AUDIT_NO='AUD-20260312-001' AND COMPANY='40'), 2, '8.5.2', 'NC_MINOR', '공정 검사 체크시트 기록 누락 3건 발견', '3월 10~14일 봉제 2라인 검사 기록 확인', TIMESTAMP '2026-04-05 00:00:00', NULL, 'OPEN', NULL, '40', '1000', 'admin');

COMMIT;
