-- ============================================================
-- IQC 검사항목/검사그룹/품목연결 시드 데이터
-- 와이어링 하네스 품목 유형별 IQC 검사 기준 등록
-- ============================================================

-- ============================================================
-- 1. IQC_ITEM_POOL : 검사항목 풀 (개별 검사항목 정의)
-- ============================================================

-- ── 공통 외관검사 항목 ──
INSERT INTO IQC_ITEM_POOL (INSP_ITEM_CODE, ID, INSP_ITEM_NAME, JUDGE_METHOD, CRITERIA, LSL, USL, UNIT, REVISION, USE_YN, REMARK)
VALUES ('IQC-V-001', SEQ_IQC_ITEM_POOL.NEXTVAL, '외관검사(스크래치/변형)', 'VISUAL', '스크래치, 변형, 이물질 없을 것', NULL, NULL, NULL, 1, 'Y', '전 품목 공통');

INSERT INTO IQC_ITEM_POOL (INSP_ITEM_CODE, ID, INSP_ITEM_NAME, JUDGE_METHOD, CRITERIA, LSL, USL, UNIT, REVISION, USE_YN, REMARK)
VALUES ('IQC-V-002', SEQ_IQC_ITEM_POOL.NEXTVAL, '색상 확인', 'VISUAL', '도면 지정 색상과 일치할 것', NULL, NULL, NULL, 1, 'Y', '전 품목 공통');

INSERT INTO IQC_ITEM_POOL (INSP_ITEM_CODE, ID, INSP_ITEM_NAME, JUDGE_METHOD, CRITERIA, LSL, USL, UNIT, REVISION, USE_YN, REMARK)
VALUES ('IQC-V-003', SEQ_IQC_ITEM_POOL.NEXTVAL, '포장상태 확인', 'VISUAL', '포장 손상, 습기 침입 없을 것', NULL, NULL, NULL, 1, 'Y', '전 품목 공통');

INSERT INTO IQC_ITEM_POOL (INSP_ITEM_CODE, ID, INSP_ITEM_NAME, JUDGE_METHOD, CRITERIA, LSL, USL, UNIT, REVISION, USE_YN, REMARK)
VALUES ('IQC-V-004', SEQ_IQC_ITEM_POOL.NEXTVAL, '라벨/LOT번호 확인', 'VISUAL', '라벨 부착 및 LOT 번호 일치할 것', NULL, NULL, NULL, 1, 'Y', '전 품목 공통');

-- ── 전선(Wire) 전용 항목 ──
INSERT INTO IQC_ITEM_POOL (INSP_ITEM_CODE, ID, INSP_ITEM_NAME, JUDGE_METHOD, CRITERIA, LSL, USL, UNIT, REVISION, USE_YN, REMARK)
VALUES ('IQC-W-001', SEQ_IQC_ITEM_POOL.NEXTVAL, '전선 외경', 'MEASURE', '규격 대비 ±0.1mm', NULL, NULL, 'mm', 1, 'Y', '전선 전용');

INSERT INTO IQC_ITEM_POOL (INSP_ITEM_CODE, ID, INSP_ITEM_NAME, JUDGE_METHOD, CRITERIA, LSL, USL, UNIT, REVISION, USE_YN, REMARK)
VALUES ('IQC-W-002', SEQ_IQC_ITEM_POOL.NEXTVAL, '피복 두께', 'MEASURE', '규격 대비 ±0.05mm', NULL, NULL, 'mm', 1, 'Y', '전선 전용');

INSERT INTO IQC_ITEM_POOL (INSP_ITEM_CODE, ID, INSP_ITEM_NAME, JUDGE_METHOD, CRITERIA, LSL, USL, UNIT, REVISION, USE_YN, REMARK)
VALUES ('IQC-W-003', SEQ_IQC_ITEM_POOL.NEXTVAL, '도체 저항', 'MEASURE', '규격값 이하', NULL, NULL, 'Ω/km', 1, 'Y', '전선 전용');

INSERT INTO IQC_ITEM_POOL (INSP_ITEM_CODE, ID, INSP_ITEM_NAME, JUDGE_METHOD, CRITERIA, LSL, USL, UNIT, REVISION, USE_YN, REMARK)
VALUES ('IQC-W-004', SEQ_IQC_ITEM_POOL.NEXTVAL, '절연 저항', 'MEASURE', '100MΩ 이상', 100, NULL, 'MΩ', 1, 'Y', '전선 전용');

INSERT INTO IQC_ITEM_POOL (INSP_ITEM_CODE, ID, INSP_ITEM_NAME, JUDGE_METHOD, CRITERIA, LSL, USL, UNIT, REVISION, USE_YN, REMARK)
VALUES ('IQC-W-005', SEQ_IQC_ITEM_POOL.NEXTVAL, '피복 벗김 상태', 'VISUAL', '도체 손상 없이 피복이 깨끗하게 벗겨질 것', NULL, NULL, NULL, 1, 'Y', '전선 전용');

-- ── 단자(Terminal) 전용 항목 ──
INSERT INTO IQC_ITEM_POOL (INSP_ITEM_CODE, ID, INSP_ITEM_NAME, JUDGE_METHOD, CRITERIA, LSL, USL, UNIT, REVISION, USE_YN, REMARK)
VALUES ('IQC-T-001', SEQ_IQC_ITEM_POOL.NEXTVAL, '단자 외관(도금상태)', 'VISUAL', '도금 박리, 산화, 변색 없을 것', NULL, NULL, NULL, 1, 'Y', '단자 전용');

INSERT INTO IQC_ITEM_POOL (INSP_ITEM_CODE, ID, INSP_ITEM_NAME, JUDGE_METHOD, CRITERIA, LSL, USL, UNIT, REVISION, USE_YN, REMARK)
VALUES ('IQC-T-002', SEQ_IQC_ITEM_POOL.NEXTVAL, '단자 폭', 'MEASURE', '규격 대비 ±0.05mm', NULL, NULL, 'mm', 1, 'Y', '단자 전용');

INSERT INTO IQC_ITEM_POOL (INSP_ITEM_CODE, ID, INSP_ITEM_NAME, JUDGE_METHOD, CRITERIA, LSL, USL, UNIT, REVISION, USE_YN, REMARK)
VALUES ('IQC-T-003', SEQ_IQC_ITEM_POOL.NEXTVAL, '크림프 배럴 높이', 'MEASURE', '규격 대비 ±0.05mm', NULL, NULL, 'mm', 1, 'Y', '단자 전용 - 압착 후 측정');

INSERT INTO IQC_ITEM_POOL (INSP_ITEM_CODE, ID, INSP_ITEM_NAME, JUDGE_METHOD, CRITERIA, LSL, USL, UNIT, REVISION, USE_YN, REMARK)
VALUES ('IQC-T-004', SEQ_IQC_ITEM_POOL.NEXTVAL, '크림프 배럴 폭', 'MEASURE', '규격 대비 ±0.1mm', NULL, NULL, 'mm', 1, 'Y', '단자 전용 - 압착 후 측정');

INSERT INTO IQC_ITEM_POOL (INSP_ITEM_CODE, ID, INSP_ITEM_NAME, JUDGE_METHOD, CRITERIA, LSL, USL, UNIT, REVISION, USE_YN, REMARK)
VALUES ('IQC-T-005', SEQ_IQC_ITEM_POOL.NEXTVAL, '인장력(단자 인발력)', 'MEASURE', '규격값 이상', NULL, NULL, 'N', 1, 'Y', '단자 전용 - 압착 강도 측정');

-- ── 커넥터(Connector) 전용 항목 ──
INSERT INTO IQC_ITEM_POOL (INSP_ITEM_CODE, ID, INSP_ITEM_NAME, JUDGE_METHOD, CRITERIA, LSL, USL, UNIT, REVISION, USE_YN, REMARK)
VALUES ('IQC-C-001', SEQ_IQC_ITEM_POOL.NEXTVAL, '커넥터 외관(성형상태)', 'VISUAL', '크랙, 버, 웰드라인, 싱크마크 없을 것', NULL, NULL, NULL, 1, 'Y', '커넥터 전용');

INSERT INTO IQC_ITEM_POOL (INSP_ITEM_CODE, ID, INSP_ITEM_NAME, JUDGE_METHOD, CRITERIA, LSL, USL, UNIT, REVISION, USE_YN, REMARK)
VALUES ('IQC-C-002', SEQ_IQC_ITEM_POOL.NEXTVAL, '커넥터 끼움 확인', 'VISUAL', '상대측 커넥터와 정상 결합될 것', NULL, NULL, NULL, 1, 'Y', '커넥터 전용');

INSERT INTO IQC_ITEM_POOL (INSP_ITEM_CODE, ID, INSP_ITEM_NAME, JUDGE_METHOD, CRITERIA, LSL, USL, UNIT, REVISION, USE_YN, REMARK)
VALUES ('IQC-C-003', SEQ_IQC_ITEM_POOL.NEXTVAL, '단자 삽입력', 'MEASURE', '규격 범위 이내', NULL, NULL, 'N', 1, 'Y', '커넥터 전용');

INSERT INTO IQC_ITEM_POOL (INSP_ITEM_CODE, ID, INSP_ITEM_NAME, JUDGE_METHOD, CRITERIA, LSL, USL, UNIT, REVISION, USE_YN, REMARK)
VALUES ('IQC-C-004', SEQ_IQC_ITEM_POOL.NEXTVAL, '단자 보지력(리텐션)', 'MEASURE', '규격값 이상', NULL, NULL, 'N', 1, 'Y', '커넥터 전용 - 단자 빠짐 방지');

INSERT INTO IQC_ITEM_POOL (INSP_ITEM_CODE, ID, INSP_ITEM_NAME, JUDGE_METHOD, CRITERIA, LSL, USL, UNIT, REVISION, USE_YN, REMARK)
VALUES ('IQC-C-005', SEQ_IQC_ITEM_POOL.NEXTVAL, '방수 시험', 'MEASURE', 'IP67 기준 만족', NULL, NULL, NULL, 1, 'Y', '방수커넥터 전용');

-- ── 보호재(Protection) 전용 항목 ──
INSERT INTO IQC_ITEM_POOL (INSP_ITEM_CODE, ID, INSP_ITEM_NAME, JUDGE_METHOD, CRITERIA, LSL, USL, UNIT, REVISION, USE_YN, REMARK)
VALUES ('IQC-P-001', SEQ_IQC_ITEM_POOL.NEXTVAL, '튜브 내경', 'MEASURE', '규격 대비 ±0.5mm', NULL, NULL, 'mm', 1, 'Y', '보호재 전용');

INSERT INTO IQC_ITEM_POOL (INSP_ITEM_CODE, ID, INSP_ITEM_NAME, JUDGE_METHOD, CRITERIA, LSL, USL, UNIT, REVISION, USE_YN, REMARK)
VALUES ('IQC-P-002', SEQ_IQC_ITEM_POOL.NEXTVAL, '테이프 점착력', 'MEASURE', '규격값 이상', NULL, NULL, 'N/25mm', 1, 'Y', '테이프류 전용');

INSERT INTO IQC_ITEM_POOL (INSP_ITEM_CODE, ID, INSP_ITEM_NAME, JUDGE_METHOD, CRITERIA, LSL, USL, UNIT, REVISION, USE_YN, REMARK)
VALUES ('IQC-P-003', SEQ_IQC_ITEM_POOL.NEXTVAL, '그로밋 내경', 'MEASURE', '규격 대비 ±0.5mm', NULL, NULL, 'mm', 1, 'Y', '그로밋 전용');

COMMIT;

-- ============================================================
-- 2. IQC_GROUPS : 검사그룹 (품목 유형별 검사항목 묶음)
-- ============================================================

INSERT INTO IQC_GROUPS (GROUP_CODE, ID, GROUP_NAME, INSPECT_METHOD, SAMPLE_QTY, USE_YN)
VALUES ('IGR-WIRE', SEQ_IQC_GROUPS.NEXTVAL, '전선류 수입검사', 'SAMPLE', 5, 'Y');

INSERT INTO IQC_GROUPS (GROUP_CODE, ID, GROUP_NAME, INSPECT_METHOD, SAMPLE_QTY, USE_YN)
VALUES ('IGR-TERM', SEQ_IQC_GROUPS.NEXTVAL, '단자류 수입검사', 'SAMPLE', 10, 'Y');

INSERT INTO IQC_GROUPS (GROUP_CODE, ID, GROUP_NAME, INSPECT_METHOD, SAMPLE_QTY, USE_YN)
VALUES ('IGR-CONN', SEQ_IQC_GROUPS.NEXTVAL, '커넥터류 수입검사', 'SAMPLE', 5, 'Y');

INSERT INTO IQC_GROUPS (GROUP_CODE, ID, GROUP_NAME, INSPECT_METHOD, SAMPLE_QTY, USE_YN)
VALUES ('IGR-CONN-WP', SEQ_IQC_GROUPS.NEXTVAL, '방수커넥터 수입검사', 'FULL', NULL, 'Y');

INSERT INTO IQC_GROUPS (GROUP_CODE, ID, GROUP_NAME, INSPECT_METHOD, SAMPLE_QTY, USE_YN)
VALUES ('IGR-PROT', SEQ_IQC_GROUPS.NEXTVAL, '보호재류 수입검사', 'SAMPLE', 3, 'Y');

COMMIT;

-- ============================================================
-- 3. IQC_GROUP_ITEMS : 검사그룹-검사항목 매핑
--    GROUP_ID와 INSP_ITEM_ID를 서브쿼리로 조회하여 매핑
-- ============================================================

-- ── IGR-WIRE (전선류): 외관 + 색상 + 포장 + 라벨 + 외경 + 피복두께 + 도체저항 + 절연저항 + 피복벗김 ──
INSERT INTO IQC_GROUP_ITEMS (GROUP_ID, INSP_ITEM_ID, SEQ)
VALUES ((SELECT ID FROM IQC_GROUPS WHERE GROUP_CODE = 'IGR-WIRE'), (SELECT ID FROM IQC_ITEM_POOL WHERE INSP_ITEM_CODE = 'IQC-V-001'), 1);
INSERT INTO IQC_GROUP_ITEMS (GROUP_ID, INSP_ITEM_ID, SEQ)
VALUES ((SELECT ID FROM IQC_GROUPS WHERE GROUP_CODE = 'IGR-WIRE'), (SELECT ID FROM IQC_ITEM_POOL WHERE INSP_ITEM_CODE = 'IQC-V-002'), 2);
INSERT INTO IQC_GROUP_ITEMS (GROUP_ID, INSP_ITEM_ID, SEQ)
VALUES ((SELECT ID FROM IQC_GROUPS WHERE GROUP_CODE = 'IGR-WIRE'), (SELECT ID FROM IQC_ITEM_POOL WHERE INSP_ITEM_CODE = 'IQC-V-003'), 3);
INSERT INTO IQC_GROUP_ITEMS (GROUP_ID, INSP_ITEM_ID, SEQ)
VALUES ((SELECT ID FROM IQC_GROUPS WHERE GROUP_CODE = 'IGR-WIRE'), (SELECT ID FROM IQC_ITEM_POOL WHERE INSP_ITEM_CODE = 'IQC-V-004'), 4);
INSERT INTO IQC_GROUP_ITEMS (GROUP_ID, INSP_ITEM_ID, SEQ)
VALUES ((SELECT ID FROM IQC_GROUPS WHERE GROUP_CODE = 'IGR-WIRE'), (SELECT ID FROM IQC_ITEM_POOL WHERE INSP_ITEM_CODE = 'IQC-W-001'), 5);
INSERT INTO IQC_GROUP_ITEMS (GROUP_ID, INSP_ITEM_ID, SEQ)
VALUES ((SELECT ID FROM IQC_GROUPS WHERE GROUP_CODE = 'IGR-WIRE'), (SELECT ID FROM IQC_ITEM_POOL WHERE INSP_ITEM_CODE = 'IQC-W-002'), 6);
INSERT INTO IQC_GROUP_ITEMS (GROUP_ID, INSP_ITEM_ID, SEQ)
VALUES ((SELECT ID FROM IQC_GROUPS WHERE GROUP_CODE = 'IGR-WIRE'), (SELECT ID FROM IQC_ITEM_POOL WHERE INSP_ITEM_CODE = 'IQC-W-003'), 7);
INSERT INTO IQC_GROUP_ITEMS (GROUP_ID, INSP_ITEM_ID, SEQ)
VALUES ((SELECT ID FROM IQC_GROUPS WHERE GROUP_CODE = 'IGR-WIRE'), (SELECT ID FROM IQC_ITEM_POOL WHERE INSP_ITEM_CODE = 'IQC-W-004'), 8);
INSERT INTO IQC_GROUP_ITEMS (GROUP_ID, INSP_ITEM_ID, SEQ)
VALUES ((SELECT ID FROM IQC_GROUPS WHERE GROUP_CODE = 'IGR-WIRE'), (SELECT ID FROM IQC_ITEM_POOL WHERE INSP_ITEM_CODE = 'IQC-W-005'), 9);

-- ── IGR-TERM (단자류): 외관 + 포장 + 라벨 + 도금외관 + 단자폭 + 크림프높이 + 크림프폭 + 인장력 ──
INSERT INTO IQC_GROUP_ITEMS (GROUP_ID, INSP_ITEM_ID, SEQ)
VALUES ((SELECT ID FROM IQC_GROUPS WHERE GROUP_CODE = 'IGR-TERM'), (SELECT ID FROM IQC_ITEM_POOL WHERE INSP_ITEM_CODE = 'IQC-V-001'), 1);
INSERT INTO IQC_GROUP_ITEMS (GROUP_ID, INSP_ITEM_ID, SEQ)
VALUES ((SELECT ID FROM IQC_GROUPS WHERE GROUP_CODE = 'IGR-TERM'), (SELECT ID FROM IQC_ITEM_POOL WHERE INSP_ITEM_CODE = 'IQC-V-003'), 2);
INSERT INTO IQC_GROUP_ITEMS (GROUP_ID, INSP_ITEM_ID, SEQ)
VALUES ((SELECT ID FROM IQC_GROUPS WHERE GROUP_CODE = 'IGR-TERM'), (SELECT ID FROM IQC_ITEM_POOL WHERE INSP_ITEM_CODE = 'IQC-V-004'), 3);
INSERT INTO IQC_GROUP_ITEMS (GROUP_ID, INSP_ITEM_ID, SEQ)
VALUES ((SELECT ID FROM IQC_GROUPS WHERE GROUP_CODE = 'IGR-TERM'), (SELECT ID FROM IQC_ITEM_POOL WHERE INSP_ITEM_CODE = 'IQC-T-001'), 4);
INSERT INTO IQC_GROUP_ITEMS (GROUP_ID, INSP_ITEM_ID, SEQ)
VALUES ((SELECT ID FROM IQC_GROUPS WHERE GROUP_CODE = 'IGR-TERM'), (SELECT ID FROM IQC_ITEM_POOL WHERE INSP_ITEM_CODE = 'IQC-T-002'), 5);
INSERT INTO IQC_GROUP_ITEMS (GROUP_ID, INSP_ITEM_ID, SEQ)
VALUES ((SELECT ID FROM IQC_GROUPS WHERE GROUP_CODE = 'IGR-TERM'), (SELECT ID FROM IQC_ITEM_POOL WHERE INSP_ITEM_CODE = 'IQC-T-003'), 6);
INSERT INTO IQC_GROUP_ITEMS (GROUP_ID, INSP_ITEM_ID, SEQ)
VALUES ((SELECT ID FROM IQC_GROUPS WHERE GROUP_CODE = 'IGR-TERM'), (SELECT ID FROM IQC_ITEM_POOL WHERE INSP_ITEM_CODE = 'IQC-T-004'), 7);
INSERT INTO IQC_GROUP_ITEMS (GROUP_ID, INSP_ITEM_ID, SEQ)
VALUES ((SELECT ID FROM IQC_GROUPS WHERE GROUP_CODE = 'IGR-TERM'), (SELECT ID FROM IQC_ITEM_POOL WHERE INSP_ITEM_CODE = 'IQC-T-005'), 8);

-- ── IGR-CONN (일반 커넥터류): 외관 + 색상 + 포장 + 라벨 + 성형외관 + 끼움확인 + 삽입력 + 보지력 ──
INSERT INTO IQC_GROUP_ITEMS (GROUP_ID, INSP_ITEM_ID, SEQ)
VALUES ((SELECT ID FROM IQC_GROUPS WHERE GROUP_CODE = 'IGR-CONN'), (SELECT ID FROM IQC_ITEM_POOL WHERE INSP_ITEM_CODE = 'IQC-V-001'), 1);
INSERT INTO IQC_GROUP_ITEMS (GROUP_ID, INSP_ITEM_ID, SEQ)
VALUES ((SELECT ID FROM IQC_GROUPS WHERE GROUP_CODE = 'IGR-CONN'), (SELECT ID FROM IQC_ITEM_POOL WHERE INSP_ITEM_CODE = 'IQC-V-002'), 2);
INSERT INTO IQC_GROUP_ITEMS (GROUP_ID, INSP_ITEM_ID, SEQ)
VALUES ((SELECT ID FROM IQC_GROUPS WHERE GROUP_CODE = 'IGR-CONN'), (SELECT ID FROM IQC_ITEM_POOL WHERE INSP_ITEM_CODE = 'IQC-V-003'), 3);
INSERT INTO IQC_GROUP_ITEMS (GROUP_ID, INSP_ITEM_ID, SEQ)
VALUES ((SELECT ID FROM IQC_GROUPS WHERE GROUP_CODE = 'IGR-CONN'), (SELECT ID FROM IQC_ITEM_POOL WHERE INSP_ITEM_CODE = 'IQC-V-004'), 4);
INSERT INTO IQC_GROUP_ITEMS (GROUP_ID, INSP_ITEM_ID, SEQ)
VALUES ((SELECT ID FROM IQC_GROUPS WHERE GROUP_CODE = 'IGR-CONN'), (SELECT ID FROM IQC_ITEM_POOL WHERE INSP_ITEM_CODE = 'IQC-C-001'), 5);
INSERT INTO IQC_GROUP_ITEMS (GROUP_ID, INSP_ITEM_ID, SEQ)
VALUES ((SELECT ID FROM IQC_GROUPS WHERE GROUP_CODE = 'IGR-CONN'), (SELECT ID FROM IQC_ITEM_POOL WHERE INSP_ITEM_CODE = 'IQC-C-002'), 6);
INSERT INTO IQC_GROUP_ITEMS (GROUP_ID, INSP_ITEM_ID, SEQ)
VALUES ((SELECT ID FROM IQC_GROUPS WHERE GROUP_CODE = 'IGR-CONN'), (SELECT ID FROM IQC_ITEM_POOL WHERE INSP_ITEM_CODE = 'IQC-C-003'), 7);
INSERT INTO IQC_GROUP_ITEMS (GROUP_ID, INSP_ITEM_ID, SEQ)
VALUES ((SELECT ID FROM IQC_GROUPS WHERE GROUP_CODE = 'IGR-CONN'), (SELECT ID FROM IQC_ITEM_POOL WHERE INSP_ITEM_CODE = 'IQC-C-004'), 8);

-- ── IGR-CONN-WP (방수커넥터): IGR-CONN 항목 + 방수시험 ──
INSERT INTO IQC_GROUP_ITEMS (GROUP_ID, INSP_ITEM_ID, SEQ)
VALUES ((SELECT ID FROM IQC_GROUPS WHERE GROUP_CODE = 'IGR-CONN-WP'), (SELECT ID FROM IQC_ITEM_POOL WHERE INSP_ITEM_CODE = 'IQC-V-001'), 1);
INSERT INTO IQC_GROUP_ITEMS (GROUP_ID, INSP_ITEM_ID, SEQ)
VALUES ((SELECT ID FROM IQC_GROUPS WHERE GROUP_CODE = 'IGR-CONN-WP'), (SELECT ID FROM IQC_ITEM_POOL WHERE INSP_ITEM_CODE = 'IQC-V-002'), 2);
INSERT INTO IQC_GROUP_ITEMS (GROUP_ID, INSP_ITEM_ID, SEQ)
VALUES ((SELECT ID FROM IQC_GROUPS WHERE GROUP_CODE = 'IGR-CONN-WP'), (SELECT ID FROM IQC_ITEM_POOL WHERE INSP_ITEM_CODE = 'IQC-V-003'), 3);
INSERT INTO IQC_GROUP_ITEMS (GROUP_ID, INSP_ITEM_ID, SEQ)
VALUES ((SELECT ID FROM IQC_GROUPS WHERE GROUP_CODE = 'IGR-CONN-WP'), (SELECT ID FROM IQC_ITEM_POOL WHERE INSP_ITEM_CODE = 'IQC-V-004'), 4);
INSERT INTO IQC_GROUP_ITEMS (GROUP_ID, INSP_ITEM_ID, SEQ)
VALUES ((SELECT ID FROM IQC_GROUPS WHERE GROUP_CODE = 'IGR-CONN-WP'), (SELECT ID FROM IQC_ITEM_POOL WHERE INSP_ITEM_CODE = 'IQC-C-001'), 5);
INSERT INTO IQC_GROUP_ITEMS (GROUP_ID, INSP_ITEM_ID, SEQ)
VALUES ((SELECT ID FROM IQC_GROUPS WHERE GROUP_CODE = 'IGR-CONN-WP'), (SELECT ID FROM IQC_ITEM_POOL WHERE INSP_ITEM_CODE = 'IQC-C-002'), 6);
INSERT INTO IQC_GROUP_ITEMS (GROUP_ID, INSP_ITEM_ID, SEQ)
VALUES ((SELECT ID FROM IQC_GROUPS WHERE GROUP_CODE = 'IGR-CONN-WP'), (SELECT ID FROM IQC_ITEM_POOL WHERE INSP_ITEM_CODE = 'IQC-C-003'), 7);
INSERT INTO IQC_GROUP_ITEMS (GROUP_ID, INSP_ITEM_ID, SEQ)
VALUES ((SELECT ID FROM IQC_GROUPS WHERE GROUP_CODE = 'IGR-CONN-WP'), (SELECT ID FROM IQC_ITEM_POOL WHERE INSP_ITEM_CODE = 'IQC-C-004'), 8);
INSERT INTO IQC_GROUP_ITEMS (GROUP_ID, INSP_ITEM_ID, SEQ)
VALUES ((SELECT ID FROM IQC_GROUPS WHERE GROUP_CODE = 'IGR-CONN-WP'), (SELECT ID FROM IQC_ITEM_POOL WHERE INSP_ITEM_CODE = 'IQC-C-005'), 9);

-- ── IGR-PROT (보호재류): 외관 + 포장 + 라벨 + 튜브내경 + 테이프점착력 + 그로밋내경 ──
INSERT INTO IQC_GROUP_ITEMS (GROUP_ID, INSP_ITEM_ID, SEQ)
VALUES ((SELECT ID FROM IQC_GROUPS WHERE GROUP_CODE = 'IGR-PROT'), (SELECT ID FROM IQC_ITEM_POOL WHERE INSP_ITEM_CODE = 'IQC-V-001'), 1);
INSERT INTO IQC_GROUP_ITEMS (GROUP_ID, INSP_ITEM_ID, SEQ)
VALUES ((SELECT ID FROM IQC_GROUPS WHERE GROUP_CODE = 'IGR-PROT'), (SELECT ID FROM IQC_ITEM_POOL WHERE INSP_ITEM_CODE = 'IQC-V-003'), 2);
INSERT INTO IQC_GROUP_ITEMS (GROUP_ID, INSP_ITEM_ID, SEQ)
VALUES ((SELECT ID FROM IQC_GROUPS WHERE GROUP_CODE = 'IGR-PROT'), (SELECT ID FROM IQC_ITEM_POOL WHERE INSP_ITEM_CODE = 'IQC-V-004'), 3);
INSERT INTO IQC_GROUP_ITEMS (GROUP_ID, INSP_ITEM_ID, SEQ)
VALUES ((SELECT ID FROM IQC_GROUPS WHERE GROUP_CODE = 'IGR-PROT'), (SELECT ID FROM IQC_ITEM_POOL WHERE INSP_ITEM_CODE = 'IQC-P-001'), 4);
INSERT INTO IQC_GROUP_ITEMS (GROUP_ID, INSP_ITEM_ID, SEQ)
VALUES ((SELECT ID FROM IQC_GROUPS WHERE GROUP_CODE = 'IGR-PROT'), (SELECT ID FROM IQC_ITEM_POOL WHERE INSP_ITEM_CODE = 'IQC-P-002'), 5);
INSERT INTO IQC_GROUP_ITEMS (GROUP_ID, INSP_ITEM_ID, SEQ)
VALUES ((SELECT ID FROM IQC_GROUPS WHERE GROUP_CODE = 'IGR-PROT'), (SELECT ID FROM IQC_ITEM_POOL WHERE INSP_ITEM_CODE = 'IQC-P-003'), 6);

COMMIT;

-- ============================================================
-- 4. IQC_PART_LINKS : 품목-검사그룹 연결
--    PARTNER_ID = '*' (기본, 거래처 무관)
--    GROUP_ID는 서브쿼리로 조회
-- ============================================================

-- ── 전선류 (RAW-W-xxx) → IGR-WIRE ──
INSERT INTO IQC_PART_LINKS (ITEM_CODE, PARTNER_ID, GROUP_ID, USE_YN)
VALUES ('RAW-W-001', '*', (SELECT ID FROM IQC_GROUPS WHERE GROUP_CODE = 'IGR-WIRE'), 'Y');
INSERT INTO IQC_PART_LINKS (ITEM_CODE, PARTNER_ID, GROUP_ID, USE_YN)
VALUES ('RAW-W-002', '*', (SELECT ID FROM IQC_GROUPS WHERE GROUP_CODE = 'IGR-WIRE'), 'Y');
INSERT INTO IQC_PART_LINKS (ITEM_CODE, PARTNER_ID, GROUP_ID, USE_YN)
VALUES ('RAW-W-003', '*', (SELECT ID FROM IQC_GROUPS WHERE GROUP_CODE = 'IGR-WIRE'), 'Y');
INSERT INTO IQC_PART_LINKS (ITEM_CODE, PARTNER_ID, GROUP_ID, USE_YN)
VALUES ('RAW-W-004', '*', (SELECT ID FROM IQC_GROUPS WHERE GROUP_CODE = 'IGR-WIRE'), 'Y');
INSERT INTO IQC_PART_LINKS (ITEM_CODE, PARTNER_ID, GROUP_ID, USE_YN)
VALUES ('RAW-W-005', '*', (SELECT ID FROM IQC_GROUPS WHERE GROUP_CODE = 'IGR-WIRE'), 'Y');

-- ── 단자류 (RAW-T-xxx) → IGR-TERM ──
INSERT INTO IQC_PART_LINKS (ITEM_CODE, PARTNER_ID, GROUP_ID, USE_YN)
VALUES ('RAW-T-001', '*', (SELECT ID FROM IQC_GROUPS WHERE GROUP_CODE = 'IGR-TERM'), 'Y');
INSERT INTO IQC_PART_LINKS (ITEM_CODE, PARTNER_ID, GROUP_ID, USE_YN)
VALUES ('RAW-T-002', '*', (SELECT ID FROM IQC_GROUPS WHERE GROUP_CODE = 'IGR-TERM'), 'Y');
INSERT INTO IQC_PART_LINKS (ITEM_CODE, PARTNER_ID, GROUP_ID, USE_YN)
VALUES ('RAW-T-003', '*', (SELECT ID FROM IQC_GROUPS WHERE GROUP_CODE = 'IGR-TERM'), 'Y');
INSERT INTO IQC_PART_LINKS (ITEM_CODE, PARTNER_ID, GROUP_ID, USE_YN)
VALUES ('RAW-T-004', '*', (SELECT ID FROM IQC_GROUPS WHERE GROUP_CODE = 'IGR-TERM'), 'Y');
INSERT INTO IQC_PART_LINKS (ITEM_CODE, PARTNER_ID, GROUP_ID, USE_YN)
VALUES ('RAW-T-005', '*', (SELECT ID FROM IQC_GROUPS WHERE GROUP_CODE = 'IGR-TERM'), 'Y');

-- ── 일반 커넥터 (RAW-C-001~003) → IGR-CONN ──
INSERT INTO IQC_PART_LINKS (ITEM_CODE, PARTNER_ID, GROUP_ID, USE_YN)
VALUES ('RAW-C-001', '*', (SELECT ID FROM IQC_GROUPS WHERE GROUP_CODE = 'IGR-CONN'), 'Y');
INSERT INTO IQC_PART_LINKS (ITEM_CODE, PARTNER_ID, GROUP_ID, USE_YN)
VALUES ('RAW-C-002', '*', (SELECT ID FROM IQC_GROUPS WHERE GROUP_CODE = 'IGR-CONN'), 'Y');
INSERT INTO IQC_PART_LINKS (ITEM_CODE, PARTNER_ID, GROUP_ID, USE_YN)
VALUES ('RAW-C-003', '*', (SELECT ID FROM IQC_GROUPS WHERE GROUP_CODE = 'IGR-CONN'), 'Y');

-- ── 방수 커넥터 (RAW-C-004) → IGR-CONN-WP ──
INSERT INTO IQC_PART_LINKS (ITEM_CODE, PARTNER_ID, GROUP_ID, USE_YN)
VALUES ('RAW-C-004', '*', (SELECT ID FROM IQC_GROUPS WHERE GROUP_CODE = 'IGR-CONN-WP'), 'Y');

-- ── 보호재류 (RAW-P-xxx) → IGR-PROT ──
INSERT INTO IQC_PART_LINKS (ITEM_CODE, PARTNER_ID, GROUP_ID, USE_YN)
VALUES ('RAW-P-001', '*', (SELECT ID FROM IQC_GROUPS WHERE GROUP_CODE = 'IGR-PROT'), 'Y');
INSERT INTO IQC_PART_LINKS (ITEM_CODE, PARTNER_ID, GROUP_ID, USE_YN)
VALUES ('RAW-P-002', '*', (SELECT ID FROM IQC_GROUPS WHERE GROUP_CODE = 'IGR-PROT'), 'Y');
INSERT INTO IQC_PART_LINKS (ITEM_CODE, PARTNER_ID, GROUP_ID, USE_YN)
VALUES ('RAW-P-003', '*', (SELECT ID FROM IQC_GROUPS WHERE GROUP_CODE = 'IGR-PROT'), 'Y');
INSERT INTO IQC_PART_LINKS (ITEM_CODE, PARTNER_ID, GROUP_ID, USE_YN)
VALUES ('RAW-P-004', '*', (SELECT ID FROM IQC_GROUPS WHERE GROUP_CODE = 'IGR-PROT'), 'Y');
INSERT INTO IQC_PART_LINKS (ITEM_CODE, PARTNER_ID, GROUP_ID, USE_YN)
VALUES ('RAW-P-005', '*', (SELECT ID FROM IQC_GROUPS WHERE GROUP_CODE = 'IGR-PROT'), 'Y');

COMMIT;
