MERGE INTO "COM_CODES" t
USING (
  SELECT 'PPAP_STATUS' AS "GROUP_CODE", 'DRAFT'     AS "DETAIL_CODE", '작성중'   AS "CODE_NAME", 1 AS "SORT_ORDER", 'Draft'     AS "ATTR1", '草稿'     AS "ATTR2", 'Bản nháp' AS "ATTR3" FROM DUAL UNION ALL
  SELECT 'PPAP_STATUS', 'SUBMITTED', '제출됨',   2, 'Submitted', '已提交',   'Đã nộp'   FROM DUAL UNION ALL
  SELECT 'PPAP_STATUS', 'APPROVED',  '승인',     3, 'Approved',  '已批准',   'Đã duyệt' FROM DUAL UNION ALL
  SELECT 'PPAP_STATUS', 'REJECTED',  '반려',     4, 'Rejected',  '已拒绝',   'Bị từ chối' FROM DUAL UNION ALL
  SELECT 'PPAP_STATUS', 'INTERIM',   '잠정승인', 5, 'Interim',   '暂时批准', 'Tạm duyệt'  FROM DUAL
) s ON (t."COMPANY" = 'HANES' AND t."PLANT_CD" = 'VINA' AND t."GROUP_CODE" = s."GROUP_CODE" AND t."DETAIL_CODE" = s."DETAIL_CODE")
WHEN NOT MATCHED THEN INSERT (
  "COMPANY", "PLANT_CD", "GROUP_CODE", "DETAIL_CODE", "CODE_NAME", "SORT_ORDER", "USE_YN", "ATTR1", "ATTR2", "ATTR3", "CREATED_BY", "CREATED_AT", "UPDATED_AT"
) VALUES (
  'HANES', 'VINA', s."GROUP_CODE", s."DETAIL_CODE", s."CODE_NAME", s."SORT_ORDER", 'Y', s."ATTR1", s."ATTR2", s."ATTR3", 'SYSTEM', SYSDATE, SYSDATE
)
