BEGIN
  FOR d IN 0..364 LOOP
    INSERT INTO WORK_CALENDAR_DAYS (
      CALENDAR_ID, WORK_DATE, DAY_TYPE, OFF_REASON,
      SHIFT_COUNT, SHIFTS, WORK_MINUTES, OT_MINUTES,
      COMPANY, PLANT_CD, CREATED_BY
    ) VALUES (
      'WC-2026-VNHNS',
      DATE '2026-01-01' + d,
      CASE
        WHEN TO_CHAR(DATE '2026-01-01' + d, 'DY', 'NLS_DATE_LANGUAGE=AMERICAN') IN ('SAT','SUN') THEN 'OFF'
        ELSE 'WORK'
      END,
      CASE
        WHEN TO_CHAR(DATE '2026-01-01' + d, 'DY', 'NLS_DATE_LANGUAGE=AMERICAN') = 'SAT' THEN 'WEEKEND'
        WHEN TO_CHAR(DATE '2026-01-01' + d, 'DY', 'NLS_DATE_LANGUAGE=AMERICAN') = 'SUN' THEN 'WEEKEND'
        ELSE NULL
      END,
      CASE
        WHEN TO_CHAR(DATE '2026-01-01' + d, 'DY', 'NLS_DATE_LANGUAGE=AMERICAN') IN ('SAT','SUN') THEN 0
        ELSE 1
      END,
      CASE
        WHEN TO_CHAR(DATE '2026-01-01' + d, 'DY', 'NLS_DATE_LANGUAGE=AMERICAN') IN ('SAT','SUN') THEN NULL
        ELSE 'DAY'
      END,
      CASE
        WHEN TO_CHAR(DATE '2026-01-01' + d, 'DY', 'NLS_DATE_LANGUAGE=AMERICAN') IN ('SAT','SUN') THEN 0
        ELSE 480
      END,
      0,
      '40',
      'VNHNS',
      'SYSTEM'
    );
  END LOOP;
  COMMIT;
END;
/
