"""
IATF 16949 전체 모듈 시드 데이터 (스키마 기반 정확 버전)
20개 테이블 / Company='40', Plant='1000'
"""
import json, oracledb, re

with open('C:/Users/hsyou/.oracle_db_config.json', 'r') as f:
    cfg = json.load(f)
p = cfg['profiles']['JSHANES']
conn = oracledb.connect(user=p['user'], password=p['password'],
    dsn=f"{p['host']}:{p['port']}/{p['service_name']}")
cur = conn.cursor()

# 역순 삭제 (FK 의존 순서)
for tbl in ['MOLD_USAGE_LOGS','MOLD_MASTERS','AUDIT_FINDINGS','AUDIT_PLANS',
            'DOCUMENT_MASTERS','TRAINING_RESULTS','TRAINING_PLANS',
            'CONTROL_PLAN_ITEMS','CONTROL_PLANS','CALIBRATION_LOGS',
            'GAUGE_MASTERS','SPC_DATA','SPC_CHARTS','PPAP_SUBMISSIONS',
            'FAI_ITEMS','FAI_REQUESTS','CAPA_ACTIONS','CAPA_REQUESTS',
            'CHANGE_ORDERS','CUSTOMER_COMPLAINTS']:
    try:
        cur.execute(f'DELETE FROM {tbl}')
    except:
        pass
conn.commit()
print('Cleared all tables.\n')

sqls = [
    # ============ 1. CUSTOMER_COMPLAINTS ============
    """INSERT INTO CUSTOMER_COMPLAINTS (COMPLAINT_NO,CUSTOMER_CODE,CUSTOMER_NAME,COMPLAINT_DATE,ITEM_CODE,LOT_NO,DEFECT_QTY,COMPLAINT_TYPE,DESCRIPTION,URGENCY,STATUS,INVESTIGATION,RESPONSIBLE_CODE,COST_AMOUNT,COMPANY,PLANT,CREATED_BY,UPDATED_BY) VALUES ('CMP-20260301-001','CUS-001','현대자동차',DATE '2026-03-01','FG-DH-001','LOT-20260228-01',5,'QUALITY','도어 하네스 커넥터 접촉 불량','HIGH','INVESTIGATING','커넥터 압착 상태 분석 중','W001',150000,'40','1000','admin','admin')""",
    """INSERT INTO CUSTOMER_COMPLAINTS (COMPLAINT_NO,CUSTOMER_CODE,CUSTOMER_NAME,COMPLAINT_DATE,ITEM_CODE,LOT_NO,DEFECT_QTY,COMPLAINT_TYPE,DESCRIPTION,URGENCY,STATUS,ROOT_CAUSE,CORRECTIVE_ACTION,PREVENTIVE_ACTION,RESPONSIBLE_CODE,COST_AMOUNT,RESOLVED_AT,COMPANY,PLANT,CREATED_BY,UPDATED_BY) VALUES ('CMP-20260215-001','CUS-002','기아자동차',DATE '2026-02-15','FG-EH-001','LOT-20260210-03',2,'QUALITY','엔진룸 하네스 단선 클레임','MEDIUM','RESOLVED','절단 공정 칼날 마모','칼날 교체 주기 단축','금형 검사 체크리스트 추가','W003',80000,SYSTIMESTAMP-5,'40','1000','admin','admin')""",
    """INSERT INTO CUSTOMER_COMPLAINTS (COMPLAINT_NO,CUSTOMER_CODE,CUSTOMER_NAME,COMPLAINT_DATE,ITEM_CODE,DEFECT_QTY,COMPLAINT_TYPE,DESCRIPTION,URGENCY,STATUS,RESPONSIBLE_CODE,COMPANY,PLANT,CREATED_BY,UPDATED_BY) VALUES ('CMP-20260310-001','CUS-001','현대자동차',DATE '2026-03-10','FG-DH-001',10,'DELIVERY','납기 지연 3일 발생','LOW','RECEIVED','W002','40','1000','admin','admin')""",

    # ============ 2. CHANGE_ORDERS ============
    """INSERT INTO CHANGE_ORDERS (CHANGE_NO,CHANGE_TYPE,TITLE,DESCRIPTION,REASON,RISK_ASSESSMENT,AFFECTED_ITEMS,PRIORITY,STATUS,REQUESTED_BY,REQUESTED_AT,EFFECTIVE_DATE,COMPANY,PLANT,CREATED_BY,UPDATED_BY) VALUES ('ECN-20260301-001','MATERIAL','커넥터 하우징 원자재 변경','6P 커넥터 하우징 A사→B사 변경','기존 공급사 단가 인상','치수/물성 동등성 확인 필요','RAW-C-001','HIGH','APPROVED','W001',SYSTIMESTAMP-10,DATE '2026-03-15','40','1000','admin','admin')""",
    """INSERT INTO CHANGE_ORDERS (CHANGE_NO,CHANGE_TYPE,TITLE,DESCRIPTION,REASON,AFFECTED_PROCESSES,PRIORITY,STATUS,REQUESTED_BY,REQUESTED_AT,COMPANY,PLANT,CREATED_BY,UPDATED_BY) VALUES ('ECN-20260305-001','METHOD','압착 공정 조건 변경','압착 높이 3.2mm→3.1mm','고객 요청 규격 변경','PRC-CRIMP','MEDIUM','REVIEWING','W003',SYSTIMESTAMP-7,'40','1000','admin','admin')""",
    """INSERT INTO CHANGE_ORDERS (CHANGE_NO,CHANGE_TYPE,TITLE,DESCRIPTION,REASON,PRIORITY,STATUS,REQUESTED_BY,REQUESTED_AT,COMPANY,PLANT,CREATED_BY,UPDATED_BY) VALUES ('ECN-20260310-001','MACHINE','절단기 교체','노후 절단기→신규 장비','장비 노후화 불량률 증가','HIGH','DRAFT','W005',SYSTIMESTAMP-2,'40','1000','admin','admin')""",

    # ============ 3. CAPA_REQUESTS ============
    """INSERT INTO CAPA_REQUESTS (CAPA_NO,CAPA_TYPE,SOURCE_TYPE,TITLE,DESCRIPTION,ROOT_CAUSE,ACTION_PLAN,TARGET_DATE,RESPONSIBLE_CODE,STATUS,PRIORITY,ITEM_CODE,LINE_CODE,COMPANY,PLANT,CREATED_BY,UPDATED_BY) VALUES ('CAPA-20260301-001','CORRECTIVE','COMPLAINT','커넥터 접촉 불량 시정조치','고객 클레임 대응','압착 금형 마모','금형 교체+공정능력 재확인',DATE '2026-03-20','W001','IN_PROGRESS','HIGH','FG-DH-001','LINE-01','40','1000','admin','admin')""",
    """INSERT INTO CAPA_REQUESTS (CAPA_NO,CAPA_TYPE,SOURCE_TYPE,TITLE,DESCRIPTION,ROOT_CAUSE,ACTION_PLAN,TARGET_DATE,RESPONSIBLE_CODE,STATUS,PRIORITY,VERIFICATION_RESULT,VERIFIED_BY,VERIFIED_AT,CLOSED_AT,COMPANY,PLANT,CREATED_BY,UPDATED_BY) VALUES ('CAPA-20260210-001','PREVENTIVE','AUDIT','내부심사 부적합 예방조치','문서관리 미비','문서 개정 이력 관리 미흡','문서관리 시스템 도입',DATE '2026-02-28','W004','CLOSED','MEDIUM','시스템 적용 완료','W002',SYSTIMESTAMP-10,SYSTIMESTAMP-8,'40','1000','admin','admin')""",
    """INSERT INTO CAPA_REQUESTS (CAPA_NO,CAPA_TYPE,SOURCE_TYPE,TITLE,DESCRIPTION,TARGET_DATE,RESPONSIBLE_CODE,STATUS,PRIORITY,COMPANY,PLANT,CREATED_BY,UPDATED_BY) VALUES ('CAPA-20260312-001','CORRECTIVE','DEFECT','탈피 공정 불량률 감소','피복 손상 불량률 1.5% 초과',DATE '2026-03-25','W005','ANALYZING','HIGH','40','1000','admin','admin')""",

    # ============ 4. CAPA_ACTIONS ============
    """INSERT INTO CAPA_ACTIONS (CAPA_ID,SEQ,ACTION_DESC,RESPONSIBLE_CODE,DUE_DATE,STATUS,RESULT,COMPLETED_AT) VALUES ((SELECT ID FROM CAPA_REQUESTS WHERE CAPA_NO='CAPA-20260301-001'),1,'압착 금형 교체','W005',DATE '2026-03-10','DONE','금형 교체 완료',SYSTIMESTAMP-3)""",
    """INSERT INTO CAPA_ACTIONS (CAPA_ID,SEQ,ACTION_DESC,RESPONSIBLE_CODE,DUE_DATE,STATUS) VALUES ((SELECT ID FROM CAPA_REQUESTS WHERE CAPA_NO='CAPA-20260301-001'),2,'초물검사 및 공정능력 분석','W003',DATE '2026-03-15','IN_PROGRESS')""",
    """INSERT INTO CAPA_ACTIONS (CAPA_ID,SEQ,ACTION_DESC,RESPONSIBLE_CODE,DUE_DATE,STATUS) VALUES ((SELECT ID FROM CAPA_REQUESTS WHERE CAPA_NO='CAPA-20260301-001'),3,'재발방지 표준작업서 개정','W004',DATE '2026-03-20','PENDING')""",
    """INSERT INTO CAPA_ACTIONS (CAPA_ID,SEQ,ACTION_DESC,RESPONSIBLE_CODE,DUE_DATE,STATUS,RESULT,COMPLETED_AT) VALUES ((SELECT ID FROM CAPA_REQUESTS WHERE CAPA_NO='CAPA-20260210-001'),1,'문서관리 시스템 구축','W004',DATE '2026-02-20','DONE','MES 모듈 도입 완료',SYSTIMESTAMP-15)""",
    """INSERT INTO CAPA_ACTIONS (CAPA_ID,SEQ,ACTION_DESC,RESPONSIBLE_CODE,DUE_DATE,STATUS,RESULT,COMPLETED_AT) VALUES ((SELECT ID FROM CAPA_REQUESTS WHERE CAPA_NO='CAPA-20260210-001'),2,'전 직원 문서관리 교육','W006',DATE '2026-02-28','DONE','교육 이수율 100%',SYSTIMESTAMP-10)""",

    # ============ 5. FAI_REQUESTS ============
    """INSERT INTO FAI_REQUESTS (FAI_NO,TRIGGER_TYPE,ITEM_CODE,ORDER_NO,LINE_CODE,SAMPLE_QTY,INSPECTOR_CODE,STATUS,INSPECT_DATE,RESULT,REMARKS,COMPANY,PLANT,CREATED_BY,UPDATED_BY) VALUES ('FAI-20260301-001','NEW_PRODUCT','FG-DH-001','JO-20260301-001','LINE-01',5,'W003','PASS',DATE '2026-03-01','PASS','전 항목 합격','40','1000','admin','admin')""",
    """INSERT INTO FAI_REQUESTS (FAI_NO,TRIGGER_TYPE,TRIGGER_REF,ITEM_CODE,LINE_CODE,SAMPLE_QTY,INSPECTOR_CODE,STATUS,COMPANY,PLANT,CREATED_BY,UPDATED_BY) VALUES ('FAI-20260310-001','ECN_CHANGE','ECN-20260301-001','FG-DH-001','LINE-01',3,'W003','INSPECTING','40','1000','admin','admin')""",
    """INSERT INTO FAI_REQUESTS (FAI_NO,TRIGGER_TYPE,ITEM_CODE,LINE_CODE,SAMPLE_QTY,STATUS,COMPANY,PLANT,CREATED_BY,UPDATED_BY) VALUES ('FAI-20260312-001','LONG_STOP','FG-EH-001','LINE-02',5,'REQUESTED','40','1000','admin','admin')""",

    # ============ 6. FAI_ITEMS ============
    """INSERT INTO FAI_ITEMS (FAI_ID,SEQ,INSPECT_ITEM,SPEC_MIN,SPEC_MAX,MEASURED_VALUE,UNIT,RESULT) VALUES ((SELECT ID FROM FAI_REQUESTS WHERE FAI_NO='FAI-20260301-001'),1,'압착 높이',3.05,3.35,3.18,'mm','OK')""",
    """INSERT INTO FAI_ITEMS (FAI_ID,SEQ,INSPECT_ITEM,SPEC_MIN,SPEC_MAX,MEASURED_VALUE,UNIT,RESULT) VALUES ((SELECT ID FROM FAI_REQUESTS WHERE FAI_NO='FAI-20260301-001'),2,'압착 폭',2.80,3.20,2.95,'mm','OK')""",
    """INSERT INTO FAI_ITEMS (FAI_ID,SEQ,INSPECT_ITEM,SPEC_MIN,MEASURED_VALUE,UNIT,RESULT) VALUES ((SELECT ID FROM FAI_REQUESTS WHERE FAI_NO='FAI-20260301-001'),3,'인장강도',50.0,65.3,'N','OK')""",
    """INSERT INTO FAI_ITEMS (FAI_ID,SEQ,INSPECT_ITEM,RESULT,REMARKS) VALUES ((SELECT ID FROM FAI_REQUESTS WHERE FAI_NO='FAI-20260301-001'),4,'외관검사','OK','이상없음')""",

    # ============ 7. SPC_CHARTS ============
    """INSERT INTO SPC_CHARTS (CHART_NO,CHART_TYPE,ITEM_CODE,PROCESS_CODE,CHARACTERISTIC_NAME,USL,LSL,TARGET,SUBGROUP_SIZE,STATUS,COMPANY,PLANT,CREATED_BY,UPDATED_BY) VALUES ('SPC-20260301-001','XBAR_R','FG-DH-001','PRC-CRIMP','압착 높이',3.35,3.05,3.20,5,'ACTIVE','40','1000','admin','admin')""",
    """INSERT INTO SPC_CHARTS (CHART_NO,CHART_TYPE,ITEM_CODE,PROCESS_CODE,CHARACTERISTIC_NAME,LSL,TARGET,SUBGROUP_SIZE,STATUS,COMPANY,PLANT,CREATED_BY,UPDATED_BY) VALUES ('SPC-20260301-002','XBAR_R','FG-DH-001','PRC-CRIMP','인장강도',50,70,5,'ACTIVE','40','1000','admin','admin')""",
    """INSERT INTO SPC_CHARTS (CHART_NO,CHART_TYPE,ITEM_CODE,PROCESS_CODE,CHARACTERISTIC_NAME,USL,TARGET,SUBGROUP_SIZE,STATUS,COMPANY,PLANT,CREATED_BY,UPDATED_BY) VALUES ('SPC-20260301-003','P_CHART','FG-EH-001','PRC-TEST','외관 불량률',0.02,0.005,50,'ACTIVE','40','1000','admin','admin')""",

    # ============ 8. SPC_DATA (VALUES=VARCHAR2 NOT NULL, OUT_OF_CONTROL=NUMBER(1) NOT NULL) ============
    """INSERT INTO SPC_DATA (CHART_ID,SAMPLE_DATE,SUBGROUP_NO,"VALUES",MEAN,RANGE_VAL,OUT_OF_CONTROL,COMPANY,PLANT,CREATED_BY) VALUES ((SELECT ID FROM SPC_CHARTS WHERE CHART_NO='SPC-20260301-001'),DATE '2026-03-10',1,'3.18,3.20,3.19,3.21,3.17',3.19,0.04,0,'40','1000','admin')""",
    """INSERT INTO SPC_DATA (CHART_ID,SAMPLE_DATE,SUBGROUP_NO,"VALUES",MEAN,RANGE_VAL,OUT_OF_CONTROL,COMPANY,PLANT,CREATED_BY) VALUES ((SELECT ID FROM SPC_CHARTS WHERE CHART_NO='SPC-20260301-001'),DATE '2026-03-10',2,'3.22,3.19,3.20,3.18,3.21',3.20,0.04,0,'40','1000','admin')""",
    """INSERT INTO SPC_DATA (CHART_ID,SAMPLE_DATE,SUBGROUP_NO,"VALUES",MEAN,RANGE_VAL,OUT_OF_CONTROL,COMPANY,PLANT,CREATED_BY) VALUES ((SELECT ID FROM SPC_CHARTS WHERE CHART_NO='SPC-20260301-001'),DATE '2026-03-11',3,'3.17,3.21,3.19,3.20,3.18',3.19,0.04,0,'40','1000','admin')""",
    """INSERT INTO SPC_DATA (CHART_ID,SAMPLE_DATE,SUBGROUP_NO,"VALUES",MEAN,RANGE_VAL,OUT_OF_CONTROL,COMPANY,PLANT,CREATED_BY) VALUES ((SELECT ID FROM SPC_CHARTS WHERE CHART_NO='SPC-20260301-001'),DATE '2026-03-11',4,'3.20,3.22,3.18,3.19,3.21',3.20,0.04,0,'40','1000','admin')""",
    """INSERT INTO SPC_DATA (CHART_ID,SAMPLE_DATE,SUBGROUP_NO,"VALUES",MEAN,RANGE_VAL,OUT_OF_CONTROL,COMPANY,PLANT,CREATED_BY) VALUES ((SELECT ID FROM SPC_CHARTS WHERE CHART_NO='SPC-20260301-001'),DATE '2026-03-12',5,'3.19,3.18,3.21,3.20,3.19',3.194,0.03,0,'40','1000','admin')""",

    # ============ 9. GAUGE_MASTERS (RESOLUTION=NUMBER(12,4), CALIBRATION_CYCLE=NUMBER NOT NULL) ============
    """INSERT INTO GAUGE_MASTERS (GAUGE_CODE,GAUGE_NAME,GAUGE_TYPE,MANUFACTURER,MODEL,SERIAL_NO,RESOLUTION,MEASURE_RANGE,CALIBRATION_CYCLE,LAST_CALIBRATION_DATE,NEXT_CALIBRATION_DATE,STATUS,LOCATION,COMPANY,PLANT,CREATED_BY,UPDATED_BY) VALUES ('GAU-001','디지털 캘리퍼스 150mm','CALIPER','Mitutoyo','CD-15CPX','SN-2024-001',0.01,'0~150mm',12,DATE '2025-09-15',DATE '2026-09-15','ACTIVE','품질검사실','40','1000','admin','admin')""",
    """INSERT INTO GAUGE_MASTERS (GAUGE_CODE,GAUGE_NAME,GAUGE_TYPE,MANUFACTURER,MODEL,SERIAL_NO,RESOLUTION,MEASURE_RANGE,CALIBRATION_CYCLE,LAST_CALIBRATION_DATE,NEXT_CALIBRATION_DATE,STATUS,LOCATION,COMPANY,PLANT,CREATED_BY,UPDATED_BY) VALUES ('GAU-002','마이크로미터 25mm','MICROMETER','Mitutoyo','MDC-25PX','SN-2024-002',0.001,'0~25mm',12,DATE '2025-08-20',DATE '2026-08-20','ACTIVE','품질검사실','40','1000','admin','admin')""",
    """INSERT INTO GAUGE_MASTERS (GAUGE_CODE,GAUGE_NAME,GAUGE_TYPE,MANUFACTURER,MODEL,SERIAL_NO,RESOLUTION,MEASURE_RANGE,CALIBRATION_CYCLE,LAST_CALIBRATION_DATE,NEXT_CALIBRATION_DATE,STATUS,LOCATION,COMPANY,PLANT,CREATED_BY,UPDATED_BY) VALUES ('GAU-003','인장시험기','TESTER','Shimadzu','AGS-X 500N','SN-2023-010',0.01,'0~500N',6,DATE '2025-12-01',DATE '2026-06-01','ACTIVE','생산현장','40','1000','admin','admin')""",
    """INSERT INTO GAUGE_MASTERS (GAUGE_CODE,GAUGE_NAME,GAUGE_TYPE,MANUFACTURER,SERIAL_NO,CALIBRATION_CYCLE,LAST_CALIBRATION_DATE,NEXT_CALIBRATION_DATE,STATUS,LOCATION,COMPANY,PLANT,CREATED_BY,UPDATED_BY) VALUES ('GAU-004','접촉저항 측정기','TESTER','Hioki','SN-2024-005',12,DATE '2025-06-15',DATE '2026-06-15','ACTIVE','품질검사실','40','1000','admin','admin')""",

    # ============ 10. CALIBRATION_LOGS ============
    """INSERT INTO CALIBRATION_LOGS (CALIBRATION_NO,GAUGE_ID,CALIBRATION_DATE,CALIBRATOR,CALIBRATION_TYPE,RESULT,CERTIFICATE_NO,NEXT_DUE_DATE,REMARKS,COMPANY,PLANT,CREATED_BY) VALUES ('CAL-20250915-001',(SELECT ID FROM GAUGE_MASTERS WHERE GAUGE_CODE='GAU-001'),DATE '2025-09-15','한국표준과학연구원','EXTERNAL','PASS','KRISS-2025-09-1234',DATE '2026-09-15','정기 교정','40','1000','admin')""",
    """INSERT INTO CALIBRATION_LOGS (CALIBRATION_NO,GAUGE_ID,CALIBRATION_DATE,CALIBRATOR,CALIBRATION_TYPE,RESULT,CERTIFICATE_NO,NEXT_DUE_DATE,COMPANY,PLANT,CREATED_BY) VALUES ('CAL-20250820-001',(SELECT ID FROM GAUGE_MASTERS WHERE GAUGE_CODE='GAU-002'),DATE '2025-08-20','한국표준과학연구원','EXTERNAL','PASS','KRISS-2025-08-5678',DATE '2026-08-20','40','1000','admin')""",
    """INSERT INTO CALIBRATION_LOGS (CALIBRATION_NO,GAUGE_ID,CALIBRATION_DATE,CALIBRATOR,CALIBRATION_TYPE,RESULT,CERTIFICATE_NO,NEXT_DUE_DATE,COMPANY,PLANT,CREATED_BY) VALUES ('CAL-20251201-001',(SELECT ID FROM GAUGE_MASTERS WHERE GAUGE_CODE='GAU-003'),DATE '2025-12-01','Shimadzu Korea','EXTERNAL','PASS','SMZ-2025-12-0099',DATE '2026-06-01','40','1000','admin')""",

    # ============ 11. CONTROL_PLANS (REVISION_NO=NUMBER NOT NULL, PHASE=VARCHAR NOT NULL) ============
    """INSERT INTO CONTROL_PLANS (PLAN_NO,ITEM_CODE,ITEM_NAME,PHASE,REVISION_NO,STATUS,APPROVED_BY,APPROVED_AT,REMARKS,COMPANY,PLANT,CREATED_BY,UPDATED_BY) VALUES ('CP-20260101-001','FG-DH-001','도어 하네스 Assy','PRODUCTION',1,'APPROVED','W002',SYSTIMESTAMP-60,'도어 하네스 양산 관리계획서','40','1000','admin','admin')""",
    """INSERT INTO CONTROL_PLANS (PLAN_NO,ITEM_CODE,ITEM_NAME,PHASE,REVISION_NO,STATUS,REMARKS,COMPANY,PLANT,CREATED_BY,UPDATED_BY) VALUES ('CP-20260301-001','FG-EH-001','엔진룸 하네스 Assy','PRE_LAUNCH',1,'DRAFT','엔진룸 하네스 사전 관리계획서','40','1000','admin','admin')""",

    # ============ 12. CONTROL_PLAN_ITEMS (CONTROL_PLAN_ID=NUMBER NOT NULL) ============
    """INSERT INTO CONTROL_PLAN_ITEMS (CONTROL_PLAN_ID,SEQ,PROCESS_NAME,CHARACTERISTIC_NO,PRODUCT_CHARACTERISTIC,PROCESS_CHARACTERISTIC,SPECIAL_CHAR_CLASS,SPECIFICATION,EVAL_METHOD,SAMPLE_SIZE,SAMPLE_FREQ,CONTROL_METHOD,REACTION_PLAN,COMPANY,PLANT,CREATED_BY) VALUES ((SELECT ID FROM CONTROL_PLANS WHERE PLAN_NO='CP-20260101-001'),1,'절단','C-001','전선 길이','절단 길이 설정','SC','150+/-2mm','자동측정','5EA','매 LOT','X-bar R 관리도','공정 정지','40','1000','admin')""",
    """INSERT INTO CONTROL_PLAN_ITEMS (CONTROL_PLAN_ID,SEQ,PROCESS_NAME,CHARACTERISTIC_NO,PRODUCT_CHARACTERISTIC,PROCESS_CHARACTERISTIC,SPECIFICATION,EVAL_METHOD,SAMPLE_SIZE,SAMPLE_FREQ,CONTROL_METHOD,REACTION_PLAN,COMPANY,PLANT,CREATED_BY) VALUES ((SELECT ID FROM CONTROL_PLANS WHERE PLAN_NO='CP-20260101-001'),2,'탈피','C-002','탈피 길이','탈피 길이 설정','8+/-0.5mm','캘리퍼스','5EA','매 LOT','초중종물 검사','공정 정지 조정','40','1000','admin')""",
    """INSERT INTO CONTROL_PLAN_ITEMS (CONTROL_PLAN_ID,SEQ,PROCESS_NAME,CHARACTERISTIC_NO,PRODUCT_CHARACTERISTIC,PROCESS_CHARACTERISTIC,SPECIAL_CHAR_CLASS,SPECIFICATION,EVAL_METHOD,SAMPLE_SIZE,SAMPLE_FREQ,CONTROL_METHOD,REACTION_PLAN,COMPANY,PLANT,CREATED_BY) VALUES ((SELECT ID FROM CONTROL_PLANS WHERE PLAN_NO='CP-20260101-001'),3,'압착','C-003','압착 높이','압착 프레스 높이','CC','3.20+/-0.15mm','마이크로미터','5EA','2시간','X-bar R 관리도','공정 정지 금형 점검','40','1000','admin')""",
    """INSERT INTO CONTROL_PLAN_ITEMS (CONTROL_PLAN_ID,SEQ,PROCESS_NAME,CHARACTERISTIC_NO,PRODUCT_CHARACTERISTIC,PROCESS_CHARACTERISTIC,SPECIFICATION,EVAL_METHOD,SAMPLE_SIZE,SAMPLE_FREQ,CONTROL_METHOD,REACTION_PLAN,COMPANY,PLANT,CREATED_BY) VALUES ((SELECT ID FROM CONTROL_PLANS WHERE PLAN_NO='CP-20260101-001'),4,'검사','C-004','도통','도통 검사','전 회로 도통','자동검사기','전수','전수','자동 판정','불합격시 재작업','40','1000','admin')""",

    # ============ 13. PPAP_SUBMISSIONS (18 element flags = NUMBER(1) NOT NULL) ============
    """INSERT INTO PPAP_SUBMISSIONS (PPAP_NO,ITEM_CODE,ITEM_NAME,CUSTOMER_CODE,CUSTOMER_NAME,PPAP_LEVEL,REASON,STATUS,SUBMITTED_AT,APPROVED_AT,APPROVED_BY,DESIGN_RECORDS,ECN_DOCUMENTS,CUSTOMER_APPROVAL,DFMEA,PROCESS_FLOW_DIAGRAM,PFMEA,CONTROL_PLAN,MSA_STUDIES,DIMENSIONAL_RESULTS,MATERIAL_TEST_RESULTS,INITIAL_PROCESS_STUDIES,QUALIFIED_LAB_DOC,APPEARANCE_APPROVAL,SAMPLE_PRODUCT,MASTER_SAMPLE,CHECKING_AIDS,CUSTOMER_SPECIFIC_REQ,PART_SUBMISSION_WARRANT,COMPANY,PLANT,CREATED_BY,UPDATED_BY) VALUES ('PPAP-20260101-001','FG-DH-001','도어 하네스 Assy','CUS-001','현대자동차',3,'NEW_PART','APPROVED',SYSTIMESTAMP-60,SYSTIMESTAMP-50,'CUS-001',1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,'40','1000','admin','admin')""",
    """INSERT INTO PPAP_SUBMISSIONS (PPAP_NO,ITEM_CODE,ITEM_NAME,CUSTOMER_CODE,CUSTOMER_NAME,PPAP_LEVEL,REASON,STATUS,DESIGN_RECORDS,ECN_DOCUMENTS,CUSTOMER_APPROVAL,DFMEA,PROCESS_FLOW_DIAGRAM,PFMEA,CONTROL_PLAN,MSA_STUDIES,DIMENSIONAL_RESULTS,MATERIAL_TEST_RESULTS,INITIAL_PROCESS_STUDIES,QUALIFIED_LAB_DOC,APPEARANCE_APPROVAL,SAMPLE_PRODUCT,MASTER_SAMPLE,CHECKING_AIDS,CUSTOMER_SPECIFIC_REQ,PART_SUBMISSION_WARRANT,COMPANY,PLANT,CREATED_BY,UPDATED_BY) VALUES ('PPAP-20260301-001','FG-EH-001','엔진룸 하네스 Assy','CUS-002','기아자동차',3,'ECN_CHANGE','SUBMITTED',1,0,0,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,'40','1000','admin','admin')""",

    # ============ 14. TRAINING_PLANS ============
    """INSERT INTO TRAINING_PLANS (PLAN_NO,TITLE,TRAINING_TYPE,DESCRIPTION,INSTRUCTOR,SCHEDULED_DATE,DURATION,TARGET_ROLE,STATUS,COMPANY,PLANT,CREATED_BY,UPDATED_BY) VALUES ('TRN-20260301-001','IATF 16949 품질경영시스템 교육','QUALITY','IATF 16949 요구사항 및 내부심사원 양성','외부강사',DATE '2026-03-05',8,'품질관리부','COMPLETED','40','1000','admin','admin')""",
    """INSERT INTO TRAINING_PLANS (PLAN_NO,TITLE,TRAINING_TYPE,DESCRIPTION,INSTRUCTOR,SCHEDULED_DATE,DURATION,TARGET_ROLE,STATUS,COMPANY,PLANT,CREATED_BY,UPDATED_BY) VALUES ('TRN-20260310-001','SPC 관리도 실무 교육','SKILL','X-bar R 관리도 작성 및 공정능력분석','W003',DATE '2026-03-15',4,'생산부','PLANNED','40','1000','admin','admin')""",
    """INSERT INTO TRAINING_PLANS (PLAN_NO,TITLE,TRAINING_TYPE,DESCRIPTION,INSTRUCTOR,SCHEDULED_DATE,DURATION,TARGET_ROLE,STATUS,COMPANY,PLANT,CREATED_BY,UPDATED_BY) VALUES ('TRN-20260201-001','안전보건 정기교육','SAFETY','산업안전보건법 정기 안전교육','안전관리자',DATE '2026-02-10',2,'전체','COMPLETED','40','1000','admin','admin')""",

    # ============ 15. TRAINING_RESULTS (PASSED=NUMBER(1) NOT NULL) ============
    """INSERT INTO TRAINING_RESULTS (PLAN_ID,WORKER_CODE,WORKER_NAME,ATTEND_DATE,SCORE,PASSED,CERTIFICATE_NO,VALID_UNTIL,COMPANY,PLANT,CREATED_BY) VALUES ((SELECT ID FROM TRAINING_PLANS WHERE PLAN_NO='TRN-20260301-001'),'W001','김철수',DATE '2026-03-05',92,1,'IATF-IA-2026-001',DATE '2029-03-05','40','1000','admin')""",
    """INSERT INTO TRAINING_RESULTS (PLAN_ID,WORKER_CODE,WORKER_NAME,ATTEND_DATE,SCORE,PASSED,CERTIFICATE_NO,VALID_UNTIL,COMPANY,PLANT,CREATED_BY) VALUES ((SELECT ID FROM TRAINING_PLANS WHERE PLAN_NO='TRN-20260301-001'),'W003','박민수',DATE '2026-03-05',88,1,'IATF-IA-2026-002',DATE '2029-03-05','40','1000','admin')""",
    """INSERT INTO TRAINING_RESULTS (PLAN_ID,WORKER_CODE,WORKER_NAME,ATTEND_DATE,SCORE,PASSED,COMPANY,PLANT,CREATED_BY) VALUES ((SELECT ID FROM TRAINING_PLANS WHERE PLAN_NO='TRN-20260301-001'),'W004','정수진',DATE '2026-03-05',65,0,'40','1000','admin')""",
    """INSERT INTO TRAINING_RESULTS (PLAN_ID,WORKER_CODE,WORKER_NAME,ATTEND_DATE,PASSED,COMPANY,PLANT,CREATED_BY) VALUES ((SELECT ID FROM TRAINING_PLANS WHERE PLAN_NO='TRN-20260201-001'),'W001','김철수',DATE '2026-02-10',1,'40','1000','admin')""",
    """INSERT INTO TRAINING_RESULTS (PLAN_ID,WORKER_CODE,WORKER_NAME,ATTEND_DATE,PASSED,COMPANY,PLANT,CREATED_BY) VALUES ((SELECT ID FROM TRAINING_PLANS WHERE PLAN_NO='TRN-20260201-001'),'W002','이영희',DATE '2026-02-10',1,'40','1000','admin')""",
    """INSERT INTO TRAINING_RESULTS (PLAN_ID,WORKER_CODE,WORKER_NAME,ATTEND_DATE,PASSED,COMPANY,PLANT,CREATED_BY) VALUES ((SELECT ID FROM TRAINING_PLANS WHERE PLAN_NO='TRN-20260201-001'),'W005','최동현',DATE '2026-02-10',1,'40','1000','admin')""",

    # ============ 16. DOCUMENT_MASTERS (DOC_TITLE, REVISION_NO=NUMBER NOT NULL) ============
    """INSERT INTO DOCUMENT_MASTERS (DOC_NO,DOC_TYPE,DOC_TITLE,CATEGORY,REVISION_NO,STATUS,APPROVED_BY,APPROVED_AT,EXPIRES_AT,DESCRIPTION,COMPANY,PLANT,CREATED_BY,UPDATED_BY) VALUES ('DOC-QM-001','MANUAL','품질매뉴얼','품질',3,'APPROVED','W002',SYSTIMESTAMP-70,DATE '2027-01-01','IATF 16949 기반 품질경영시스템 매뉴얼','40','1000','admin','admin')""",
    """INSERT INTO DOCUMENT_MASTERS (DOC_NO,DOC_TYPE,DOC_TITLE,CATEGORY,REVISION_NO,STATUS,APPROVED_BY,APPROVED_AT,EXPIRES_AT,DESCRIPTION,COMPANY,PLANT,CREATED_BY,UPDATED_BY) VALUES ('DOC-QP-001','PROCEDURE','입고검사 절차서','품질',2,'APPROVED','W001',SYSTIMESTAMP-120,DATE '2026-10-01','원자재 입고검사 절차 및 기준','40','1000','admin','admin')""",
    """INSERT INTO DOCUMENT_MASTERS (DOC_NO,DOC_TYPE,DOC_TITLE,CATEGORY,REVISION_NO,STATUS,APPROVED_BY,APPROVED_AT,EXPIRES_AT,DESCRIPTION,COMPANY,PLANT,CREATED_BY,UPDATED_BY) VALUES ('DOC-WI-001','WORK_INSTRUCTION','압착 공정 작업표준서','생산',1,'APPROVED','W001',SYSTIMESTAMP-100,DATE '2026-11-01','와이어 하네스 압착 공정 상세 작업 기준','40','1000','admin','admin')""",
    """INSERT INTO DOCUMENT_MASTERS (DOC_NO,DOC_TYPE,DOC_TITLE,CATEGORY,REVISION_NO,STATUS,DESCRIPTION,COMPANY,PLANT,CREATED_BY,UPDATED_BY) VALUES ('DOC-QP-010','PROCEDURE','CAPA 관리 절차서','품질',1,'DRAFT','시정/예방조치 처리 절차','40','1000','admin','admin')""",
    """INSERT INTO DOCUMENT_MASTERS (DOC_NO,DOC_TYPE,DOC_TITLE,CATEGORY,REVISION_NO,STATUS,APPROVED_BY,APPROVED_AT,EXPIRES_AT,DESCRIPTION,COMPANY,PLANT,CREATED_BY,UPDATED_BY) VALUES ('DOC-WI-002','WORK_INSTRUCTION','절단 공정 작업표준서','생산',2,'APPROVED','W001',SYSTIMESTAMP-35,DATE '2026-04-01','와이어 절단 공정 상세 작업 기준','40','1000','admin','admin')""",

    # ============ 17. AUDIT_PLANS (SCHEDULED_DATE=TIMESTAMP NOT NULL) ============
    """INSERT INTO AUDIT_PLANS (AUDIT_NO,AUDIT_TYPE,AUDIT_SCOPE,TARGET_DEPT,AUDITOR,CO_AUDITOR,SCHEDULED_DATE,ACTUAL_DATE,STATUS,OVERALL_RESULT,SUMMARY,COMPANY,PLANT,CREATED_BY,UPDATED_BY) VALUES ('AUD-20260201-001','SYSTEM','IATF 16949 전체 조항 (4~10절)','전체','W001','W003,W004',DATE '2026-02-20',DATE '2026-02-20','CLOSED','PASS','경미부적합 2건, 관찰사항 1건','40','1000','admin','admin')""",
    """INSERT INTO AUDIT_PLANS (AUDIT_NO,AUDIT_TYPE,AUDIT_SCOPE,TARGET_DEPT,AUDITOR,CO_AUDITOR,SCHEDULED_DATE,STATUS,COMPANY,PLANT,CREATED_BY,UPDATED_BY) VALUES ('AUD-20260401-001','PROCESS','압착 공정 관리 상태 점검','생산부','W003','W006',DATE '2026-04-01','PLANNED','40','1000','admin','admin')""",
    """INSERT INTO AUDIT_PLANS (AUDIT_NO,AUDIT_TYPE,AUDIT_SCOPE,TARGET_DEPT,AUDITOR,CO_AUDITOR,SCHEDULED_DATE,STATUS,COMPANY,PLANT,CREATED_BY,UPDATED_BY) VALUES ('AUD-20260301-001','PRODUCT','FG-DH-001 제품 적합성 심사','품질관리부','W001','W003',DATE '2026-03-15','IN_PROGRESS','40','1000','admin','admin')""",

    # ============ 18. AUDIT_FINDINGS (FINDING_NO=NUMBER, AUDIT_ID=NUMBER) ============
    """INSERT INTO AUDIT_FINDINGS (AUDIT_ID,FINDING_NO,CATEGORY,CLAUSE_REF,DESCRIPTION,EVIDENCE,DUE_DATE,STATUS,COMPANY,PLANT,CREATED_BY) VALUES ((SELECT ID FROM AUDIT_PLANS WHERE AUDIT_NO='AUD-20260201-001'),1,'MINOR_NC','7.5','문서관리 절차서 일부 미승인 상태 발견','절단 공정 작업표준서 Rev.1 미승인',DATE '2026-03-10','CLOSED','40','1000','admin')""",
    """INSERT INTO AUDIT_FINDINGS (AUDIT_ID,FINDING_NO,CATEGORY,CLAUSE_REF,DESCRIPTION,EVIDENCE,DUE_DATE,STATUS,COMPANY,PLANT,CREATED_BY) VALUES ((SELECT ID FROM AUDIT_PLANS WHERE AUDIT_NO='AUD-20260201-001'),2,'OBSERVATION','7.1.5','계측기 교정 주기 관리 개선 필요','일부 계측기 교정 만료일 관리가 수기',DATE '2026-04-01','OPEN','40','1000','admin')""",
    """INSERT INTO AUDIT_FINDINGS (AUDIT_ID,FINDING_NO,CATEGORY,CLAUSE_REF,DESCRIPTION,EVIDENCE,STATUS,COMPANY,PLANT,CREATED_BY) VALUES ((SELECT ID FROM AUDIT_PLANS WHERE AUDIT_NO='AUD-20260201-001'),3,'OPPORTUNITY','9.1.1','SPC 관리도 활용 확대 기회','현재 압착 공정만 SPC 적용, 확대 가능','OPEN','40','1000','admin')""",

    # ============ 19. MOLD_MASTERS (CAVITY=NUMBER NOT NULL, CURRENT_SHOTS=NUMBER NOT NULL) ============
    """INSERT INTO MOLD_MASTERS (MOLD_CODE,MOLD_NAME,MOLD_TYPE,ITEM_CODE,CAVITY,GUARANTEED_SHOTS,CURRENT_SHOTS,MAINTENANCE_CYCLE,LAST_MAINTENANCE_DATE,NEXT_MAINTENANCE_DATE,MAKER,PURCHASE_DATE,STATUS,LOCATION,COMPANY,PLANT,CREATED_BY,UPDATED_BY) VALUES ('MLD-CR-001','6P 압착 금형 A','CRIMP','RAW-C-001',1,500000,350000,50000,DATE '2026-02-15',DATE '2026-03-20','금형제작소A',DATE '2024-01-15','ACTIVE','압착기 #1','40','1000','admin','admin')""",
    """INSERT INTO MOLD_MASTERS (MOLD_CODE,MOLD_NAME,MOLD_TYPE,ITEM_CODE,CAVITY,GUARANTEED_SHOTS,CURRENT_SHOTS,MAINTENANCE_CYCLE,LAST_MAINTENANCE_DATE,NEXT_MAINTENANCE_DATE,MAKER,PURCHASE_DATE,STATUS,LOCATION,COMPANY,PLANT,CREATED_BY,UPDATED_BY) VALUES ('MLD-CR-002','6P 압착 금형 B (신규)','CRIMP','RAW-C-001',1,500000,5000,50000,DATE '2026-03-10',DATE '2026-04-25','금형제작소A',DATE '2026-03-01','ACTIVE','압착기 #2','40','1000','admin','admin')""",
    """INSERT INTO MOLD_MASTERS (MOLD_CODE,MOLD_NAME,MOLD_TYPE,ITEM_CODE,CAVITY,GUARANTEED_SHOTS,CURRENT_SHOTS,MAINTENANCE_CYCLE,LAST_MAINTENANCE_DATE,NEXT_MAINTENANCE_DATE,MAKER,PURCHASE_DATE,STATUS,LOCATION,COMPANY,PLANT,CREATED_BY,UPDATED_BY) VALUES ('MLD-CR-003','10P 압착 금형','CRIMP','RAW-C-002',1,500000,420000,50000,DATE '2026-01-20',DATE '2026-03-05','금형제작소B',DATE '2023-06-10','MAINTENANCE','보전실','40','1000','admin','admin')""",
    """INSERT INTO MOLD_MASTERS (MOLD_CODE,MOLD_NAME,MOLD_TYPE,ITEM_CODE,CAVITY,GUARANTEED_SHOTS,CURRENT_SHOTS,MAINTENANCE_CYCLE,MAKER,PURCHASE_DATE,STATUS,LOCATION,COMPANY,PLANT,CREATED_BY,UPDATED_BY) VALUES ('MLD-CUT-001','절단 블레이드 세트','CUT','RAW-P-001',1,100000,85000,20000,'절단기부품사',DATE '2024-06-01','ACTIVE','절단기 #1','40','1000','admin','admin')""",

    # ============ 20. MOLD_USAGE_LOGS (MOLD_ID=NUMBER, WORKER_CODE, USAGE_DATE=TIMESTAMP) ============
    """INSERT INTO MOLD_USAGE_LOGS (MOLD_ID,USAGE_DATE,SHOT_COUNT,ORDER_NO,WORKER_CODE,REMARKS,COMPANY,PLANT,CREATED_BY) VALUES ((SELECT ID FROM MOLD_MASTERS WHERE MOLD_CODE='MLD-CR-001'),DATE '2026-03-10',1200,'JO-20260310-001','W005','정상 가동','40','1000','admin')""",
    """INSERT INTO MOLD_USAGE_LOGS (MOLD_ID,USAGE_DATE,SHOT_COUNT,ORDER_NO,WORKER_CODE,COMPANY,PLANT,CREATED_BY) VALUES ((SELECT ID FROM MOLD_MASTERS WHERE MOLD_CODE='MLD-CR-001'),DATE '2026-03-11',1500,'JO-20260311-001','W005','40','1000','admin')""",
    """INSERT INTO MOLD_USAGE_LOGS (MOLD_ID,USAGE_DATE,SHOT_COUNT,ORDER_NO,WORKER_CODE,COMPANY,PLANT,CREATED_BY) VALUES ((SELECT ID FROM MOLD_MASTERS WHERE MOLD_CODE='MLD-CR-002'),DATE '2026-03-10',2500,'JO-20260310-002','W009','40','1000','admin')""",
    """INSERT INTO MOLD_USAGE_LOGS (MOLD_ID,USAGE_DATE,SHOT_COUNT,ORDER_NO,WORKER_CODE,REMARKS,COMPANY,PLANT,CREATED_BY) VALUES ((SELECT ID FROM MOLD_MASTERS WHERE MOLD_CODE='MLD-CR-002'),DATE '2026-03-11',2500,'JO-20260311-002','W009','금형 교체 후 초도','40','1000','admin')""",
    """INSERT INTO MOLD_USAGE_LOGS (MOLD_ID,USAGE_DATE,SHOT_COUNT,WORKER_CODE,COMPANY,PLANT,CREATED_BY) VALUES ((SELECT ID FROM MOLD_MASTERS WHERE MOLD_CODE='MLD-CUT-001'),DATE '2026-03-10',3000,'W007','40','1000','admin')""",
]

ok = 0
fail = 0
for i, sql in enumerate(sqls):
    try:
        cur.execute(sql)
        ok += 1
    except Exception as e:
        m = re.search(r'INTO\s+(\w+)', sql, re.IGNORECASE)
        tbl = m.group(1) if m else '?'
        err = str(e).split('\n')[0][:120]
        print(f'[{i+1:2d}] FAIL ({tbl}): {err}')
        fail += 1

conn.commit()
cur.close()
conn.close()
print(f'\n=== Total: {ok} OK, {fail} FAIL (out of {len(sqls)}) ===')
