MERGE INTO "COM_CODES" t
USING (
  SELECT 'FAI_TRIGGER_TYPE' AS "GROUP_CODE", 'EQUIP_CHANGE' AS "DETAIL_CODE", '설비변경' AS "CODE_NAME", 5 AS "SORT_ORDER", 'Equipment Change' AS "ATTR1", '设备变更' AS "ATTR2", 'Thay đổi thiết bị' AS "ATTR3" FROM DUAL
) s ON (t."COMPANY" = 'HANES' AND t."PLANT_CD" = 'VINA' AND t."GROUP_CODE" = s."GROUP_CODE" AND t."DETAIL_CODE" = s."DETAIL_CODE")
WHEN NOT MATCHED THEN INSERT (
  "COMPANY", "PLANT_CD", "GROUP_CODE", "DETAIL_CODE", "CODE_NAME", "SORT_ORDER", "USE_YN", "ATTR1", "ATTR2", "ATTR3", "CREATED_BY"
) VALUES (
  'HANES', 'VINA', s."GROUP_CODE", s."DETAIL_CODE", s."CODE_NAME", s."SORT_ORDER", 'Y', s."ATTR1", s."ATTR2", s."ATTR3", 'SYSTEM'
)
