-- =================================================================
-- CONTROL_PLANS + CONTROL_PLAN_ITEMS 시드 데이터
-- 실제 ITEM_MASTERS 품목 기준
-- COMPANY: 40, PLANT: 1000 (HANES)
-- =================================================================

-- =============================================
-- 1) 엔진룸 하네스 Assy - 양산단계, 승인완료 (Rev.2)
-- =============================================
INSERT INTO CONTROL_PLANS (PLAN_NO, ITEM_CODE, ITEM_NAME, REVISION_NO, REVISION_DATE, PHASE, STATUS, APPROVED_BY, APPROVED_AT, REMARKS, COMPANY, PLANT, CREATED_BY, UPDATED_BY, CREATED_AT, UPDATED_AT)
VALUES ('CP-20260115-001', 'FG-EH-001', '엔진룸 하네스 Assy', 2, TIMESTAMP '2026-02-01 09:00:00', 'PRODUCTION', 'APPROVED', 'admin', TIMESTAMP '2026-02-05 14:00:00', '양산 관리계획서 Rev.2 - 검사기준 강화', '40', '1000', 'admin', 'admin', TIMESTAMP '2026-01-15 10:00:00', TIMESTAMP '2026-02-05 14:00:00');

-- =============================================
-- 2) 6P 커넥터 하우징 - 양산시험단계, 작성중
-- =============================================
INSERT INTO CONTROL_PLANS (PLAN_NO, ITEM_CODE, ITEM_NAME, REVISION_NO, REVISION_DATE, PHASE, STATUS, APPROVED_BY, APPROVED_AT, REMARKS, COMPANY, PLANT, CREATED_BY, UPDATED_BY, CREATED_AT, UPDATED_AT)
VALUES ('CP-20260220-001', 'RAW-C-001', '6P 커넥터 하우징', 1, TIMESTAMP '2026-02-20 09:00:00', 'PRE_LAUNCH', 'DRAFT', NULL, NULL, '양산시험 관리계획서 초안', '40', '1000', 'admin', 'admin', TIMESTAMP '2026-02-20 09:00:00', TIMESTAMP '2026-02-20 09:00:00');

-- =============================================
-- 3) 10P 커넥터 하우징 - 양산단계, 승인완료
-- =============================================
INSERT INTO CONTROL_PLANS (PLAN_NO, ITEM_CODE, ITEM_NAME, REVISION_NO, REVISION_DATE, PHASE, STATUS, APPROVED_BY, APPROVED_AT, REMARKS, COMPANY, PLANT, CREATED_BY, UPDATED_BY, CREATED_AT, UPDATED_AT)
VALUES ('CP-20260110-001', 'RAW-C-002', '10P 커넥터 하우징', 1, TIMESTAMP '2026-01-10 09:00:00', 'PRODUCTION', 'APPROVED', 'admin', TIMESTAMP '2026-01-15 11:00:00', '양산 관리계획서', '40', '1000', 'admin', 'admin', TIMESTAMP '2026-01-10 09:00:00', TIMESTAMP '2026-01-15 11:00:00');

-- =============================================
-- 4) 090형 암단자 - 시작품단계, 작성중
-- =============================================
INSERT INTO CONTROL_PLANS (PLAN_NO, ITEM_CODE, ITEM_NAME, REVISION_NO, REVISION_DATE, PHASE, STATUS, APPROVED_BY, APPROVED_AT, REMARKS, COMPANY, PLANT, CREATED_BY, UPDATED_BY, CREATED_AT, UPDATED_AT)
VALUES ('CP-20260310-001', 'RAW-T-001', '090형 암단자', 1, TIMESTAMP '2026-03-10 09:00:00', 'PROTOTYPE', 'DRAFT', NULL, NULL, '시작품 평가용 관리계획서', '40', '1000', 'admin', 'admin', TIMESTAMP '2026-03-10 09:00:00', TIMESTAMP '2026-03-10 09:00:00');

-- =============================================
-- 5) AVS 0.5sq 흑색 전선 - 양산단계, 승인완료
-- =============================================
INSERT INTO CONTROL_PLANS (PLAN_NO, ITEM_CODE, ITEM_NAME, REVISION_NO, REVISION_DATE, PHASE, STATUS, APPROVED_BY, APPROVED_AT, REMARKS, COMPANY, PLANT, CREATED_BY, UPDATED_BY, CREATED_AT, UPDATED_AT)
VALUES ('CP-20260105-001', 'RAW-W-001', 'AVS 0.5sq 흑색 전선', 1, TIMESTAMP '2026-01-05 09:00:00', 'PRODUCTION', 'APPROVED', 'admin', TIMESTAMP '2026-01-08 16:00:00', '전선류 양산 관리계획서', '40', '1000', 'admin', 'admin', TIMESTAMP '2026-01-05 09:00:00', TIMESTAMP '2026-01-08 16:00:00');

-- =============================================
-- 6) 2P 방수커넥터 - 양산시험, 승인완료
-- =============================================
INSERT INTO CONTROL_PLANS (PLAN_NO, ITEM_CODE, ITEM_NAME, REVISION_NO, REVISION_DATE, PHASE, STATUS, APPROVED_BY, APPROVED_AT, REMARKS, COMPANY, PLANT, CREATED_BY, UPDATED_BY, CREATED_AT, UPDATED_AT)
VALUES ('CP-20260201-001', 'RAW-C-004', '2P 방수커넥터', 1, TIMESTAMP '2026-02-01 09:00:00', 'PRE_LAUNCH', 'APPROVED', 'admin', TIMESTAMP '2026-02-10 15:00:00', 'IP67 방수 성능 시험 포함', '40', '1000', 'admin', 'admin', TIMESTAMP '2026-02-01 09:00:00', TIMESTAMP '2026-02-10 15:00:00');

-- =============================================
-- 7) 환형단자 M6 - 양산, 폐기(OBSOLETE) - 개정 전 버전
-- =============================================
INSERT INTO CONTROL_PLANS (PLAN_NO, ITEM_CODE, ITEM_NAME, REVISION_NO, REVISION_DATE, PHASE, STATUS, APPROVED_BY, APPROVED_AT, REMARKS, COMPANY, PLANT, CREATED_BY, UPDATED_BY, CREATED_AT, UPDATED_AT)
VALUES ('CP-20251201-001', 'RAW-T-005', '환형단자 M6', 1, TIMESTAMP '2025-12-01 09:00:00', 'PRODUCTION', 'OBSOLETE', 'admin', TIMESTAMP '2025-12-05 10:00:00', 'Rev.1 - Rev.2로 개정됨', '40', '1000', 'admin', 'admin', TIMESTAMP '2025-12-01 09:00:00', TIMESTAMP '2026-01-20 09:00:00');

-- =============================================
-- 8) 환형단자 M6 - 양산, 승인완료 (Rev.2 - 개정본)
-- =============================================
INSERT INTO CONTROL_PLANS (PLAN_NO, ITEM_CODE, ITEM_NAME, REVISION_NO, REVISION_DATE, PHASE, STATUS, APPROVED_BY, APPROVED_AT, REMARKS, COMPANY, PLANT, CREATED_BY, UPDATED_BY, CREATED_AT, UPDATED_AT)
VALUES ('CP-20260120-001', 'RAW-T-005', '환형단자 M6', 2, TIMESTAMP '2026-01-20 09:00:00', 'PRODUCTION', 'APPROVED', 'admin', TIMESTAMP '2026-01-25 14:00:00', 'Rev.2 - 금형 이관 후 검사기준 변경', '40', '1000', 'admin', 'admin', TIMESTAMP '2026-01-20 09:00:00', TIMESTAMP '2026-01-25 14:00:00');

-- =============================================
-- CONTROL_PLAN_ITEMS (관리항목)
-- =============================================

-- CP-20260115-001 (엔진룸 하네스 Assy) 항목들
INSERT INTO CONTROL_PLAN_ITEMS (CONTROL_PLAN_ID, SEQ, PROCESS_CODE, PROCESS_NAME, CHARACTERISTIC_NO, PRODUCT_CHARACTERISTIC, PROCESS_CHARACTERISTIC, SPECIAL_CHAR_CLASS, SPECIFICATION, EVAL_METHOD, SAMPLE_SIZE, SAMPLE_FREQ, CONTROL_METHOD, REACTION_PLAN, REMARKS, COMPANY, PLANT, CREATED_BY, CREATED_AT)
SELECT ID, 1, 'P-010', '전선 절단', 'C-001', '전선 길이', '절단 길이 설정', 'SC', '250±2mm', '버니어캘리퍼스', '5EA', '매 LOT', 'X-R 관리도', '재절단 및 원인분석', NULL, '40', '1000', 'admin', TIMESTAMP '2026-01-15 10:00:00' FROM CONTROL_PLANS WHERE PLAN_NO = 'CP-20260115-001';

INSERT INTO CONTROL_PLAN_ITEMS (CONTROL_PLAN_ID, SEQ, PROCESS_CODE, PROCESS_NAME, CHARACTERISTIC_NO, PRODUCT_CHARACTERISTIC, PROCESS_CHARACTERISTIC, SPECIAL_CHAR_CLASS, SPECIFICATION, EVAL_METHOD, SAMPLE_SIZE, SAMPLE_FREQ, CONTROL_METHOD, REACTION_PLAN, REMARKS, COMPANY, PLANT, CREATED_BY, CREATED_AT)
SELECT ID, 2, 'P-020', '단자 압착', 'C-002', '압착 높이', '크림프 높이', 'CC', '1.2±0.05mm', '마이크로미터', '5EA', '2시간/1회', 'X-R 관리도', '설비 조정 후 재검사', '핵심 안전 특성', '40', '1000', 'admin', TIMESTAMP '2026-01-15 10:00:00' FROM CONTROL_PLANS WHERE PLAN_NO = 'CP-20260115-001';

INSERT INTO CONTROL_PLAN_ITEMS (CONTROL_PLAN_ID, SEQ, PROCESS_CODE, PROCESS_NAME, CHARACTERISTIC_NO, PRODUCT_CHARACTERISTIC, PROCESS_CHARACTERISTIC, SPECIAL_CHAR_CLASS, SPECIFICATION, EVAL_METHOD, SAMPLE_SIZE, SAMPLE_FREQ, CONTROL_METHOD, REACTION_PLAN, REMARKS, COMPANY, PLANT, CREATED_BY, CREATED_AT)
SELECT ID, 3, 'P-020', '단자 압착', 'C-003', '인장강도', '압착 인장력', 'CC', '≥50N', '인장시험기', '5EA', '매 LOT', '체크시트', '전수검사 및 라인 정지', '핵심 안전 특성', '40', '1000', 'admin', TIMESTAMP '2026-01-15 10:00:00' FROM CONTROL_PLANS WHERE PLAN_NO = 'CP-20260115-001';

INSERT INTO CONTROL_PLAN_ITEMS (CONTROL_PLAN_ID, SEQ, PROCESS_CODE, PROCESS_NAME, CHARACTERISTIC_NO, PRODUCT_CHARACTERISTIC, PROCESS_CHARACTERISTIC, SPECIAL_CHAR_CLASS, SPECIFICATION, EVAL_METHOD, SAMPLE_SIZE, SAMPLE_FREQ, CONTROL_METHOD, REACTION_PLAN, REMARKS, COMPANY, PLANT, CREATED_BY, CREATED_AT)
SELECT ID, 4, 'P-030', '커넥터 삽입', 'C-004', '삽입 상태', '삽입력', NULL, '완전 삽입 확인', '치구 검사', '전수', '매 EA', '체크시트', '재삽입 후 확인', NULL, '40', '1000', 'admin', TIMESTAMP '2026-01-15 10:00:00' FROM CONTROL_PLANS WHERE PLAN_NO = 'CP-20260115-001';

INSERT INTO CONTROL_PLAN_ITEMS (CONTROL_PLAN_ID, SEQ, PROCESS_CODE, PROCESS_NAME, CHARACTERISTIC_NO, PRODUCT_CHARACTERISTIC, PROCESS_CHARACTERISTIC, SPECIAL_CHAR_CLASS, SPECIFICATION, EVAL_METHOD, SAMPLE_SIZE, SAMPLE_FREQ, CONTROL_METHOD, REACTION_PLAN, REMARKS, COMPANY, PLANT, CREATED_BY, CREATED_AT)
SELECT ID, 5, 'P-040', '도통 검사', 'C-005', '회로 도통', '도통 저항', 'SC', '≤50mΩ', '도통시험기', '전수', '매 EA', '자동검사기록', '불량 격리 및 재작업', NULL, '40', '1000', 'admin', TIMESTAMP '2026-01-15 10:00:00' FROM CONTROL_PLANS WHERE PLAN_NO = 'CP-20260115-001';

INSERT INTO CONTROL_PLAN_ITEMS (CONTROL_PLAN_ID, SEQ, PROCESS_CODE, PROCESS_NAME, CHARACTERISTIC_NO, PRODUCT_CHARACTERISTIC, PROCESS_CHARACTERISTIC, SPECIAL_CHAR_CLASS, SPECIFICATION, EVAL_METHOD, SAMPLE_SIZE, SAMPLE_FREQ, CONTROL_METHOD, REACTION_PLAN, REMARKS, COMPANY, PLANT, CREATED_BY, CREATED_AT)
SELECT ID, 6, 'P-050', '외관 검사', 'C-006', '외관 상태', '테이핑/클립 상태', NULL, '기준서 대비 합격', '육안검사', '전수', '매 EA', '체크시트', '수정 후 재검사', NULL, '40', '1000', 'admin', TIMESTAMP '2026-01-15 10:00:00' FROM CONTROL_PLANS WHERE PLAN_NO = 'CP-20260115-001';

-- CP-20260110-001 (10P 커넥터 하우징) 항목들
INSERT INTO CONTROL_PLAN_ITEMS (CONTROL_PLAN_ID, SEQ, PROCESS_CODE, PROCESS_NAME, CHARACTERISTIC_NO, PRODUCT_CHARACTERISTIC, PROCESS_CHARACTERISTIC, SPECIAL_CHAR_CLASS, SPECIFICATION, EVAL_METHOD, SAMPLE_SIZE, SAMPLE_FREQ, CONTROL_METHOD, REACTION_PLAN, REMARKS, COMPANY, PLANT, CREATED_BY, CREATED_AT)
SELECT ID, 1, 'P-110', '사출 성형', 'C-101', '외형 치수', '금형 온도/압력', 'SC', '도면 공차 이내', '3차원 측정기', '5EA', '매 LOT', 'X-R 관리도', '금형 보정', NULL, '40', '1000', 'admin', TIMESTAMP '2026-01-10 09:00:00' FROM CONTROL_PLANS WHERE PLAN_NO = 'CP-20260110-001';

INSERT INTO CONTROL_PLAN_ITEMS (CONTROL_PLAN_ID, SEQ, PROCESS_CODE, PROCESS_NAME, CHARACTERISTIC_NO, PRODUCT_CHARACTERISTIC, PROCESS_CHARACTERISTIC, SPECIAL_CHAR_CLASS, SPECIFICATION, EVAL_METHOD, SAMPLE_SIZE, SAMPLE_FREQ, CONTROL_METHOD, REACTION_PLAN, REMARKS, COMPANY, PLANT, CREATED_BY, CREATED_AT)
SELECT ID, 2, 'P-110', '사출 성형', 'C-102', '핀 간격', '금형 정밀도', 'CC', '2.5±0.05mm', '핀게이지', '5EA', '4시간/1회', 'X-R 관리도', '라인 정지, 금형 점검', '핵심 특성', '40', '1000', 'admin', TIMESTAMP '2026-01-10 09:00:00' FROM CONTROL_PLANS WHERE PLAN_NO = 'CP-20260110-001';

INSERT INTO CONTROL_PLAN_ITEMS (CONTROL_PLAN_ID, SEQ, PROCESS_CODE, PROCESS_NAME, CHARACTERISTIC_NO, PRODUCT_CHARACTERISTIC, PROCESS_CHARACTERISTIC, SPECIAL_CHAR_CLASS, SPECIFICATION, EVAL_METHOD, SAMPLE_SIZE, SAMPLE_FREQ, CONTROL_METHOD, REACTION_PLAN, REMARKS, COMPANY, PLANT, CREATED_BY, CREATED_AT)
SELECT ID, 3, 'P-120', '외관 검사', 'C-103', '외관 불량', '사출 조건', NULL, '버, 미성형, 변색 없음', '육안검사', '전수', '매 EA', '체크시트', '불량 격리', NULL, '40', '1000', 'admin', TIMESTAMP '2026-01-10 09:00:00' FROM CONTROL_PLANS WHERE PLAN_NO = 'CP-20260110-001';

-- CP-20260105-001 (AVS 0.5sq 전선) 항목들
INSERT INTO CONTROL_PLAN_ITEMS (CONTROL_PLAN_ID, SEQ, PROCESS_CODE, PROCESS_NAME, CHARACTERISTIC_NO, PRODUCT_CHARACTERISTIC, PROCESS_CHARACTERISTIC, SPECIAL_CHAR_CLASS, SPECIFICATION, EVAL_METHOD, SAMPLE_SIZE, SAMPLE_FREQ, CONTROL_METHOD, REACTION_PLAN, REMARKS, COMPANY, PLANT, CREATED_BY, CREATED_AT)
SELECT ID, 1, 'P-210', '수입 검사', 'C-201', '도체 저항', '전선 품질', 'SC', '≤36.7Ω/km', '저항측정기', '3EA', '매 입고시', '체크시트', '반품 처리', NULL, '40', '1000', 'admin', TIMESTAMP '2026-01-05 09:00:00' FROM CONTROL_PLANS WHERE PLAN_NO = 'CP-20260105-001';

INSERT INTO CONTROL_PLAN_ITEMS (CONTROL_PLAN_ID, SEQ, PROCESS_CODE, PROCESS_NAME, CHARACTERISTIC_NO, PRODUCT_CHARACTERISTIC, PROCESS_CHARACTERISTIC, SPECIAL_CHAR_CLASS, SPECIFICATION, EVAL_METHOD, SAMPLE_SIZE, SAMPLE_FREQ, CONTROL_METHOD, REACTION_PLAN, REMARKS, COMPANY, PLANT, CREATED_BY, CREATED_AT)
SELECT ID, 2, 'P-210', '수입 검사', 'C-202', '피복 두께', '전선 품질', NULL, '0.3±0.05mm', '마이크로미터', '3EA', '매 입고시', '체크시트', '반품 처리', NULL, '40', '1000', 'admin', TIMESTAMP '2026-01-05 09:00:00' FROM CONTROL_PLANS WHERE PLAN_NO = 'CP-20260105-001';

INSERT INTO CONTROL_PLAN_ITEMS (CONTROL_PLAN_ID, SEQ, PROCESS_CODE, PROCESS_NAME, CHARACTERISTIC_NO, PRODUCT_CHARACTERISTIC, PROCESS_CHARACTERISTIC, SPECIAL_CHAR_CLASS, SPECIFICATION, EVAL_METHOD, SAMPLE_SIZE, SAMPLE_FREQ, CONTROL_METHOD, REACTION_PLAN, REMARKS, COMPANY, PLANT, CREATED_BY, CREATED_AT)
SELECT ID, 3, 'P-210', '수입 검사', 'C-203', '내열성', '전선 품질', 'HI', '105°C/240h 이상', '항온항습기', '1EA', '월 1회', '시험성적서', '공급업체 시정조치', '내열 등급 필수', '40', '1000', 'admin', TIMESTAMP '2026-01-05 09:00:00' FROM CONTROL_PLANS WHERE PLAN_NO = 'CP-20260105-001';

-- CP-20260120-001 (환형단자 M6 Rev.2) 항목들
INSERT INTO CONTROL_PLAN_ITEMS (CONTROL_PLAN_ID, SEQ, PROCESS_CODE, PROCESS_NAME, CHARACTERISTIC_NO, PRODUCT_CHARACTERISTIC, PROCESS_CHARACTERISTIC, SPECIAL_CHAR_CLASS, SPECIFICATION, EVAL_METHOD, SAMPLE_SIZE, SAMPLE_FREQ, CONTROL_METHOD, REACTION_PLAN, REMARKS, COMPANY, PLANT, CREATED_BY, CREATED_AT)
SELECT ID, 1, 'P-310', '프레스 성형', 'C-301', '내경 치수', '프레스 압력', 'SC', 'Φ6.4±0.1mm', '플러그게이지', '5EA', '매 LOT', 'X-R 관리도', '금형 교정', NULL, '40', '1000', 'admin', TIMESTAMP '2026-01-20 09:00:00' FROM CONTROL_PLANS WHERE PLAN_NO = 'CP-20260120-001';

INSERT INTO CONTROL_PLAN_ITEMS (CONTROL_PLAN_ID, SEQ, PROCESS_CODE, PROCESS_NAME, CHARACTERISTIC_NO, PRODUCT_CHARACTERISTIC, PROCESS_CHARACTERISTIC, SPECIAL_CHAR_CLASS, SPECIFICATION, EVAL_METHOD, SAMPLE_SIZE, SAMPLE_FREQ, CONTROL_METHOD, REACTION_PLAN, REMARKS, COMPANY, PLANT, CREATED_BY, CREATED_AT)
SELECT ID, 2, 'P-320', '도금', 'C-302', '도금 두께', '도금 시간/전류', NULL, '≥3μm', '도금두께측정기', '3EA', '매 LOT', '체크시트', '재도금', NULL, '40', '1000', 'admin', TIMESTAMP '2026-01-20 09:00:00' FROM CONTROL_PLANS WHERE PLAN_NO = 'CP-20260120-001';

INSERT INTO CONTROL_PLAN_ITEMS (CONTROL_PLAN_ID, SEQ, PROCESS_CODE, PROCESS_NAME, CHARACTERISTIC_NO, PRODUCT_CHARACTERISTIC, PROCESS_CHARACTERISTIC, SPECIAL_CHAR_CLASS, SPECIFICATION, EVAL_METHOD, SAMPLE_SIZE, SAMPLE_FREQ, CONTROL_METHOD, REACTION_PLAN, REMARKS, COMPANY, PLANT, CREATED_BY, CREATED_AT)
SELECT ID, 3, 'P-330', '압착 강도', 'C-303', '인장강도', '크림프 압력', 'CC', '≥80N (2.0sq)', '인장시험기', '5EA', '매 LOT', 'X-R 관리도', '압착 금형 교체', '핵심 안전 특성', '40', '1000', 'admin', TIMESTAMP '2026-01-20 09:00:00' FROM CONTROL_PLANS WHERE PLAN_NO = 'CP-20260120-001';

COMMIT;
