MERGE INTO "COM_CODES" t
USING (
  SELECT 'GAUGE_STATUS' AS "GROUP_CODE", 'ACTIVE'   AS "DETAIL_CODE", '사용중'   AS "CODE_NAME", 1 AS "SORT_ORDER", 'Active'   AS "ATTR1", '使用中' AS "ATTR2", 'Đang sử dụng' AS "ATTR3" FROM DUAL UNION ALL
  SELECT 'GAUGE_STATUS', 'EXPIRED',  '교정만료', 2, 'Expired',  '已过期', 'Đã hết hạn'   FROM DUAL UNION ALL
  SELECT 'GAUGE_STATUS', 'SCRAPPED', '폐기',     3, 'Scrapped', '报废',   'Đã bỏ'        FROM DUAL
) s ON (t."COMPANY" = 'HANES' AND t."PLANT_CD" = 'VINA' AND t."GROUP_CODE" = s."GROUP_CODE" AND t."DETAIL_CODE" = s."DETAIL_CODE")
WHEN NOT MATCHED THEN INSERT (
  "COMPANY", "PLANT_CD", "GROUP_CODE", "DETAIL_CODE", "CODE_NAME", "SORT_ORDER", "USE_YN", "ATTR1", "ATTR2", "ATTR3", "CREATED_BY"
) VALUES (
  'HANES', 'VINA', s."GROUP_CODE", s."DETAIL_CODE", s."CODE_NAME", s."SORT_ORDER", 'Y', s."ATTR1", s."ATTR2", s."ATTR3", 'SYSTEM'
)
