-- 교육 계획 채번 — Oracle SEQUENCE + SEQ_RULES 방식
-- PKG_SEQ_GENERATOR.GET_NO('TRAINING_PLAN') 호출 시 사용
-- 생성 번호 예시: TRN261205-001

-- 1. Oracle SEQUENCE 생성
CREATE SEQUENCE SEQ_TRAINING_PLAN
  START WITH 1
  INCREMENT BY 1
  NOCACHE
  NOCYCLE;

-- 2. SEQ_RULES 에 규칙 등록
INSERT INTO SEQ_RULES (DOC_TYPE, PREFIX, SEQ_NAME, PAD_LENGTH, DATE_FORMAT, DESCRIPTION)
VALUES ('TRAINING_PLAN', 'TRN', 'SEQ_TRAINING_PLAN', 3, 'YYMMDD', '교육계획번호');

COMMIT;
