CREATE OR REPLACE TRIGGER TRG_PHYSICAL_INV_SESSIONS_INS
  BEFORE INSERT ON PHYSICAL_INV_SESSIONS
  FOR EACH ROW
BEGIN
  IF :NEW.ID IS NULL THEN
    :NEW.ID := SEQ_PHYSICAL_INV_SESSIONS.NEXTVAL;
  END IF;
END;
