-- =============================================================================
-- 대시보드 점검/PM 시드 데이터 (2026-04-03 기준)
-- 대상 테이블: EQUIP_INSPECT_ITEM_MASTERS, EQUIP_INSPECT_LOGS, PM_WORK_ORDERS
-- =============================================================================

-- ─────────────────────────────────────────────────────────────────────────────
-- 1. EQUIP_INSPECT_ITEM_MASTERS: 일상점검(DAILY) 항목 추가
--    EQ-CUT-01은 이미 5건 있으므로 skip
-- ─────────────────────────────────────────────────────────────────────────────

-- EQ-CUT-02 일상점검 3항목
INSERT INTO EQUIP_INSPECT_ITEM_MASTERS (COMPANY, PLANT_CD, EQUIP_CODE, INSPECT_TYPE, SEQ, ITEM_NAME, CRITERIA, USE_YN, CREATED_AT, UPDATED_AT)
VALUES ('40', '1000', 'EQ-CUT-02', 'DAILY', 1, '블레이드 상태', '마모/파손 없을 것', 'Y', SYSTIMESTAMP, SYSTIMESTAMP);
INSERT INTO EQUIP_INSPECT_ITEM_MASTERS (COMPANY, PLANT_CD, EQUIP_CODE, INSPECT_TYPE, SEQ, ITEM_NAME, CRITERIA, USE_YN, CREATED_AT, UPDATED_AT)
VALUES ('40', '1000', 'EQ-CUT-02', 'DAILY', 2, '에어압력 확인', '0.5~0.7 MPa', 'Y', SYSTIMESTAMP, SYSTIMESTAMP);
INSERT INTO EQUIP_INSPECT_ITEM_MASTERS (COMPANY, PLANT_CD, EQUIP_CODE, INSPECT_TYPE, SEQ, ITEM_NAME, CRITERIA, USE_YN, CREATED_AT, UPDATED_AT)
VALUES ('40', '1000', 'EQ-CUT-02', 'DAILY', 3, '안전장치 동작', '정상 작동', 'Y', SYSTIMESTAMP, SYSTIMESTAMP);

-- EQ-CRIMP-01 일상점검 3항목
INSERT INTO EQUIP_INSPECT_ITEM_MASTERS (COMPANY, PLANT_CD, EQUIP_CODE, INSPECT_TYPE, SEQ, ITEM_NAME, CRITERIA, USE_YN, CREATED_AT, UPDATED_AT)
VALUES ('40', '1000', 'EQ-CRIMP-01', 'DAILY', 1, '다이 마모 상태', '마모한계 이내', 'Y', SYSTIMESTAMP, SYSTIMESTAMP);
INSERT INTO EQUIP_INSPECT_ITEM_MASTERS (COMPANY, PLANT_CD, EQUIP_CODE, INSPECT_TYPE, SEQ, ITEM_NAME, CRITERIA, USE_YN, CREATED_AT, UPDATED_AT)
VALUES ('40', '1000', 'EQ-CRIMP-01', 'DAILY', 2, '압착 높이', '규격 ±0.05mm', 'Y', SYSTIMESTAMP, SYSTIMESTAMP);
INSERT INTO EQUIP_INSPECT_ITEM_MASTERS (COMPANY, PLANT_CD, EQUIP_CODE, INSPECT_TYPE, SEQ, ITEM_NAME, CRITERIA, USE_YN, CREATED_AT, UPDATED_AT)
VALUES ('40', '1000', 'EQ-CRIMP-01', 'DAILY', 3, '안전커버 상태', '체결 양호', 'Y', SYSTIMESTAMP, SYSTIMESTAMP);

-- EQ-STRIP-01 일상점검 3항목
INSERT INTO EQUIP_INSPECT_ITEM_MASTERS (COMPANY, PLANT_CD, EQUIP_CODE, INSPECT_TYPE, SEQ, ITEM_NAME, CRITERIA, USE_YN, CREATED_AT, UPDATED_AT)
VALUES ('40', '1000', 'EQ-STRIP-01', 'DAILY', 1, '블레이드 간격', '규격 ±0.1mm', 'Y', SYSTIMESTAMP, SYSTIMESTAMP);
INSERT INTO EQUIP_INSPECT_ITEM_MASTERS (COMPANY, PLANT_CD, EQUIP_CODE, INSPECT_TYPE, SEQ, ITEM_NAME, CRITERIA, USE_YN, CREATED_AT, UPDATED_AT)
VALUES ('40', '1000', 'EQ-STRIP-01', 'DAILY', 2, '센서 동작', '정상 감지', 'Y', SYSTIMESTAMP, SYSTIMESTAMP);
INSERT INTO EQUIP_INSPECT_ITEM_MASTERS (COMPANY, PLANT_CD, EQUIP_CODE, INSPECT_TYPE, SEQ, ITEM_NAME, CRITERIA, USE_YN, CREATED_AT, UPDATED_AT)
VALUES ('40', '1000', 'EQ-STRIP-01', 'DAILY', 3, '청소 상태', '이물질 없을 것', 'Y', SYSTIMESTAMP, SYSTIMESTAMP);

-- EQ-TEST-01 일상점검 3항목
INSERT INTO EQUIP_INSPECT_ITEM_MASTERS (COMPANY, PLANT_CD, EQUIP_CODE, INSPECT_TYPE, SEQ, ITEM_NAME, CRITERIA, USE_YN, CREATED_AT, UPDATED_AT)
VALUES ('40', '1000', 'EQ-TEST-01', 'DAILY', 1, '프로브 상태', '접촉 양호', 'Y', SYSTIMESTAMP, SYSTIMESTAMP);
INSERT INTO EQUIP_INSPECT_ITEM_MASTERS (COMPANY, PLANT_CD, EQUIP_CODE, INSPECT_TYPE, SEQ, ITEM_NAME, CRITERIA, USE_YN, CREATED_AT, UPDATED_AT)
VALUES ('40', '1000', 'EQ-TEST-01', 'DAILY', 2, '기준저항 확인', '기준값 ±5%', 'Y', SYSTIMESTAMP, SYSTIMESTAMP);
INSERT INTO EQUIP_INSPECT_ITEM_MASTERS (COMPANY, PLANT_CD, EQUIP_CODE, INSPECT_TYPE, SEQ, ITEM_NAME, CRITERIA, USE_YN, CREATED_AT, UPDATED_AT)
VALUES ('40', '1000', 'EQ-TEST-01', 'DAILY', 3, '디스플레이 표시', '정상 표시', 'Y', SYSTIMESTAMP, SYSTIMESTAMP);

-- ─────────────────────────────────────────────────────────────────────────────
-- 2. EQUIP_INSPECT_ITEM_MASTERS: 정기점검(PERIODIC) 항목 추가
-- ─────────────────────────────────────────────────────────────────────────────

-- EQ-CUT-01 정기점검 3항목
INSERT INTO EQUIP_INSPECT_ITEM_MASTERS (COMPANY, PLANT_CD, EQUIP_CODE, INSPECT_TYPE, SEQ, ITEM_NAME, CRITERIA, CYCLE, USE_YN, CREATED_AT, UPDATED_AT)
VALUES ('40', '1000', 'EQ-CUT-01', 'PERIODIC', 1, '모터 진동 측정', '0.5mm/s 이하', 'MONTHLY', 'Y', SYSTIMESTAMP, SYSTIMESTAMP);
INSERT INTO EQUIP_INSPECT_ITEM_MASTERS (COMPANY, PLANT_CD, EQUIP_CODE, INSPECT_TYPE, SEQ, ITEM_NAME, CRITERIA, CYCLE, USE_YN, CREATED_AT, UPDATED_AT)
VALUES ('40', '1000', 'EQ-CUT-01', 'PERIODIC', 2, '베어링 온도', '60°C 이하', 'MONTHLY', 'Y', SYSTIMESTAMP, SYSTIMESTAMP);
INSERT INTO EQUIP_INSPECT_ITEM_MASTERS (COMPANY, PLANT_CD, EQUIP_CODE, INSPECT_TYPE, SEQ, ITEM_NAME, CRITERIA, CYCLE, USE_YN, CREATED_AT, UPDATED_AT)
VALUES ('40', '1000', 'EQ-CUT-01', 'PERIODIC', 3, '윤활유 상태', '적정량/변색 없음', 'MONTHLY', 'Y', SYSTIMESTAMP, SYSTIMESTAMP);

-- EQ-CRIMP-01 정기점검 3항목
INSERT INTO EQUIP_INSPECT_ITEM_MASTERS (COMPANY, PLANT_CD, EQUIP_CODE, INSPECT_TYPE, SEQ, ITEM_NAME, CRITERIA, CYCLE, USE_YN, CREATED_AT, UPDATED_AT)
VALUES ('40', '1000', 'EQ-CRIMP-01', 'PERIODIC', 1, '유압 실린더 누유', '누유 없을 것', 'MONTHLY', 'Y', SYSTIMESTAMP, SYSTIMESTAMP);
INSERT INTO EQUIP_INSPECT_ITEM_MASTERS (COMPANY, PLANT_CD, EQUIP_CODE, INSPECT_TYPE, SEQ, ITEM_NAME, CRITERIA, CYCLE, USE_YN, CREATED_AT, UPDATED_AT)
VALUES ('40', '1000', 'EQ-CRIMP-01', 'PERIODIC', 2, '압력 게이지 교정', '기준값 ±2%', 'MONTHLY', 'Y', SYSTIMESTAMP, SYSTIMESTAMP);
INSERT INTO EQUIP_INSPECT_ITEM_MASTERS (COMPANY, PLANT_CD, EQUIP_CODE, INSPECT_TYPE, SEQ, ITEM_NAME, CRITERIA, CYCLE, USE_YN, CREATED_AT, UPDATED_AT)
VALUES ('40', '1000', 'EQ-CRIMP-01', 'PERIODIC', 3, '전기 절연 저항', '1MΩ 이상', 'MONTHLY', 'Y', SYSTIMESTAMP, SYSTIMESTAMP);

-- EQ-TEST-01 정기점검 3항목
INSERT INTO EQUIP_INSPECT_ITEM_MASTERS (COMPANY, PLANT_CD, EQUIP_CODE, INSPECT_TYPE, SEQ, ITEM_NAME, CRITERIA, CYCLE, USE_YN, CREATED_AT, UPDATED_AT)
VALUES ('40', '1000', 'EQ-TEST-01', 'PERIODIC', 1, '검사기 교정', '기준 시편 합격', 'MONTHLY', 'Y', SYSTIMESTAMP, SYSTIMESTAMP);
INSERT INTO EQUIP_INSPECT_ITEM_MASTERS (COMPANY, PLANT_CD, EQUIP_CODE, INSPECT_TYPE, SEQ, ITEM_NAME, CRITERIA, CYCLE, USE_YN, CREATED_AT, UPDATED_AT)
VALUES ('40', '1000', 'EQ-TEST-01', 'PERIODIC', 2, '측정 정확도', '±0.01Ω 이내', 'MONTHLY', 'Y', SYSTIMESTAMP, SYSTIMESTAMP);
INSERT INTO EQUIP_INSPECT_ITEM_MASTERS (COMPANY, PLANT_CD, EQUIP_CODE, INSPECT_TYPE, SEQ, ITEM_NAME, CRITERIA, CYCLE, USE_YN, CREATED_AT, UPDATED_AT)
VALUES ('40', '1000', 'EQ-TEST-01', 'PERIODIC', 3, '접지 저항 확인', '10Ω 이하', 'MONTHLY', 'Y', SYSTIMESTAMP, SYSTIMESTAMP);

-- ─────────────────────────────────────────────────────────────────────────────
-- 3. EQUIP_INSPECT_LOGS: 오늘(2026-04-03) 일상점검 결과
--    5대 중 4대 완료 (3 PASS, 1 FAIL), EQ-TEST-01 미실시
-- ─────────────────────────────────────────────────────────────────────────────

INSERT INTO EQUIP_INSPECT_LOGS (EQUIP_CODE, INSPECT_TYPE, INSPECT_DATE, INSPECTOR_NAME, OVERALL_RESULT, DETAILS, COMPANY, PLANT_CD, CREATED_AT, UPDATED_AT)
VALUES ('EQ-CUT-01', 'DAILY', DATE '2026-04-03', '김철수', 'PASS',
  '{"items":[{"seq":1,"itemName":"블레이드 상태","result":"PASS"},{"seq":2,"itemName":"에어압력 확인","result":"PASS"},{"seq":3,"itemName":"안전장치 동작","result":"PASS"},{"seq":4,"itemName":"절단 길이","result":"PASS"},{"seq":5,"itemName":"청소 상태","result":"PASS"}]}',
  '40', '1000', SYSTIMESTAMP, SYSTIMESTAMP);

INSERT INTO EQUIP_INSPECT_LOGS (EQUIP_CODE, INSPECT_TYPE, INSPECT_DATE, INSPECTOR_NAME, OVERALL_RESULT, DETAILS, COMPANY, PLANT_CD, CREATED_AT, UPDATED_AT)
VALUES ('EQ-CUT-02', 'DAILY', DATE '2026-04-03', '이영희', 'PASS',
  '{"items":[{"seq":1,"itemName":"블레이드 상태","result":"PASS"},{"seq":2,"itemName":"에어압력 확인","result":"PASS"},{"seq":3,"itemName":"안전장치 동작","result":"PASS"}]}',
  '40', '1000', SYSTIMESTAMP, SYSTIMESTAMP);

INSERT INTO EQUIP_INSPECT_LOGS (EQUIP_CODE, INSPECT_TYPE, INSPECT_DATE, INSPECTOR_NAME, OVERALL_RESULT, DETAILS, COMPANY, PLANT_CD, CREATED_AT, UPDATED_AT)
VALUES ('EQ-CRIMP-01', 'DAILY', DATE '2026-04-03', '박민수', 'FAIL',
  '{"items":[{"seq":1,"itemName":"다이 마모 상태","result":"FAIL","remark":"마모한계 초과"},{"seq":2,"itemName":"압착 높이","result":"PASS"},{"seq":3,"itemName":"안전커버 상태","result":"PASS"}]}',
  '40', '1000', SYSTIMESTAMP, SYSTIMESTAMP);

INSERT INTO EQUIP_INSPECT_LOGS (EQUIP_CODE, INSPECT_TYPE, INSPECT_DATE, INSPECTOR_NAME, OVERALL_RESULT, DETAILS, COMPANY, PLANT_CD, CREATED_AT, UPDATED_AT)
VALUES ('EQ-STRIP-01', 'DAILY', DATE '2026-04-03', '최지은', 'PASS',
  '{"items":[{"seq":1,"itemName":"블레이드 간격","result":"PASS"},{"seq":2,"itemName":"센서 동작","result":"PASS"},{"seq":3,"itemName":"청소 상태","result":"PASS"}]}',
  '40', '1000', SYSTIMESTAMP, SYSTIMESTAMP);

-- EQ-TEST-01 → 일상점검 미실시 (로그 없음)

-- ─────────────────────────────────────────────────────────────────────────────
-- 4. EQUIP_INSPECT_LOGS: 오늘(2026-04-03) 정기점검 결과
--    3대 중 2대 완료 (1 PASS, 1 FAIL), EQ-CRIMP-01 미실시
-- ─────────────────────────────────────────────────────────────────────────────

INSERT INTO EQUIP_INSPECT_LOGS (EQUIP_CODE, INSPECT_TYPE, INSPECT_DATE, INSPECTOR_NAME, OVERALL_RESULT, DETAILS, COMPANY, PLANT_CD, CREATED_AT, UPDATED_AT)
VALUES ('EQ-CUT-01', 'PERIODIC', DATE '2026-04-03', '김철수', 'PASS',
  '{"items":[{"seq":1,"itemName":"모터 진동 측정","result":"PASS","remark":"0.3mm/s"},{"seq":2,"itemName":"베어링 온도","result":"PASS","remark":"45°C"},{"seq":3,"itemName":"윤활유 상태","result":"PASS"}]}',
  '40', '1000', SYSTIMESTAMP, SYSTIMESTAMP);

INSERT INTO EQUIP_INSPECT_LOGS (EQUIP_CODE, INSPECT_TYPE, INSPECT_DATE, INSPECTOR_NAME, OVERALL_RESULT, DETAILS, COMPANY, PLANT_CD, CREATED_AT, UPDATED_AT)
VALUES ('EQ-TEST-01', 'PERIODIC', DATE '2026-04-03', '이영희', 'FAIL',
  '{"items":[{"seq":1,"itemName":"검사기 교정","result":"PASS"},{"seq":2,"itemName":"측정 정확도","result":"FAIL","remark":"±0.03Ω 초과"},{"seq":3,"itemName":"접지 저항 확인","result":"PASS"}]}',
  '40', '1000', SYSTIMESTAMP, SYSTIMESTAMP);

-- EQ-CRIMP-01 → 정기점검 미실시 (로그 없음)

-- ─────────────────────────────────────────────────────────────────────────────
-- 5. PM_WORK_ORDERS: 오늘(2026-04-03) 예방보전 작업지시 4건
--    2건 완료(1 PASS, 1 FAIL), 1건 진행중, 1건 계획
-- ─────────────────────────────────────────────────────────────────────────────

INSERT INTO PM_WORK_ORDERS (WORK_ORDER_NO, EQUIP_CODE, WO_TYPE, SCHEDULED_DATE, DUE_DATE, STARTED_AT, COMPLETED_AT, STATUS, PRIORITY, OVERALL_RESULT, COMPANY, PLANT_CD, CREATED_AT, UPDATED_AT)
VALUES ('WO-PM-20260403-001', 'EQ-CUT-01', 'PLANNED', DATE '2026-04-03', DATE '2026-04-03',
  TIMESTAMP '2026-04-03 08:00:00', TIMESTAMP '2026-04-03 09:30:00',
  'COMPLETED', 'HIGH', 'PASS', '40', '1000', SYSTIMESTAMP, SYSTIMESTAMP);

INSERT INTO PM_WORK_ORDERS (WORK_ORDER_NO, EQUIP_CODE, WO_TYPE, SCHEDULED_DATE, DUE_DATE, STARTED_AT, COMPLETED_AT, STATUS, PRIORITY, OVERALL_RESULT, COMPANY, PLANT_CD, CREATED_AT, UPDATED_AT)
VALUES ('WO-PM-20260403-002', 'EQ-CRIMP-01', 'PLANNED', DATE '2026-04-03', DATE '2026-04-03',
  TIMESTAMP '2026-04-03 08:30:00', TIMESTAMP '2026-04-03 10:00:00',
  'COMPLETED', 'MEDIUM', 'FAIL', '40', '1000', SYSTIMESTAMP, SYSTIMESTAMP);

INSERT INTO PM_WORK_ORDERS (WORK_ORDER_NO, EQUIP_CODE, WO_TYPE, SCHEDULED_DATE, DUE_DATE, STARTED_AT, STATUS, PRIORITY, COMPANY, PLANT_CD, CREATED_AT, UPDATED_AT)
VALUES ('WO-PM-20260403-003', 'EQ-TEST-01', 'PLANNED', DATE '2026-04-03', DATE '2026-04-03',
  TIMESTAMP '2026-04-03 10:00:00',
  'IN_PROGRESS', 'MEDIUM', '40', '1000', SYSTIMESTAMP, SYSTIMESTAMP);

INSERT INTO PM_WORK_ORDERS (WORK_ORDER_NO, EQUIP_CODE, WO_TYPE, SCHEDULED_DATE, DUE_DATE, STATUS, PRIORITY, COMPANY, PLANT_CD, CREATED_AT, UPDATED_AT)
VALUES ('WO-PM-20260403-004', 'EQ-STRIP-01', 'PLANNED', DATE '2026-04-03', DATE '2026-04-03',
  'PLANNED', 'LOW', '40', '1000', SYSTIMESTAMP, SYSTIMESTAMP);

COMMIT;
