-- 품목별 IQC 기준 헤더
CREATE TABLE IQC_PART_SPECS (
  COMPANY      VARCHAR2(50)  NOT NULL,
  PLANT_CD     VARCHAR2(50)  NOT NULL,
  ITEM_CODE    VARCHAR2(50)  NOT NULL,
  SAMPLE_QTY   NUMBER(5)     DEFAULT 1 NOT NULL,
  IS_DEST      VARCHAR2(1)   DEFAULT 'N' NOT NULL,
  USE_YN       VARCHAR2(1)   DEFAULT 'Y' NOT NULL,
  CREATED_BY   VARCHAR2(50),
  UPDATED_BY   VARCHAR2(50),
  CREATED_AT   TIMESTAMP     DEFAULT SYSTIMESTAMP,
  UPDATED_AT   TIMESTAMP     DEFAULT SYSTIMESTAMP,
  CONSTRAINT PK_IQC_PART_SPECS PRIMARY KEY (COMPANY, PLANT_CD, ITEM_CODE)
)
/
COMMENT ON TABLE  IQC_PART_SPECS              IS '품목별 IQC 기준 헤더'
/
COMMENT ON COLUMN IQC_PART_SPECS.COMPANY      IS '회사코드 (PK)'
/
COMMENT ON COLUMN IQC_PART_SPECS.PLANT_CD     IS '공장코드 (PK)'
/
COMMENT ON COLUMN IQC_PART_SPECS.ITEM_CODE    IS '품목코드 (PK)'
/
COMMENT ON COLUMN IQC_PART_SPECS.SAMPLE_QTY   IS '기본 시료수 (IQC 실적 입력 시 기본값)'
/
COMMENT ON COLUMN IQC_PART_SPECS.IS_DEST      IS '파괴검사 여부 Y/N'
/
COMMENT ON COLUMN IQC_PART_SPECS.USE_YN       IS '사용여부 Y/N'
/
-- 품목별 IQC 검사항목 세부
CREATE TABLE IQC_PART_SPEC_ITEMS (
  COMPANY         VARCHAR2(50)  NOT NULL,
  PLANT_CD        VARCHAR2(50)  NOT NULL,
  ITEM_CODE       VARCHAR2(50)  NOT NULL,
  SEQ             NUMBER(5)     NOT NULL,
  INSP_ITEM_CODE  VARCHAR2(20)  NOT NULL,
  LSL             NUMBER(12,4),
  USL             NUMBER(12,4),
  USE_YN          VARCHAR2(1)   DEFAULT 'Y' NOT NULL,
  CREATED_BY      VARCHAR2(50),
  UPDATED_BY      VARCHAR2(50),
  CREATED_AT      TIMESTAMP     DEFAULT SYSTIMESTAMP,
  UPDATED_AT      TIMESTAMP     DEFAULT SYSTIMESTAMP,
  CONSTRAINT PK_IQC_PART_SPEC_ITEMS PRIMARY KEY (COMPANY, PLANT_CD, ITEM_CODE, SEQ),
  CONSTRAINT FK_SPEC_ITEMS_INSP  FOREIGN KEY (COMPANY, PLANT_CD, INSP_ITEM_CODE)
    REFERENCES IQC_ITEM_POOL(COMPANY, PLANT_CD, INSP_ITEM_CODE),
  CONSTRAINT FK_SPEC_ITEMS_SPEC  FOREIGN KEY (COMPANY, PLANT_CD, ITEM_CODE)
    REFERENCES IQC_PART_SPECS(COMPANY, PLANT_CD, ITEM_CODE) ON DELETE CASCADE
)
/
COMMENT ON TABLE  IQC_PART_SPEC_ITEMS                 IS '품목별 IQC 검사항목 세부'
/
COMMENT ON COLUMN IQC_PART_SPEC_ITEMS.COMPANY          IS '회사코드 (PK/FK → IQC_PART_SPECS)'
/
COMMENT ON COLUMN IQC_PART_SPEC_ITEMS.PLANT_CD         IS '공장코드 (PK/FK → IQC_PART_SPECS)'
/
COMMENT ON COLUMN IQC_PART_SPEC_ITEMS.ITEM_CODE        IS '품목코드 (PK/FK → IQC_PART_SPECS)'
/
COMMENT ON COLUMN IQC_PART_SPEC_ITEMS.SEQ              IS '검사 순서'
/
COMMENT ON COLUMN IQC_PART_SPEC_ITEMS.INSP_ITEM_CODE   IS '검사항목코드 (FK → IQC_ITEM_POOL)'
/
COMMENT ON COLUMN IQC_PART_SPEC_ITEMS.LSL              IS '하한 규격값 (측정형에만 사용)'
/
COMMENT ON COLUMN IQC_PART_SPEC_ITEMS.USL              IS '상한 규격값 (측정형에만 사용)'
/
