-- ============================================================================
-- 2026-05-18 좌측 메뉴 카테고리/순서 관리 — 신규 테이블 2개 생성
-- 사이트: JSHANES
-- ============================================================================

-- 1) MENU_CATEGORIES : 카테고리 정의
CREATE TABLE MENU_CATEGORIES (
  CATEGORY_CODE   VARCHAR2(50)   NOT NULL,
  LABEL_KEY       VARCHAR2(200)  NOT NULL,
  ICON_NAME       VARCHAR2(50)   NULL,
  SORT_ORDER      NUMBER(10)     DEFAULT 0    NOT NULL,
  IS_ACTIVE       CHAR(1)        DEFAULT 'Y'  NOT NULL,
  COMPANY         VARCHAR2(20)   NOT NULL,
  PLANT_CD        VARCHAR2(20)   NOT NULL,
  CREATED_AT      TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
  CREATED_BY      VARCHAR2(50)   NOT NULL,
  UPDATED_AT      TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
  UPDATED_BY      VARCHAR2(50)   NOT NULL,
  CONSTRAINT PK_MENU_CATEGORIES PRIMARY KEY (CATEGORY_CODE),
  CONSTRAINT CK_MENU_CATEGORIES_IS_ACTIVE CHECK (IS_ACTIVE IN ('Y','N'))
);

CREATE INDEX IDX_MENU_CATEGORIES_SCOPE
  ON MENU_CATEGORIES (COMPANY, PLANT_CD, SORT_ORDER);

COMMENT ON TABLE  MENU_CATEGORIES IS '사이드바 카테고리(상위 메뉴) 정의';
COMMENT ON COLUMN MENU_CATEGORIES.CATEGORY_CODE IS '카테고리 코드 (영문 대문자/언더스코어, 예약어 __ROOT__ 포함)';
COMMENT ON COLUMN MENU_CATEGORIES.LABEL_KEY     IS 'i18n 키 (예: menu.master)';
COMMENT ON COLUMN MENU_CATEGORIES.ICON_NAME     IS 'lucide-react 아이콘 이름. NULL이면 기본 폴더 아이콘';
COMMENT ON COLUMN MENU_CATEGORIES.SORT_ORDER    IS '사이드바 최상위 표시 순서(10단위 권장)';
COMMENT ON COLUMN MENU_CATEGORIES.IS_ACTIVE     IS 'Y/N — N이면 사이드바에서 숨김';
COMMENT ON COLUMN MENU_CATEGORIES.COMPANY       IS '멀티테넌시 — 회사';
COMMENT ON COLUMN MENU_CATEGORIES.PLANT_CD      IS '멀티테넌시 — 사업장';

-- 2) MENU_CATEGORY_ITEMS : 메뉴 ↔ 카테고리 배치
CREATE TABLE MENU_CATEGORY_ITEMS (
  MENU_CODE       VARCHAR2(100)  NOT NULL,
  CATEGORY_CODE   VARCHAR2(50)   NOT NULL,
  SORT_ORDER      NUMBER(10)     DEFAULT 0  NOT NULL,
  COMPANY         VARCHAR2(20)   NOT NULL,
  PLANT_CD        VARCHAR2(20)   NOT NULL,
  CREATED_AT      TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
  CREATED_BY      VARCHAR2(50)   NOT NULL,
  UPDATED_AT      TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
  UPDATED_BY      VARCHAR2(50)   NOT NULL,
  CONSTRAINT PK_MENU_CATEGORY_ITEMS PRIMARY KEY (MENU_CODE),
  CONSTRAINT FK_MCI_CATEGORY FOREIGN KEY (CATEGORY_CODE)
    REFERENCES MENU_CATEGORIES (CATEGORY_CODE)
);

CREATE INDEX IDX_MCI_CATEGORY
  ON MENU_CATEGORY_ITEMS (CATEGORY_CODE, SORT_ORDER);

COMMENT ON TABLE  MENU_CATEGORY_ITEMS IS '메뉴(leaf) ↔ 카테고리 배치';
COMMENT ON COLUMN MENU_CATEGORY_ITEMS.MENU_CODE     IS 'menuConfig.ts의 leaf 메뉴 코드';
COMMENT ON COLUMN MENU_CATEGORY_ITEMS.CATEGORY_CODE IS '소속 카테고리 (FK)';
COMMENT ON COLUMN MENU_CATEGORY_ITEMS.SORT_ORDER    IS '카테고리 내 표시 순서(10단위 권장)';
