-- ============================================================================
-- 2026-05-18 좌측 메뉴 카테고리/순서 — 초기 시드
-- 생성: scripts/gen-menu-category-seed.js (자동 생성, 직접 편집 금지)
-- ============================================================================

INSERT INTO MENU_CATEGORIES (CATEGORY_CODE, LABEL_KEY, ICON_NAME, SORT_ORDER, IS_ACTIVE, COMPANY, PLANT_CD, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES ('__ROOT__', 'menu.root', NULL, 0, 'Y', 'HANES', '-', SYSTIMESTAMP, 'system', SYSTIMESTAMP, 'system');

INSERT INTO MENU_CATEGORIES (CATEGORY_CODE, LABEL_KEY, ICON_NAME, SORT_ORDER, IS_ACTIVE, COMPANY, PLANT_CD, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES ('MONITORING', 'menu.monitoring', 'Monitor', 10, 'Y', 'HANES', '-', SYSTIMESTAMP, 'system', SYSTIMESTAMP, 'system');
INSERT INTO MENU_CATEGORIES (CATEGORY_CODE, LABEL_KEY, ICON_NAME, SORT_ORDER, IS_ACTIVE, COMPANY, PLANT_CD, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES ('MASTER', 'menu.master', 'Database', 20, 'Y', 'HANES', '-', SYSTIMESTAMP, 'system', SYSTIMESTAMP, 'system');
INSERT INTO MENU_CATEGORIES (CATEGORY_CODE, LABEL_KEY, ICON_NAME, SORT_ORDER, IS_ACTIVE, COMPANY, PLANT_CD, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES ('INVENTORY', 'menu.matInventory', 'Warehouse', 30, 'Y', 'HANES', '-', SYSTIMESTAMP, 'system', SYSTIMESTAMP, 'system');
INSERT INTO MENU_CATEGORIES (CATEGORY_CODE, LABEL_KEY, ICON_NAME, SORT_ORDER, IS_ACTIVE, COMPANY, PLANT_CD, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES ('PRODUCT_INVENTORY', 'menu.productInventory', 'ClipboardCheck', 40, 'Y', 'HANES', '-', SYSTIMESTAMP, 'system', SYSTIMESTAMP, 'system');
INSERT INTO MENU_CATEGORIES (CATEGORY_CODE, LABEL_KEY, ICON_NAME, SORT_ORDER, IS_ACTIVE, COMPANY, PLANT_CD, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES ('PRODUCT_MGMT', 'menu.productMgmt', 'PackageCheck', 50, 'Y', 'HANES', '-', SYSTIMESTAMP, 'system', SYSTIMESTAMP, 'system');
INSERT INTO MENU_CATEGORIES (CATEGORY_CODE, LABEL_KEY, ICON_NAME, SORT_ORDER, IS_ACTIVE, COMPANY, PLANT_CD, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES ('MATERIAL', 'menu.material', 'Package', 60, 'Y', 'HANES', '-', SYSTIMESTAMP, 'system', SYSTIMESTAMP, 'system');
INSERT INTO MENU_CATEGORIES (CATEGORY_CODE, LABEL_KEY, ICON_NAME, SORT_ORDER, IS_ACTIVE, COMPANY, PLANT_CD, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES ('PURCHASING', 'menu.purchasing', 'ShoppingCart', 70, 'Y', 'HANES', '-', SYSTIMESTAMP, 'system', SYSTIMESTAMP, 'system');
INSERT INTO MENU_CATEGORIES (CATEGORY_CODE, LABEL_KEY, ICON_NAME, SORT_ORDER, IS_ACTIVE, COMPANY, PLANT_CD, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES ('PRODUCTION', 'menu.production', 'Factory', 80, 'Y', 'HANES', '-', SYSTIMESTAMP, 'system', SYSTIMESTAMP, 'system');
INSERT INTO MENU_CATEGORIES (CATEGORY_CODE, LABEL_KEY, ICON_NAME, SORT_ORDER, IS_ACTIVE, COMPANY, PLANT_CD, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES ('INSPECTION', 'menu.inspection', 'ScanLine', 90, 'Y', 'HANES', '-', SYSTIMESTAMP, 'system', SYSTIMESTAMP, 'system');
INSERT INTO MENU_CATEGORIES (CATEGORY_CODE, LABEL_KEY, ICON_NAME, SORT_ORDER, IS_ACTIVE, COMPANY, PLANT_CD, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES ('QUALITY', 'menu.quality', 'Shield', 100, 'Y', 'HANES', '-', SYSTIMESTAMP, 'system', SYSTIMESTAMP, 'system');
INSERT INTO MENU_CATEGORIES (CATEGORY_CODE, LABEL_KEY, ICON_NAME, SORT_ORDER, IS_ACTIVE, COMPANY, PLANT_CD, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES ('EQUIPMENT', 'menu.equipment', 'Wrench', 110, 'Y', 'HANES', '-', SYSTIMESTAMP, 'system', SYSTIMESTAMP, 'system');
INSERT INTO MENU_CATEGORIES (CATEGORY_CODE, LABEL_KEY, ICON_NAME, SORT_ORDER, IS_ACTIVE, COMPANY, PLANT_CD, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES ('GAUGE_MGMT', 'menu.gauge', 'Ruler', 120, 'Y', 'HANES', '-', SYSTIMESTAMP, 'system', SYSTIMESTAMP, 'system');
INSERT INTO MENU_CATEGORIES (CATEGORY_CODE, LABEL_KEY, ICON_NAME, SORT_ORDER, IS_ACTIVE, COMPANY, PLANT_CD, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES ('SHIPPING', 'menu.shipping', 'Truck', 130, 'Y', 'HANES', '-', SYSTIMESTAMP, 'system', SYSTIMESTAMP, 'system');
INSERT INTO MENU_CATEGORIES (CATEGORY_CODE, LABEL_KEY, ICON_NAME, SORT_ORDER, IS_ACTIVE, COMPANY, PLANT_CD, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES ('SALES', 'menu.sales', 'ShoppingCart', 140, 'Y', 'HANES', '-', SYSTIMESTAMP, 'system', SYSTIMESTAMP, 'system');
INSERT INTO MENU_CATEGORIES (CATEGORY_CODE, LABEL_KEY, ICON_NAME, SORT_ORDER, IS_ACTIVE, COMPANY, PLANT_CD, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES ('CUSTOMS', 'menu.customs', 'FileBox', 150, 'Y', 'HANES', '-', SYSTIMESTAMP, 'system', SYSTIMESTAMP, 'system');
INSERT INTO MENU_CATEGORIES (CATEGORY_CODE, LABEL_KEY, ICON_NAME, SORT_ORDER, IS_ACTIVE, COMPANY, PLANT_CD, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES ('CONSUMABLES', 'menu.consumables', 'Cog', 160, 'Y', 'HANES', '-', SYSTIMESTAMP, 'system', SYSTIMESTAMP, 'system');
INSERT INTO MENU_CATEGORIES (CATEGORY_CODE, LABEL_KEY, ICON_NAME, SORT_ORDER, IS_ACTIVE, COMPANY, PLANT_CD, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES ('OUTSOURCING', 'menu.outsourcing', 'Building2', 170, 'Y', 'HANES', '-', SYSTIMESTAMP, 'system', SYSTIMESTAMP, 'system');
INSERT INTO MENU_CATEGORIES (CATEGORY_CODE, LABEL_KEY, ICON_NAME, SORT_ORDER, IS_ACTIVE, COMPANY, PLANT_CD, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES ('INTERFACE', 'menu.interface', 'ArrowLeftRight', 180, 'Y', 'HANES', '-', SYSTIMESTAMP, 'system', SYSTIMESTAMP, 'system');
INSERT INTO MENU_CATEGORIES (CATEGORY_CODE, LABEL_KEY, ICON_NAME, SORT_ORDER, IS_ACTIVE, COMPANY, PLANT_CD, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES ('SYSTEM', 'menu.system', 'UserCog', 190, 'Y', 'HANES', '-', SYSTIMESTAMP, 'system', SYSTIMESTAMP, 'system');

INSERT INTO MENU_CATEGORY_ITEMS (MENU_CODE, CATEGORY_CODE, SORT_ORDER, COMPANY, PLANT_CD, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES ('DASHBOARD', '__ROOT__', 10, 'HANES', '-', SYSTIMESTAMP, 'system', SYSTIMESTAMP, 'system');
INSERT INTO MENU_CATEGORY_ITEMS (MENU_CODE, CATEGORY_CODE, SORT_ORDER, COMPANY, PLANT_CD, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES ('WORKFLOW', '__ROOT__', 20, 'HANES', '-', SYSTIMESTAMP, 'system', SYSTIMESTAMP, 'system');
INSERT INTO MENU_CATEGORY_ITEMS (MENU_CODE, CATEGORY_CODE, SORT_ORDER, COMPANY, PLANT_CD, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES ('MON_EQUIP_STATUS', 'MONITORING', 10, 'HANES', '-', SYSTIMESTAMP, 'system', SYSTIMESTAMP, 'system');
INSERT INTO MENU_CATEGORY_ITEMS (MENU_CODE, CATEGORY_CODE, SORT_ORDER, COMPANY, PLANT_CD, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES ('MST_PART', 'MASTER', 10, 'HANES', '-', SYSTIMESTAMP, 'system', SYSTIMESTAMP, 'system');
INSERT INTO MENU_CATEGORY_ITEMS (MENU_CODE, CATEGORY_CODE, SORT_ORDER, COMPANY, PLANT_CD, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES ('MST_BOM', 'MASTER', 20, 'HANES', '-', SYSTIMESTAMP, 'system', SYSTIMESTAMP, 'system');
INSERT INTO MENU_CATEGORY_ITEMS (MENU_CODE, CATEGORY_CODE, SORT_ORDER, COMPANY, PLANT_CD, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES ('MST_PARTNER', 'MASTER', 30, 'HANES', '-', SYSTIMESTAMP, 'system', SYSTIMESTAMP, 'system');
INSERT INTO MENU_CATEGORY_ITEMS (MENU_CODE, CATEGORY_CODE, SORT_ORDER, COMPANY, PLANT_CD, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES ('EQUIP_MASTER', 'MASTER', 40, 'HANES', '-', SYSTIMESTAMP, 'system', SYSTIMESTAMP, 'system');
INSERT INTO MENU_CATEGORY_ITEMS (MENU_CODE, CATEGORY_CODE, SORT_ORDER, COMPANY, PLANT_CD, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES ('MST_PROCESS', 'MASTER', 50, 'HANES', '-', SYSTIMESTAMP, 'system', SYSTIMESTAMP, 'system');
INSERT INTO MENU_CATEGORY_ITEMS (MENU_CODE, CATEGORY_CODE, SORT_ORDER, COMPANY, PLANT_CD, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES ('MST_PROD_LINE', 'MASTER', 60, 'HANES', '-', SYSTIMESTAMP, 'system', SYSTIMESTAMP, 'system');
INSERT INTO MENU_CATEGORY_ITEMS (MENU_CODE, CATEGORY_CODE, SORT_ORDER, COMPANY, PLANT_CD, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES ('MST_ROUTING', 'MASTER', 70, 'HANES', '-', SYSTIMESTAMP, 'system', SYSTIMESTAMP, 'system');
INSERT INTO MENU_CATEGORY_ITEMS (MENU_CODE, CATEGORY_CODE, SORT_ORDER, COMPANY, PLANT_CD, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES ('MST_WORK_CALENDAR', 'MASTER', 80, 'HANES', '-', SYSTIMESTAMP, 'system', SYSTIMESTAMP, 'system');
INSERT INTO MENU_CATEGORY_ITEMS (MENU_CODE, CATEGORY_CODE, SORT_ORDER, COMPANY, PLANT_CD, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES ('MST_WORKER', 'MASTER', 90, 'HANES', '-', SYSTIMESTAMP, 'system', SYSTIMESTAMP, 'system');
INSERT INTO MENU_CATEGORY_ITEMS (MENU_CODE, CATEGORY_CODE, SORT_ORDER, COMPANY, PLANT_CD, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES ('MST_WORK_INST', 'MASTER', 100, 'HANES', '-', SYSTIMESTAMP, 'system', SYSTIMESTAMP, 'system');
INSERT INTO MENU_CATEGORY_ITEMS (MENU_CODE, CATEGORY_CODE, SORT_ORDER, COMPANY, PLANT_CD, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES ('MST_WAREHOUSE', 'MASTER', 110, 'HANES', '-', SYSTIMESTAMP, 'system', SYSTIMESTAMP, 'system');
INSERT INTO MENU_CATEGORY_ITEMS (MENU_CODE, CATEGORY_CODE, SORT_ORDER, COMPANY, PLANT_CD, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES ('MST_LABEL', 'MASTER', 120, 'HANES', '-', SYSTIMESTAMP, 'system', SYSTIMESTAMP, 'system');
INSERT INTO MENU_CATEGORY_ITEMS (MENU_CODE, CATEGORY_CODE, SORT_ORDER, COMPANY, PLANT_CD, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES ('MST_VENDOR_BARCODE', 'MASTER', 130, 'HANES', '-', SYSTIMESTAMP, 'system', SYSTIMESTAMP, 'system');
INSERT INTO MENU_CATEGORY_ITEMS (MENU_CODE, CATEGORY_CODE, SORT_ORDER, COMPANY, PLANT_CD, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES ('MST_PROCESS_CAPA', 'MASTER', 140, 'HANES', '-', SYSTIMESTAMP, 'system', SYSTIMESTAMP, 'system');
INSERT INTO MENU_CATEGORY_ITEMS (MENU_CODE, CATEGORY_CODE, SORT_ORDER, COMPANY, PLANT_CD, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES ('SYS_DOCUMENT', 'MASTER', 150, 'HANES', '-', SYSTIMESTAMP, 'system', SYSTIMESTAMP, 'system');
INSERT INTO MENU_CATEGORY_ITEMS (MENU_CODE, CATEGORY_CODE, SORT_ORDER, COMPANY, PLANT_CD, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES ('INV_MAT_STOCK', 'INVENTORY', 10, 'HANES', '-', SYSTIMESTAMP, 'system', SYSTIMESTAMP, 'system');
INSERT INTO MENU_CATEGORY_ITEMS (MENU_CODE, CATEGORY_CODE, SORT_ORDER, COMPANY, PLANT_CD, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES ('INV_TRANSACTION', 'INVENTORY', 20, 'HANES', '-', SYSTIMESTAMP, 'system', SYSTIMESTAMP, 'system');
INSERT INTO MENU_CATEGORY_ITEMS (MENU_CODE, CATEGORY_CODE, SORT_ORDER, COMPANY, PLANT_CD, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES ('INV_MAT_PHYSICAL_INV', 'INVENTORY', 30, 'HANES', '-', SYSTIMESTAMP, 'system', SYSTIMESTAMP, 'system');
INSERT INTO MENU_CATEGORY_ITEMS (MENU_CODE, CATEGORY_CODE, SORT_ORDER, COMPANY, PLANT_CD, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES ('INV_MAT_PHYSICAL_INV_HISTORY', 'INVENTORY', 40, 'HANES', '-', SYSTIMESTAMP, 'system', SYSTIMESTAMP, 'system');
INSERT INTO MENU_CATEGORY_ITEMS (MENU_CODE, CATEGORY_CODE, SORT_ORDER, COMPANY, PLANT_CD, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES ('INV_ARRIVAL_STOCK', 'INVENTORY', 50, 'HANES', '-', SYSTIMESTAMP, 'system', SYSTIMESTAMP, 'system');
INSERT INTO MENU_CATEGORY_ITEMS (MENU_CODE, CATEGORY_CODE, SORT_ORDER, COMPANY, PLANT_CD, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES ('MAT_HOLD', 'INVENTORY', 60, 'HANES', '-', SYSTIMESTAMP, 'system', SYSTIMESTAMP, 'system');
INSERT INTO MENU_CATEGORY_ITEMS (MENU_CODE, CATEGORY_CODE, SORT_ORDER, COMPANY, PLANT_CD, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES ('INV_PRODUCT_STOCK', 'PRODUCT_INVENTORY', 10, 'HANES', '-', SYSTIMESTAMP, 'system', SYSTIMESTAMP, 'system');
INSERT INTO MENU_CATEGORY_ITEMS (MENU_CODE, CATEGORY_CODE, SORT_ORDER, COMPANY, PLANT_CD, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES ('INV_PRODUCT_PHYSICAL_INV', 'PRODUCT_INVENTORY', 20, 'HANES', '-', SYSTIMESTAMP, 'system', SYSTIMESTAMP, 'system');
INSERT INTO MENU_CATEGORY_ITEMS (MENU_CODE, CATEGORY_CODE, SORT_ORDER, COMPANY, PLANT_CD, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES ('INV_PRODUCT_PHYSICAL_INV_HISTORY', 'PRODUCT_INVENTORY', 30, 'HANES', '-', SYSTIMESTAMP, 'system', SYSTIMESTAMP, 'system');
INSERT INTO MENU_CATEGORY_ITEMS (MENU_CODE, CATEGORY_CODE, SORT_ORDER, COMPANY, PLANT_CD, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES ('PROD_HOLD', 'PRODUCT_INVENTORY', 40, 'HANES', '-', SYSTIMESTAMP, 'system', SYSTIMESTAMP, 'system');
INSERT INTO MENU_CATEGORY_ITEMS (MENU_CODE, CATEGORY_CODE, SORT_ORDER, COMPANY, PLANT_CD, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES ('PROD_RECEIVE', 'PRODUCT_MGMT', 10, 'HANES', '-', SYSTIMESTAMP, 'system', SYSTIMESTAMP, 'system');
INSERT INTO MENU_CATEGORY_ITEMS (MENU_CODE, CATEGORY_CODE, SORT_ORDER, COMPANY, PLANT_CD, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES ('PROD_RECEIPT_CANCEL', 'PRODUCT_MGMT', 20, 'HANES', '-', SYSTIMESTAMP, 'system', SYSTIMESTAMP, 'system');
INSERT INTO MENU_CATEGORY_ITEMS (MENU_CODE, CATEGORY_CODE, SORT_ORDER, COMPANY, PLANT_CD, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES ('PROD_ISSUE', 'PRODUCT_MGMT', 30, 'HANES', '-', SYSTIMESTAMP, 'system', SYSTIMESTAMP, 'system');
INSERT INTO MENU_CATEGORY_ITEMS (MENU_CODE, CATEGORY_CODE, SORT_ORDER, COMPANY, PLANT_CD, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES ('PROD_ISSUE_CANCEL', 'PRODUCT_MGMT', 40, 'HANES', '-', SYSTIMESTAMP, 'system', SYSTIMESTAMP, 'system');
INSERT INTO MENU_CATEGORY_ITEMS (MENU_CODE, CATEGORY_CODE, SORT_ORDER, COMPANY, PLANT_CD, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES ('MAT_ARRIVAL', 'MATERIAL', 10, 'HANES', '-', SYSTIMESTAMP, 'system', SYSTIMESTAMP, 'system');
INSERT INTO MENU_CATEGORY_ITEMS (MENU_CODE, CATEGORY_CODE, SORT_ORDER, COMPANY, PLANT_CD, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES ('MAT_RECEIVE_LABEL', 'MATERIAL', 20, 'HANES', '-', SYSTIMESTAMP, 'system', SYSTIMESTAMP, 'system');
INSERT INTO MENU_CATEGORY_ITEMS (MENU_CODE, CATEGORY_CODE, SORT_ORDER, COMPANY, PLANT_CD, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES ('MAT_RECEIVE', 'MATERIAL', 30, 'HANES', '-', SYSTIMESTAMP, 'system', SYSTIMESTAMP, 'system');
INSERT INTO MENU_CATEGORY_ITEMS (MENU_CODE, CATEGORY_CODE, SORT_ORDER, COMPANY, PLANT_CD, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES ('MAT_RECEIVE_HISTORY', 'MATERIAL', 40, 'HANES', '-', SYSTIMESTAMP, 'system', SYSTIMESTAMP, 'system');
INSERT INTO MENU_CATEGORY_ITEMS (MENU_CODE, CATEGORY_CODE, SORT_ORDER, COMPANY, PLANT_CD, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES ('MAT_REQUEST', 'MATERIAL', 50, 'HANES', '-', SYSTIMESTAMP, 'system', SYSTIMESTAMP, 'system');
INSERT INTO MENU_CATEGORY_ITEMS (MENU_CODE, CATEGORY_CODE, SORT_ORDER, COMPANY, PLANT_CD, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES ('MAT_ISSUE', 'MATERIAL', 60, 'HANES', '-', SYSTIMESTAMP, 'system', SYSTIMESTAMP, 'system');
INSERT INTO MENU_CATEGORY_ITEMS (MENU_CODE, CATEGORY_CODE, SORT_ORDER, COMPANY, PLANT_CD, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES ('MAT_LOT', 'MATERIAL', 70, 'HANES', '-', SYSTIMESTAMP, 'system', SYSTIMESTAMP, 'system');
INSERT INTO MENU_CATEGORY_ITEMS (MENU_CODE, CATEGORY_CODE, SORT_ORDER, COMPANY, PLANT_CD, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES ('MAT_LOT_SPLIT', 'MATERIAL', 80, 'HANES', '-', SYSTIMESTAMP, 'system', SYSTIMESTAMP, 'system');
INSERT INTO MENU_CATEGORY_ITEMS (MENU_CODE, CATEGORY_CODE, SORT_ORDER, COMPANY, PLANT_CD, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES ('MAT_LOT_MERGE', 'MATERIAL', 90, 'HANES', '-', SYSTIMESTAMP, 'system', SYSTIMESTAMP, 'system');
INSERT INTO MENU_CATEGORY_ITEMS (MENU_CODE, CATEGORY_CODE, SORT_ORDER, COMPANY, PLANT_CD, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES ('MAT_SHELF_LIFE', 'MATERIAL', 100, 'HANES', '-', SYSTIMESTAMP, 'system', SYSTIMESTAMP, 'system');
INSERT INTO MENU_CATEGORY_ITEMS (MENU_CODE, CATEGORY_CODE, SORT_ORDER, COMPANY, PLANT_CD, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES ('MAT_SCRAP', 'MATERIAL', 110, 'HANES', '-', SYSTIMESTAMP, 'system', SYSTIMESTAMP, 'system');
INSERT INTO MENU_CATEGORY_ITEMS (MENU_CODE, CATEGORY_CODE, SORT_ORDER, COMPANY, PLANT_CD, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES ('MAT_ADJUSTMENT', 'MATERIAL', 120, 'HANES', '-', SYSTIMESTAMP, 'system', SYSTIMESTAMP, 'system');
INSERT INTO MENU_CATEGORY_ITEMS (MENU_CODE, CATEGORY_CODE, SORT_ORDER, COMPANY, PLANT_CD, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES ('MAT_MISC_RECEIPT', 'MATERIAL', 130, 'HANES', '-', SYSTIMESTAMP, 'system', SYSTIMESTAMP, 'system');
INSERT INTO MENU_CATEGORY_ITEMS (MENU_CODE, CATEGORY_CODE, SORT_ORDER, COMPANY, PLANT_CD, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES ('MAT_RECEIPT_CANCEL', 'MATERIAL', 140, 'HANES', '-', SYSTIMESTAMP, 'system', SYSTIMESTAMP, 'system');
INSERT INTO MENU_CATEGORY_ITEMS (MENU_CODE, CATEGORY_CODE, SORT_ORDER, COMPANY, PLANT_CD, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES ('PUR_PO', 'PURCHASING', 10, 'HANES', '-', SYSTIMESTAMP, 'system', SYSTIMESTAMP, 'system');
INSERT INTO MENU_CATEGORY_ITEMS (MENU_CODE, CATEGORY_CODE, SORT_ORDER, COMPANY, PLANT_CD, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES ('PUR_PO_STATUS', 'PURCHASING', 20, 'HANES', '-', SYSTIMESTAMP, 'system', SYSTIMESTAMP, 'system');
INSERT INTO MENU_CATEGORY_ITEMS (MENU_CODE, CATEGORY_CODE, SORT_ORDER, COMPANY, PLANT_CD, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES ('PROD_MONTHLY_PLAN', 'PRODUCTION', 10, 'HANES', '-', SYSTIMESTAMP, 'system', SYSTIMESTAMP, 'system');
INSERT INTO MENU_CATEGORY_ITEMS (MENU_CODE, CATEGORY_CODE, SORT_ORDER, COMPANY, PLANT_CD, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES ('PROD_SIMULATION', 'PRODUCTION', 20, 'HANES', '-', SYSTIMESTAMP, 'system', SYSTIMESTAMP, 'system');
INSERT INTO MENU_CATEGORY_ITEMS (MENU_CODE, CATEGORY_CODE, SORT_ORDER, COMPANY, PLANT_CD, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES ('PROD_ORDER', 'PRODUCTION', 30, 'HANES', '-', SYSTIMESTAMP, 'system', SYSTIMESTAMP, 'system');
INSERT INTO MENU_CATEGORY_ITEMS (MENU_CODE, CATEGORY_CODE, SORT_ORDER, COMPANY, PLANT_CD, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES ('PROD_RESULT', 'PRODUCTION', 40, 'HANES', '-', SYSTIMESTAMP, 'system', SYSTIMESTAMP, 'system');
INSERT INTO MENU_CATEGORY_ITEMS (MENU_CODE, CATEGORY_CODE, SORT_ORDER, COMPANY, PLANT_CD, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES ('PROD_PROGRESS', 'PRODUCTION', 50, 'HANES', '-', SYSTIMESTAMP, 'system', SYSTIMESTAMP, 'system');
INSERT INTO MENU_CATEGORY_ITEMS (MENU_CODE, CATEGORY_CODE, SORT_ORDER, COMPANY, PLANT_CD, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES ('PROD_INPUT_MANUAL', 'PRODUCTION', 60, 'HANES', '-', SYSTIMESTAMP, 'system', SYSTIMESTAMP, 'system');
INSERT INTO MENU_CATEGORY_ITEMS (MENU_CODE, CATEGORY_CODE, SORT_ORDER, COMPANY, PLANT_CD, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES ('PROD_INPUT_MACHINE', 'PRODUCTION', 70, 'HANES', '-', SYSTIMESTAMP, 'system', SYSTIMESTAMP, 'system');
INSERT INTO MENU_CATEGORY_ITEMS (MENU_CODE, CATEGORY_CODE, SORT_ORDER, COMPANY, PLANT_CD, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES ('PROD_INPUT_INSPECT', 'PRODUCTION', 80, 'HANES', '-', SYSTIMESTAMP, 'system', SYSTIMESTAMP, 'system');
INSERT INTO MENU_CATEGORY_ITEMS (MENU_CODE, CATEGORY_CODE, SORT_ORDER, COMPANY, PLANT_CD, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES ('PROD_INPUT_EQUIP', 'PRODUCTION', 90, 'HANES', '-', SYSTIMESTAMP, 'system', SYSTIMESTAMP, 'system');
INSERT INTO MENU_CATEGORY_ITEMS (MENU_CODE, CATEGORY_CODE, SORT_ORDER, COMPANY, PLANT_CD, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES ('PROD_RESULT_SUMMARY', 'PRODUCTION', 100, 'HANES', '-', SYSTIMESTAMP, 'system', SYSTIMESTAMP, 'system');
INSERT INTO MENU_CATEGORY_ITEMS (MENU_CODE, CATEGORY_CODE, SORT_ORDER, COMPANY, PLANT_CD, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES ('PROD_WIP_STOCK', 'PRODUCTION', 110, 'HANES', '-', SYSTIMESTAMP, 'system', SYSTIMESTAMP, 'system');
INSERT INTO MENU_CATEGORY_ITEMS (MENU_CODE, CATEGORY_CODE, SORT_ORDER, COMPANY, PLANT_CD, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES ('QC_REWORK', 'PRODUCTION', 120, 'HANES', '-', SYSTIMESTAMP, 'system', SYSTIMESTAMP, 'system');
INSERT INTO MENU_CATEGORY_ITEMS (MENU_CODE, CATEGORY_CODE, SORT_ORDER, COMPANY, PLANT_CD, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES ('QC_REWORK_HISTORY', 'PRODUCTION', 130, 'HANES', '-', SYSTIMESTAMP, 'system', SYSTIMESTAMP, 'system');
INSERT INTO MENU_CATEGORY_ITEMS (MENU_CODE, CATEGORY_CODE, SORT_ORDER, COMPANY, PLANT_CD, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES ('PROD_REPAIR', 'PRODUCTION', 140, 'HANES', '-', SYSTIMESTAMP, 'system', SYSTIMESTAMP, 'system');
INSERT INTO MENU_CATEGORY_ITEMS (MENU_CODE, CATEGORY_CODE, SORT_ORDER, COMPANY, PLANT_CD, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES ('INSP_RESULT', 'INSPECTION', 10, 'HANES', '-', SYSTIMESTAMP, 'system', SYSTIMESTAMP, 'system');
INSERT INTO MENU_CATEGORY_ITEMS (MENU_CODE, CATEGORY_CODE, SORT_ORDER, COMPANY, PLANT_CD, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES ('INSP_HISTORY', 'INSPECTION', 20, 'HANES', '-', SYSTIMESTAMP, 'system', SYSTIMESTAMP, 'system');
INSERT INTO MENU_CATEGORY_ITEMS (MENU_CODE, CATEGORY_CODE, SORT_ORDER, COMPANY, PLANT_CD, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES ('INSP_PROTOCOL', 'INSPECTION', 30, 'HANES', '-', SYSTIMESTAMP, 'system', SYSTIMESTAMP, 'system');
INSERT INTO MENU_CATEGORY_ITEMS (MENU_CODE, CATEGORY_CODE, SORT_ORDER, COMPANY, PLANT_CD, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES ('QC_IQC_ITEM', 'QUALITY', 10, 'HANES', '-', SYSTIMESTAMP, 'system', SYSTIMESTAMP, 'system');
INSERT INTO MENU_CATEGORY_ITEMS (MENU_CODE, CATEGORY_CODE, SORT_ORDER, COMPANY, PLANT_CD, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES ('QC_IQC', 'QUALITY', 20, 'HANES', '-', SYSTIMESTAMP, 'system', SYSTIMESTAMP, 'system');
INSERT INTO MENU_CATEGORY_ITEMS (MENU_CODE, CATEGORY_CODE, SORT_ORDER, COMPANY, PLANT_CD, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES ('QC_IQC_HISTORY', 'QUALITY', 30, 'HANES', '-', SYSTIMESTAMP, 'system', SYSTIMESTAMP, 'system');
INSERT INTO MENU_CATEGORY_ITEMS (MENU_CODE, CATEGORY_CODE, SORT_ORDER, COMPANY, PLANT_CD, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES ('QC_DEFECT', 'QUALITY', 40, 'HANES', '-', SYSTIMESTAMP, 'system', SYSTIMESTAMP, 'system');
INSERT INTO MENU_CATEGORY_ITEMS (MENU_CODE, CATEGORY_CODE, SORT_ORDER, COMPANY, PLANT_CD, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES ('QC_REWORK_INSPECT', 'QUALITY', 50, 'HANES', '-', SYSTIMESTAMP, 'system', SYSTIMESTAMP, 'system');
INSERT INTO MENU_CATEGORY_ITEMS (MENU_CODE, CATEGORY_CODE, SORT_ORDER, COMPANY, PLANT_CD, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES ('QC_INSPECT', 'QUALITY', 60, 'HANES', '-', SYSTIMESTAMP, 'system', SYSTIMESTAMP, 'system');
INSERT INTO MENU_CATEGORY_ITEMS (MENU_CODE, CATEGORY_CODE, SORT_ORDER, COMPANY, PLANT_CD, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES ('QC_SAMPLE_INSPECT', 'QUALITY', 70, 'HANES', '-', SYSTIMESTAMP, 'system', SYSTIMESTAMP, 'system');
INSERT INTO MENU_CATEGORY_ITEMS (MENU_CODE, CATEGORY_CODE, SORT_ORDER, COMPANY, PLANT_CD, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES ('QC_OQC', 'QUALITY', 80, 'HANES', '-', SYSTIMESTAMP, 'system', SYSTIMESTAMP, 'system');
INSERT INTO MENU_CATEGORY_ITEMS (MENU_CODE, CATEGORY_CODE, SORT_ORDER, COMPANY, PLANT_CD, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES ('QC_OQC_HISTORY', 'QUALITY', 90, 'HANES', '-', SYSTIMESTAMP, 'system', SYSTIMESTAMP, 'system');
INSERT INTO MENU_CATEGORY_ITEMS (MENU_CODE, CATEGORY_CODE, SORT_ORDER, COMPANY, PLANT_CD, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES ('QC_TRACE', 'QUALITY', 100, 'HANES', '-', SYSTIMESTAMP, 'system', SYSTIMESTAMP, 'system');
INSERT INTO MENU_CATEGORY_ITEMS (MENU_CODE, CATEGORY_CODE, SORT_ORDER, COMPANY, PLANT_CD, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES ('QC_CHANGE', 'QUALITY', 110, 'HANES', '-', SYSTIMESTAMP, 'system', SYSTIMESTAMP, 'system');
INSERT INTO MENU_CATEGORY_ITEMS (MENU_CODE, CATEGORY_CODE, SORT_ORDER, COMPANY, PLANT_CD, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES ('QC_COMPLAINT', 'QUALITY', 120, 'HANES', '-', SYSTIMESTAMP, 'system', SYSTIMESTAMP, 'system');
INSERT INTO MENU_CATEGORY_ITEMS (MENU_CODE, CATEGORY_CODE, SORT_ORDER, COMPANY, PLANT_CD, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES ('QC_CAPA', 'QUALITY', 130, 'HANES', '-', SYSTIMESTAMP, 'system', SYSTIMESTAMP, 'system');
INSERT INTO MENU_CATEGORY_ITEMS (MENU_CODE, CATEGORY_CODE, SORT_ORDER, COMPANY, PLANT_CD, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES ('QC_FAI', 'QUALITY', 140, 'HANES', '-', SYSTIMESTAMP, 'system', SYSTIMESTAMP, 'system');
INSERT INTO MENU_CATEGORY_ITEMS (MENU_CODE, CATEGORY_CODE, SORT_ORDER, COMPANY, PLANT_CD, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES ('QC_PPAP', 'QUALITY', 150, 'HANES', '-', SYSTIMESTAMP, 'system', SYSTIMESTAMP, 'system');
INSERT INTO MENU_CATEGORY_ITEMS (MENU_CODE, CATEGORY_CODE, SORT_ORDER, COMPANY, PLANT_CD, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES ('QC_SPC', 'QUALITY', 160, 'HANES', '-', SYSTIMESTAMP, 'system', SYSTIMESTAMP, 'system');
INSERT INTO MENU_CATEGORY_ITEMS (MENU_CODE, CATEGORY_CODE, SORT_ORDER, COMPANY, PLANT_CD, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES ('QC_CONTROL_PLAN', 'QUALITY', 170, 'HANES', '-', SYSTIMESTAMP, 'system', SYSTIMESTAMP, 'system');
INSERT INTO MENU_CATEGORY_ITEMS (MENU_CODE, CATEGORY_CODE, SORT_ORDER, COMPANY, PLANT_CD, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES ('QC_AUDIT', 'QUALITY', 180, 'HANES', '-', SYSTIMESTAMP, 'system', SYSTIMESTAMP, 'system');
INSERT INTO MENU_CATEGORY_ITEMS (MENU_CODE, CATEGORY_CODE, SORT_ORDER, COMPANY, PLANT_CD, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES ('SYS_TRAINING', 'QUALITY', 190, 'HANES', '-', SYSTIMESTAMP, 'system', SYSTIMESTAMP, 'system');
INSERT INTO MENU_CATEGORY_ITEMS (MENU_CODE, CATEGORY_CODE, SORT_ORDER, COMPANY, PLANT_CD, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES ('EQ_MOLD_MGMT', 'EQUIPMENT', 10, 'HANES', '-', SYSTIMESTAMP, 'system', SYSTIMESTAMP, 'system');
INSERT INTO MENU_CATEGORY_ITEMS (MENU_CODE, CATEGORY_CODE, SORT_ORDER, COMPANY, PLANT_CD, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES ('EQUIP_INSPECT_ITEM_MASTER', 'EQUIPMENT', 20, 'HANES', '-', SYSTIMESTAMP, 'system', SYSTIMESTAMP, 'system');
INSERT INTO MENU_CATEGORY_ITEMS (MENU_CODE, CATEGORY_CODE, SORT_ORDER, COMPANY, PLANT_CD, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES ('EQUIP_INSPECT_ITEM', 'EQUIPMENT', 30, 'HANES', '-', SYSTIMESTAMP, 'system', SYSTIMESTAMP, 'system');
INSERT INTO MENU_CATEGORY_ITEMS (MENU_CODE, CATEGORY_CODE, SORT_ORDER, COMPANY, PLANT_CD, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES ('EQUIP_INSPECT_CALENDAR', 'EQUIPMENT', 40, 'HANES', '-', SYSTIMESTAMP, 'system', SYSTIMESTAMP, 'system');
INSERT INTO MENU_CATEGORY_ITEMS (MENU_CODE, CATEGORY_CODE, SORT_ORDER, COMPANY, PLANT_CD, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES ('EQUIP_DAILY', 'EQUIPMENT', 50, 'HANES', '-', SYSTIMESTAMP, 'system', SYSTIMESTAMP, 'system');
INSERT INTO MENU_CATEGORY_ITEMS (MENU_CODE, CATEGORY_CODE, SORT_ORDER, COMPANY, PLANT_CD, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES ('EQUIP_PERIODIC_CALENDAR', 'EQUIPMENT', 60, 'HANES', '-', SYSTIMESTAMP, 'system', SYSTIMESTAMP, 'system');
INSERT INTO MENU_CATEGORY_ITEMS (MENU_CODE, CATEGORY_CODE, SORT_ORDER, COMPANY, PLANT_CD, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES ('EQUIP_PERIODIC', 'EQUIPMENT', 70, 'HANES', '-', SYSTIMESTAMP, 'system', SYSTIMESTAMP, 'system');
INSERT INTO MENU_CATEGORY_ITEMS (MENU_CODE, CATEGORY_CODE, SORT_ORDER, COMPANY, PLANT_CD, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES ('EQUIP_HISTORY', 'EQUIPMENT', 80, 'HANES', '-', SYSTIMESTAMP, 'system', SYSTIMESTAMP, 'system');
INSERT INTO MENU_CATEGORY_ITEMS (MENU_CODE, CATEGORY_CODE, SORT_ORDER, COMPANY, PLANT_CD, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES ('EQUIP_PM_PLAN', 'EQUIPMENT', 90, 'HANES', '-', SYSTIMESTAMP, 'system', SYSTIMESTAMP, 'system');
INSERT INTO MENU_CATEGORY_ITEMS (MENU_CODE, CATEGORY_CODE, SORT_ORDER, COMPANY, PLANT_CD, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES ('EQUIP_PM_CALENDAR', 'EQUIPMENT', 100, 'HANES', '-', SYSTIMESTAMP, 'system', SYSTIMESTAMP, 'system');
INSERT INTO MENU_CATEGORY_ITEMS (MENU_CODE, CATEGORY_CODE, SORT_ORDER, COMPANY, PLANT_CD, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES ('EQUIP_PM_RESULT', 'EQUIPMENT', 110, 'HANES', '-', SYSTIMESTAMP, 'system', SYSTIMESTAMP, 'system');
INSERT INTO MENU_CATEGORY_ITEMS (MENU_CODE, CATEGORY_CODE, SORT_ORDER, COMPANY, PLANT_CD, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES ('GAUGE_MASTER', 'GAUGE_MGMT', 10, 'HANES', '-', SYSTIMESTAMP, 'system', SYSTIMESTAMP, 'system');
INSERT INTO MENU_CATEGORY_ITEMS (MENU_CODE, CATEGORY_CODE, SORT_ORDER, COMPANY, PLANT_CD, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES ('GAUGE_CALIBRATION', 'GAUGE_MGMT', 20, 'HANES', '-', SYSTIMESTAMP, 'system', SYSTIMESTAMP, 'system');
INSERT INTO MENU_CATEGORY_ITEMS (MENU_CODE, CATEGORY_CODE, SORT_ORDER, COMPANY, PLANT_CD, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES ('GAUGE_CALIBRATION_HISTORY', 'GAUGE_MGMT', 30, 'HANES', '-', SYSTIMESTAMP, 'system', SYSTIMESTAMP, 'system');
INSERT INTO MENU_CATEGORY_ITEMS (MENU_CODE, CATEGORY_CODE, SORT_ORDER, COMPANY, PLANT_CD, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES ('SHIP_PACK_RESULT', 'SHIPPING', 10, 'HANES', '-', SYSTIMESTAMP, 'system', SYSTIMESTAMP, 'system');
INSERT INTO MENU_CATEGORY_ITEMS (MENU_CODE, CATEGORY_CODE, SORT_ORDER, COMPANY, PLANT_CD, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES ('SHIP_PACK', 'SHIPPING', 20, 'HANES', '-', SYSTIMESTAMP, 'system', SYSTIMESTAMP, 'system');
INSERT INTO MENU_CATEGORY_ITEMS (MENU_CODE, CATEGORY_CODE, SORT_ORDER, COMPANY, PLANT_CD, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES ('SHIP_PALLET', 'SHIPPING', 30, 'HANES', '-', SYSTIMESTAMP, 'system', SYSTIMESTAMP, 'system');
INSERT INTO MENU_CATEGORY_ITEMS (MENU_CODE, CATEGORY_CODE, SORT_ORDER, COMPANY, PLANT_CD, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES ('SHIP_CONFIRM', 'SHIPPING', 40, 'HANES', '-', SYSTIMESTAMP, 'system', SYSTIMESTAMP, 'system');
INSERT INTO MENU_CATEGORY_ITEMS (MENU_CODE, CATEGORY_CODE, SORT_ORDER, COMPANY, PLANT_CD, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES ('SHIP_ORDER', 'SHIPPING', 50, 'HANES', '-', SYSTIMESTAMP, 'system', SYSTIMESTAMP, 'system');
INSERT INTO MENU_CATEGORY_ITEMS (MENU_CODE, CATEGORY_CODE, SORT_ORDER, COMPANY, PLANT_CD, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES ('SHIP_HISTORY', 'SHIPPING', 60, 'HANES', '-', SYSTIMESTAMP, 'system', SYSTIMESTAMP, 'system');
INSERT INTO MENU_CATEGORY_ITEMS (MENU_CODE, CATEGORY_CODE, SORT_ORDER, COMPANY, PLANT_CD, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES ('SHIP_RETURN', 'SHIPPING', 70, 'HANES', '-', SYSTIMESTAMP, 'system', SYSTIMESTAMP, 'system');
INSERT INTO MENU_CATEGORY_ITEMS (MENU_CODE, CATEGORY_CODE, SORT_ORDER, COMPANY, PLANT_CD, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES ('SALES_CUST_PO', 'SALES', 10, 'HANES', '-', SYSTIMESTAMP, 'system', SYSTIMESTAMP, 'system');
INSERT INTO MENU_CATEGORY_ITEMS (MENU_CODE, CATEGORY_CODE, SORT_ORDER, COMPANY, PLANT_CD, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES ('SALES_CUST_PO_STATUS', 'SALES', 20, 'HANES', '-', SYSTIMESTAMP, 'system', SYSTIMESTAMP, 'system');
INSERT INTO MENU_CATEGORY_ITEMS (MENU_CODE, CATEGORY_CODE, SORT_ORDER, COMPANY, PLANT_CD, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES ('CUST_ENTRY', 'CUSTOMS', 10, 'HANES', '-', SYSTIMESTAMP, 'system', SYSTIMESTAMP, 'system');
INSERT INTO MENU_CATEGORY_ITEMS (MENU_CODE, CATEGORY_CODE, SORT_ORDER, COMPANY, PLANT_CD, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES ('CUST_STOCK', 'CUSTOMS', 20, 'HANES', '-', SYSTIMESTAMP, 'system', SYSTIMESTAMP, 'system');
INSERT INTO MENU_CATEGORY_ITEMS (MENU_CODE, CATEGORY_CODE, SORT_ORDER, COMPANY, PLANT_CD, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES ('CUST_USAGE', 'CUSTOMS', 30, 'HANES', '-', SYSTIMESTAMP, 'system', SYSTIMESTAMP, 'system');
INSERT INTO MENU_CATEGORY_ITEMS (MENU_CODE, CATEGORY_CODE, SORT_ORDER, COMPANY, PLANT_CD, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES ('CONS_MASTER', 'CONSUMABLES', 10, 'HANES', '-', SYSTIMESTAMP, 'system', SYSTIMESTAMP, 'system');
INSERT INTO MENU_CATEGORY_ITEMS (MENU_CODE, CATEGORY_CODE, SORT_ORDER, COMPANY, PLANT_CD, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES ('CONS_LABEL', 'CONSUMABLES', 20, 'HANES', '-', SYSTIMESTAMP, 'system', SYSTIMESTAMP, 'system');
INSERT INTO MENU_CATEGORY_ITEMS (MENU_CODE, CATEGORY_CODE, SORT_ORDER, COMPANY, PLANT_CD, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES ('CONS_RECEIVING', 'CONSUMABLES', 30, 'HANES', '-', SYSTIMESTAMP, 'system', SYSTIMESTAMP, 'system');
INSERT INTO MENU_CATEGORY_ITEMS (MENU_CODE, CATEGORY_CODE, SORT_ORDER, COMPANY, PLANT_CD, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES ('CONS_ISSUING', 'CONSUMABLES', 40, 'HANES', '-', SYSTIMESTAMP, 'system', SYSTIMESTAMP, 'system');
INSERT INTO MENU_CATEGORY_ITEMS (MENU_CODE, CATEGORY_CODE, SORT_ORDER, COMPANY, PLANT_CD, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES ('CONS_STOCK', 'CONSUMABLES', 50, 'HANES', '-', SYSTIMESTAMP, 'system', SYSTIMESTAMP, 'system');
INSERT INTO MENU_CATEGORY_ITEMS (MENU_CODE, CATEGORY_CODE, SORT_ORDER, COMPANY, PLANT_CD, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES ('CONS_LIFE', 'CONSUMABLES', 60, 'HANES', '-', SYSTIMESTAMP, 'system', SYSTIMESTAMP, 'system');
INSERT INTO MENU_CATEGORY_ITEMS (MENU_CODE, CATEGORY_CODE, SORT_ORDER, COMPANY, PLANT_CD, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES ('CONS_MOUNT', 'CONSUMABLES', 70, 'HANES', '-', SYSTIMESTAMP, 'system', SYSTIMESTAMP, 'system');
INSERT INTO MENU_CATEGORY_ITEMS (MENU_CODE, CATEGORY_CODE, SORT_ORDER, COMPANY, PLANT_CD, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES ('OUT_VENDOR', 'OUTSOURCING', 10, 'HANES', '-', SYSTIMESTAMP, 'system', SYSTIMESTAMP, 'system');
INSERT INTO MENU_CATEGORY_ITEMS (MENU_CODE, CATEGORY_CODE, SORT_ORDER, COMPANY, PLANT_CD, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES ('OUT_ORDER', 'OUTSOURCING', 20, 'HANES', '-', SYSTIMESTAMP, 'system', SYSTIMESTAMP, 'system');
INSERT INTO MENU_CATEGORY_ITEMS (MENU_CODE, CATEGORY_CODE, SORT_ORDER, COMPANY, PLANT_CD, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES ('OUT_RECEIVE', 'OUTSOURCING', 30, 'HANES', '-', SYSTIMESTAMP, 'system', SYSTIMESTAMP, 'system');
INSERT INTO MENU_CATEGORY_ITEMS (MENU_CODE, CATEGORY_CODE, SORT_ORDER, COMPANY, PLANT_CD, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES ('IF_DASHBOARD', 'INTERFACE', 10, 'HANES', '-', SYSTIMESTAMP, 'system', SYSTIMESTAMP, 'system');
INSERT INTO MENU_CATEGORY_ITEMS (MENU_CODE, CATEGORY_CODE, SORT_ORDER, COMPANY, PLANT_CD, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES ('IF_LOG', 'INTERFACE', 20, 'HANES', '-', SYSTIMESTAMP, 'system', SYSTIMESTAMP, 'system');
INSERT INTO MENU_CATEGORY_ITEMS (MENU_CODE, CATEGORY_CODE, SORT_ORDER, COMPANY, PLANT_CD, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES ('IF_MANUAL', 'INTERFACE', 30, 'HANES', '-', SYSTIMESTAMP, 'system', SYSTIMESTAMP, 'system');
INSERT INTO MENU_CATEGORY_ITEMS (MENU_CODE, CATEGORY_CODE, SORT_ORDER, COMPANY, PLANT_CD, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES ('SYS_COMPANY', 'SYSTEM', 10, 'HANES', '-', SYSTIMESTAMP, 'system', SYSTIMESTAMP, 'system');
INSERT INTO MENU_CATEGORY_ITEMS (MENU_CODE, CATEGORY_CODE, SORT_ORDER, COMPANY, PLANT_CD, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES ('SYS_DEPT', 'SYSTEM', 20, 'HANES', '-', SYSTIMESTAMP, 'system', SYSTIMESTAMP, 'system');
INSERT INTO MENU_CATEGORY_ITEMS (MENU_CODE, CATEGORY_CODE, SORT_ORDER, COMPANY, PLANT_CD, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES ('SYS_USER', 'SYSTEM', 30, 'HANES', '-', SYSTIMESTAMP, 'system', SYSTIMESTAMP, 'system');
INSERT INTO MENU_CATEGORY_ITEMS (MENU_CODE, CATEGORY_CODE, SORT_ORDER, COMPANY, PLANT_CD, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES ('SYS_ROLE', 'SYSTEM', 40, 'HANES', '-', SYSTIMESTAMP, 'system', SYSTIMESTAMP, 'system');
INSERT INTO MENU_CATEGORY_ITEMS (MENU_CODE, CATEGORY_CODE, SORT_ORDER, COMPANY, PLANT_CD, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES ('SYS_PDA_ROLE', 'SYSTEM', 50, 'HANES', '-', SYSTIMESTAMP, 'system', SYSTIMESTAMP, 'system');
INSERT INTO MENU_CATEGORY_ITEMS (MENU_CODE, CATEGORY_CODE, SORT_ORDER, COMPANY, PLANT_CD, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES ('SYS_COMM', 'SYSTEM', 60, 'HANES', '-', SYSTIMESTAMP, 'system', SYSTIMESTAMP, 'system');
INSERT INTO MENU_CATEGORY_ITEMS (MENU_CODE, CATEGORY_CODE, SORT_ORDER, COMPANY, PLANT_CD, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES ('SYS_CONFIG', 'SYSTEM', 70, 'HANES', '-', SYSTIMESTAMP, 'system', SYSTIMESTAMP, 'system');
INSERT INTO MENU_CATEGORY_ITEMS (MENU_CODE, CATEGORY_CODE, SORT_ORDER, COMPANY, PLANT_CD, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES ('SYS_CODE', 'SYSTEM', 80, 'HANES', '-', SYSTIMESTAMP, 'system', SYSTIMESTAMP, 'system');
INSERT INTO MENU_CATEGORY_ITEMS (MENU_CODE, CATEGORY_CODE, SORT_ORDER, COMPANY, PLANT_CD, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES ('SYS_SCHEDULER', 'SYSTEM', 90, 'HANES', '-', SYSTIMESTAMP, 'system', SYSTIMESTAMP, 'system');

COMMIT;
