-- SCHEDULER_JOBS 테이블 생성
CREATE TABLE SCHEDULER_JOBS (
    COMPANY VARCHAR2(20) NOT NULL,
    PLANT_CD VARCHAR2(20) NOT NULL,
    JOB_CODE VARCHAR2(50) NOT NULL,
    JOB_NAME NVARCHAR2(100) NOT NULL,
    JOB_GROUP VARCHAR2(20) NOT NULL,
    EXEC_TYPE VARCHAR2(20) NOT NULL,
    EXEC_TARGET NVARCHAR2(500) NOT NULL,
    EXEC_PARAMS NVARCHAR2(2000),
    CRON_EXPR VARCHAR2(50) NOT NULL,
    IS_ACTIVE CHAR(1) DEFAULT 'N' NOT NULL,
    MAX_RETRY NUMBER DEFAULT 0 NOT NULL,
    TIMEOUT_SEC NUMBER DEFAULT 300 NOT NULL,
    DESCRIPTION NVARCHAR2(500),
    LAST_RUN_AT TIMESTAMP,
    LAST_STATUS VARCHAR2(20),
    LAST_ERROR_AT TIMESTAMP,
    NEXT_RUN_AT TIMESTAMP,
    CREATED_BY VARCHAR2(50),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_BY VARCHAR2(50),
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT PK_SCHEDULER_JOBS PRIMARY KEY (COMPANY, PLANT_CD, JOB_CODE)
);

-- SCHEDULER_LOGS 테이블 생성
CREATE TABLE SCHEDULER_LOGS (
    ID VARCHAR2(50) NOT NULL PRIMARY KEY,
    COMPANY VARCHAR2(20),
    PLANT_CD VARCHAR2(20),
    JOB_CODE VARCHAR2(50) NOT NULL,
    JOB_GROUP VARCHAR2(20),
    EXEC_TYPE VARCHAR2(20),
    EXEC_TARGET NVARCHAR2(500),
    STARTED_AT TIMESTAMP NOT NULL,
    ENDED_AT TIMESTAMP,
    STATUS VARCHAR2(20) NOT NULL,
    RESULT_MSG NVARCHAR2(2000),
    ERROR_MSG NVARCHAR2(2000),
    DURATION_MS NUMBER,
    RETRY_COUNT NUMBER DEFAULT 0,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- SCHEDULER_NOTIFICATIONS 테이블 생성
CREATE TABLE SCHEDULER_NOTIFICATIONS (
    ID VARCHAR2(50) NOT NULL PRIMARY KEY,
    COMPANY VARCHAR2(20),
    PLANT_CD VARCHAR2(20),
    JOB_CODE VARCHAR2(50) NOT NULL,
    NOTI_TYPE VARCHAR2(20) NOT NULL,
    NOTI_TITLE NVARCHAR2(200) NOT NULL,
    NOTI_MESSAGE NVARCHAR2(1000),
    IS_READ CHAR(1) DEFAULT 'N' NOT NULL,
    READ_AT TIMESTAMP,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- 인덱스 생성
CREATE INDEX IDX_SCHEDULER_LOGS_JOB ON SCHEDULER_LOGS(JOB_CODE, STARTED_AT);
CREATE INDEX IDX_SCHEDULER_LOGS_STATUS ON SCHEDULER_LOGS(STATUS);
CREATE INDEX IDX_SCHEDULER_NOTI_UNREAD ON SCHEDULER_NOTIFICATIONS(IS_READ, CREATED_AT);

-- 테이블 코멘트
COMMENT ON TABLE SCHEDULER_JOBS IS '스케줄러 작업 마스터';
COMMENT ON TABLE SCHEDULER_LOGS IS '스케줄러 실행 로그';
COMMENT ON TABLE SCHEDULER_NOTIFICATIONS IS '스케줄러 알림';

-- 컬럼 코멘트
COMMENT ON COLUMN SCHEDULER_JOBS.COMPANY IS '회사코드';
COMMENT ON COLUMN SCHEDULER_JOBS.PLANT_CD IS '공장코드';
COMMENT ON COLUMN SCHEDULER_JOBS.JOB_CODE IS '작업코드';
COMMENT ON COLUMN SCHEDULER_JOBS.JOB_NAME IS '작업명';
COMMENT ON COLUMN SCHEDULER_JOBS.JOB_GROUP IS '작업그룹';
COMMENT ON COLUMN SCHEDULER_JOBS.EXEC_TYPE IS '실행유형';
COMMENT ON COLUMN SCHEDULER_JOBS.EXEC_TARGET IS '실행대상';
COMMENT ON COLUMN SCHEDULER_JOBS.CRON_EXPR IS 'CRON표현식';
COMMENT ON COLUMN SCHEDULER_JOBS.IS_ACTIVE IS '활성여부';
