CREATE TABLE SIMULATION_HEADERS (
  SIM_ID           VARCHAR2(50)   NOT NULL,
  SIM_MONTH        VARCHAR2(7)    NOT NULL,
  STRATEGY         VARCHAR2(20)   DEFAULT 'DUE_DATE' NOT NULL,
  SHIFT_COUNT      NUMBER(1)      DEFAULT 1 NOT NULL,
  INCLUDE_OT       VARCHAR2(1)    DEFAULT 'N' NOT NULL,
  APPLY_SETUP      VARCHAR2(1)    DEFAULT 'Y' NOT NULL,
  DEDUCT_STOCK     VARCHAR2(1)    DEFAULT 'N' NOT NULL,
  TOTAL_PLANS      NUMBER         DEFAULT 0 NOT NULL,
  ON_TIME_COUNT    NUMBER         DEFAULT 0 NOT NULL,
  DELAY_COUNT      NUMBER         DEFAULT 0 NOT NULL,
  TOTAL_QTY        NUMBER         DEFAULT 0 NOT NULL,
  WORK_DAYS        NUMBER         DEFAULT 0 NOT NULL,
  UTILIZATION_RATE NUMBER(5,1)    DEFAULT 0 NOT NULL,
  REQUIRED_HOURS   NUMBER(10,1)   DEFAULT 0 NOT NULL,
  AVAILABLE_HOURS  NUMBER(10,1)   DEFAULT 0 NOT NULL,
  COMPANY          VARCHAR2(50)   NOT NULL,
  PLANT_CD         VARCHAR2(50)   NOT NULL,
  CREATED_BY       VARCHAR2(50),
  CREATED_AT       TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT PK_SIMULATION_HEADERS PRIMARY KEY (SIM_ID)
)
/
CREATE TABLE SIMULATION_PLANS (
  SIM_ID              VARCHAR2(50)   NOT NULL,
  PLAN_NO             VARCHAR2(50)   NOT NULL,
  ITEM_CODE           VARCHAR2(50),
  ITEM_NAME           VARCHAR2(200),
  ITEM_TYPE           VARCHAR2(20),
  CUSTOMER            VARCHAR2(50),
  CUSTOMER_NAME       VARCHAR2(200),
  PLAN_QTY            NUMBER         DEFAULT 0 NOT NULL,
  DUE_DATE            VARCHAR2(10),
  PRIORITY            NUMBER         DEFAULT 5 NOT NULL,
  START_DATE          VARCHAR2(10),
  END_DATE            VARCHAR2(10),
  ON_TIME             VARCHAR2(1)    DEFAULT 'Y' NOT NULL,
  DELAY_DAYS          NUMBER         DEFAULT 0 NOT NULL,
  REQUIRED_DAYS       NUMBER         DEFAULT 0 NOT NULL,
  BOTTLENECK_PROCESS  VARCHAR2(100),
  DAILY_CAPA          NUMBER         DEFAULT 0 NOT NULL,
  CONSTRAINT PK_SIMULATION_PLANS PRIMARY KEY (SIM_ID, PLAN_NO)
)
/
CREATE TABLE SIMULATION_SCHEDULES (
  SIM_ID         VARCHAR2(50)   NOT NULL,
  PLAN_NO        VARCHAR2(50)   NOT NULL,
  PROCESS_CODE   VARCHAR2(50)   NOT NULL,
  PROCESS_NAME   VARCHAR2(100),
  START_DATE     VARCHAR2(10),
  END_DATE       VARCHAR2(10),
  TOTAL_QTY      NUMBER         DEFAULT 0 NOT NULL,
  CONSTRAINT PK_SIMULATION_SCHEDULES PRIMARY KEY (SIM_ID, PLAN_NO, PROCESS_CODE)
)
