-- MAT_ARRIVALS 테이블 생성 (입하 업무 전용)
CREATE TABLE MAT_ARRIVALS (
    ID            RAW(16) DEFAULT SYS_GUID() PRIMARY KEY,
    ARRIVAL_NO    VARCHAR2(50)   NOT NULL,
    INVOICE_NO    VARCHAR2(100),
    PO_ID         VARCHAR2(50),
    PO_ITEM_ID    VARCHAR2(50),
    PO_NO         VARCHAR2(50),
    VENDOR_ID     VARCHAR2(50),
    VENDOR_NAME   VARCHAR2(200),
    LOT_ID        VARCHAR2(50)   NOT NULL,
    PART_ID       VARCHAR2(50)   NOT NULL,
    QTY           NUMBER(10)     NOT NULL,
    WAREHOUSE_CODE VARCHAR2(50)  NOT NULL,
    ARRIVAL_DATE  TIMESTAMP      DEFAULT CURRENT_TIMESTAMP,
    ARRIVAL_TYPE  VARCHAR2(20)   DEFAULT 'PO',
    WORKER_ID     VARCHAR2(50),
    REMARK        VARCHAR2(500),
    STATUS        VARCHAR2(20)   DEFAULT 'DONE',
    COMPANY       VARCHAR2(50),
    PLANT_CD      VARCHAR2(50),
    CREATED_BY    VARCHAR2(50),
    UPDATED_BY    VARCHAR2(50),
    CREATED_AT    TIMESTAMP      DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT    TIMESTAMP      DEFAULT CURRENT_TIMESTAMP
);

-- 인덱스 생성
CREATE INDEX IDX_MAT_ARRIVALS_ARRIVAL_NO  ON MAT_ARRIVALS(ARRIVAL_NO);
CREATE INDEX IDX_MAT_ARRIVALS_LOT_ID      ON MAT_ARRIVALS(LOT_ID);
CREATE INDEX IDX_MAT_ARRIVALS_PART_ID     ON MAT_ARRIVALS(PART_ID);
CREATE INDEX IDX_MAT_ARRIVALS_ARRIVAL_DT  ON MAT_ARRIVALS(ARRIVAL_DATE);
CREATE INDEX IDX_MAT_ARRIVALS_INVOICE_NO  ON MAT_ARRIVALS(INVOICE_NO);
CREATE INDEX IDX_MAT_ARRIVALS_VENDOR_ID   ON MAT_ARRIVALS(VENDOR_ID);

COMMENT ON TABLE MAT_ARRIVALS IS '입하 업무 이력 테이블';
COMMENT ON COLUMN MAT_ARRIVALS.ARRIVAL_NO IS '입하번호 (같은 배치 동일번호)';
COMMENT ON COLUMN MAT_ARRIVALS.INVOICE_NO IS '인보이스번호';
COMMENT ON COLUMN MAT_ARRIVALS.PO_ID IS '발주 ID';
COMMENT ON COLUMN MAT_ARRIVALS.PO_NO IS '발주번호';
COMMENT ON COLUMN MAT_ARRIVALS.VENDOR_ID IS '거래처 ID';
COMMENT ON COLUMN MAT_ARRIVALS.VENDOR_NAME IS '거래처명';
COMMENT ON COLUMN MAT_ARRIVALS.LOT_ID IS 'LOT ID';
COMMENT ON COLUMN MAT_ARRIVALS.PART_ID IS '품목 ID';
COMMENT ON COLUMN MAT_ARRIVALS.QTY IS '입하수량';
COMMENT ON COLUMN MAT_ARRIVALS.WAREHOUSE_CODE IS '입고창고코드';
COMMENT ON COLUMN MAT_ARRIVALS.ARRIVAL_DATE IS '입하일시';
COMMENT ON COLUMN MAT_ARRIVALS.ARRIVAL_TYPE IS '입하유형 (PO/MANUAL)';
COMMENT ON COLUMN MAT_ARRIVALS.STATUS IS '상태 (DONE/CANCELED)';
