-- ============================================================
-- 자재 제조사 바코드 매핑 테이블
-- 제조사 바코드를 MES 품목과 매핑하여 자동 파트넘버 변환
-- ============================================================

CREATE TABLE VENDOR_BARCODE_MAPPINGS (
    ID              RAW(16) DEFAULT SYS_GUID() PRIMARY KEY,
    VENDOR_BARCODE  VARCHAR2(200)  NOT NULL,
    PART_ID         RAW(16),
    PART_CODE       VARCHAR2(50),
    PART_NAME       VARCHAR2(100),
    VENDOR_CODE     VARCHAR2(50),
    VENDOR_NAME     VARCHAR2(100),
    MAPPING_RULE    VARCHAR2(200),
    MATCH_TYPE      VARCHAR2(20)   DEFAULT 'EXACT'  NOT NULL,
    REMARK          VARCHAR2(500),
    USE_YN          VARCHAR2(1)    DEFAULT 'Y'      NOT NULL,
    CREATED_BY      VARCHAR2(50),
    CREATED_AT      TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT      TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
    DELETED_AT      TIMESTAMP
);

-- 인덱스
CREATE UNIQUE INDEX UQ_VBM_VENDOR_BARCODE ON VENDOR_BARCODE_MAPPINGS (VENDOR_BARCODE);
CREATE INDEX IDX_VBM_PART_ID     ON VENDOR_BARCODE_MAPPINGS (PART_ID);
CREATE INDEX IDX_VBM_VENDOR_CODE ON VENDOR_BARCODE_MAPPINGS (VENDOR_CODE);
CREATE INDEX IDX_VBM_MATCH_TYPE  ON VENDOR_BARCODE_MAPPINGS (MATCH_TYPE);

COMMENT ON TABLE  VENDOR_BARCODE_MAPPINGS              IS '자재 제조사 바코드 매핑';
COMMENT ON COLUMN VENDOR_BARCODE_MAPPINGS.VENDOR_BARCODE IS '제조사 바코드 값';
COMMENT ON COLUMN VENDOR_BARCODE_MAPPINGS.PART_ID        IS 'MES 품목 ID (FK → PART_MASTERS.ID)';
COMMENT ON COLUMN VENDOR_BARCODE_MAPPINGS.PART_CODE      IS 'MES 품번';
COMMENT ON COLUMN VENDOR_BARCODE_MAPPINGS.VENDOR_CODE    IS '제조사 코드 (FK → VENDOR_MASTERS)';
COMMENT ON COLUMN VENDOR_BARCODE_MAPPINGS.MATCH_TYPE     IS '매칭 유형: EXACT(정확), PREFIX(접두사), REGEX(정규식)';
COMMENT ON COLUMN VENDOR_BARCODE_MAPPINGS.USE_YN         IS '사용여부 (Y/N)';
