-- IQC 검사항목 풀(Pool) 테이블 DDL
-- IQC 검사항목의 글로벌 정의 마스터 (IQC-001 ~ IQC-xxx)

CREATE TABLE IQC_ITEM_POOL (
    ID            RAW(16) DEFAULT SYS_GUID() PRIMARY KEY,
    ITEM_CODE     VARCHAR2(20)   NOT NULL,
    ITEM_NAME     VARCHAR2(100)  NOT NULL,
    JUDGE_METHOD  VARCHAR2(20)   NOT NULL,   -- VISUAL / MEASURE
    CRITERIA      VARCHAR2(255),
    LSL           NUMBER(12,4),
    USL           NUMBER(12,4),
    UNIT          VARCHAR2(20),
    REVISION      NUMBER(10)     DEFAULT 1 NOT NULL,
    EFFECTIVE_DATE TIMESTAMP,
    USE_YN        VARCHAR2(1)    DEFAULT 'Y' NOT NULL,
    REMARK        VARCHAR2(500),
    COMPANY       VARCHAR2(50),
    PLANT_CD      VARCHAR2(50),
    CREATED_BY    VARCHAR2(50),
    UPDATED_BY    VARCHAR2(50),
    CREATED_AT    TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT    TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
    DELETED_AT    TIMESTAMP
);

CREATE UNIQUE INDEX UQ_IQC_ITEM_POOL_CODE ON IQC_ITEM_POOL (ITEM_CODE);

COMMENT ON TABLE IQC_ITEM_POOL IS 'IQC 검사항목 풀 마스터';
COMMENT ON COLUMN IQC_ITEM_POOL.ID IS '고유 ID';
COMMENT ON COLUMN IQC_ITEM_POOL.ITEM_CODE IS '항목코드 (IQC-001)';
COMMENT ON COLUMN IQC_ITEM_POOL.ITEM_NAME IS '항목명';
COMMENT ON COLUMN IQC_ITEM_POOL.JUDGE_METHOD IS '판정방법 (VISUAL/MEASURE)';
COMMENT ON COLUMN IQC_ITEM_POOL.CRITERIA IS '판정기준 설명';
COMMENT ON COLUMN IQC_ITEM_POOL.LSL IS '하한값 (계측항목)';
COMMENT ON COLUMN IQC_ITEM_POOL.USL IS '상한값 (계측항목)';
COMMENT ON COLUMN IQC_ITEM_POOL.UNIT IS '단위 (mm, Ω/km 등)';
COMMENT ON COLUMN IQC_ITEM_POOL.REVISION IS '리비전 번호';
COMMENT ON COLUMN IQC_ITEM_POOL.EFFECTIVE_DATE IS '시행일';
COMMENT ON COLUMN IQC_ITEM_POOL.USE_YN IS '사용여부 (Y/N)';
COMMENT ON COLUMN IQC_ITEM_POOL.REMARK IS '비고';

-- 초기 시드 데이터 삽입
INSERT INTO IQC_ITEM_POOL (ID, ITEM_CODE, ITEM_NAME, JUDGE_METHOD, CRITERIA, LSL, USL, UNIT)
VALUES (SYS_GUID(), 'IQC-001', '외관검사(전선)', 'VISUAL', '이물/손상 없을것', NULL, NULL, NULL);
INSERT INTO IQC_ITEM_POOL (ID, ITEM_CODE, ITEM_NAME, JUDGE_METHOD, CRITERIA, LSL, USL, UNIT)
VALUES (SYS_GUID(), 'IQC-002', '도체저항(소선)', 'MEASURE', '규격 이내', 20, 26, 'Ω/km');
INSERT INTO IQC_ITEM_POOL (ID, ITEM_CODE, ITEM_NAME, JUDGE_METHOD, CRITERIA, LSL, USL, UNIT)
VALUES (SYS_GUID(), 'IQC-003', '피복두께', 'MEASURE', '규격 이내', 0.4, 0.6, 'mm');
INSERT INTO IQC_ITEM_POOL (ID, ITEM_CODE, ITEM_NAME, JUDGE_METHOD, CRITERIA, LSL, USL, UNIT)
VALUES (SYS_GUID(), 'IQC-004', '외관검사(단자)', 'VISUAL', '변형/부식 없을것', NULL, NULL, NULL);
INSERT INTO IQC_ITEM_POOL (ID, ITEM_CODE, ITEM_NAME, JUDGE_METHOD, CRITERIA, LSL, USL, UNIT)
VALUES (SYS_GUID(), 'IQC-005', '도금두께', 'MEASURE', '규격 이내', 0.5, 1.2, 'μm');
INSERT INTO IQC_ITEM_POOL (ID, ITEM_CODE, ITEM_NAME, JUDGE_METHOD, CRITERIA, LSL, USL, UNIT)
VALUES (SYS_GUID(), 'IQC-006', '삽입력', 'MEASURE', '규격 이내', 5, 20, 'N');
INSERT INTO IQC_ITEM_POOL (ID, ITEM_CODE, ITEM_NAME, JUDGE_METHOD, CRITERIA, LSL, USL, UNIT)
VALUES (SYS_GUID(), 'IQC-007', '외관검사(커넥터)', 'VISUAL', '크랙/변형 없을것', NULL, NULL, NULL);
INSERT INTO IQC_ITEM_POOL (ID, ITEM_CODE, ITEM_NAME, JUDGE_METHOD, CRITERIA, LSL, USL, UNIT)
VALUES (SYS_GUID(), 'IQC-008', '치수검사', 'MEASURE', '규격 이내', 19.8, 20.2, 'mm');
INSERT INTO IQC_ITEM_POOL (ID, ITEM_CODE, ITEM_NAME, JUDGE_METHOD, CRITERIA, LSL, USL, UNIT)
VALUES (SYS_GUID(), 'IQC-009', '유효기한확인', 'VISUAL', '제조일 기준 유효기간 이내', NULL, NULL, NULL);
INSERT INTO IQC_ITEM_POOL (ID, ITEM_CODE, ITEM_NAME, JUDGE_METHOD, CRITERIA, LSL, USL, UNIT)
VALUES (SYS_GUID(), 'IQC-010', '점도측정', 'MEASURE', '규격 이내', 200, 400, 'cP');
INSERT INTO IQC_ITEM_POOL (ID, ITEM_CODE, ITEM_NAME, JUDGE_METHOD, CRITERIA, LSL, USL, UNIT)
VALUES (SYS_GUID(), 'IQC-011', '도체저항(대선)', 'MEASURE', '규격 이내', 4.5, 6.5, 'Ω/km');
INSERT INTO IQC_ITEM_POOL (ID, ITEM_CODE, ITEM_NAME, JUDGE_METHOD, CRITERIA, LSL, USL, UNIT)
VALUES (SYS_GUID(), 'IQC-012', '편조상태검사', 'VISUAL', '편조 풀림/손상 없을것', NULL, NULL, NULL);
INSERT INTO IQC_ITEM_POOL (ID, ITEM_CODE, ITEM_NAME, JUDGE_METHOD, CRITERIA, LSL, USL, UNIT)
VALUES (SYS_GUID(), 'IQC-013', '도체저항(중선)', 'MEASURE', '규격 이내', 12, 16, 'Ω/km');
INSERT INTO IQC_ITEM_POOL (ID, ITEM_CODE, ITEM_NAME, JUDGE_METHOD, CRITERIA, LSL, USL, UNIT)
VALUES (SYS_GUID(), 'IQC-014', '내전압시험', 'MEASURE', '절연파괴 없을것', 1000, NULL, 'V');

COMMIT;
