-- ============================================================
-- Phase 3 (자재관리) + Phase 4 (생산관리) DDL
-- ============================================================

-- 1. JOB_ORDERS에 PARENT_ID 추가 (완제품→반제품 계층 구조)
ALTER TABLE JOB_ORDERS ADD (
  PARENT_ID VARCHAR2(36) NULL
);
COMMENT ON COLUMN JOB_ORDERS.PARENT_ID IS '상위 작업지시 ID (반제품 자동생성 시)';

-- 자기참조 FK (선택사항)
-- ALTER TABLE JOB_ORDERS ADD CONSTRAINT FK_JOB_ORDER_PARENT
--   FOREIGN KEY (PARENT_ID) REFERENCES JOB_ORDERS(ID);

CREATE INDEX IDX_JOB_ORDERS_PARENT ON JOB_ORDERS(PARENT_ID);

-- 2. 반제품 샘플검사 결과 테이블 (낱개단위 측정값 저장)
CREATE TABLE SAMPLE_INSPECT_RESULTS (
  ID              VARCHAR2(36) DEFAULT SYS_GUID() PRIMARY KEY,
  JOB_ORDER_ID    VARCHAR2(36) NOT NULL,
  INSPECT_DATE    DATE         NOT NULL,
  INSPECTOR_NAME  VARCHAR2(100) NOT NULL,
  INSPECT_TYPE    VARCHAR2(50),
  SAMPLE_NO       NUMBER(10)   NOT NULL,
  MEASURED_VALUE  VARCHAR2(100),
  SPEC_UPPER      VARCHAR2(50),
  SPEC_LOWER      VARCHAR2(50),
  PASS_YN         VARCHAR2(1)  DEFAULT 'Y',
  REMARK          VARCHAR2(500),
  COMPANY         VARCHAR2(255),
  PLANT_CD        VARCHAR2(255),
  CREATED_BY      VARCHAR2(255),
  CREATED_AT      TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE SAMPLE_INSPECT_RESULTS IS '반제품 샘플검사 결과 (낱개단위)';
COMMENT ON COLUMN SAMPLE_INSPECT_RESULTS.JOB_ORDER_ID IS '작업지시 ID (FK)';
COMMENT ON COLUMN SAMPLE_INSPECT_RESULTS.INSPECT_DATE IS '검사일';
COMMENT ON COLUMN SAMPLE_INSPECT_RESULTS.INSPECTOR_NAME IS '검사자명';
COMMENT ON COLUMN SAMPLE_INSPECT_RESULTS.INSPECT_TYPE IS '검사 유형 (외관/치수/전기 등)';
COMMENT ON COLUMN SAMPLE_INSPECT_RESULTS.SAMPLE_NO IS '샘플 번호 (1, 2, 3...)';
COMMENT ON COLUMN SAMPLE_INSPECT_RESULTS.MEASURED_VALUE IS '측정값';
COMMENT ON COLUMN SAMPLE_INSPECT_RESULTS.SPEC_UPPER IS '규격 상한치';
COMMENT ON COLUMN SAMPLE_INSPECT_RESULTS.SPEC_LOWER IS '규격 하한치';
COMMENT ON COLUMN SAMPLE_INSPECT_RESULTS.PASS_YN IS '합불 판정 (Y/N)';

CREATE INDEX IDX_SAMPLE_INSPECT_JO ON SAMPLE_INSPECT_RESULTS(JOB_ORDER_ID);
CREATE INDEX IDX_SAMPLE_INSPECT_DATE ON SAMPLE_INSPECT_RESULTS(INSPECT_DATE);
CREATE INDEX IDX_SAMPLE_INSPECT_PASS ON SAMPLE_INSPECT_RESULTS(PASS_YN);
