-- ============================================================
-- 설비 BOM 관리 테이블 DDL
-- EQUIP_BOM_ITEMS: 설비 BOM 품목 마스터 (부품/소모품)
-- EQUIP_BOM_RELS: 설비와 BOM 품목의 연결 관계
-- ============================================================

-- ------------------------------------------------------------
-- 1. EQUIP_BOM_ITEMS: BOM 품목 마스터
-- ------------------------------------------------------------
CREATE TABLE EQUIP_BOM_ITEMS (
    ID              VARCHAR2(36) PRIMARY KEY,
    ITEM_CODE       VARCHAR2(50) NOT NULL UNIQUE,
    ITEM_NAME       VARCHAR2(200) NOT NULL,
    ITEM_TYPE       VARCHAR2(20) DEFAULT 'PART' NOT NULL,  -- PART: 부품, CONSUMABLE: 소모품
    SPEC            VARCHAR2(200),
    MAKER           VARCHAR2(100),
    UNIT            VARCHAR2(20) DEFAULT 'EA',
    UNIT_PRICE      NUMBER(15, 2),
    REPLACEMENT_CYCLE NUMBER(5),  -- 교체 주기 (일)
    STOCK_QTY       NUMBER(10, 2) DEFAULT 0,
    SAFETY_STOCK    NUMBER(10, 2) DEFAULT 0,
    USE_YN          VARCHAR2(1) DEFAULT 'Y' NOT NULL,
    COMPANY         VARCHAR2(50),
    PLANT_CD        VARCHAR2(50),
    CREATED_BY      VARCHAR2(50),
    UPDATED_BY      VARCHAR2(50),
    CREATED_AT      TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT      TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    DELETED_AT      TIMESTAMP
);

-- 인덱스 생성
CREATE INDEX IDX_EQUIP_BOM_ITEMS_TYPE ON EQUIP_BOM_ITEMS(ITEM_TYPE);
CREATE INDEX IDX_EQUIP_BOM_ITEMS_USE ON EQUIP_BOM_ITEMS(USE_YN);
CREATE INDEX IDX_EQUIP_BOM_ITEMS_CODE ON EQUIP_BOM_ITEMS(ITEM_CODE);

-- 테이블 코멘트
COMMENT ON TABLE EQUIP_BOM_ITEMS IS '설비 BOM 품목 마스터';
COMMENT ON COLUMN EQUIP_BOM_ITEMS.ID IS '고유 ID (UUID)';
COMMENT ON COLUMN EQUIP_BOM_ITEMS.ITEM_CODE IS '품목 코드';
COMMENT ON COLUMN EQUIP_BOM_ITEMS.ITEM_NAME IS '품목명';
COMMENT ON COLUMN EQUIP_BOM_ITEMS.ITEM_TYPE IS '품목 유형 (PART: 부품, CONSUMABLE: 소모품)';
COMMENT ON COLUMN EQUIP_BOM_ITEMS.SPEC IS '규격';
COMMENT ON COLUMN EQUIP_BOM_ITEMS.MAKER IS '제조사';
COMMENT ON COLUMN EQUIP_BOM_ITEMS.UNIT IS '단위';
COMMENT ON COLUMN EQUIP_BOM_ITEMS.UNIT_PRICE IS '단가';
COMMENT ON COLUMN EQUIP_BOM_ITEMS.REPLACEMENT_CYCLE IS '교체 주기 (일)';
COMMENT ON COLUMN EQUIP_BOM_ITEMS.STOCK_QTY IS '현재 재고 수량';
COMMENT ON COLUMN EQUIP_BOM_ITEMS.SAFETY_STOCK IS '안전 재고 수량';
COMMENT ON COLUMN EQUIP_BOM_ITEMS.USE_YN IS '사용 여부 (Y/N)';

-- ------------------------------------------------------------
-- 2. EQUIP_BOM_RELS: 설비-BOM 연결 테이블
-- ------------------------------------------------------------
CREATE TABLE EQUIP_BOM_RELS (
    ID              VARCHAR2(36) PRIMARY KEY,
    EQUIP_ID        VARCHAR2(36) NOT NULL,
    BOM_ITEM_ID     VARCHAR2(36) NOT NULL,
    QUANTITY        NUMBER(10, 2) DEFAULT 1 NOT NULL,
    INSTALL_DATE    DATE,
    EXPIRE_DATE     DATE,  -- 유효기한 (소모품용)
    REMARK          VARCHAR2(500),
    USE_YN          VARCHAR2(1) DEFAULT 'Y' NOT NULL,
    COMPANY         VARCHAR2(50),
    PLANT_CD        VARCHAR2(50),
    CREATED_BY      VARCHAR2(50),
    UPDATED_BY      VARCHAR2(50),
    CREATED_AT      TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT      TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    DELETED_AT      TIMESTAMP,
    
    -- 외래키 제약
    CONSTRAINT FK_EQUIP_BOM_RELS_EQUIP 
        FOREIGN KEY (EQUIP_ID) REFERENCES EQUIP_MASTERS(ID),
    CONSTRAINT FK_EQUIP_BOM_RELS_ITEM 
        FOREIGN KEY (BOM_ITEM_ID) REFERENCES EQUIP_BOM_ITEMS(ID)
);

-- 인덱스 생성
CREATE INDEX IDX_EQUIP_BOM_RELS_EQUIP ON EQUIP_BOM_RELS(EQUIP_ID);
CREATE INDEX IDX_EQUIP_BOM_RELS_ITEM ON EQUIP_BOM_RELS(BOM_ITEM_ID);
CREATE INDEX IDX_EQUIP_BOM_RELS_USE ON EQUIP_BOM_RELS(USE_YN);

-- 테이블 코멘트
COMMENT ON TABLE EQUIP_BOM_RELS IS '설비-BOM 품목 연결 관계';
COMMENT ON COLUMN EQUIP_BOM_RELS.ID IS '고유 ID (UUID)';
COMMENT ON COLUMN EQUIP_BOM_RELS.EQUIP_ID IS '설비 ID (FK)';
COMMENT ON COLUMN EQUIP_BOM_RELS.BOM_ITEM_ID IS 'BOM 품목 ID (FK)';
COMMENT ON COLUMN EQUIP_BOM_RELS.QUANTITY IS '필요 수량';
COMMENT ON COLUMN EQUIP_BOM_RELS.INSTALL_DATE IS '설치일';
COMMENT ON COLUMN EQUIP_BOM_RELS.EXPIRE_DATE IS '유효기한 (소모품)';
COMMENT ON COLUMN EQUIP_BOM_RELS.REMARK IS '비고';
COMMENT ON COLUMN EQUIP_BOM_RELS.USE_YN IS '사용 여부 (Y/N)';

-- ------------------------------------------------------------
-- 3. 트리거: UPDATED_AT 자동 갱신
-- ------------------------------------------------------------
CREATE OR REPLACE TRIGGER TRG_EQUIP_BOM_ITEMS_UPD
    BEFORE UPDATE ON EQUIP_BOM_ITEMS
    FOR EACH ROW
BEGIN
    :NEW.UPDATED_AT := CURRENT_TIMESTAMP;
END;
/

CREATE OR REPLACE TRIGGER TRG_EQUIP_BOM_RELS_UPD
    BEFORE UPDATE ON EQUIP_BOM_RELS
    FOR EACH ROW
BEGIN
    :NEW.UPDATED_AT := CURRENT_TIMESTAMP;
END;
/

-- ------------------------------------------------------------
-- 4. 시드 데이터 (예시)
-- ------------------------------------------------------------
-- BOM 품목 예시 데이터
INSERT INTO EQUIP_BOM_ITEMS (ID, ITEM_CODE, ITEM_NAME, ITEM_TYPE, SPEC, MAKER, UNIT, UNIT_PRICE, REPLACEMENT_CYCLE, SAFETY_STOCK, USE_YN)
VALUES 
    (SYS_GUID(), 'PART-001', '커팅 블레이드', 'PART', '100x50x2mm', '日本特殊鋼', 'EA', 150000, 90, 2, 'Y');

INSERT INTO EQUIP_BOM_ITEMS (ID, ITEM_CODE, ITEM_NAME, ITEM_TYPE, SPEC, MAKER, UNIT, UNIT_PRICE, REPLACEMENT_CYCLE, SAFETY_STOCK, USE_YN)
VALUES 
    (SYS_GUID(), 'PART-002', '압착 다이스', 'PART', 'AWG 20-22', 'TE Connectivity', 'SET', 250000, 180, 1, 'Y');

INSERT INTO EQUIP_BOM_ITEMS (ID, ITEM_CODE, ITEM_NAME, ITEM_TYPE, SPEC, MAKER, UNIT, UNIT_PRICE, REPLACEMENT_CYCLE, SAFETY_STOCK, USE_YN)
VALUES 
    (SYS_GUID(), 'CONS-001', '그리스', 'CONSUMABLE', 'NLGI #2', 'SKF', 'CAN', 35000, 30, 5, 'Y');

INSERT INTO EQUIP_BOM_ITEMS (ID, ITEM_CODE, ITEM_NAME, ITEM_TYPE, SPEC, MAKER, UNIT, UNIT_PRICE, REPLACEMENT_CYCLE, SAFETY_STOCK, USE_YN)
VALUES 
    (SYS_GUID(), 'CONS-002', '클리닝 와이프', 'CONSUMABLE', '300x300mm 무지', '3M', 'BOX', 25000, 14, 10, 'Y');

COMMIT;
