-- 창고 로케이션(세부위치) 테이블 DDL
-- 실행환경: Oracle DB

CREATE TABLE WAREHOUSE_LOCATIONS (
  ID           VARCHAR2(36)  DEFAULT SYS_GUID() PRIMARY KEY,
  WAREHOUSE_ID VARCHAR2(255) NOT NULL,
  LOCATION_CODE VARCHAR2(50) NOT NULL,
  LOCATION_NAME VARCHAR2(100) NOT NULL,
  ZONE          VARCHAR2(50),
  ROW_NO        VARCHAR2(50),
  COL_NO        VARCHAR2(50),
  LEVEL_NO      VARCHAR2(50),
  USE_YN        VARCHAR2(1)  DEFAULT 'Y',
  REMARK        VARCHAR2(500),
  COMPANY       VARCHAR2(50),
  PLANT_CD      VARCHAR2(50),
  CREATED_AT    TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
  UPDATED_AT    TIMESTAMP    DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX UQ_WH_LOC_CODE ON WAREHOUSE_LOCATIONS (WAREHOUSE_ID, LOCATION_CODE);

COMMENT ON TABLE  WAREHOUSE_LOCATIONS IS '창고 로케이션(세부위치)';
COMMENT ON COLUMN WAREHOUSE_LOCATIONS.WAREHOUSE_ID  IS '창고 ID (FK → WAREHOUSES.ID)';
COMMENT ON COLUMN WAREHOUSE_LOCATIONS.LOCATION_CODE IS '로케이션 코드 (창고 내 유일)';
COMMENT ON COLUMN WAREHOUSE_LOCATIONS.LOCATION_NAME IS '로케이션명';
COMMENT ON COLUMN WAREHOUSE_LOCATIONS.ZONE          IS '존(구역) - A, B, C 등';
COMMENT ON COLUMN WAREHOUSE_LOCATIONS.ROW_NO        IS '행 번호';
COMMENT ON COLUMN WAREHOUSE_LOCATIONS.COL_NO        IS '열 번호';
COMMENT ON COLUMN WAREHOUSE_LOCATIONS.LEVEL_NO      IS '단(층) 번호';
COMMENT ON COLUMN WAREHOUSE_LOCATIONS.USE_YN        IS '사용여부';
