-- =============================================================
-- MAT_RECEIVINGS 테이블 생성 + MAT_ISSUES.ISSUE_NO 컬럼 추가
-- 실행 대상: Oracle DB
-- =============================================================

-- 1) MAT_RECEIVINGS 테이블 생성
CREATE TABLE MAT_RECEIVINGS (
  ID              VARCHAR2(50) DEFAULT SYS_GUID() PRIMARY KEY,
  RECEIVE_NO      VARCHAR2(50)  NOT NULL,
  LOT_ID          VARCHAR2(50)  NOT NULL,
  PART_ID         VARCHAR2(50)  NOT NULL,
  QTY             NUMBER(10)    NOT NULL,
  WAREHOUSE_CODE  VARCHAR2(50)  NOT NULL,
  RECEIVE_DATE    TIMESTAMP     DEFAULT CURRENT_TIMESTAMP,
  WORKER_ID       VARCHAR2(50),
  REMARK          VARCHAR2(500),
  STATUS          VARCHAR2(20)  DEFAULT 'DONE',
  COMPANY         VARCHAR2(50),
  PLANT_CD        VARCHAR2(50),
  CREATED_BY      VARCHAR2(50),
  CREATED_AT      TIMESTAMP     DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IDX_MAT_RECV_NO   ON MAT_RECEIVINGS(RECEIVE_NO);
CREATE INDEX IDX_MAT_RECV_LOT  ON MAT_RECEIVINGS(LOT_ID);
CREATE INDEX IDX_MAT_RECV_PART ON MAT_RECEIVINGS(PART_ID);
CREATE INDEX IDX_MAT_RECV_DATE ON MAT_RECEIVINGS(RECEIVE_DATE);

-- 2) MAT_ISSUES 테이블에 ISSUE_NO 컬럼 추가
ALTER TABLE MAT_ISSUES ADD ISSUE_NO VARCHAR2(50);
CREATE INDEX IDX_MAT_ISSUE_NO ON MAT_ISSUES(ISSUE_NO);
