-- ============================================================
-- 라우팅 공정 상세정보 + 공정 대분류 + 품목 마스터 보강 DDL
-- Phase 2.2 + 2.3 구현
-- ============================================================

-- 1) PROCESS_MAPS: 공정 상세 파라미터 컬럼 추가
ALTER TABLE PROCESS_MAPS ADD WIRE_LENGTH    NUMBER(10,2);
ALTER TABLE PROCESS_MAPS ADD STRIP_LENGTH   NUMBER(10,2);
ALTER TABLE PROCESS_MAPS ADD CRIMP_HEIGHT   NUMBER(10,3);
ALTER TABLE PROCESS_MAPS ADD CRIMP_WIDTH    NUMBER(10,3);
ALTER TABLE PROCESS_MAPS ADD WELD_CONDITION VARCHAR2(500);
ALTER TABLE PROCESS_MAPS ADD PROCESS_PARAMS VARCHAR2(2000);

COMMENT ON COLUMN PROCESS_MAPS.WIRE_LENGTH    IS '전선길이 (mm)';
COMMENT ON COLUMN PROCESS_MAPS.STRIP_LENGTH   IS '탈피길이 (mm)';
COMMENT ON COLUMN PROCESS_MAPS.CRIMP_HEIGHT   IS '압착높이 (mm)';
COMMENT ON COLUMN PROCESS_MAPS.CRIMP_WIDTH    IS '압착폭 (mm)';
COMMENT ON COLUMN PROCESS_MAPS.WELD_CONDITION IS '융착조건 (온도/시간/압력 등)';
COMMENT ON COLUMN PROCESS_MAPS.PROCESS_PARAMS IS '기타 공정 파라미터 (JSON 형식)';

-- 2) PROCESS_MASTERS: 공정 대분류 + 샘플검사 필요여부 추가
ALTER TABLE PROCESS_MASTERS ADD PROCESS_CATEGORY  VARCHAR2(50);
ALTER TABLE PROCESS_MASTERS ADD SAMPLE_INSPECT_YN VARCHAR2(1) DEFAULT 'N' NOT NULL;

COMMENT ON COLUMN PROCESS_MASTERS.PROCESS_CATEGORY  IS '공정 대분류 (ASSY-조립, INSP-검사, CUTTING-절단 등)';
COMMENT ON COLUMN PROCESS_MASTERS.SAMPLE_INSPECT_YN IS '샘플검사 필요여부 (Y/N)';

CREATE INDEX IDX_PM_CATEGORY ON PROCESS_MASTERS (PROCESS_CATEGORY);

-- 3) PART_MASTERS: 포장단위 + 적재로케이션 추가
ALTER TABLE PART_MASTERS ADD PACK_UNIT         VARCHAR2(50);
ALTER TABLE PART_MASTERS ADD STORAGE_LOCATION  VARCHAR2(100);

COMMENT ON COLUMN PART_MASTERS.PACK_UNIT        IS '포장단위 (EA, BOX, BAG 등)';
COMMENT ON COLUMN PART_MASTERS.STORAGE_LOCATION IS '적재 로케이션 (창고 내 위치)';
