-- =============================================================
-- OQC (출하검사) 테이블 DDL
-- 목적: 출하 전 제품 품질 검증을 위한 OQC 의뢰/박스 연결 테이블
-- =============================================================

-- 1) OQC 의뢰 마스터
CREATE TABLE OQC_REQUESTS (
  ID VARCHAR2(36) DEFAULT SYS_GUID() PRIMARY KEY,
  REQUEST_NO VARCHAR2(50) NOT NULL UNIQUE,
  PART_ID VARCHAR2(36) NOT NULL,
  CUSTOMER VARCHAR2(100),
  REQUEST_DATE DATE NOT NULL,
  TOTAL_BOX_COUNT NUMBER(10) DEFAULT 0,
  TOTAL_QTY NUMBER(10) DEFAULT 0,
  SAMPLE_SIZE NUMBER(10),
  STATUS VARCHAR2(50) DEFAULT 'PENDING',
  RESULT VARCHAR2(50),
  DETAILS CLOB,
  INSPECTOR_NAME VARCHAR2(100),
  INSPECT_DATE TIMESTAMP,
  REMARK VARCHAR2(500),
  COMPANY VARCHAR2(255),
  PLANT_CD VARCHAR2(255),
  CREATED_BY VARCHAR2(255),
  UPDATED_BY VARCHAR2(255),
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  DELETED_AT TIMESTAMP
);

CREATE INDEX IDX_OQC_REQ_STATUS ON OQC_REQUESTS (STATUS);
CREATE INDEX IDX_OQC_REQ_PART ON OQC_REQUESTS (PART_ID);
CREATE INDEX IDX_OQC_REQ_DATE ON OQC_REQUESTS (REQUEST_DATE);

-- 2) OQC 의뢰-박스 연결
CREATE TABLE OQC_REQUEST_BOXES (
  ID VARCHAR2(36) DEFAULT SYS_GUID() PRIMARY KEY,
  OQC_REQUEST_ID VARCHAR2(36) NOT NULL,
  BOX_ID VARCHAR2(36) NOT NULL,
  BOX_NO VARCHAR2(50),
  QTY NUMBER(10) DEFAULT 0,
  IS_SAMPLE VARCHAR2(1) DEFAULT 'N',
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IDX_OQC_RBOX_REQ ON OQC_REQUEST_BOXES (OQC_REQUEST_ID);
CREATE INDEX IDX_OQC_RBOX_BOX ON OQC_REQUEST_BOXES (BOX_ID);

-- 3) BoxMaster에 OQC 상태 컬럼 추가
ALTER TABLE BOX_MASTERS ADD (OQC_STATUS VARCHAR2(50));
