-- fix_product_tables_id.sql
-- PRODUCT_TRANSACTIONS, PRODUCT_STOCKS 테이블의 ID 컬럼을
-- RAW(16) → VARCHAR2(36)으로 변경 (ORA-01465 해결)
-- 두 테이블 모두 데이터 없음 확인 후 실행

-- 1. PRODUCT_TRANSACTIONS 재생성
DROP TABLE PRODUCT_TRANSACTIONS CASCADE CONSTRAINTS PURGE;

CREATE TABLE PRODUCT_TRANSACTIONS (
  ID              VARCHAR2(36)  DEFAULT SYS_GUID() NOT NULL,
  TRANS_NO        VARCHAR2(50)  NOT NULL,
  TRANS_TYPE      VARCHAR2(50)  NOT NULL,
  TRANS_DATE      TIMESTAMP(6)  DEFAULT CURRENT_TIMESTAMP,
  FROM_WAREHOUSE_ID VARCHAR2(50),
  TO_WAREHOUSE_ID VARCHAR2(50),
  PART_ID         VARCHAR2(50)  NOT NULL,
  PART_TYPE       VARCHAR2(10),
  LOT_ID          VARCHAR2(50),
  JOB_ORDER_ID    VARCHAR2(50),
  PROCESS_CODE    VARCHAR2(50),
  QTY             NUMBER        NOT NULL,
  UNIT_PRICE      NUMBER(12,4),
  TOTAL_AMOUNT    NUMBER(14,2),
  REF_TYPE        VARCHAR2(50),
  REF_ID          VARCHAR2(50),
  CANCEL_REF_ID   VARCHAR2(50),
  WORKER_ID       VARCHAR2(50),
  REMARK          VARCHAR2(500),
  STATUS          VARCHAR2(20)  DEFAULT 'DONE',
  COMPANY         VARCHAR2(50),
  PLANT_CD        VARCHAR2(50),
  CREATED_BY      VARCHAR2(50),
  UPDATED_BY      VARCHAR2(50),
  CREATED_AT      TIMESTAMP(6)  DEFAULT CURRENT_TIMESTAMP,
  UPDATED_AT      TIMESTAMP(6)  DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT PK_PRODUCT_TRANSACTIONS PRIMARY KEY (ID),
  CONSTRAINT UQ_PRODUCT_TX_TRANSNO UNIQUE (TRANS_NO)
);

CREATE INDEX IDX_PROD_TX_TYPE ON PRODUCT_TRANSACTIONS (TRANS_TYPE);
CREATE INDEX IDX_PROD_TX_DATE ON PRODUCT_TRANSACTIONS (TRANS_DATE);
CREATE INDEX IDX_PROD_TX_FROM_WH ON PRODUCT_TRANSACTIONS (FROM_WAREHOUSE_ID);
CREATE INDEX IDX_PROD_TX_TO_WH ON PRODUCT_TRANSACTIONS (TO_WAREHOUSE_ID);
CREATE INDEX IDX_PROD_TX_PART ON PRODUCT_TRANSACTIONS (PART_ID);
CREATE INDEX IDX_PROD_TX_LOT ON PRODUCT_TRANSACTIONS (LOT_ID);
CREATE INDEX IDX_PROD_TX_REF ON PRODUCT_TRANSACTIONS (REF_TYPE, REF_ID);
CREATE INDEX IDX_PROD_TX_CANCEL ON PRODUCT_TRANSACTIONS (CANCEL_REF_ID);

-- 2. PRODUCT_STOCKS 재생성
DROP TABLE PRODUCT_STOCKS CASCADE CONSTRAINTS PURGE;

CREATE TABLE PRODUCT_STOCKS (
  ID              VARCHAR2(36)  DEFAULT SYS_GUID() NOT NULL,
  WAREHOUSE_CODE  VARCHAR2(50)  NOT NULL,
  LOCATION_CODE   VARCHAR2(50),
  PART_ID         VARCHAR2(50)  NOT NULL,
  PART_TYPE       VARCHAR2(10)  NOT NULL,
  LOT_ID          VARCHAR2(50),
  JOB_ORDER_ID    VARCHAR2(50),
  PROCESS_CODE    VARCHAR2(50),
  QTY             NUMBER        DEFAULT 0,
  RESERVED_QTY    NUMBER        DEFAULT 0,
  AVAILABLE_QTY   NUMBER        DEFAULT 0,
  STATUS          VARCHAR2(20)  DEFAULT 'NORMAL',
  HOLD_REASON     VARCHAR2(500),
  HOLD_AT         TIMESTAMP(6),
  HOLD_BY         VARCHAR2(50),
  LAST_COUNT      TIMESTAMP(6),
  COMPANY         VARCHAR2(50),
  PLANT_CD        VARCHAR2(50),
  CREATED_BY      VARCHAR2(50),
  UPDATED_BY      VARCHAR2(50),
  CREATED_AT      TIMESTAMP(6)  DEFAULT CURRENT_TIMESTAMP,
  UPDATED_AT      TIMESTAMP(6)  DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT PK_PRODUCT_STOCKS PRIMARY KEY (ID),
  CONSTRAINT UQ_PROD_STOCK_WH_PART_LOT UNIQUE (WAREHOUSE_CODE, PART_ID, LOT_ID)
);

CREATE INDEX IDX_PROD_STK_WH ON PRODUCT_STOCKS (WAREHOUSE_CODE);
CREATE INDEX IDX_PROD_STK_PART ON PRODUCT_STOCKS (PART_ID);
CREATE INDEX IDX_PROD_STK_TYPE ON PRODUCT_STOCKS (PART_TYPE);
