DROP SEQUENCE SEQ_MAT_ARRIVALS
/
CREATE SEQUENCE SEQ_MAT_ARRIVALS START WITH 1 INCREMENT BY 1 NOCACHE
/
DROP SEQUENCE SEQ_IQC_LOGS
/
CREATE SEQUENCE SEQ_IQC_LOGS START WITH 1 INCREMENT BY 1 NOCACHE
/
DROP SEQUENCE SEQ_MAT_RECEIVINGS
/
CREATE SEQUENCE SEQ_MAT_RECEIVINGS START WITH 1 INCREMENT BY 1 NOCACHE
/
DROP SEQUENCE SEQ_STOCK_TRANSACTIONS
/
CREATE SEQUENCE SEQ_STOCK_TRANSACTIONS START WITH 1 INCREMENT BY 1 NOCACHE
/
DROP SEQUENCE SEQ_MAT_ISSUES
/
CREATE SEQUENCE SEQ_MAT_ISSUES START WITH 1 INCREMENT BY 1 NOCACHE
/
DROP SEQUENCE SEQ_MAT_ISSUE_REQUESTS
/
CREATE SEQUENCE SEQ_MAT_ISSUE_REQUESTS START WITH 1 INCREMENT BY 1 NOCACHE
/
DROP SEQUENCE SEQ_MAT_ISSUE_REQ_ITEMS
/
CREATE SEQUENCE SEQ_MAT_ISSUE_REQ_ITEMS START WITH 1 INCREMENT BY 1 NOCACHE
/
DROP SEQUENCE SEQ_INV_ADJ_LOGS
/
CREATE SEQUENCE SEQ_INV_ADJ_LOGS START WITH 1 INCREMENT BY 1 NOCACHE
/
DROP SEQUENCE MAT_UID_SEQ
/
CREATE SEQUENCE MAT_UID_SEQ START WITH 1 INCREMENT BY 1 NOCACHE
/
