-- PROD_PLANS 시드 데이터
-- 2026년 1~6월, 완제품 2종(FG-DH-001, FG-EH-001), 고객 2사

-- 2026-01 (CONFIRMED)
INSERT INTO PROD_PLANS (PLAN_NO, PLAN_MONTH, ITEM_CODE, ITEM_TYPE, PLAN_QTY, ORDER_QTY, CUSTOMER, LINE_CODE, PRIORITY, STATUS, REMARK, COMPANY, PLANT_CD, CREATED_BY, UPDATED_BY, CREATED_AT, UPDATED_AT)
VALUES ('PP-202601-001', '2026-01', 'FG-DH-001', 'FINISHED', 5000, 4800, 'CUS-001', 'LINE-03', 1, 'CONFIRMED', '1월 도어 하네스 생산계획', '40', 'VNHNS', 'admin', 'admin', SYSTIMESTAMP, SYSTIMESTAMP);

INSERT INTO PROD_PLANS (PLAN_NO, PLAN_MONTH, ITEM_CODE, ITEM_TYPE, PLAN_QTY, ORDER_QTY, CUSTOMER, LINE_CODE, PRIORITY, STATUS, REMARK, COMPANY, PLANT_CD, CREATED_BY, UPDATED_BY, CREATED_AT, UPDATED_AT)
VALUES ('PP-202601-002', '2026-01', 'FG-EH-001', 'FINISHED', 3000, 2900, 'CUS-001', 'LINE-04', 2, 'CONFIRMED', '1월 엔진룸 하네스 생산계획', '40', 'VNHNS', 'admin', 'admin', SYSTIMESTAMP, SYSTIMESTAMP);

INSERT INTO PROD_PLANS (PLAN_NO, PLAN_MONTH, ITEM_CODE, ITEM_TYPE, PLAN_QTY, ORDER_QTY, CUSTOMER, LINE_CODE, PRIORITY, STATUS, REMARK, COMPANY, PLANT_CD, CREATED_BY, UPDATED_BY, CREATED_AT, UPDATED_AT)
VALUES ('PP-202601-003', '2026-01', 'FG-DH-001', 'FINISHED', 2000, 1800, 'CUS-002', 'LINE-03', 3, 'CONFIRMED', '1월 기아향 도어 하네스', '40', 'VNHNS', 'admin', 'admin', SYSTIMESTAMP, SYSTIMESTAMP);

-- 2026-02 (CONFIRMED)
INSERT INTO PROD_PLANS (PLAN_NO, PLAN_MONTH, ITEM_CODE, ITEM_TYPE, PLAN_QTY, ORDER_QTY, CUSTOMER, LINE_CODE, PRIORITY, STATUS, REMARK, COMPANY, PLANT_CD, CREATED_BY, UPDATED_BY, CREATED_AT, UPDATED_AT)
VALUES ('PP-202602-001', '2026-02', 'FG-DH-001', 'FINISHED', 5500, 5200, 'CUS-001', 'LINE-03', 1, 'CONFIRMED', '2월 도어 하네스 생산계획', '40', 'VNHNS', 'admin', 'admin', SYSTIMESTAMP, SYSTIMESTAMP);

INSERT INTO PROD_PLANS (PLAN_NO, PLAN_MONTH, ITEM_CODE, ITEM_TYPE, PLAN_QTY, ORDER_QTY, CUSTOMER, LINE_CODE, PRIORITY, STATUS, REMARK, COMPANY, PLANT_CD, CREATED_BY, UPDATED_BY, CREATED_AT, UPDATED_AT)
VALUES ('PP-202602-002', '2026-02', 'FG-EH-001', 'FINISHED', 3200, 3100, 'CUS-001', 'LINE-04', 2, 'CONFIRMED', '2월 엔진룸 하네스 생산계획', '40', 'VNHNS', 'admin', 'admin', SYSTIMESTAMP, SYSTIMESTAMP);

INSERT INTO PROD_PLANS (PLAN_NO, PLAN_MONTH, ITEM_CODE, ITEM_TYPE, PLAN_QTY, ORDER_QTY, CUSTOMER, LINE_CODE, PRIORITY, STATUS, REMARK, COMPANY, PLANT_CD, CREATED_BY, UPDATED_BY, CREATED_AT, UPDATED_AT)
VALUES ('PP-202602-003', '2026-02', 'FG-EH-001', 'FINISHED', 1500, 1400, 'CUS-002', 'LINE-04', 3, 'CONFIRMED', '2월 기아향 엔진룸 하네스', '40', 'VNHNS', 'admin', 'admin', SYSTIMESTAMP, SYSTIMESTAMP);

-- 2026-03 (CONFIRMED)
INSERT INTO PROD_PLANS (PLAN_NO, PLAN_MONTH, ITEM_CODE, ITEM_TYPE, PLAN_QTY, ORDER_QTY, CUSTOMER, LINE_CODE, PRIORITY, STATUS, REMARK, COMPANY, PLANT_CD, CREATED_BY, UPDATED_BY, CREATED_AT, UPDATED_AT)
VALUES ('PP-202603-001', '2026-03', 'FG-DH-001', 'FINISHED', 6000, 5800, 'CUS-001', 'LINE-03', 1, 'CONFIRMED', '3월 도어 하네스 생산계획 (증산)', '40', 'VNHNS', 'admin', 'admin', SYSTIMESTAMP, SYSTIMESTAMP);

INSERT INTO PROD_PLANS (PLAN_NO, PLAN_MONTH, ITEM_CODE, ITEM_TYPE, PLAN_QTY, ORDER_QTY, CUSTOMER, LINE_CODE, PRIORITY, STATUS, REMARK, COMPANY, PLANT_CD, CREATED_BY, UPDATED_BY, CREATED_AT, UPDATED_AT)
VALUES ('PP-202603-002', '2026-03', 'FG-EH-001', 'FINISHED', 3500, 3300, 'CUS-001', 'LINE-04', 2, 'CONFIRMED', '3월 엔진룸 하네스 생산계획', '40', 'VNHNS', 'admin', 'admin', SYSTIMESTAMP, SYSTIMESTAMP);

INSERT INTO PROD_PLANS (PLAN_NO, PLAN_MONTH, ITEM_CODE, ITEM_TYPE, PLAN_QTY, ORDER_QTY, CUSTOMER, LINE_CODE, PRIORITY, STATUS, REMARK, COMPANY, PLANT_CD, CREATED_BY, UPDATED_BY, CREATED_AT, UPDATED_AT)
VALUES ('PP-202603-003', '2026-03', 'FG-DH-001', 'FINISHED', 2500, 2300, 'CUS-002', 'LINE-03', 3, 'CONFIRMED', '3월 기아향 도어 하네스', '40', 'VNHNS', 'admin', 'admin', SYSTIMESTAMP, SYSTIMESTAMP);

INSERT INTO PROD_PLANS (PLAN_NO, PLAN_MONTH, ITEM_CODE, ITEM_TYPE, PLAN_QTY, ORDER_QTY, CUSTOMER, LINE_CODE, PRIORITY, STATUS, REMARK, COMPANY, PLANT_CD, CREATED_BY, UPDATED_BY, CREATED_AT, UPDATED_AT)
VALUES ('PP-202603-004', '2026-03', 'FG-EH-001', 'FINISHED', 1800, 1700, 'CUS-002', 'LINE-04', 4, 'CONFIRMED', '3월 기아향 엔진룸 하네스', '40', 'VNHNS', 'admin', 'admin', SYSTIMESTAMP, SYSTIMESTAMP);

-- 2026-04 (DRAFT - 아직 확정 전)
INSERT INTO PROD_PLANS (PLAN_NO, PLAN_MONTH, ITEM_CODE, ITEM_TYPE, PLAN_QTY, ORDER_QTY, CUSTOMER, LINE_CODE, PRIORITY, STATUS, REMARK, COMPANY, PLANT_CD, CREATED_BY, UPDATED_BY, CREATED_AT, UPDATED_AT)
VALUES ('PP-202604-001', '2026-04', 'FG-DH-001', 'FINISHED', 5800, 5500, 'CUS-001', 'LINE-03', 1, 'DRAFT', '4월 도어 하네스 계획(초안)', '40', 'VNHNS', 'admin', 'admin', SYSTIMESTAMP, SYSTIMESTAMP);

INSERT INTO PROD_PLANS (PLAN_NO, PLAN_MONTH, ITEM_CODE, ITEM_TYPE, PLAN_QTY, ORDER_QTY, CUSTOMER, LINE_CODE, PRIORITY, STATUS, REMARK, COMPANY, PLANT_CD, CREATED_BY, UPDATED_BY, CREATED_AT, UPDATED_AT)
VALUES ('PP-202604-002', '2026-04', 'FG-EH-001', 'FINISHED', 3400, 3200, 'CUS-001', 'LINE-04', 2, 'DRAFT', '4월 엔진룸 하네스 계획(초안)', '40', 'VNHNS', 'admin', 'admin', SYSTIMESTAMP, SYSTIMESTAMP);

INSERT INTO PROD_PLANS (PLAN_NO, PLAN_MONTH, ITEM_CODE, ITEM_TYPE, PLAN_QTY, ORDER_QTY, CUSTOMER, LINE_CODE, PRIORITY, STATUS, REMARK, COMPANY, PLANT_CD, CREATED_BY, UPDATED_BY, CREATED_AT, UPDATED_AT)
VALUES ('PP-202604-003', '2026-04', 'FG-DH-001', 'FINISHED', 2200, 2000, 'CUS-002', 'LINE-03', 3, 'DRAFT', '4월 기아향 도어 하네스(초안)', '40', 'VNHNS', 'admin', 'admin', SYSTIMESTAMP, SYSTIMESTAMP);

-- 2026-05 (DRAFT)
INSERT INTO PROD_PLANS (PLAN_NO, PLAN_MONTH, ITEM_CODE, ITEM_TYPE, PLAN_QTY, ORDER_QTY, CUSTOMER, LINE_CODE, PRIORITY, STATUS, REMARK, COMPANY, PLANT_CD, CREATED_BY, UPDATED_BY, CREATED_AT, UPDATED_AT)
VALUES ('PP-202605-001', '2026-05', 'FG-DH-001', 'FINISHED', 6200, 0, 'CUS-001', 'LINE-03', 1, 'DRAFT', '5월 도어 하네스 계획', '40', 'VNHNS', 'admin', 'admin', SYSTIMESTAMP, SYSTIMESTAMP);

INSERT INTO PROD_PLANS (PLAN_NO, PLAN_MONTH, ITEM_CODE, ITEM_TYPE, PLAN_QTY, ORDER_QTY, CUSTOMER, LINE_CODE, PRIORITY, STATUS, REMARK, COMPANY, PLANT_CD, CREATED_BY, UPDATED_BY, CREATED_AT, UPDATED_AT)
VALUES ('PP-202605-002', '2026-05', 'FG-EH-001', 'FINISHED', 3600, 0, 'CUS-001', 'LINE-04', 2, 'DRAFT', '5월 엔진룸 하네스 계획', '40', 'VNHNS', 'admin', 'admin', SYSTIMESTAMP, SYSTIMESTAMP);

INSERT INTO PROD_PLANS (PLAN_NO, PLAN_MONTH, ITEM_CODE, ITEM_TYPE, PLAN_QTY, ORDER_QTY, CUSTOMER, LINE_CODE, PRIORITY, STATUS, REMARK, COMPANY, PLANT_CD, CREATED_BY, UPDATED_BY, CREATED_AT, UPDATED_AT)
VALUES ('PP-202605-003', '2026-05', 'FG-DH-001', 'FINISHED', 2800, 0, 'CUS-002', 'LINE-03', 3, 'DRAFT', '5월 기아향 도어 하네스', '40', 'VNHNS', 'admin', 'admin', SYSTIMESTAMP, SYSTIMESTAMP);

INSERT INTO PROD_PLANS (PLAN_NO, PLAN_MONTH, ITEM_CODE, ITEM_TYPE, PLAN_QTY, ORDER_QTY, CUSTOMER, LINE_CODE, PRIORITY, STATUS, REMARK, COMPANY, PLANT_CD, CREATED_BY, UPDATED_BY, CREATED_AT, UPDATED_AT)
VALUES ('PP-202605-004', '2026-05', 'FG-EH-001', 'FINISHED', 2000, 0, 'CUS-002', 'LINE-04', 4, 'DRAFT', '5월 기아향 엔진룸 하네스', '40', 'VNHNS', 'admin', 'admin', SYSTIMESTAMP, SYSTIMESTAMP);

-- 2026-06 (DRAFT)
INSERT INTO PROD_PLANS (PLAN_NO, PLAN_MONTH, ITEM_CODE, ITEM_TYPE, PLAN_QTY, ORDER_QTY, CUSTOMER, LINE_CODE, PRIORITY, STATUS, REMARK, COMPANY, PLANT_CD, CREATED_BY, UPDATED_BY, CREATED_AT, UPDATED_AT)
VALUES ('PP-202606-001', '2026-06', 'FG-DH-001', 'FINISHED', 5500, 0, 'CUS-001', 'LINE-03', 1, 'DRAFT', '6월 도어 하네스 계획', '40', 'VNHNS', 'admin', 'admin', SYSTIMESTAMP, SYSTIMESTAMP);

INSERT INTO PROD_PLANS (PLAN_NO, PLAN_MONTH, ITEM_CODE, ITEM_TYPE, PLAN_QTY, ORDER_QTY, CUSTOMER, LINE_CODE, PRIORITY, STATUS, REMARK, COMPANY, PLANT_CD, CREATED_BY, UPDATED_BY, CREATED_AT, UPDATED_AT)
VALUES ('PP-202606-002', '2026-06', 'FG-EH-001', 'FINISHED', 3200, 0, 'CUS-001', 'LINE-04', 2, 'DRAFT', '6월 엔진룸 하네스 계획', '40', 'VNHNS', 'admin', 'admin', SYSTIMESTAMP, SYSTIMESTAMP);

INSERT INTO PROD_PLANS (PLAN_NO, PLAN_MONTH, ITEM_CODE, ITEM_TYPE, PLAN_QTY, ORDER_QTY, CUSTOMER, LINE_CODE, PRIORITY, STATUS, REMARK, COMPANY, PLANT_CD, CREATED_BY, UPDATED_BY, CREATED_AT, UPDATED_AT)
VALUES ('PP-202606-003', '2026-06', 'FG-DH-001', 'FINISHED', 2400, 0, 'CUS-002', 'LINE-03', 3, 'DRAFT', '6월 기아향 도어 하네스', '40', 'VNHNS', 'admin', 'admin', SYSTIMESTAMP, SYSTIMESTAMP);

INSERT INTO PROD_PLANS (PLAN_NO, PLAN_MONTH, ITEM_CODE, ITEM_TYPE, PLAN_QTY, ORDER_QTY, CUSTOMER, LINE_CODE, PRIORITY, STATUS, REMARK, COMPANY, PLANT_CD, CREATED_BY, UPDATED_BY, CREATED_AT, UPDATED_AT)
VALUES ('PP-202606-004', '2026-06', 'FG-EH-001', 'FINISHED', 1600, 0, 'CUS-002', 'LINE-04', 4, 'DRAFT', '6월 기아향 엔진룸 하네스', '40', 'VNHNS', 'admin', 'admin', SYSTIMESTAMP, SYSTIMESTAMP);

COMMIT;
