-- SYS_CONFIGS 시드 데이터
-- 시스템 환경설정 초기값 INSERT
-- 실행: Oracle SQL에서 실행 후 COMMIT

-- ========== 자재관리(MATERIAL) 그룹 ==========
INSERT INTO SYS_CONFIGS (ID, CONFIG_GROUP, CONFIG_KEY, CONFIG_VALUE, CONFIG_TYPE, LABEL, DESCRIPTION, OPTIONS, SORT_ORDER, IS_ACTIVE, CREATED_AT, UPDATED_AT)
VALUES (SYS_GUID(), 'MATERIAL', 'FIFO_ENABLED', 'Y', 'BOOLEAN', '선입선출 사용', '자재 출고 시 선입선출(FIFO) 적용 여부', NULL, 1, 'Y', SYSTIMESTAMP, SYSTIMESTAMP);

INSERT INTO SYS_CONFIGS (ID, CONFIG_GROUP, CONFIG_KEY, CONFIG_VALUE, CONFIG_TYPE, LABEL, DESCRIPTION, OPTIONS, SORT_ORDER, IS_ACTIVE, CREATED_AT, UPDATED_AT)
VALUES (SYS_GUID(), 'MATERIAL', 'FIFO_CRITERIA', 'RECEIVE_DATE', 'SELECT', '선입선출 기준', '선입선출 적용 시 정렬 기준 (입고일/제조일)', '[{"value":"RECEIVE_DATE","label":"입고일 기준"},{"value":"MFG_DATE","label":"제조일 기준"}]', 2, 'Y', SYSTIMESTAMP, SYSTIMESTAMP);

INSERT INTO SYS_CONFIGS (ID, CONFIG_GROUP, CONFIG_KEY, CONFIG_VALUE, CONFIG_TYPE, LABEL, DESCRIPTION, OPTIONS, SORT_ORDER, IS_ACTIVE, CREATED_AT, UPDATED_AT)
VALUES (SYS_GUID(), 'MATERIAL', 'LONG_STOCK_CHECK', 'Y', 'BOOLEAN', '장기재고 체크', '장기재고 자재에 대한 경고 표시 여부', NULL, 3, 'Y', SYSTIMESTAMP, SYSTIMESTAMP);

INSERT INTO SYS_CONFIGS (ID, CONFIG_GROUP, CONFIG_KEY, CONFIG_VALUE, CONFIG_TYPE, LABEL, DESCRIPTION, OPTIONS, SORT_ORDER, IS_ACTIVE, CREATED_AT, UPDATED_AT)
VALUES (SYS_GUID(), 'MATERIAL', 'LONG_STOCK_DAYS', '90', 'NUMBER', '장기재고 기준일수', '장기재고로 판단하는 기준 일수', NULL, 4, 'Y', SYSTIMESTAMP, SYSTIMESTAMP);

INSERT INTO SYS_CONFIGS (ID, CONFIG_GROUP, CONFIG_KEY, CONFIG_VALUE, CONFIG_TYPE, LABEL, DESCRIPTION, OPTIONS, SORT_ORDER, IS_ACTIVE, CREATED_AT, UPDATED_AT)
VALUES (SYS_GUID(), 'MATERIAL', 'MFG_DATE_REQUIRED', 'N', 'BOOLEAN', '제조일자 필수등록', '자재 입고 시 제조일자 입력 필수 여부', NULL, 5, 'Y', SYSTIMESTAMP, SYSTIMESTAMP);

INSERT INTO SYS_CONFIGS (ID, CONFIG_GROUP, CONFIG_KEY, CONFIG_VALUE, CONFIG_TYPE, LABEL, DESCRIPTION, OPTIONS, SORT_ORDER, IS_ACTIVE, CREATED_AT, UPDATED_AT)
VALUES (SYS_GUID(), 'MATERIAL', 'SHELF_LIFE_CHECK', 'Y', 'BOOLEAN', '유수명 체크', '유효기간이 지난 자재의 출고 차단 여부', NULL, 6, 'Y', SYSTIMESTAMP, SYSTIMESTAMP);

INSERT INTO SYS_CONFIGS (ID, CONFIG_GROUP, CONFIG_KEY, CONFIG_VALUE, CONFIG_TYPE, LABEL, DESCRIPTION, OPTIONS, SORT_ORDER, IS_ACTIVE, CREATED_AT, UPDATED_AT)
VALUES (SYS_GUID(), 'MATERIAL', 'HOLD_ISSUE_BLOCK', 'Y', 'BOOLEAN', '홀드 출고 차단', '홀드 상태 LOT의 출고 차단 여부', NULL, 7, 'Y', SYSTIMESTAMP, SYSTIMESTAMP);

INSERT INTO SYS_CONFIGS (ID, CONFIG_GROUP, CONFIG_KEY, CONFIG_VALUE, CONFIG_TYPE, LABEL, DESCRIPTION, OPTIONS, SORT_ORDER, IS_ACTIVE, CREATED_AT, UPDATED_AT)
VALUES (SYS_GUID(), 'MATERIAL', 'IQC_AUTO_RECEIVE', 'N', 'BOOLEAN', 'IQC 합격 자동입고', 'IQC 합격 시 자동으로 입고 처리 여부', NULL, 8, 'Y', SYSTIMESTAMP, SYSTIMESTAMP);

INSERT INTO SYS_CONFIGS (ID, CONFIG_GROUP, CONFIG_KEY, CONFIG_VALUE, CONFIG_TYPE, LABEL, DESCRIPTION, OPTIONS, SORT_ORDER, IS_ACTIVE, CREATED_AT, UPDATED_AT)
VALUES (SYS_GUID(), 'MATERIAL', 'MAT_AUTO_ISSUE_TIMING', 'OFF', 'SELECT', '자재 자동차감 시점', 'BOM 기반 자재 자동차감 실행 시점 설정', '[{"value":"OFF","label":"수동(사용안함)"},{"value":"ON_CREATE","label":"실적 등록 시"},{"value":"ON_COMPLETE","label":"실적 완료 시"}]', 9, 'Y', SYSTIMESTAMP, SYSTIMESTAMP);

INSERT INTO SYS_CONFIGS (ID, CONFIG_GROUP, CONFIG_KEY, CONFIG_VALUE, CONFIG_TYPE, LABEL, DESCRIPTION, OPTIONS, SORT_ORDER, IS_ACTIVE, CREATED_AT, UPDATED_AT)
VALUES (SYS_GUID(), 'MATERIAL', 'MAT_ISSUE_STOCK_CHECK', 'WARN', 'SELECT', '재고부족 시 처리', '자동차감 시 재고 부족 시 처리 방법', '[{"value":"WARN","label":"경고 후 진행"},{"value":"BLOCK","label":"차단(실적등록 불가)"}]', 10, 'Y', SYSTIMESTAMP, SYSTIMESTAMP);

-- ========== 생산관리(PRODUCTION) 그룹 ==========
INSERT INTO SYS_CONFIGS (ID, CONFIG_GROUP, CONFIG_KEY, CONFIG_VALUE, CONFIG_TYPE, LABEL, DESCRIPTION, OPTIONS, SORT_ORDER, IS_ACTIVE, CREATED_AT, UPDATED_AT)
VALUES (SYS_GUID(), 'PRODUCTION', 'AUTO_JOB_NO', 'Y', 'BOOLEAN', '작업지시번호 자동채번', '작업지시 등록 시 번호 자동 생성 여부', NULL, 1, 'Y', SYSTIMESTAMP, SYSTIMESTAMP);

INSERT INTO SYS_CONFIGS (ID, CONFIG_GROUP, CONFIG_KEY, CONFIG_VALUE, CONFIG_TYPE, LABEL, DESCRIPTION, OPTIONS, SORT_ORDER, IS_ACTIVE, CREATED_AT, UPDATED_AT)
VALUES (SYS_GUID(), 'PRODUCTION', 'DEFECT_LIMIT_RATE', '5', 'NUMBER', '불량률 한계(%)', '불량률이 이 값을 초과하면 경고 표시', NULL, 2, 'Y', SYSTIMESTAMP, SYSTIMESTAMP);

INSERT INTO SYS_CONFIGS (ID, CONFIG_GROUP, CONFIG_KEY, CONFIG_VALUE, CONFIG_TYPE, LABEL, DESCRIPTION, OPTIONS, SORT_ORDER, IS_ACTIVE, CREATED_AT, UPDATED_AT)
VALUES (SYS_GUID(), 'PRODUCTION', 'WORK_REPORT_REQUIRED', 'Y', 'BOOLEAN', '작업일보 필수', '생산 완료 시 작업일보 작성 필수 여부', NULL, 3, 'Y', SYSTIMESTAMP, SYSTIMESTAMP);

-- ========== 품질관리(QUALITY) 그룹 ==========
INSERT INTO SYS_CONFIGS (ID, CONFIG_GROUP, CONFIG_KEY, CONFIG_VALUE, CONFIG_TYPE, LABEL, DESCRIPTION, OPTIONS, SORT_ORDER, IS_ACTIVE, CREATED_AT, UPDATED_AT)
VALUES (SYS_GUID(), 'QUALITY', 'IQC_MANDATORY', 'Y', 'BOOLEAN', 'IQC 검사 필수', '입고 시 IQC 검사 필수 여부', NULL, 1, 'Y', SYSTIMESTAMP, SYSTIMESTAMP);

INSERT INTO SYS_CONFIGS (ID, CONFIG_GROUP, CONFIG_KEY, CONFIG_VALUE, CONFIG_TYPE, LABEL, DESCRIPTION, OPTIONS, SORT_ORDER, IS_ACTIVE, CREATED_AT, UPDATED_AT)
VALUES (SYS_GUID(), 'QUALITY', 'IQC_SAMPLE_RATIO', '10', 'NUMBER', 'IQC 샘플 비율(%)', '수입검사 시 기본 샘플링 비율', NULL, 2, 'Y', SYSTIMESTAMP, SYSTIMESTAMP);

-- ========== 시스템(SYSTEM) 그룹 ==========
INSERT INTO SYS_CONFIGS (ID, CONFIG_GROUP, CONFIG_KEY, CONFIG_VALUE, CONFIG_TYPE, LABEL, DESCRIPTION, OPTIONS, SORT_ORDER, IS_ACTIVE, CREATED_AT, UPDATED_AT)
VALUES (SYS_GUID(), 'SYSTEM', 'SESSION_TIMEOUT', '30', 'NUMBER', '세션 타임아웃(분)', '사용자 세션 자동 만료 시간(분)', NULL, 1, 'Y', SYSTIMESTAMP, SYSTIMESTAMP);

INSERT INTO SYS_CONFIGS (ID, CONFIG_GROUP, CONFIG_KEY, CONFIG_VALUE, CONFIG_TYPE, LABEL, DESCRIPTION, OPTIONS, SORT_ORDER, IS_ACTIVE, CREATED_AT, UPDATED_AT)
VALUES (SYS_GUID(), 'SYSTEM', 'DATE_FORMAT', 'YYYY-MM-DD', 'SELECT', '날짜 형식', '시스템 전체 날짜 표시 형식', '[{"value":"YYYY-MM-DD","label":"2025-01-01"},{"value":"YYYY/MM/DD","label":"2025/01/01"},{"value":"DD-MM-YYYY","label":"01-01-2025"}]', 2, 'Y', SYSTIMESTAMP, SYSTIMESTAMP);

INSERT INTO SYS_CONFIGS (ID, CONFIG_GROUP, CONFIG_KEY, CONFIG_VALUE, CONFIG_TYPE, LABEL, DESCRIPTION, OPTIONS, SORT_ORDER, IS_ACTIVE, CREATED_AT, UPDATED_AT)
VALUES (SYS_GUID(), 'SYSTEM', 'DEFAULT_PAGE_SIZE', '20', 'SELECT', '기본 페이지 크기', '목록 조회 시 기본 표시 건수', '[{"value":"10","label":"10건"},{"value":"20","label":"20건"},{"value":"50","label":"50건"},{"value":"100","label":"100건"}]', 3, 'Y', SYSTIMESTAMP, SYSTIMESTAMP);

COMMIT;
