-- Task 15: LABEL_TEMPLATES 테이블에 ZPL 관련 컬럼 추가 (개별 실행)
ALTER TABLE LABEL_TEMPLATES ADD ZPL_CODE CLOB DEFAULT NULL;

ALTER TABLE LABEL_TEMPLATES ADD PRINT_MODE VARCHAR2(20) DEFAULT 'BROWSER';

ALTER TABLE LABEL_TEMPLATES ADD PRINTER_ID VARCHAR2(36) DEFAULT NULL;

COMMENT ON COLUMN LABEL_TEMPLATES.ZPL_CODE IS '외부 디자이너에서 만든 ZPL 코드 (변수 플레이스홀더 포함)';

COMMENT ON COLUMN LABEL_TEMPLATES.PRINT_MODE IS '인쇄 모드: BROWSER, ZPL, BOTH';

COMMENT ON COLUMN LABEL_TEMPLATES.PRINTER_ID IS '기본 프린터 ID (EQUIP_MASTERS FK, 옵션)';
