MERGE INTO COM_CODES t
USING (
  SELECT 'PRINT_MODE' AS GROUP_CODE, 'BROWSER' AS DETAIL_CODE, '브라우저 인쇄' AS CODE_NAME, '브라우저에서 HTML 라벨 인쇄' AS CODE_DESC, 1 AS SORT_ORDER, '40' AS COMPANY, '1000' AS PLANT_CD FROM DUAL
  UNION ALL
  SELECT 'PRINT_MODE', 'ZPL', 'ZPL 인쇄', 'ZPL 코드로 Zebra 프린터 인쇄', 2, '40', '1000' FROM DUAL
  UNION ALL
  SELECT 'PRINT_MODE', 'BOTH', '브라우저+ZPL', '브라우저 및 ZPL 모두 지원', 3, '40', '1000' FROM DUAL
) s ON (t.GROUP_CODE = s.GROUP_CODE AND t.DETAIL_CODE = s.DETAIL_CODE AND t.COMPANY = s.COMPANY AND t.PLANT_CD = s.PLANT_CD)
WHEN NOT MATCHED THEN INSERT (ID, GROUP_CODE, DETAIL_CODE, CODE_NAME, CODE_DESC, SORT_ORDER, USE_YN, COMPANY, PLANT_CD)
VALUES (SYS_GUID(), s.GROUP_CODE, s.DETAIL_CODE, s.CODE_NAME, s.CODE_DESC, s.SORT_ORDER, 'Y', s.COMPANY, s.PLANT_CD)
