CREATE TABLE LABEL_PRINT_LOGS (
  ID           VARCHAR2(36) PRIMARY KEY,
  TEMPLATE_ID  VARCHAR2(36) NOT NULL,
  CATEGORY     VARCHAR2(50) NOT NULL,
  PRINT_MODE   VARCHAR2(20) NOT NULL,
  PRINTER_NAME VARCHAR2(200),
  LOT_IDS      CLOB,
  LABEL_COUNT  NUMBER DEFAULT 0,
  WORKER_ID    VARCHAR2(50),
  PRINTED_AT   TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  STATUS       VARCHAR2(20) DEFAULT 'SUCCESS',
  ERROR_MSG    VARCHAR2(1000),
  COMPANY      VARCHAR2(50) NOT NULL,
  PLANT_CD     VARCHAR2(50) NOT NULL,
  CREATED_AT   TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  UPDATED_AT   TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
)
