-- 자주검사 항목 마스터 테이블
-- 공정별 자주검사 항목 정의 (FIRST=초물, MID=중물, LAST=종물)
CREATE TABLE SELF_INSPECT_ITEMS (
  ID          VARCHAR2(36)  NOT NULL,
  PROCESS_CODE VARCHAR2(50),
  ITEM_NAME   VARCHAR2(200) NOT NULL,
  STANDARD    VARCHAR2(500),
  INSPECT_METHOD VARCHAR2(20) DEFAULT 'DIRECT' NOT NULL,  -- DIRECT | DELEGATE
  TIMING      VARCHAR2(50)  DEFAULT 'MID' NOT NULL,       -- FIRST,MID,LAST (콤마 구분)
  IS_DESTRUCTIVE NUMBER(1)  DEFAULT 0,
  SORT_ORDER  NUMBER        DEFAULT 0,
  USE_YN      VARCHAR2(1)   DEFAULT 'Y' NOT NULL,
  COMPANY     VARCHAR2(50),
  PLANT_CD    VARCHAR2(50),
  CREATED_BY  VARCHAR2(50),
  UPDATED_BY  VARCHAR2(50),
  CREATED_AT  TIMESTAMP     DEFAULT CURRENT_TIMESTAMP NOT NULL,
  UPDATED_AT  TIMESTAMP     DEFAULT CURRENT_TIMESTAMP NOT NULL,
  CONSTRAINT PK_SELF_INSPECT_ITEMS PRIMARY KEY (ID)
);

CREATE INDEX IDX_SI_ITEMS_PROCESS ON SELF_INSPECT_ITEMS(PROCESS_CODE);
CREATE INDEX IDX_SI_ITEMS_TENANT  ON SELF_INSPECT_ITEMS(COMPANY, PLANT_CD);

-- 자주검사 결과 테이블
-- 실제 검사 결과 저장 (직접검사: 즉시 PASS/FAIL, 의뢰검사: PENDING → 관리화면에서 업데이트)
CREATE TABLE SELF_INSPECT_RESULTS (
  ID               VARCHAR2(36)  NOT NULL,
  ORDER_NO         VARCHAR2(50)  NOT NULL,
  EQUIP_CODE       VARCHAR2(50),
  PROCESS_CODE     VARCHAR2(50),
  INSPECT_ITEM_ID  VARCHAR2(36),
  ITEM_NAME        VARCHAR2(200) NOT NULL,
  TIMING           VARCHAR2(20)  NOT NULL,   -- FIRST | MID | LAST
  INSPECT_METHOD   VARCHAR2(20)  DEFAULT 'DIRECT' NOT NULL,
  STATUS           VARCHAR2(20)  DEFAULT 'PENDING' NOT NULL,  -- PASS | FAIL | PENDING
  PROD_QTY_AT_INSPECT NUMBER,
  INSPECTOR_ID     VARCHAR2(50),
  REMARK           VARCHAR2(500),
  INSPECTED_AT     TIMESTAMP,
  COMPANY          VARCHAR2(50),
  PLANT_CD         VARCHAR2(50),
  CREATED_BY       VARCHAR2(50),
  UPDATED_BY       VARCHAR2(50),
  CREATED_AT       TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  UPDATED_AT       TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  CONSTRAINT PK_SELF_INSPECT_RESULTS PRIMARY KEY (ID)
);

CREATE INDEX IDX_SI_RESULTS_ORDER  ON SELF_INSPECT_RESULTS(ORDER_NO);
CREATE INDEX IDX_SI_RESULTS_STATUS ON SELF_INSPECT_RESULTS(STATUS);
CREATE INDEX IDX_SI_RESULTS_TENANT ON SELF_INSPECT_RESULTS(COMPANY, PLANT_CD);
