CREATE TABLE "IQC_TEMPLATES" (
  "COMPANY" VARCHAR2(50) NOT NULL,
  "PLANT_CD" VARCHAR2(50) NOT NULL,
  "TEMPLATE_ID" VARCHAR2(50) NOT NULL,
  "TEMPLATE_NAME" VARCHAR2(200) NOT NULL,
  "SAMPLE_QTY" NUMBER DEFAULT 1 NOT NULL,
  "IS_DEST" CHAR(1) DEFAULT 'N' NOT NULL,
  "USE_YN" CHAR(1) DEFAULT 'Y' NOT NULL,
  "CREATED_BY" VARCHAR2(50),
  "UPDATED_BY" VARCHAR2(50),
  "CREATED_AT" TIMESTAMP DEFAULT SYSTIMESTAMP,
  "UPDATED_AT" TIMESTAMP DEFAULT SYSTIMESTAMP,
  CONSTRAINT "PK_IQC_TEMPLATES" PRIMARY KEY ("COMPANY", "PLANT_CD", "TEMPLATE_ID")
)
/
CREATE TABLE "IQC_TEMPLATE_ITEMS" (
  "COMPANY" VARCHAR2(50) NOT NULL,
  "PLANT_CD" VARCHAR2(50) NOT NULL,
  "TEMPLATE_ID" VARCHAR2(50) NOT NULL,
  "SEQ" NUMBER NOT NULL,
  "INSP_ITEM_CODE" VARCHAR2(20) NOT NULL,
  "LSL" NUMBER(12,4),
  "USL" NUMBER(12,4),
  "JUDGE_CRITERIA" VARCHAR2(500),
  "USE_YN" CHAR(1) DEFAULT 'Y' NOT NULL,
  "CREATED_BY" VARCHAR2(50),
  "UPDATED_BY" VARCHAR2(50),
  "CREATED_AT" TIMESTAMP DEFAULT SYSTIMESTAMP,
  "UPDATED_AT" TIMESTAMP DEFAULT SYSTIMESTAMP,
  CONSTRAINT "PK_IQC_TEMPLATE_ITEMS" PRIMARY KEY ("COMPANY", "PLANT_CD", "TEMPLATE_ID", "SEQ"),
  CONSTRAINT "FK_IQC_TPL_ITEMS_TPL" FOREIGN KEY ("COMPANY", "PLANT_CD", "TEMPLATE_ID")
    REFERENCES "IQC_TEMPLATES" ("COMPANY", "PLANT_CD", "TEMPLATE_ID") ON DELETE CASCADE
)
/
ALTER TABLE "IQC_PART_SPEC_ITEMS" ADD ("JUDGE_CRITERIA" VARCHAR2(500))
/
BEGIN
  INSERT INTO "migrations" ("timestamp","name") VALUES (1771886000000,'AddIqcTemplateAndJudgeCriteria1771886000000');
  COMMIT;
END;
/
