BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE ROLE_MENU_PERMISSIONS ADD (COMPANY VARCHAR2(50) DEFAULT ''40'' NOT NULL)';
  EXECUTE IMMEDIATE 'ALTER TABLE ROLE_MENU_PERMISSIONS ADD (PLANT_CD VARCHAR2(50) DEFAULT ''1000'' NOT NULL)';
  EXECUTE IMMEDIATE 'ALTER TABLE ROLE_MENU_PERMISSIONS DROP PRIMARY KEY DROP INDEX';
  EXECUTE IMMEDIATE 'ALTER TABLE ROLE_MENU_PERMISSIONS ADD CONSTRAINT PK_ROLE_MENU_PERM PRIMARY KEY (COMPANY, PLANT_CD, ROLE_CODE, MENU_CODE)';
END;
/
