BEGIN
  -- 1. 기존 UK(PDA_ROLE_CODE + MENU_CODE만 포함) 삭제
  EXECUTE IMMEDIATE 'ALTER TABLE PDA_ROLE_MENU DROP CONSTRAINT UK_PDA_ROLE_MENU';
  -- 2. FK 삭제 (PK 추가 후 재생성)
  EXECUTE IMMEDIATE 'ALTER TABLE PDA_ROLE_MENU DROP CONSTRAINT FK_PDA_ROLE_MENU_ROLE';
  -- 3. 복합 PK 생성 (COMPANY + PLANT_CD + PDA_ROLE_CODE + MENU_CODE)
  EXECUTE IMMEDIATE 'ALTER TABLE PDA_ROLE_MENU ADD CONSTRAINT PK_PDA_ROLE_MENU PRIMARY KEY (COMPANY, PLANT_CD, PDA_ROLE_CODE, MENU_CODE)';
  COMMIT;
END;
/
