BEGIN
  UPDATE EQUIP_MASTERS SET STATUS = 'NORMAL' WHERE STATUS = 'ACTIVE';
  UPDATE EQUIP_MASTERS SET STATUS = 'STOP'   WHERE STATUS = 'INTERLOCK';
  UPDATE EQUIP_MASTERS SET EQUIP_TYPE = 'AUTO_CRIMP'  WHERE EQUIP_TYPE = 'CRIMP_MACHINE';
  UPDATE EQUIP_MASTERS SET EQUIP_TYPE = 'SINGLE_CUT'  WHERE EQUIP_TYPE = 'CUT_MACHINE';
  UPDATE EQUIP_MASTERS SET EQUIP_TYPE = 'OTHER'       WHERE EQUIP_TYPE = 'STRIP_MACHINE';
  UPDATE EQUIP_MASTERS SET EQUIP_TYPE = 'TESTER'      WHERE EQUIP_TYPE = 'TEST_MACHINE';
  COMMIT;
END;
/
