BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE PROCESS_EQUIPMENTS ADD (COMPANY VARCHAR2(50) DEFAULT ''40'' NOT NULL)';
  EXECUTE IMMEDIATE 'ALTER TABLE PROCESS_EQUIPMENTS ADD (PLANT_CD VARCHAR2(50) DEFAULT ''1000'' NOT NULL)';
  EXECUTE IMMEDIATE 'ALTER TABLE PROCESS_EQUIPMENTS DROP PRIMARY KEY DROP INDEX';
  EXECUTE IMMEDIATE 'ALTER TABLE PROCESS_EQUIPMENTS ADD CONSTRAINT PK_PROCESS_EQUIPMENTS PRIMARY KEY (COMPANY, PLANT_CD, PROCESS_CODE, EQUIP_CODE)';
END;
/
