-- ERP 품목 마스터 인터페이스 프로시저
-- 대상: ITEM_MASTERS (COMPANY='40', PLANT_CD='1000')
-- 소스: MTL_SYSTEM_ITEMS@ERP_PROD (ORGANIZATION_ID=123)
-- 변경 감지: ERP_LAST_UPD_DATE 컬럼 비교 (변경 없는 건 SKIP)
CREATE OR REPLACE PROCEDURE IF_ITEM_MASTER(
    N_RETURN  OUT NUMBER,
    V_RETURN  OUT VARCHAR2,
    N_INSERT  OUT NUMBER,
    N_UPDATE  OUT NUMBER
)
IS
    V_BEFORE NUMBER;
    V_AFTER  NUMBER;
    V_TOTAL  NUMBER;
BEGIN
    N_INSERT := 0;
    N_UPDATE := 0;

    SELECT COUNT(*) INTO V_BEFORE
    FROM ITEM_MASTERS
    WHERE COMPANY = '40' AND PLANT_CD = '1000';

    MERGE INTO ITEM_MASTERS T
    USING (
        SELECT
            SEGMENT1           AS ITEM_CODE,
            ATTRIBUTE3         AS ITEM_NAME,
            ATTRIBUTE4         AS SPEC,
            ITEM_TYPE          AS ITEM_TYPE,
            PRIMARY_UOM_CODE   AS UNIT,
            ENABLED_FLAG       AS USE_YN,
            LAST_UPDATE_DATE   AS ERP_LAST_UPD_DATE
        FROM MTL_SYSTEM_ITEMS@ERP_PROD
        WHERE ORGANIZATION_ID = 123
          AND ITEM_TYPE IN ('RM', 'CM', 'FG')
          AND ATTRIBUTE3 IS NOT NULL
    ) E ON (T.ITEM_CODE = E.ITEM_CODE AND T.COMPANY = '40' AND T.PLANT_CD = '1000')
    WHEN NOT MATCHED THEN
        INSERT (
            ITEM_CODE, PART_NO, ITEM_NAME, SPEC, ITEM_TYPE, UNIT, USE_YN,
            COMPANY, PLANT_CD, CREATED_BY, CREATED_AT, UPDATED_AT, ERP_LAST_UPD_DATE
        )
        VALUES (
            E.ITEM_CODE, E.ITEM_CODE, E.ITEM_NAME, E.SPEC, E.ITEM_TYPE, E.UNIT, E.USE_YN,
            '40', '1000', 'ERP-IF', SYSTIMESTAMP, SYSTIMESTAMP, E.ERP_LAST_UPD_DATE
        )
    WHEN MATCHED THEN
        UPDATE SET
            T.ITEM_NAME         = E.ITEM_NAME,
            T.SPEC              = E.SPEC,
            T.ITEM_TYPE         = E.ITEM_TYPE,
            T.UNIT              = E.UNIT,
            T.USE_YN            = E.USE_YN,
            T.ERP_LAST_UPD_DATE = E.ERP_LAST_UPD_DATE,
            T.UPDATED_AT        = SYSTIMESTAMP
        WHERE E.ERP_LAST_UPD_DATE > T.ERP_LAST_UPD_DATE
           OR T.ERP_LAST_UPD_DATE IS NULL;

    V_TOTAL := SQL%ROWCOUNT;

    SELECT COUNT(*) INTO V_AFTER
    FROM ITEM_MASTERS
    WHERE COMPANY = '40' AND PLANT_CD = '1000';

    N_INSERT := V_AFTER - V_BEFORE;
    N_UPDATE := V_TOTAL - N_INSERT;

    COMMIT;

    N_RETURN := 0;
    V_RETURN := 'OK';

EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        N_RETURN := 1;
        V_RETURN := SQLERRM;
END IF_ITEM_MASTER;
