DECLARE v NUMBER;
BEGIN
  SELECT COUNT(*) INTO v FROM user_tables WHERE table_name = 'migrations';
  IF v = 0 THEN
    EXECUTE IMMEDIATE 'CREATE TABLE "migrations" (' ||
      '"id" NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY, ' ||
      '"timestamp" NUMBER NOT NULL, ' ||
      '"name" VARCHAR2(255) NOT NULL, ' ||
      'CONSTRAINT "PK_migrations_id" PRIMARY KEY ("id"))';
  END IF;
END;
/
BEGIN
  INSERT INTO "migrations" ("timestamp","name") VALUES (1771631486424,'AddUserPhotoUrl1771631486424');
  INSERT INTO "migrations" ("timestamp","name") VALUES (1771635888013,'AddEquipProcessCode1771635888013');
  INSERT INTO "migrations" ("timestamp","name") VALUES (1771882101037,'AddToleranceRateToPartMaster1771882101037');
  INSERT INTO "migrations" ("timestamp","name") VALUES (1771882552632,'AddPartMasterFields1771882552632');
  INSERT INTO "migrations" ("timestamp","name") VALUES (1771882596757,'AddTraceLogParentId1771882596757');
  INSERT INTO "migrations" ("timestamp","name") VALUES (1771882748530,'AddMatIssueProdResultId1771882748530');
  INSERT INTO "migrations" ("timestamp","name") VALUES (1771882800000,'AddInspectScopeToInspectResult1771882800000');
  INSERT INTO "migrations" ("timestamp","name") VALUES (1771882900000,'AddPartImageUrl1771882900000');
  INSERT INTO "migrations" ("timestamp","name") VALUES (1771883000000,'CreateProcessEquipments1771883000000');
  INSERT INTO "migrations" ("timestamp","name") VALUES (1771883200000,'DropBomRoutingCode1771883200000');
  INSERT INTO "migrations" ("timestamp","name") VALUES (1771883300000,'CreateRoutingMaterials1771883300000');
  INSERT INTO "migrations" ("timestamp","name") VALUES (1771883400000,'AddTenantToProcessEquipments1771883400000');
  INSERT INTO "migrations" ("timestamp","name") VALUES (1771883500000,'AlignRoutingTenantPrimaryKeys1771883500000');
  INSERT INTO "migrations" ("timestamp","name") VALUES (1771883600000,'AlignProcessEquipmentTenantPrimaryKey1771883600000');
  INSERT INTO "migrations" ("timestamp","name") VALUES (1771883700000,'AlignWarehouseTenantPrimaryKeys1771883700000');
  INSERT INTO "migrations" ("timestamp","name") VALUES (1771883800000,'AlignStockTenantPrimaryKeys1771883800000');
  INSERT INTO "migrations" ("timestamp","name") VALUES (1771883900000,'AlignPdaRoleTenantPrimaryKeys1771883900000');
  INSERT INTO "migrations" ("timestamp","name") VALUES (1771884000000,'AlignRoleTenantPrimaryKeys1771884000000');
  INSERT INTO "migrations" ("timestamp","name") VALUES (1771884100000,'AlignMenuCategoryTenantPrimaryKeys1771884100000');
  COMMIT;
END;
/
