-- 0. MAT_ISSUE_REQUESTS 테이블: ISSUE_TYPE 컬럼 추가 (없는 경우)
-- ALTER TABLE "MAT_ISSUE_REQUESTS" ADD ("ISSUE_TYPE" VARCHAR2(20 CHAR));

-- 1. MAT_ISSUES 테이블: 기존 ISSUE_TYPE 값을 새 코드값으로 변환
UPDATE "MAT_ISSUES" SET "ISSUE_TYPE" = 'PRODUCTION'  WHERE "ISSUE_TYPE" = 'PROD';
UPDATE "MAT_ISSUES" SET "ISSUE_TYPE" = 'ADJUSTMENT'  WHERE "ISSUE_TYPE" = 'ADJ';
UPDATE "MAT_ISSUES" SET "ISSUE_TYPE" = 'SUBCONTRACT' WHERE "ISSUE_TYPE" = 'SUBCON';
-- SAMPLE은 그대로 유지
COMMIT;

-- 2. COM_CODES 테이블: 기존 코드값 비활성화 (USE_YN='N')
-- JSHANES 사이트 기준: COMPANY='40', PLANT_CD='1000'
UPDATE "COM_CODES" SET "USE_YN" = 'N' WHERE "COMPANY" = '40' AND "PLANT_CD" = '1000' AND "GROUP_CODE" = 'ISSUE_TYPE' AND "DETAIL_CODE" = 'PROD';
UPDATE "COM_CODES" SET "USE_YN" = 'N' WHERE "COMPANY" = '40' AND "PLANT_CD" = '1000' AND "GROUP_CODE" = 'ISSUE_TYPE' AND "DETAIL_CODE" = 'SUBCON';
UPDATE "COM_CODES" SET "USE_YN" = 'N' WHERE "COMPANY" = '40' AND "PLANT_CD" = '1000' AND "GROUP_CODE" = 'ISSUE_TYPE' AND "DETAIL_CODE" = 'ADJ';
COMMIT;
