BEGIN
  INSERT INTO COM_CODES (
    GROUP_CODE, DETAIL_CODE, PARENT_CODE, CODE_NAME, CODE_DESC,
    SORT_ORDER, USE_YN, ATTR1, ATTR2, ATTR3,
    COMPANY, PLANT_CD, CREATED_BY, UPDATED_BY, CREATED_AT, UPDATED_AT
  )
  SELECT
    GROUP_CODE, DETAIL_CODE, PARENT_CODE, CODE_NAME, CODE_DESC,
    SORT_ORDER, USE_YN, ATTR1, ATTR2, ATTR3,
    '40', '1000', CREATED_BY, UPDATED_BY, CREATED_AT, SYSTIMESTAMP
  FROM COM_CODES AS OF TIMESTAMP (SYSTIMESTAMP - INTERVAL '90' MINUTE)
  WHERE COMPANY <> '40';
  COMMIT;
END;
/
