BEGIN
  -- ============================================================
  -- IQC_PART_SPECS: 품목별 IQC 검사 기준 헤더 (19개 자재)
  -- COMPANY='40', PLANT_CD='1000'
  -- ============================================================

  -- 커넥터류
  INSERT INTO IQC_PART_SPECS (COMPANY, PLANT_CD, ITEM_CODE, SAMPLE_QTY, IS_DEST, USE_YN, CREATED_BY, UPDATED_BY)
    VALUES ('40', '1000', 'RAW-C-001', 5, 'N', 'Y', 'SYSTEM', 'SYSTEM');
  INSERT INTO IQC_PART_SPECS (COMPANY, PLANT_CD, ITEM_CODE, SAMPLE_QTY, IS_DEST, USE_YN, CREATED_BY, UPDATED_BY)
    VALUES ('40', '1000', 'RAW-C-002', 5, 'N', 'Y', 'SYSTEM', 'SYSTEM');
  INSERT INTO IQC_PART_SPECS (COMPANY, PLANT_CD, ITEM_CODE, SAMPLE_QTY, IS_DEST, USE_YN, CREATED_BY, UPDATED_BY)
    VALUES ('40', '1000', 'RAW-C-003', 5, 'N', 'Y', 'SYSTEM', 'SYSTEM');
  INSERT INTO IQC_PART_SPECS (COMPANY, PLANT_CD, ITEM_CODE, SAMPLE_QTY, IS_DEST, USE_YN, CREATED_BY, UPDATED_BY)
    VALUES ('40', '1000', 'RAW-C-004', 5, 'Y', 'Y', 'SYSTEM', 'SYSTEM');

  -- 보호재류
  INSERT INTO IQC_PART_SPECS (COMPANY, PLANT_CD, ITEM_CODE, SAMPLE_QTY, IS_DEST, USE_YN, CREATED_BY, UPDATED_BY)
    VALUES ('40', '1000', 'RAW-P-001', 3, 'N', 'Y', 'SYSTEM', 'SYSTEM');
  INSERT INTO IQC_PART_SPECS (COMPANY, PLANT_CD, ITEM_CODE, SAMPLE_QTY, IS_DEST, USE_YN, CREATED_BY, UPDATED_BY)
    VALUES ('40', '1000', 'RAW-P-002', 3, 'N', 'Y', 'SYSTEM', 'SYSTEM');
  INSERT INTO IQC_PART_SPECS (COMPANY, PLANT_CD, ITEM_CODE, SAMPLE_QTY, IS_DEST, USE_YN, CREATED_BY, UPDATED_BY)
    VALUES ('40', '1000', 'RAW-P-003', 3, 'N', 'Y', 'SYSTEM', 'SYSTEM');
  INSERT INTO IQC_PART_SPECS (COMPANY, PLANT_CD, ITEM_CODE, SAMPLE_QTY, IS_DEST, USE_YN, CREATED_BY, UPDATED_BY)
    VALUES ('40', '1000', 'RAW-P-004', 3, 'N', 'Y', 'SYSTEM', 'SYSTEM');
  INSERT INTO IQC_PART_SPECS (COMPANY, PLANT_CD, ITEM_CODE, SAMPLE_QTY, IS_DEST, USE_YN, CREATED_BY, UPDATED_BY)
    VALUES ('40', '1000', 'RAW-P-005', 3, 'N', 'Y', 'SYSTEM', 'SYSTEM');

  -- 단자류 (크림프 측정 = 파괴검사)
  INSERT INTO IQC_PART_SPECS (COMPANY, PLANT_CD, ITEM_CODE, SAMPLE_QTY, IS_DEST, USE_YN, CREATED_BY, UPDATED_BY)
    VALUES ('40', '1000', 'RAW-T-001', 5, 'Y', 'Y', 'SYSTEM', 'SYSTEM');
  INSERT INTO IQC_PART_SPECS (COMPANY, PLANT_CD, ITEM_CODE, SAMPLE_QTY, IS_DEST, USE_YN, CREATED_BY, UPDATED_BY)
    VALUES ('40', '1000', 'RAW-T-002', 5, 'Y', 'Y', 'SYSTEM', 'SYSTEM');
  INSERT INTO IQC_PART_SPECS (COMPANY, PLANT_CD, ITEM_CODE, SAMPLE_QTY, IS_DEST, USE_YN, CREATED_BY, UPDATED_BY)
    VALUES ('40', '1000', 'RAW-T-003', 5, 'Y', 'Y', 'SYSTEM', 'SYSTEM');
  INSERT INTO IQC_PART_SPECS (COMPANY, PLANT_CD, ITEM_CODE, SAMPLE_QTY, IS_DEST, USE_YN, CREATED_BY, UPDATED_BY)
    VALUES ('40', '1000', 'RAW-T-004', 5, 'Y', 'Y', 'SYSTEM', 'SYSTEM');
  INSERT INTO IQC_PART_SPECS (COMPANY, PLANT_CD, ITEM_CODE, SAMPLE_QTY, IS_DEST, USE_YN, CREATED_BY, UPDATED_BY)
    VALUES ('40', '1000', 'RAW-T-005', 5, 'Y', 'Y', 'SYSTEM', 'SYSTEM');

  -- 전선류
  INSERT INTO IQC_PART_SPECS (COMPANY, PLANT_CD, ITEM_CODE, SAMPLE_QTY, IS_DEST, USE_YN, CREATED_BY, UPDATED_BY)
    VALUES ('40', '1000', 'RAW-W-001', 5, 'N', 'Y', 'SYSTEM', 'SYSTEM');
  INSERT INTO IQC_PART_SPECS (COMPANY, PLANT_CD, ITEM_CODE, SAMPLE_QTY, IS_DEST, USE_YN, CREATED_BY, UPDATED_BY)
    VALUES ('40', '1000', 'RAW-W-002', 5, 'N', 'Y', 'SYSTEM', 'SYSTEM');
  INSERT INTO IQC_PART_SPECS (COMPANY, PLANT_CD, ITEM_CODE, SAMPLE_QTY, IS_DEST, USE_YN, CREATED_BY, UPDATED_BY)
    VALUES ('40', '1000', 'RAW-W-003', 5, 'N', 'Y', 'SYSTEM', 'SYSTEM');
  INSERT INTO IQC_PART_SPECS (COMPANY, PLANT_CD, ITEM_CODE, SAMPLE_QTY, IS_DEST, USE_YN, CREATED_BY, UPDATED_BY)
    VALUES ('40', '1000', 'RAW-W-004', 5, 'N', 'Y', 'SYSTEM', 'SYSTEM');
  INSERT INTO IQC_PART_SPECS (COMPANY, PLANT_CD, ITEM_CODE, SAMPLE_QTY, IS_DEST, USE_YN, CREATED_BY, UPDATED_BY)
    VALUES ('40', '1000', 'RAW-W-005', 5, 'N', 'Y', 'SYSTEM', 'SYSTEM');

  -- ============================================================
  -- IQC_PART_SPEC_ITEMS: 품목별 검사항목 + 규격
  -- ============================================================

  -- RAW-C-001 (6P 커넥터 하우징)
  INSERT INTO IQC_PART_SPEC_ITEMS (COMPANY, PLANT_CD, ITEM_CODE, SEQ, INSP_ITEM_CODE, LSL, USL, USE_YN, CREATED_BY, UPDATED_BY)
    VALUES ('40', '1000', 'RAW-C-001', 1, 'IQC-V-003', NULL, NULL, 'Y', 'SYSTEM', 'SYSTEM');
  INSERT INTO IQC_PART_SPEC_ITEMS (COMPANY, PLANT_CD, ITEM_CODE, SEQ, INSP_ITEM_CODE, LSL, USL, USE_YN, CREATED_BY, UPDATED_BY)
    VALUES ('40', '1000', 'RAW-C-001', 2, 'IQC-V-004', NULL, NULL, 'Y', 'SYSTEM', 'SYSTEM');
  INSERT INTO IQC_PART_SPEC_ITEMS (COMPANY, PLANT_CD, ITEM_CODE, SEQ, INSP_ITEM_CODE, LSL, USL, USE_YN, CREATED_BY, UPDATED_BY)
    VALUES ('40', '1000', 'RAW-C-001', 3, 'IQC-C-001', NULL, NULL, 'Y', 'SYSTEM', 'SYSTEM');
  INSERT INTO IQC_PART_SPEC_ITEMS (COMPANY, PLANT_CD, ITEM_CODE, SEQ, INSP_ITEM_CODE, LSL, USL, USE_YN, CREATED_BY, UPDATED_BY)
    VALUES ('40', '1000', 'RAW-C-001', 4, 'IQC-C-002', NULL, NULL, 'Y', 'SYSTEM', 'SYSTEM');
  INSERT INTO IQC_PART_SPEC_ITEMS (COMPANY, PLANT_CD, ITEM_CODE, SEQ, INSP_ITEM_CODE, LSL, USL, USE_YN, CREATED_BY, UPDATED_BY)
    VALUES ('40', '1000', 'RAW-C-001', 5, 'IQC-C-003', NULL, 20, 'Y', 'SYSTEM', 'SYSTEM');
  INSERT INTO IQC_PART_SPEC_ITEMS (COMPANY, PLANT_CD, ITEM_CODE, SEQ, INSP_ITEM_CODE, LSL, USL, USE_YN, CREATED_BY, UPDATED_BY)
    VALUES ('40', '1000', 'RAW-C-001', 6, 'IQC-C-004', 30, NULL, 'Y', 'SYSTEM', 'SYSTEM');

  -- RAW-C-002 (10P 커넥터 하우징)
  INSERT INTO IQC_PART_SPEC_ITEMS (COMPANY, PLANT_CD, ITEM_CODE, SEQ, INSP_ITEM_CODE, LSL, USL, USE_YN, CREATED_BY, UPDATED_BY)
    VALUES ('40', '1000', 'RAW-C-002', 1, 'IQC-V-003', NULL, NULL, 'Y', 'SYSTEM', 'SYSTEM');
  INSERT INTO IQC_PART_SPEC_ITEMS (COMPANY, PLANT_CD, ITEM_CODE, SEQ, INSP_ITEM_CODE, LSL, USL, USE_YN, CREATED_BY, UPDATED_BY)
    VALUES ('40', '1000', 'RAW-C-002', 2, 'IQC-V-004', NULL, NULL, 'Y', 'SYSTEM', 'SYSTEM');
  INSERT INTO IQC_PART_SPEC_ITEMS (COMPANY, PLANT_CD, ITEM_CODE, SEQ, INSP_ITEM_CODE, LSL, USL, USE_YN, CREATED_BY, UPDATED_BY)
    VALUES ('40', '1000', 'RAW-C-002', 3, 'IQC-C-001', NULL, NULL, 'Y', 'SYSTEM', 'SYSTEM');
  INSERT INTO IQC_PART_SPEC_ITEMS (COMPANY, PLANT_CD, ITEM_CODE, SEQ, INSP_ITEM_CODE, LSL, USL, USE_YN, CREATED_BY, UPDATED_BY)
    VALUES ('40', '1000', 'RAW-C-002', 4, 'IQC-C-002', NULL, NULL, 'Y', 'SYSTEM', 'SYSTEM');
  INSERT INTO IQC_PART_SPEC_ITEMS (COMPANY, PLANT_CD, ITEM_CODE, SEQ, INSP_ITEM_CODE, LSL, USL, USE_YN, CREATED_BY, UPDATED_BY)
    VALUES ('40', '1000', 'RAW-C-002', 5, 'IQC-C-003', NULL, 20, 'Y', 'SYSTEM', 'SYSTEM');
  INSERT INTO IQC_PART_SPEC_ITEMS (COMPANY, PLANT_CD, ITEM_CODE, SEQ, INSP_ITEM_CODE, LSL, USL, USE_YN, CREATED_BY, UPDATED_BY)
    VALUES ('40', '1000', 'RAW-C-002', 6, 'IQC-C-004', 30, NULL, 'Y', 'SYSTEM', 'SYSTEM');

  -- RAW-C-003 (4P 커넥터 하우징)
  INSERT INTO IQC_PART_SPEC_ITEMS (COMPANY, PLANT_CD, ITEM_CODE, SEQ, INSP_ITEM_CODE, LSL, USL, USE_YN, CREATED_BY, UPDATED_BY)
    VALUES ('40', '1000', 'RAW-C-003', 1, 'IQC-V-003', NULL, NULL, 'Y', 'SYSTEM', 'SYSTEM');
  INSERT INTO IQC_PART_SPEC_ITEMS (COMPANY, PLANT_CD, ITEM_CODE, SEQ, INSP_ITEM_CODE, LSL, USL, USE_YN, CREATED_BY, UPDATED_BY)
    VALUES ('40', '1000', 'RAW-C-003', 2, 'IQC-V-004', NULL, NULL, 'Y', 'SYSTEM', 'SYSTEM');
  INSERT INTO IQC_PART_SPEC_ITEMS (COMPANY, PLANT_CD, ITEM_CODE, SEQ, INSP_ITEM_CODE, LSL, USL, USE_YN, CREATED_BY, UPDATED_BY)
    VALUES ('40', '1000', 'RAW-C-003', 3, 'IQC-C-001', NULL, NULL, 'Y', 'SYSTEM', 'SYSTEM');
  INSERT INTO IQC_PART_SPEC_ITEMS (COMPANY, PLANT_CD, ITEM_CODE, SEQ, INSP_ITEM_CODE, LSL, USL, USE_YN, CREATED_BY, UPDATED_BY)
    VALUES ('40', '1000', 'RAW-C-003', 4, 'IQC-C-002', NULL, NULL, 'Y', 'SYSTEM', 'SYSTEM');
  INSERT INTO IQC_PART_SPEC_ITEMS (COMPANY, PLANT_CD, ITEM_CODE, SEQ, INSP_ITEM_CODE, LSL, USL, USE_YN, CREATED_BY, UPDATED_BY)
    VALUES ('40', '1000', 'RAW-C-003', 5, 'IQC-C-003', NULL, 20, 'Y', 'SYSTEM', 'SYSTEM');
  INSERT INTO IQC_PART_SPEC_ITEMS (COMPANY, PLANT_CD, ITEM_CODE, SEQ, INSP_ITEM_CODE, LSL, USL, USE_YN, CREATED_BY, UPDATED_BY)
    VALUES ('40', '1000', 'RAW-C-003', 6, 'IQC-C-004', 30, NULL, 'Y', 'SYSTEM', 'SYSTEM');

  -- RAW-C-004 (2P 방수커넥터 — 방수시험 추가)
  INSERT INTO IQC_PART_SPEC_ITEMS (COMPANY, PLANT_CD, ITEM_CODE, SEQ, INSP_ITEM_CODE, LSL, USL, USE_YN, CREATED_BY, UPDATED_BY)
    VALUES ('40', '1000', 'RAW-C-004', 1, 'IQC-V-003', NULL, NULL, 'Y', 'SYSTEM', 'SYSTEM');
  INSERT INTO IQC_PART_SPEC_ITEMS (COMPANY, PLANT_CD, ITEM_CODE, SEQ, INSP_ITEM_CODE, LSL, USL, USE_YN, CREATED_BY, UPDATED_BY)
    VALUES ('40', '1000', 'RAW-C-004', 2, 'IQC-V-004', NULL, NULL, 'Y', 'SYSTEM', 'SYSTEM');
  INSERT INTO IQC_PART_SPEC_ITEMS (COMPANY, PLANT_CD, ITEM_CODE, SEQ, INSP_ITEM_CODE, LSL, USL, USE_YN, CREATED_BY, UPDATED_BY)
    VALUES ('40', '1000', 'RAW-C-004', 3, 'IQC-C-001', NULL, NULL, 'Y', 'SYSTEM', 'SYSTEM');
  INSERT INTO IQC_PART_SPEC_ITEMS (COMPANY, PLANT_CD, ITEM_CODE, SEQ, INSP_ITEM_CODE, LSL, USL, USE_YN, CREATED_BY, UPDATED_BY)
    VALUES ('40', '1000', 'RAW-C-004', 4, 'IQC-C-002', NULL, NULL, 'Y', 'SYSTEM', 'SYSTEM');
  INSERT INTO IQC_PART_SPEC_ITEMS (COMPANY, PLANT_CD, ITEM_CODE, SEQ, INSP_ITEM_CODE, LSL, USL, USE_YN, CREATED_BY, UPDATED_BY)
    VALUES ('40', '1000', 'RAW-C-004', 5, 'IQC-C-003', NULL, 25, 'Y', 'SYSTEM', 'SYSTEM');
  INSERT INTO IQC_PART_SPEC_ITEMS (COMPANY, PLANT_CD, ITEM_CODE, SEQ, INSP_ITEM_CODE, LSL, USL, USE_YN, CREATED_BY, UPDATED_BY)
    VALUES ('40', '1000', 'RAW-C-004', 6, 'IQC-C-004', 40, NULL, 'Y', 'SYSTEM', 'SYSTEM');
  INSERT INTO IQC_PART_SPEC_ITEMS (COMPANY, PLANT_CD, ITEM_CODE, SEQ, INSP_ITEM_CODE, LSL, USL, USE_YN, CREATED_BY, UPDATED_BY)
    VALUES ('40', '1000', 'RAW-C-004', 7, 'IQC-C-005', NULL, NULL, 'Y', 'SYSTEM', 'SYSTEM');

  -- RAW-P-001 (코루게이트 튜브 10mm)
  INSERT INTO IQC_PART_SPEC_ITEMS (COMPANY, PLANT_CD, ITEM_CODE, SEQ, INSP_ITEM_CODE, LSL, USL, USE_YN, CREATED_BY, UPDATED_BY)
    VALUES ('40', '1000', 'RAW-P-001', 1, 'IQC-V-001', NULL, NULL, 'Y', 'SYSTEM', 'SYSTEM');
  INSERT INTO IQC_PART_SPEC_ITEMS (COMPANY, PLANT_CD, ITEM_CODE, SEQ, INSP_ITEM_CODE, LSL, USL, USE_YN, CREATED_BY, UPDATED_BY)
    VALUES ('40', '1000', 'RAW-P-001', 2, 'IQC-V-003', NULL, NULL, 'Y', 'SYSTEM', 'SYSTEM');
  INSERT INTO IQC_PART_SPEC_ITEMS (COMPANY, PLANT_CD, ITEM_CODE, SEQ, INSP_ITEM_CODE, LSL, USL, USE_YN, CREATED_BY, UPDATED_BY)
    VALUES ('40', '1000', 'RAW-P-001', 3, 'IQC-V-004', NULL, NULL, 'Y', 'SYSTEM', 'SYSTEM');
  INSERT INTO IQC_PART_SPEC_ITEMS (COMPANY, PLANT_CD, ITEM_CODE, SEQ, INSP_ITEM_CODE, LSL, USL, USE_YN, CREATED_BY, UPDATED_BY)
    VALUES ('40', '1000', 'RAW-P-001', 4, 'IQC-P-001', 9.5, 10.5, 'Y', 'SYSTEM', 'SYSTEM');

  -- RAW-P-002 (비닐테이프 19mm)
  INSERT INTO IQC_PART_SPEC_ITEMS (COMPANY, PLANT_CD, ITEM_CODE, SEQ, INSP_ITEM_CODE, LSL, USL, USE_YN, CREATED_BY, UPDATED_BY)
    VALUES ('40', '1000', 'RAW-P-002', 1, 'IQC-V-001', NULL, NULL, 'Y', 'SYSTEM', 'SYSTEM');
  INSERT INTO IQC_PART_SPEC_ITEMS (COMPANY, PLANT_CD, ITEM_CODE, SEQ, INSP_ITEM_CODE, LSL, USL, USE_YN, CREATED_BY, UPDATED_BY)
    VALUES ('40', '1000', 'RAW-P-002', 2, 'IQC-V-003', NULL, NULL, 'Y', 'SYSTEM', 'SYSTEM');
  INSERT INTO IQC_PART_SPEC_ITEMS (COMPANY, PLANT_CD, ITEM_CODE, SEQ, INSP_ITEM_CODE, LSL, USL, USE_YN, CREATED_BY, UPDATED_BY)
    VALUES ('40', '1000', 'RAW-P-002', 3, 'IQC-P-002', 3, NULL, 'Y', 'SYSTEM', 'SYSTEM');

  -- RAW-P-003 (와이어프로텍터)
  INSERT INTO IQC_PART_SPEC_ITEMS (COMPANY, PLANT_CD, ITEM_CODE, SEQ, INSP_ITEM_CODE, LSL, USL, USE_YN, CREATED_BY, UPDATED_BY)
    VALUES ('40', '1000', 'RAW-P-003', 1, 'IQC-V-001', NULL, NULL, 'Y', 'SYSTEM', 'SYSTEM');
  INSERT INTO IQC_PART_SPEC_ITEMS (COMPANY, PLANT_CD, ITEM_CODE, SEQ, INSP_ITEM_CODE, LSL, USL, USE_YN, CREATED_BY, UPDATED_BY)
    VALUES ('40', '1000', 'RAW-P-003', 2, 'IQC-V-003', NULL, NULL, 'Y', 'SYSTEM', 'SYSTEM');
  INSERT INTO IQC_PART_SPEC_ITEMS (COMPANY, PLANT_CD, ITEM_CODE, SEQ, INSP_ITEM_CODE, LSL, USL, USE_YN, CREATED_BY, UPDATED_BY)
    VALUES ('40', '1000', 'RAW-P-003', 3, 'IQC-P-001', 8, 12, 'Y', 'SYSTEM', 'SYSTEM');

  -- RAW-P-004 (클립)
  INSERT INTO IQC_PART_SPEC_ITEMS (COMPANY, PLANT_CD, ITEM_CODE, SEQ, INSP_ITEM_CODE, LSL, USL, USE_YN, CREATED_BY, UPDATED_BY)
    VALUES ('40', '1000', 'RAW-P-004', 1, 'IQC-V-001', NULL, NULL, 'Y', 'SYSTEM', 'SYSTEM');
  INSERT INTO IQC_PART_SPEC_ITEMS (COMPANY, PLANT_CD, ITEM_CODE, SEQ, INSP_ITEM_CODE, LSL, USL, USE_YN, CREATED_BY, UPDATED_BY)
    VALUES ('40', '1000', 'RAW-P-004', 2, 'IQC-V-003', NULL, NULL, 'Y', 'SYSTEM', 'SYSTEM');
  INSERT INTO IQC_PART_SPEC_ITEMS (COMPANY, PLANT_CD, ITEM_CODE, SEQ, INSP_ITEM_CODE, LSL, USL, USE_YN, CREATED_BY, UPDATED_BY)
    VALUES ('40', '1000', 'RAW-P-004', 3, 'IQC-V-004', NULL, NULL, 'Y', 'SYSTEM', 'SYSTEM');

  -- RAW-P-005 (그로밋)
  INSERT INTO IQC_PART_SPEC_ITEMS (COMPANY, PLANT_CD, ITEM_CODE, SEQ, INSP_ITEM_CODE, LSL, USL, USE_YN, CREATED_BY, UPDATED_BY)
    VALUES ('40', '1000', 'RAW-P-005', 1, 'IQC-V-001', NULL, NULL, 'Y', 'SYSTEM', 'SYSTEM');
  INSERT INTO IQC_PART_SPEC_ITEMS (COMPANY, PLANT_CD, ITEM_CODE, SEQ, INSP_ITEM_CODE, LSL, USL, USE_YN, CREATED_BY, UPDATED_BY)
    VALUES ('40', '1000', 'RAW-P-005', 2, 'IQC-V-003', NULL, NULL, 'Y', 'SYSTEM', 'SYSTEM');
  INSERT INTO IQC_PART_SPEC_ITEMS (COMPANY, PLANT_CD, ITEM_CODE, SEQ, INSP_ITEM_CODE, LSL, USL, USE_YN, CREATED_BY, UPDATED_BY)
    VALUES ('40', '1000', 'RAW-P-005', 3, 'IQC-P-003', 9.8, 10.5, 'Y', 'SYSTEM', 'SYSTEM');

  -- RAW-T-001 (090형 암단자)
  INSERT INTO IQC_PART_SPEC_ITEMS (COMPANY, PLANT_CD, ITEM_CODE, SEQ, INSP_ITEM_CODE, LSL, USL, USE_YN, CREATED_BY, UPDATED_BY)
    VALUES ('40', '1000', 'RAW-T-001', 1, 'IQC-V-003', NULL, NULL, 'Y', 'SYSTEM', 'SYSTEM');
  INSERT INTO IQC_PART_SPEC_ITEMS (COMPANY, PLANT_CD, ITEM_CODE, SEQ, INSP_ITEM_CODE, LSL, USL, USE_YN, CREATED_BY, UPDATED_BY)
    VALUES ('40', '1000', 'RAW-T-001', 2, 'IQC-V-004', NULL, NULL, 'Y', 'SYSTEM', 'SYSTEM');
  INSERT INTO IQC_PART_SPEC_ITEMS (COMPANY, PLANT_CD, ITEM_CODE, SEQ, INSP_ITEM_CODE, LSL, USL, USE_YN, CREATED_BY, UPDATED_BY)
    VALUES ('40', '1000', 'RAW-T-001', 3, 'IQC-T-001', NULL, NULL, 'Y', 'SYSTEM', 'SYSTEM');
  INSERT INTO IQC_PART_SPEC_ITEMS (COMPANY, PLANT_CD, ITEM_CODE, SEQ, INSP_ITEM_CODE, LSL, USL, USE_YN, CREATED_BY, UPDATED_BY)
    VALUES ('40', '1000', 'RAW-T-001', 4, 'IQC-T-002', 0.85, 0.95, 'Y', 'SYSTEM', 'SYSTEM');
  INSERT INTO IQC_PART_SPEC_ITEMS (COMPANY, PLANT_CD, ITEM_CODE, SEQ, INSP_ITEM_CODE, LSL, USL, USE_YN, CREATED_BY, UPDATED_BY)
    VALUES ('40', '1000', 'RAW-T-001', 5, 'IQC-T-003', 0.8, 1.2, 'Y', 'SYSTEM', 'SYSTEM');
  INSERT INTO IQC_PART_SPEC_ITEMS (COMPANY, PLANT_CD, ITEM_CODE, SEQ, INSP_ITEM_CODE, LSL, USL, USE_YN, CREATED_BY, UPDATED_BY)
    VALUES ('40', '1000', 'RAW-T-001', 6, 'IQC-T-004', 0.9, 1.1, 'Y', 'SYSTEM', 'SYSTEM');
  INSERT INTO IQC_PART_SPEC_ITEMS (COMPANY, PLANT_CD, ITEM_CODE, SEQ, INSP_ITEM_CODE, LSL, USL, USE_YN, CREATED_BY, UPDATED_BY)
    VALUES ('40', '1000', 'RAW-T-001', 7, 'IQC-T-005', 30, NULL, 'Y', 'SYSTEM', 'SYSTEM');

  -- RAW-T-002 (090형 수단자)
  INSERT INTO IQC_PART_SPEC_ITEMS (COMPANY, PLANT_CD, ITEM_CODE, SEQ, INSP_ITEM_CODE, LSL, USL, USE_YN, CREATED_BY, UPDATED_BY)
    VALUES ('40', '1000', 'RAW-T-002', 1, 'IQC-V-003', NULL, NULL, 'Y', 'SYSTEM', 'SYSTEM');
  INSERT INTO IQC_PART_SPEC_ITEMS (COMPANY, PLANT_CD, ITEM_CODE, SEQ, INSP_ITEM_CODE, LSL, USL, USE_YN, CREATED_BY, UPDATED_BY)
    VALUES ('40', '1000', 'RAW-T-002', 2, 'IQC-V-004', NULL, NULL, 'Y', 'SYSTEM', 'SYSTEM');
  INSERT INTO IQC_PART_SPEC_ITEMS (COMPANY, PLANT_CD, ITEM_CODE, SEQ, INSP_ITEM_CODE, LSL, USL, USE_YN, CREATED_BY, UPDATED_BY)
    VALUES ('40', '1000', 'RAW-T-002', 3, 'IQC-T-001', NULL, NULL, 'Y', 'SYSTEM', 'SYSTEM');
  INSERT INTO IQC_PART_SPEC_ITEMS (COMPANY, PLANT_CD, ITEM_CODE, SEQ, INSP_ITEM_CODE, LSL, USL, USE_YN, CREATED_BY, UPDATED_BY)
    VALUES ('40', '1000', 'RAW-T-002', 4, 'IQC-T-002', 0.85, 0.95, 'Y', 'SYSTEM', 'SYSTEM');
  INSERT INTO IQC_PART_SPEC_ITEMS (COMPANY, PLANT_CD, ITEM_CODE, SEQ, INSP_ITEM_CODE, LSL, USL, USE_YN, CREATED_BY, UPDATED_BY)
    VALUES ('40', '1000', 'RAW-T-002', 5, 'IQC-T-003', 0.8, 1.2, 'Y', 'SYSTEM', 'SYSTEM');
  INSERT INTO IQC_PART_SPEC_ITEMS (COMPANY, PLANT_CD, ITEM_CODE, SEQ, INSP_ITEM_CODE, LSL, USL, USE_YN, CREATED_BY, UPDATED_BY)
    VALUES ('40', '1000', 'RAW-T-002', 6, 'IQC-T-004', 0.9, 1.1, 'Y', 'SYSTEM', 'SYSTEM');
  INSERT INTO IQC_PART_SPEC_ITEMS (COMPANY, PLANT_CD, ITEM_CODE, SEQ, INSP_ITEM_CODE, LSL, USL, USE_YN, CREATED_BY, UPDATED_BY)
    VALUES ('40', '1000', 'RAW-T-002', 7, 'IQC-T-005', 30, NULL, 'Y', 'SYSTEM', 'SYSTEM');

  -- RAW-T-003 (250형 암단자)
  INSERT INTO IQC_PART_SPEC_ITEMS (COMPANY, PLANT_CD, ITEM_CODE, SEQ, INSP_ITEM_CODE, LSL, USL, USE_YN, CREATED_BY, UPDATED_BY)
    VALUES ('40', '1000', 'RAW-T-003', 1, 'IQC-V-003', NULL, NULL, 'Y', 'SYSTEM', 'SYSTEM');
  INSERT INTO IQC_PART_SPEC_ITEMS (COMPANY, PLANT_CD, ITEM_CODE, SEQ, INSP_ITEM_CODE, LSL, USL, USE_YN, CREATED_BY, UPDATED_BY)
    VALUES ('40', '1000', 'RAW-T-003', 2, 'IQC-V-004', NULL, NULL, 'Y', 'SYSTEM', 'SYSTEM');
  INSERT INTO IQC_PART_SPEC_ITEMS (COMPANY, PLANT_CD, ITEM_CODE, SEQ, INSP_ITEM_CODE, LSL, USL, USE_YN, CREATED_BY, UPDATED_BY)
    VALUES ('40', '1000', 'RAW-T-003', 3, 'IQC-T-001', NULL, NULL, 'Y', 'SYSTEM', 'SYSTEM');
  INSERT INTO IQC_PART_SPEC_ITEMS (COMPANY, PLANT_CD, ITEM_CODE, SEQ, INSP_ITEM_CODE, LSL, USL, USE_YN, CREATED_BY, UPDATED_BY)
    VALUES ('40', '1000', 'RAW-T-003', 4, 'IQC-T-002', 2.4, 2.6, 'Y', 'SYSTEM', 'SYSTEM');
  INSERT INTO IQC_PART_SPEC_ITEMS (COMPANY, PLANT_CD, ITEM_CODE, SEQ, INSP_ITEM_CODE, LSL, USL, USE_YN, CREATED_BY, UPDATED_BY)
    VALUES ('40', '1000', 'RAW-T-003', 5, 'IQC-T-003', 2.0, 2.4, 'Y', 'SYSTEM', 'SYSTEM');
  INSERT INTO IQC_PART_SPEC_ITEMS (COMPANY, PLANT_CD, ITEM_CODE, SEQ, INSP_ITEM_CODE, LSL, USL, USE_YN, CREATED_BY, UPDATED_BY)
    VALUES ('40', '1000', 'RAW-T-003', 6, 'IQC-T-004', 2.5, 2.9, 'Y', 'SYSTEM', 'SYSTEM');
  INSERT INTO IQC_PART_SPEC_ITEMS (COMPANY, PLANT_CD, ITEM_CODE, SEQ, INSP_ITEM_CODE, LSL, USL, USE_YN, CREATED_BY, UPDATED_BY)
    VALUES ('40', '1000', 'RAW-T-003', 7, 'IQC-T-005', 50, NULL, 'Y', 'SYSTEM', 'SYSTEM');

  -- RAW-T-004 (250형 수단자)
  INSERT INTO IQC_PART_SPEC_ITEMS (COMPANY, PLANT_CD, ITEM_CODE, SEQ, INSP_ITEM_CODE, LSL, USL, USE_YN, CREATED_BY, UPDATED_BY)
    VALUES ('40', '1000', 'RAW-T-004', 1, 'IQC-V-003', NULL, NULL, 'Y', 'SYSTEM', 'SYSTEM');
  INSERT INTO IQC_PART_SPEC_ITEMS (COMPANY, PLANT_CD, ITEM_CODE, SEQ, INSP_ITEM_CODE, LSL, USL, USE_YN, CREATED_BY, UPDATED_BY)
    VALUES ('40', '1000', 'RAW-T-004', 2, 'IQC-V-004', NULL, NULL, 'Y', 'SYSTEM', 'SYSTEM');
  INSERT INTO IQC_PART_SPEC_ITEMS (COMPANY, PLANT_CD, ITEM_CODE, SEQ, INSP_ITEM_CODE, LSL, USL, USE_YN, CREATED_BY, UPDATED_BY)
    VALUES ('40', '1000', 'RAW-T-004', 3, 'IQC-T-001', NULL, NULL, 'Y', 'SYSTEM', 'SYSTEM');
  INSERT INTO IQC_PART_SPEC_ITEMS (COMPANY, PLANT_CD, ITEM_CODE, SEQ, INSP_ITEM_CODE, LSL, USL, USE_YN, CREATED_BY, UPDATED_BY)
    VALUES ('40', '1000', 'RAW-T-004', 4, 'IQC-T-002', 2.4, 2.6, 'Y', 'SYSTEM', 'SYSTEM');
  INSERT INTO IQC_PART_SPEC_ITEMS (COMPANY, PLANT_CD, ITEM_CODE, SEQ, INSP_ITEM_CODE, LSL, USL, USE_YN, CREATED_BY, UPDATED_BY)
    VALUES ('40', '1000', 'RAW-T-004', 5, 'IQC-T-003', 2.0, 2.4, 'Y', 'SYSTEM', 'SYSTEM');
  INSERT INTO IQC_PART_SPEC_ITEMS (COMPANY, PLANT_CD, ITEM_CODE, SEQ, INSP_ITEM_CODE, LSL, USL, USE_YN, CREATED_BY, UPDATED_BY)
    VALUES ('40', '1000', 'RAW-T-004', 6, 'IQC-T-004', 2.5, 2.9, 'Y', 'SYSTEM', 'SYSTEM');
  INSERT INTO IQC_PART_SPEC_ITEMS (COMPANY, PLANT_CD, ITEM_CODE, SEQ, INSP_ITEM_CODE, LSL, USL, USE_YN, CREATED_BY, UPDATED_BY)
    VALUES ('40', '1000', 'RAW-T-004', 7, 'IQC-T-005', 50, NULL, 'Y', 'SYSTEM', 'SYSTEM');

  -- RAW-T-005 (환형단자 M6)
  INSERT INTO IQC_PART_SPEC_ITEMS (COMPANY, PLANT_CD, ITEM_CODE, SEQ, INSP_ITEM_CODE, LSL, USL, USE_YN, CREATED_BY, UPDATED_BY)
    VALUES ('40', '1000', 'RAW-T-005', 1, 'IQC-V-003', NULL, NULL, 'Y', 'SYSTEM', 'SYSTEM');
  INSERT INTO IQC_PART_SPEC_ITEMS (COMPANY, PLANT_CD, ITEM_CODE, SEQ, INSP_ITEM_CODE, LSL, USL, USE_YN, CREATED_BY, UPDATED_BY)
    VALUES ('40', '1000', 'RAW-T-005', 2, 'IQC-V-004', NULL, NULL, 'Y', 'SYSTEM', 'SYSTEM');
  INSERT INTO IQC_PART_SPEC_ITEMS (COMPANY, PLANT_CD, ITEM_CODE, SEQ, INSP_ITEM_CODE, LSL, USL, USE_YN, CREATED_BY, UPDATED_BY)
    VALUES ('40', '1000', 'RAW-T-005', 3, 'IQC-T-001', NULL, NULL, 'Y', 'SYSTEM', 'SYSTEM');
  INSERT INTO IQC_PART_SPEC_ITEMS (COMPANY, PLANT_CD, ITEM_CODE, SEQ, INSP_ITEM_CODE, LSL, USL, USE_YN, CREATED_BY, UPDATED_BY)
    VALUES ('40', '1000', 'RAW-T-005', 4, 'IQC-T-005', 100, NULL, 'Y', 'SYSTEM', 'SYSTEM');

  -- RAW-W-001 (AVS 0.5sq 흑색 전선)
  INSERT INTO IQC_PART_SPEC_ITEMS (COMPANY, PLANT_CD, ITEM_CODE, SEQ, INSP_ITEM_CODE, LSL, USL, USE_YN, CREATED_BY, UPDATED_BY)
    VALUES ('40', '1000', 'RAW-W-001', 1, 'IQC-V-002', NULL, NULL, 'Y', 'SYSTEM', 'SYSTEM');
  INSERT INTO IQC_PART_SPEC_ITEMS (COMPANY, PLANT_CD, ITEM_CODE, SEQ, INSP_ITEM_CODE, LSL, USL, USE_YN, CREATED_BY, UPDATED_BY)
    VALUES ('40', '1000', 'RAW-W-001', 2, 'IQC-V-003', NULL, NULL, 'Y', 'SYSTEM', 'SYSTEM');
  INSERT INTO IQC_PART_SPEC_ITEMS (COMPANY, PLANT_CD, ITEM_CODE, SEQ, INSP_ITEM_CODE, LSL, USL, USE_YN, CREATED_BY, UPDATED_BY)
    VALUES ('40', '1000', 'RAW-W-001', 3, 'IQC-V-004', NULL, NULL, 'Y', 'SYSTEM', 'SYSTEM');
  INSERT INTO IQC_PART_SPEC_ITEMS (COMPANY, PLANT_CD, ITEM_CODE, SEQ, INSP_ITEM_CODE, LSL, USL, USE_YN, CREATED_BY, UPDATED_BY)
    VALUES ('40', '1000', 'RAW-W-001', 4, 'IQC-W-001', 1.5, 2.0, 'Y', 'SYSTEM', 'SYSTEM');
  INSERT INTO IQC_PART_SPEC_ITEMS (COMPANY, PLANT_CD, ITEM_CODE, SEQ, INSP_ITEM_CODE, LSL, USL, USE_YN, CREATED_BY, UPDATED_BY)
    VALUES ('40', '1000', 'RAW-W-001', 5, 'IQC-W-002', 0.3, 0.6, 'Y', 'SYSTEM', 'SYSTEM');
  INSERT INTO IQC_PART_SPEC_ITEMS (COMPANY, PLANT_CD, ITEM_CODE, SEQ, INSP_ITEM_CODE, LSL, USL, USE_YN, CREATED_BY, UPDATED_BY)
    VALUES ('40', '1000', 'RAW-W-001', 6, 'IQC-W-003', NULL, 39, 'Y', 'SYSTEM', 'SYSTEM');
  INSERT INTO IQC_PART_SPEC_ITEMS (COMPANY, PLANT_CD, ITEM_CODE, SEQ, INSP_ITEM_CODE, LSL, USL, USE_YN, CREATED_BY, UPDATED_BY)
    VALUES ('40', '1000', 'RAW-W-001', 7, 'IQC-W-004', 1000, NULL, 'Y', 'SYSTEM', 'SYSTEM');
  INSERT INTO IQC_PART_SPEC_ITEMS (COMPANY, PLANT_CD, ITEM_CODE, SEQ, INSP_ITEM_CODE, LSL, USL, USE_YN, CREATED_BY, UPDATED_BY)
    VALUES ('40', '1000', 'RAW-W-001', 8, 'IQC-W-005', NULL, NULL, 'Y', 'SYSTEM', 'SYSTEM');

  -- RAW-W-002 (AVS 0.85sq 적색 전선)
  INSERT INTO IQC_PART_SPEC_ITEMS (COMPANY, PLANT_CD, ITEM_CODE, SEQ, INSP_ITEM_CODE, LSL, USL, USE_YN, CREATED_BY, UPDATED_BY)
    VALUES ('40', '1000', 'RAW-W-002', 1, 'IQC-V-002', NULL, NULL, 'Y', 'SYSTEM', 'SYSTEM');
  INSERT INTO IQC_PART_SPEC_ITEMS (COMPANY, PLANT_CD, ITEM_CODE, SEQ, INSP_ITEM_CODE, LSL, USL, USE_YN, CREATED_BY, UPDATED_BY)
    VALUES ('40', '1000', 'RAW-W-002', 2, 'IQC-V-003', NULL, NULL, 'Y', 'SYSTEM', 'SYSTEM');
  INSERT INTO IQC_PART_SPEC_ITEMS (COMPANY, PLANT_CD, ITEM_CODE, SEQ, INSP_ITEM_CODE, LSL, USL, USE_YN, CREATED_BY, UPDATED_BY)
    VALUES ('40', '1000', 'RAW-W-002', 3, 'IQC-V-004', NULL, NULL, 'Y', 'SYSTEM', 'SYSTEM');
  INSERT INTO IQC_PART_SPEC_ITEMS (COMPANY, PLANT_CD, ITEM_CODE, SEQ, INSP_ITEM_CODE, LSL, USL, USE_YN, CREATED_BY, UPDATED_BY)
    VALUES ('40', '1000', 'RAW-W-002', 4, 'IQC-W-001', 2.0, 2.5, 'Y', 'SYSTEM', 'SYSTEM');
  INSERT INTO IQC_PART_SPEC_ITEMS (COMPANY, PLANT_CD, ITEM_CODE, SEQ, INSP_ITEM_CODE, LSL, USL, USE_YN, CREATED_BY, UPDATED_BY)
    VALUES ('40', '1000', 'RAW-W-002', 5, 'IQC-W-002', 0.3, 0.6, 'Y', 'SYSTEM', 'SYSTEM');
  INSERT INTO IQC_PART_SPEC_ITEMS (COMPANY, PLANT_CD, ITEM_CODE, SEQ, INSP_ITEM_CODE, LSL, USL, USE_YN, CREATED_BY, UPDATED_BY)
    VALUES ('40', '1000', 'RAW-W-002', 6, 'IQC-W-003', NULL, 23, 'Y', 'SYSTEM', 'SYSTEM');
  INSERT INTO IQC_PART_SPEC_ITEMS (COMPANY, PLANT_CD, ITEM_CODE, SEQ, INSP_ITEM_CODE, LSL, USL, USE_YN, CREATED_BY, UPDATED_BY)
    VALUES ('40', '1000', 'RAW-W-002', 7, 'IQC-W-004', 1000, NULL, 'Y', 'SYSTEM', 'SYSTEM');
  INSERT INTO IQC_PART_SPEC_ITEMS (COMPANY, PLANT_CD, ITEM_CODE, SEQ, INSP_ITEM_CODE, LSL, USL, USE_YN, CREATED_BY, UPDATED_BY)
    VALUES ('40', '1000', 'RAW-W-002', 8, 'IQC-W-005', NULL, NULL, 'Y', 'SYSTEM', 'SYSTEM');

  -- RAW-W-003 (AVS 1.25sq 청색 전선)
  INSERT INTO IQC_PART_SPEC_ITEMS (COMPANY, PLANT_CD, ITEM_CODE, SEQ, INSP_ITEM_CODE, LSL, USL, USE_YN, CREATED_BY, UPDATED_BY)
    VALUES ('40', '1000', 'RAW-W-003', 1, 'IQC-V-002', NULL, NULL, 'Y', 'SYSTEM', 'SYSTEM');
  INSERT INTO IQC_PART_SPEC_ITEMS (COMPANY, PLANT_CD, ITEM_CODE, SEQ, INSP_ITEM_CODE, LSL, USL, USE_YN, CREATED_BY, UPDATED_BY)
    VALUES ('40', '1000', 'RAW-W-003', 2, 'IQC-V-003', NULL, NULL, 'Y', 'SYSTEM', 'SYSTEM');
  INSERT INTO IQC_PART_SPEC_ITEMS (COMPANY, PLANT_CD, ITEM_CODE, SEQ, INSP_ITEM_CODE, LSL, USL, USE_YN, CREATED_BY, UPDATED_BY)
    VALUES ('40', '1000', 'RAW-W-003', 3, 'IQC-V-004', NULL, NULL, 'Y', 'SYSTEM', 'SYSTEM');
  INSERT INTO IQC_PART_SPEC_ITEMS (COMPANY, PLANT_CD, ITEM_CODE, SEQ, INSP_ITEM_CODE, LSL, USL, USE_YN, CREATED_BY, UPDATED_BY)
    VALUES ('40', '1000', 'RAW-W-003', 4, 'IQC-W-001', 2.5, 3.0, 'Y', 'SYSTEM', 'SYSTEM');
  INSERT INTO IQC_PART_SPEC_ITEMS (COMPANY, PLANT_CD, ITEM_CODE, SEQ, INSP_ITEM_CODE, LSL, USL, USE_YN, CREATED_BY, UPDATED_BY)
    VALUES ('40', '1000', 'RAW-W-003', 5, 'IQC-W-002', 0.3, 0.6, 'Y', 'SYSTEM', 'SYSTEM');
  INSERT INTO IQC_PART_SPEC_ITEMS (COMPANY, PLANT_CD, ITEM_CODE, SEQ, INSP_ITEM_CODE, LSL, USL, USE_YN, CREATED_BY, UPDATED_BY)
    VALUES ('40', '1000', 'RAW-W-003', 6, 'IQC-W-003', NULL, 15.2, 'Y', 'SYSTEM', 'SYSTEM');
  INSERT INTO IQC_PART_SPEC_ITEMS (COMPANY, PLANT_CD, ITEM_CODE, SEQ, INSP_ITEM_CODE, LSL, USL, USE_YN, CREATED_BY, UPDATED_BY)
    VALUES ('40', '1000', 'RAW-W-003', 7, 'IQC-W-004', 1000, NULL, 'Y', 'SYSTEM', 'SYSTEM');
  INSERT INTO IQC_PART_SPEC_ITEMS (COMPANY, PLANT_CD, ITEM_CODE, SEQ, INSP_ITEM_CODE, LSL, USL, USE_YN, CREATED_BY, UPDATED_BY)
    VALUES ('40', '1000', 'RAW-W-003', 8, 'IQC-W-005', NULL, NULL, 'Y', 'SYSTEM', 'SYSTEM');

  -- RAW-W-004 (AVS 2.0sq 황색 전선)
  INSERT INTO IQC_PART_SPEC_ITEMS (COMPANY, PLANT_CD, ITEM_CODE, SEQ, INSP_ITEM_CODE, LSL, USL, USE_YN, CREATED_BY, UPDATED_BY)
    VALUES ('40', '1000', 'RAW-W-004', 1, 'IQC-V-002', NULL, NULL, 'Y', 'SYSTEM', 'SYSTEM');
  INSERT INTO IQC_PART_SPEC_ITEMS (COMPANY, PLANT_CD, ITEM_CODE, SEQ, INSP_ITEM_CODE, LSL, USL, USE_YN, CREATED_BY, UPDATED_BY)
    VALUES ('40', '1000', 'RAW-W-004', 2, 'IQC-V-003', NULL, NULL, 'Y', 'SYSTEM', 'SYSTEM');
  INSERT INTO IQC_PART_SPEC_ITEMS (COMPANY, PLANT_CD, ITEM_CODE, SEQ, INSP_ITEM_CODE, LSL, USL, USE_YN, CREATED_BY, UPDATED_BY)
    VALUES ('40', '1000', 'RAW-W-004', 3, 'IQC-V-004', NULL, NULL, 'Y', 'SYSTEM', 'SYSTEM');
  INSERT INTO IQC_PART_SPEC_ITEMS (COMPANY, PLANT_CD, ITEM_CODE, SEQ, INSP_ITEM_CODE, LSL, USL, USE_YN, CREATED_BY, UPDATED_BY)
    VALUES ('40', '1000', 'RAW-W-004', 4, 'IQC-W-001', 3.2, 3.8, 'Y', 'SYSTEM', 'SYSTEM');
  INSERT INTO IQC_PART_SPEC_ITEMS (COMPANY, PLANT_CD, ITEM_CODE, SEQ, INSP_ITEM_CODE, LSL, USL, USE_YN, CREATED_BY, UPDATED_BY)
    VALUES ('40', '1000', 'RAW-W-004', 5, 'IQC-W-002', 0.35, 0.65, 'Y', 'SYSTEM', 'SYSTEM');
  INSERT INTO IQC_PART_SPEC_ITEMS (COMPANY, PLANT_CD, ITEM_CODE, SEQ, INSP_ITEM_CODE, LSL, USL, USE_YN, CREATED_BY, UPDATED_BY)
    VALUES ('40', '1000', 'RAW-W-004', 6, 'IQC-W-003', NULL, 9.61, 'Y', 'SYSTEM', 'SYSTEM');
  INSERT INTO IQC_PART_SPEC_ITEMS (COMPANY, PLANT_CD, ITEM_CODE, SEQ, INSP_ITEM_CODE, LSL, USL, USE_YN, CREATED_BY, UPDATED_BY)
    VALUES ('40', '1000', 'RAW-W-004', 7, 'IQC-W-004', 1000, NULL, 'Y', 'SYSTEM', 'SYSTEM');
  INSERT INTO IQC_PART_SPEC_ITEMS (COMPANY, PLANT_CD, ITEM_CODE, SEQ, INSP_ITEM_CODE, LSL, USL, USE_YN, CREATED_BY, UPDATED_BY)
    VALUES ('40', '1000', 'RAW-W-004', 8, 'IQC-W-005', NULL, NULL, 'Y', 'SYSTEM', 'SYSTEM');

  -- RAW-W-005 (AVSS 0.5sq 백색 전선)
  INSERT INTO IQC_PART_SPEC_ITEMS (COMPANY, PLANT_CD, ITEM_CODE, SEQ, INSP_ITEM_CODE, LSL, USL, USE_YN, CREATED_BY, UPDATED_BY)
    VALUES ('40', '1000', 'RAW-W-005', 1, 'IQC-V-002', NULL, NULL, 'Y', 'SYSTEM', 'SYSTEM');
  INSERT INTO IQC_PART_SPEC_ITEMS (COMPANY, PLANT_CD, ITEM_CODE, SEQ, INSP_ITEM_CODE, LSL, USL, USE_YN, CREATED_BY, UPDATED_BY)
    VALUES ('40', '1000', 'RAW-W-005', 2, 'IQC-V-003', NULL, NULL, 'Y', 'SYSTEM', 'SYSTEM');
  INSERT INTO IQC_PART_SPEC_ITEMS (COMPANY, PLANT_CD, ITEM_CODE, SEQ, INSP_ITEM_CODE, LSL, USL, USE_YN, CREATED_BY, UPDATED_BY)
    VALUES ('40', '1000', 'RAW-W-005', 3, 'IQC-V-004', NULL, NULL, 'Y', 'SYSTEM', 'SYSTEM');
  INSERT INTO IQC_PART_SPEC_ITEMS (COMPANY, PLANT_CD, ITEM_CODE, SEQ, INSP_ITEM_CODE, LSL, USL, USE_YN, CREATED_BY, UPDATED_BY)
    VALUES ('40', '1000', 'RAW-W-005', 4, 'IQC-W-001', 1.4, 1.9, 'Y', 'SYSTEM', 'SYSTEM');
  INSERT INTO IQC_PART_SPEC_ITEMS (COMPANY, PLANT_CD, ITEM_CODE, SEQ, INSP_ITEM_CODE, LSL, USL, USE_YN, CREATED_BY, UPDATED_BY)
    VALUES ('40', '1000', 'RAW-W-005', 5, 'IQC-W-002', 0.25, 0.5, 'Y', 'SYSTEM', 'SYSTEM');
  INSERT INTO IQC_PART_SPEC_ITEMS (COMPANY, PLANT_CD, ITEM_CODE, SEQ, INSP_ITEM_CODE, LSL, USL, USE_YN, CREATED_BY, UPDATED_BY)
    VALUES ('40', '1000', 'RAW-W-005', 6, 'IQC-W-003', NULL, 39, 'Y', 'SYSTEM', 'SYSTEM');
  INSERT INTO IQC_PART_SPEC_ITEMS (COMPANY, PLANT_CD, ITEM_CODE, SEQ, INSP_ITEM_CODE, LSL, USL, USE_YN, CREATED_BY, UPDATED_BY)
    VALUES ('40', '1000', 'RAW-W-005', 7, 'IQC-W-004', 1000, NULL, 'Y', 'SYSTEM', 'SYSTEM');
  INSERT INTO IQC_PART_SPEC_ITEMS (COMPANY, PLANT_CD, ITEM_CODE, SEQ, INSP_ITEM_CODE, LSL, USL, USE_YN, CREATED_BY, UPDATED_BY)
    VALUES ('40', '1000', 'RAW-W-005', 8, 'IQC-W-005', NULL, NULL, 'Y', 'SYSTEM', 'SYSTEM');

  COMMIT;
END;
/
