-- 자주검사 항목 마스터 시드 데이터 (하네스 제조 공정 기준)
-- SELF_INSPECT_ITEMS 테이블
-- JSHANES 사이트: COMPANY='40', PLANT_CD='1000'
-- INSPECT_METHOD: DIRECT(직접검사) | DELEGATE(의뢰검사)
-- TIMING: FIRST(초물), MID(중물), LAST(종물) — 콤마 구분 복수 가능
-- IS_DESTRUCTIVE: 1=파괴검사, 0=비파괴검사

-- =============================================
-- PRC-CRIMP (압착 공정)
-- =============================================
INSERT INTO "SELF_INSPECT_ITEMS"
  ("ID","PROCESS_CODE","ITEM_NAME","STANDARD","INSPECT_METHOD","TIMING","IS_DESTRUCTIVE","SORT_ORDER","USE_YN","COMPANY","PLANT_CD","CREATED_AT","UPDATED_AT")
VALUES (SYS_GUID(),'PRC-CRIMP','압착 단면 검사 (CS 검사)','압착 단면이 원형이며 절연체·도체 비율 기준 내','DIRECT','FIRST,MID',1,1,'Y','40','1000',SYSDATE,SYSDATE);

INSERT INTO "SELF_INSPECT_ITEMS"
  ("ID","PROCESS_CODE","ITEM_NAME","STANDARD","INSPECT_METHOD","TIMING","IS_DESTRUCTIVE","SORT_ORDER","USE_YN","COMPANY","PLANT_CD","CREATED_AT","UPDATED_AT")
VALUES (SYS_GUID(),'PRC-CRIMP','압착 높이(CH) 측정','도면 기준 ±0.05mm 이내','DIRECT','FIRST,MID',0,2,'Y','40','1000',SYSDATE,SYSDATE);

INSERT INTO "SELF_INSPECT_ITEMS"
  ("ID","PROCESS_CODE","ITEM_NAME","STANDARD","INSPECT_METHOD","TIMING","IS_DESTRUCTIVE","SORT_ORDER","USE_YN","COMPANY","PLANT_CD","CREATED_AT","UPDATED_AT")
VALUES (SYS_GUID(),'PRC-CRIMP','압착 폭(CW) 측정','도면 기준 ±0.1mm 이내','DIRECT','FIRST',0,3,'Y','40','1000',SYSDATE,SYSDATE);

INSERT INTO "SELF_INSPECT_ITEMS"
  ("ID","PROCESS_CODE","ITEM_NAME","STANDARD","INSPECT_METHOD","TIMING","IS_DESTRUCTIVE","SORT_ORDER","USE_YN","COMPANY","PLANT_CD","CREATED_AT","UPDATED_AT")
VALUES (SYS_GUID(),'PRC-CRIMP','전선 인출 길이','도면 기준 ±1mm 이내','DIRECT','FIRST,MID',0,4,'Y','40','1000',SYSDATE,SYSDATE);

INSERT INTO "SELF_INSPECT_ITEMS"
  ("ID","PROCESS_CODE","ITEM_NAME","STANDARD","INSPECT_METHOD","TIMING","IS_DESTRUCTIVE","SORT_ORDER","USE_YN","COMPANY","PLANT_CD","CREATED_AT","UPDATED_AT")
VALUES (SYS_GUID(),'PRC-CRIMP','인장강도 시험 (Pull test)','규격 이상 하중에서 단선 없을 것','DELEGATE','FIRST',1,5,'Y','40','1000',SYSDATE,SYSDATE);

INSERT INTO "SELF_INSPECT_ITEMS"
  ("ID","PROCESS_CODE","ITEM_NAME","STANDARD","INSPECT_METHOD","TIMING","IS_DESTRUCTIVE","SORT_ORDER","USE_YN","COMPANY","PLANT_CD","CREATED_AT","UPDATED_AT")
VALUES (SYS_GUID(),'PRC-CRIMP','절연체 손상 여부','절연 피복 찍힘·손상 없을 것','DIRECT','FIRST,MID,LAST',0,6,'Y','40','1000',SYSDATE,SYSDATE);

-- =============================================
-- PRC-CUT (절단 공정)
-- =============================================
INSERT INTO "SELF_INSPECT_ITEMS"
  ("ID","PROCESS_CODE","ITEM_NAME","STANDARD","INSPECT_METHOD","TIMING","IS_DESTRUCTIVE","SORT_ORDER","USE_YN","COMPANY","PLANT_CD","CREATED_AT","UPDATED_AT")
VALUES (SYS_GUID(),'PRC-CUT','전선 절단 길이 측정','도면 기준 ±2mm 이내','DIRECT','FIRST,MID',0,1,'Y','40','1000',SYSDATE,SYSDATE);

INSERT INTO "SELF_INSPECT_ITEMS"
  ("ID","PROCESS_CODE","ITEM_NAME","STANDARD","INSPECT_METHOD","TIMING","IS_DESTRUCTIVE","SORT_ORDER","USE_YN","COMPANY","PLANT_CD","CREATED_AT","UPDATED_AT")
VALUES (SYS_GUID(),'PRC-CUT','절단면 상태 확인','단면 직각, 심선 손상 없을 것','DIRECT','FIRST,MID',0,2,'Y','40','1000',SYSDATE,SYSDATE);

INSERT INTO "SELF_INSPECT_ITEMS"
  ("ID","PROCESS_CODE","ITEM_NAME","STANDARD","INSPECT_METHOD","TIMING","IS_DESTRUCTIVE","SORT_ORDER","USE_YN","COMPANY","PLANT_CD","CREATED_AT","UPDATED_AT")
VALUES (SYS_GUID(),'PRC-CUT','전선 색상·규격 확인','작업지시서 지정 색상·단면적 일치','DIRECT','FIRST',0,3,'Y','40','1000',SYSDATE,SYSDATE);

-- =============================================
-- PRC-STRIP (탈피 공정)
-- =============================================
INSERT INTO "SELF_INSPECT_ITEMS"
  ("ID","PROCESS_CODE","ITEM_NAME","STANDARD","INSPECT_METHOD","TIMING","IS_DESTRUCTIVE","SORT_ORDER","USE_YN","COMPANY","PLANT_CD","CREATED_AT","UPDATED_AT")
VALUES (SYS_GUID(),'PRC-STRIP','탈피 길이 측정','도면 기준 ±0.5mm 이내','DIRECT','FIRST,MID',0,1,'Y','40','1000',SYSDATE,SYSDATE);

INSERT INTO "SELF_INSPECT_ITEMS"
  ("ID","PROCESS_CODE","ITEM_NAME","STANDARD","INSPECT_METHOD","TIMING","IS_DESTRUCTIVE","SORT_ORDER","USE_YN","COMPANY","PLANT_CD","CREATED_AT","UPDATED_AT")
VALUES (SYS_GUID(),'PRC-STRIP','절연체 손상 여부 확인','탈피 부위 인접 절연 피복 손상 없을 것','DIRECT','FIRST,MID',0,2,'Y','40','1000',SYSDATE,SYSDATE);

INSERT INTO "SELF_INSPECT_ITEMS"
  ("ID","PROCESS_CODE","ITEM_NAME","STANDARD","INSPECT_METHOD","TIMING","IS_DESTRUCTIVE","SORT_ORDER","USE_YN","COMPANY","PLANT_CD","CREATED_AT","UPDATED_AT")
VALUES (SYS_GUID(),'PRC-STRIP','심선 단선 여부 확인','심선 가닥 수 100% 유지, 단선 없을 것','DIRECT','FIRST,MID',0,3,'Y','40','1000',SYSDATE,SYSDATE);

-- =============================================
-- PRC-ASSY (조립 공정)
-- =============================================
INSERT INTO "SELF_INSPECT_ITEMS"
  ("ID","PROCESS_CODE","ITEM_NAME","STANDARD","INSPECT_METHOD","TIMING","IS_DESTRUCTIVE","SORT_ORDER","USE_YN","COMPANY","PLANT_CD","CREATED_AT","UPDATED_AT")
VALUES (SYS_GUID(),'PRC-ASSY','커넥터 체결 상태 확인','딸깍 소리 확인, 불완전 체결 없을 것','DIRECT','FIRST,MID,LAST',0,1,'Y','40','1000',SYSDATE,SYSDATE);

INSERT INTO "SELF_INSPECT_ITEMS"
  ("ID","PROCESS_CODE","ITEM_NAME","STANDARD","INSPECT_METHOD","TIMING","IS_DESTRUCTIVE","SORT_ORDER","USE_YN","COMPANY","PLANT_CD","CREATED_AT","UPDATED_AT")
VALUES (SYS_GUID(),'PRC-ASSY','전선 배열 순서 확인','회로도 기준 핀 배열 일치','DIRECT','FIRST,MID',0,2,'Y','40','1000',SYSDATE,SYSDATE);

INSERT INTO "SELF_INSPECT_ITEMS"
  ("ID","PROCESS_CODE","ITEM_NAME","STANDARD","INSPECT_METHOD","TIMING","IS_DESTRUCTIVE","SORT_ORDER","USE_YN","COMPANY","PLANT_CD","CREATED_AT","UPDATED_AT")
VALUES (SYS_GUID(),'PRC-ASSY','전선 꼬임·교차 여부','전선 꼬임, 불필요한 교차 없을 것','DIRECT','FIRST,MID',0,3,'Y','40','1000',SYSDATE,SYSDATE);

INSERT INTO "SELF_INSPECT_ITEMS"
  ("ID","PROCESS_CODE","ITEM_NAME","STANDARD","INSPECT_METHOD","TIMING","IS_DESTRUCTIVE","SORT_ORDER","USE_YN","COMPANY","PLANT_CD","CREATED_AT","UPDATED_AT")
VALUES (SYS_GUID(),'PRC-ASSY','도통 검사','전체 회로 도통 OK, 단선·혼선 없을 것','DELEGATE','FIRST',0,4,'Y','40','1000',SYSDATE,SYSDATE);

-- =============================================
-- PRC-TAPE (테이핑 공정)
-- =============================================
INSERT INTO "SELF_INSPECT_ITEMS"
  ("ID","PROCESS_CODE","ITEM_NAME","STANDARD","INSPECT_METHOD","TIMING","IS_DESTRUCTIVE","SORT_ORDER","USE_YN","COMPANY","PLANT_CD","CREATED_AT","UPDATED_AT")
VALUES (SYS_GUID(),'PRC-TAPE','테이핑 피치(간격) 확인','테이프 겹침 1/2 이상, 빈틈 없을 것','DIRECT','FIRST,MID',0,1,'Y','40','1000',SYSDATE,SYSDATE);

INSERT INTO "SELF_INSPECT_ITEMS"
  ("ID","PROCESS_CODE","ITEM_NAME","STANDARD","INSPECT_METHOD","TIMING","IS_DESTRUCTIVE","SORT_ORDER","USE_YN","COMPANY","PLANT_CD","CREATED_AT","UPDATED_AT")
VALUES (SYS_GUID(),'PRC-TAPE','테이핑 위치 및 범위 확인','도면 기준 시작/끝 위치 ±5mm 이내','DIRECT','FIRST,MID',0,2,'Y','40','1000',SYSDATE,SYSDATE);

INSERT INTO "SELF_INSPECT_ITEMS"
  ("ID","PROCESS_CODE","ITEM_NAME","STANDARD","INSPECT_METHOD","TIMING","IS_DESTRUCTIVE","SORT_ORDER","USE_YN","COMPANY","PLANT_CD","CREATED_AT","UPDATED_AT")
VALUES (SYS_GUID(),'PRC-TAPE','테이프 종류·색상 확인','작업지시서 지정 테이프 사용','DIRECT','FIRST',0,3,'Y','40','1000',SYSDATE,SYSDATE);

-- =============================================
-- PRC-PRESUB (선조립 공정)
-- =============================================
INSERT INTO "SELF_INSPECT_ITEMS"
  ("ID","PROCESS_CODE","ITEM_NAME","STANDARD","INSPECT_METHOD","TIMING","IS_DESTRUCTIVE","SORT_ORDER","USE_YN","COMPANY","PLANT_CD","CREATED_AT","UPDATED_AT")
VALUES (SYS_GUID(),'PRC-PRESUB','선조립 형상 확인','도면 기준 가지 분기 위치 ±10mm 이내','DIRECT','FIRST,MID',0,1,'Y','40','1000',SYSDATE,SYSDATE);

INSERT INTO "SELF_INSPECT_ITEMS"
  ("ID","PROCESS_CODE","ITEM_NAME","STANDARD","INSPECT_METHOD","TIMING","IS_DESTRUCTIVE","SORT_ORDER","USE_YN","COMPANY","PLANT_CD","CREATED_AT","UPDATED_AT")
VALUES (SYS_GUID(),'PRC-PRESUB','클립·고정류 체결 확인','도면 지정 위치에 클립 누락 없을 것','DIRECT','FIRST,MID',0,2,'Y','40','1000',SYSDATE,SYSDATE);

-- =============================================
-- PRC-TEST (검사 공정)
-- =============================================
INSERT INTO "SELF_INSPECT_ITEMS"
  ("ID","PROCESS_CODE","ITEM_NAME","STANDARD","INSPECT_METHOD","TIMING","IS_DESTRUCTIVE","SORT_ORDER","USE_YN","COMPANY","PLANT_CD","CREATED_AT","UPDATED_AT")
VALUES (SYS_GUID(),'PRC-TEST','전기 도통 검사','전체 회로 도통 OK, 오결선 없을 것','DIRECT','FIRST,MID,LAST',0,1,'Y','40','1000',SYSDATE,SYSDATE);

INSERT INTO "SELF_INSPECT_ITEMS"
  ("ID","PROCESS_CODE","ITEM_NAME","STANDARD","INSPECT_METHOD","TIMING","IS_DESTRUCTIVE","SORT_ORDER","USE_YN","COMPANY","PLANT_CD","CREATED_AT","UPDATED_AT")
VALUES (SYS_GUID(),'PRC-TEST','절연 저항 측정','500V 인가 시 1MΩ 이상','DELEGATE','FIRST',0,2,'Y','40','1000',SYSDATE,SYSDATE);

INSERT INTO "SELF_INSPECT_ITEMS"
  ("ID","PROCESS_CODE","ITEM_NAME","STANDARD","INSPECT_METHOD","TIMING","IS_DESTRUCTIVE","SORT_ORDER","USE_YN","COMPANY","PLANT_CD","CREATED_AT","UPDATED_AT")
VALUES (SYS_GUID(),'PRC-TEST','외관 최종 확인','찍힘·긁힘·오염 없을 것','DIRECT','LAST',0,3,'Y','40','1000',SYSDATE,SYSDATE);

-- =============================================
-- PRC-PACK (포장 공정)
-- =============================================
INSERT INTO "SELF_INSPECT_ITEMS"
  ("ID","PROCESS_CODE","ITEM_NAME","STANDARD","INSPECT_METHOD","TIMING","IS_DESTRUCTIVE","SORT_ORDER","USE_YN","COMPANY","PLANT_CD","CREATED_AT","UPDATED_AT")
VALUES (SYS_GUID(),'PRC-PACK','포장 수량 확인','작업지시 수량과 실포장 수량 일치','DIRECT','FIRST,MID,LAST',0,1,'Y','40','1000',SYSDATE,SYSDATE);

INSERT INTO "SELF_INSPECT_ITEMS"
  ("ID","PROCESS_CODE","ITEM_NAME","STANDARD","INSPECT_METHOD","TIMING","IS_DESTRUCTIVE","SORT_ORDER","USE_YN","COMPANY","PLANT_CD","CREATED_AT","UPDATED_AT")
VALUES (SYS_GUID(),'PRC-PACK','라벨 부착 확인','품번·Lot No·수량 정확, 오부착 없을 것','DIRECT','FIRST,LAST',0,2,'Y','40','1000',SYSDATE,SYSDATE);

INSERT INTO "SELF_INSPECT_ITEMS"
  ("ID","PROCESS_CODE","ITEM_NAME","STANDARD","INSPECT_METHOD","TIMING","IS_DESTRUCTIVE","SORT_ORDER","USE_YN","COMPANY","PLANT_CD","CREATED_AT","UPDATED_AT")
VALUES (SYS_GUID(),'PRC-PACK','포장 상태 확인','포장재 손상 없고 밀봉 완전할 것','DIRECT','LAST',0,3,'Y','40','1000',SYSDATE,SYSDATE);

COMMIT;
