-- 직급(JOB_POSITION) ComCode seed 데이터
-- 작업자 마스터 직급 드롭다운용
-- JSHANES 사이트 기준: COMPANY='40', PLANT_CD='1000'

MERGE INTO "COM_CODES" t
USING (
  SELECT 'JOB_POSITION' AS "GROUP_CODE", 'EXECUTIVE'  AS "DETAIL_CODE", '임원'   AS "CODE_NAME", 1  AS "SORT_ORDER" FROM DUAL UNION ALL
  SELECT 'JOB_POSITION', 'MANAGER',     '부장',  2  FROM DUAL UNION ALL
  SELECT 'JOB_POSITION', 'ASSISTANT_MGR','차장',  3  FROM DUAL UNION ALL
  SELECT 'JOB_POSITION', 'SECTION_CHIEF','과장',  4  FROM DUAL UNION ALL
  SELECT 'JOB_POSITION', 'SENIOR',      '대리',  5  FROM DUAL UNION ALL
  SELECT 'JOB_POSITION', 'STAFF',       '사원',  6  FROM DUAL UNION ALL
  SELECT 'JOB_POSITION', 'TECHNICIAN',  '기사',  7  FROM DUAL UNION ALL
  SELECT 'JOB_POSITION', 'OPERATOR',    '작업자', 8  FROM DUAL UNION ALL
  SELECT 'JOB_POSITION', 'LEADER',      '반장',  9  FROM DUAL UNION ALL
  SELECT 'JOB_POSITION', 'INTERN',      '인턴',  10 FROM DUAL
) s ON (t."COMPANY" = '40' AND t."PLANT_CD" = '1000' AND t."GROUP_CODE" = s."GROUP_CODE" AND t."DETAIL_CODE" = s."DETAIL_CODE")
WHEN NOT MATCHED THEN INSERT (
  "COMPANY", "PLANT_CD", "GROUP_CODE", "DETAIL_CODE", "CODE_NAME", "SORT_ORDER", "USE_YN", "CREATED_AT", "UPDATED_AT"
) VALUES (
  '40', '1000', s."GROUP_CODE", s."DETAIL_CODE", s."CODE_NAME", s."SORT_ORDER", 'Y', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
)
