-- 단위(Unit) ComCode seed 데이터
-- 품목마스터 단위 드롭다운용
-- JSHANES 사이트 기준: COMPANY='40', PLANT_CD='1000'

MERGE INTO "COM_CODES" t
USING (
  SELECT 'UNIT_TYPE' AS "GROUP_CODE", 'EA'   AS "DETAIL_CODE", '개'         AS "CODE_NAME", 1  AS "SORT_ORDER" FROM DUAL UNION ALL
  SELECT 'UNIT_TYPE', 'M',        '미터',      2  FROM DUAL UNION ALL
  SELECT 'UNIT_TYPE', 'KG',       '킬로그램',  3  FROM DUAL UNION ALL
  SELECT 'UNIT_TYPE', 'SET',      '세트',      4  FROM DUAL UNION ALL
  SELECT 'UNIT_TYPE', 'ROLL',     '롤',        5  FROM DUAL UNION ALL
  SELECT 'UNIT_TYPE', 'BOX',      '박스',      6  FROM DUAL UNION ALL
  SELECT 'UNIT_TYPE', 'L',        '리터',      7  FROM DUAL UNION ALL
  SELECT 'UNIT_TYPE', 'PCS',      '피스',      8  FROM DUAL UNION ALL
  SELECT 'UNIT_TYPE', 'G',        '그램',      9  FROM DUAL UNION ALL
  SELECT 'UNIT_TYPE', 'MM',       '밀리미터',  10 FROM DUAL UNION ALL
  SELECT 'UNIT_TYPE', 'CM',       '센티미터',  11 FROM DUAL UNION ALL
  SELECT 'UNIT_TYPE', 'BAG',      '백',        12 FROM DUAL UNION ALL
  SELECT 'UNIT_TYPE', 'PAIR',     '쌍',        13 FROM DUAL
) s ON (t."COMPANY" = '40' AND t."PLANT_CD" = '1000' AND t."GROUP_CODE" = s."GROUP_CODE" AND t."DETAIL_CODE" = s."DETAIL_CODE")
WHEN NOT MATCHED THEN INSERT (
  "COMPANY", "PLANT_CD", "GROUP_CODE", "DETAIL_CODE", "CODE_NAME", "SORT_ORDER", "USE_YN", "CREATED_AT", "UPDATED_AT"
) VALUES (
  '40', '1000', s."GROUP_CODE", s."DETAIL_CODE", s."CODE_NAME", s."SORT_ORDER", 'Y', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
)
