-- ============================================================
-- EQUIP_PROTOCOLS - 장비 통신 프로토콜 설정
-- 통전검사기 등 장비별 데이터 포맷/파싱 규칙 정의
-- ============================================================
CREATE TABLE EQUIP_PROTOCOLS (
  PROTOCOL_ID     VARCHAR2(30)  NOT NULL,
  EQUIP_CODE      VARCHAR2(50),
  PROTOCOL_NAME   VARCHAR2(100) NOT NULL,
  COMM_TYPE       VARCHAR2(20)  DEFAULT 'SERIAL',
  DELIMITER       VARCHAR2(10)  DEFAULT ',',
  RESULT_INDEX    NUMBER(3)     DEFAULT 1,
  PASS_VALUE      VARCHAR2(20)  DEFAULT 'PASS',
  FAIL_VALUE      VARCHAR2(20)  DEFAULT 'FAIL',
  ERROR_INDEX     NUMBER(3),
  DATA_START_CHAR VARCHAR2(5)   DEFAULT 'STX',
  DATA_END_CHAR   VARCHAR2(5)   DEFAULT 'ETX',
  SAMPLE_DATA     VARCHAR2(500),
  DESCRIPTION     VARCHAR2(200),
  USE_YN          VARCHAR2(1)   DEFAULT 'Y',
  COMPANY         VARCHAR2(50)  DEFAULT '40',
  PLANT_CD        VARCHAR2(50)  DEFAULT '1000',
  CREATED_AT      TIMESTAMP     DEFAULT CURRENT_TIMESTAMP,
  UPDATED_AT      TIMESTAMP     DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT PK_EQUIP_PROTOCOLS PRIMARY KEY (PROTOCOL_ID)
)
