-- ============================================================
-- FG_LABELS - 완제품 바코드 라벨 마스터
-- 통전검사 합격 시 FG_BARCODE 채번 + 라벨 발행
-- ============================================================
CREATE TABLE FG_LABELS (
  FG_BARCODE        VARCHAR2(30)  NOT NULL,
  ITEM_CODE         VARCHAR2(50)  NOT NULL,
  ORDER_NO          VARCHAR2(50),
  EQUIP_CODE        VARCHAR2(50),
  WORKER_ID         VARCHAR2(50),
  LINE_CODE         VARCHAR2(50),
  ISSUED_AT         TIMESTAMP     DEFAULT CURRENT_TIMESTAMP,
  STATUS            VARCHAR2(20)  DEFAULT 'ISSUED',
  REPRINT_COUNT     NUMBER(3)     DEFAULT 0,
  VOID_REASON       VARCHAR2(200),
  REPLACED_BY       VARCHAR2(30),
  CUSTOMER_BARCODE  VARCHAR2(100),
  INSPECT_RESULT_ID NUMBER,
  COMPANY           VARCHAR2(50)  DEFAULT '40',
  PLANT_CD          VARCHAR2(50)  DEFAULT '1000',
  CREATED_BY        VARCHAR2(50),
  UPDATED_BY        VARCHAR2(50),
  CREATED_AT        TIMESTAMP     DEFAULT CURRENT_TIMESTAMP,
  UPDATED_AT        TIMESTAMP     DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT PK_FG_LABELS PRIMARY KEY (FG_BARCODE)
)
