INSERT INTO SEQ_RULES (DOC_TYPE, PREFIX, SEQ_NAME, PAD_LENGTH, DATE_FORMAT, DESCRIPTION) VALUES ('MAT_UID',     'M',  'MAT_UID_SEQ',      5, 'YYMMDD', '자재 시리얼')
/
INSERT INTO SEQ_RULES (DOC_TYPE, PREFIX, SEQ_NAME, PAD_LENGTH, DATE_FORMAT, DESCRIPTION) VALUES ('PRD_UID',     'P',  'PRD_UID_SEQ',      5, 'YYMMDD', '제품 시리얼')
/
INSERT INTO SEQ_RULES (DOC_TYPE, PREFIX, SEQ_NAME, PAD_LENGTH, DATE_FORMAT, DESCRIPTION) VALUES ('CON_UID',     'C',  'CON_UID_SEQ',      5, 'YYMMDD', '소모품 시리얼')
/
INSERT INTO SEQ_RULES (DOC_TYPE, PREFIX, SEQ_NAME, PAD_LENGTH, DATE_FORMAT, DESCRIPTION) VALUES ('FG_BARCODE',  'FG', 'SEQ_FG_BARCODE',   5, 'YYMMDD', '완제품 바코드')
/
INSERT INTO SEQ_RULES (DOC_TYPE, PREFIX, SEQ_NAME, PAD_LENGTH, DATE_FORMAT, DESCRIPTION) VALUES ('JOB_ORDER',   'WO', 'SEQ_JOB_ORDER',    4, 'YYMMDD', '작업지시')
/
INSERT INTO SEQ_RULES (DOC_TYPE, PREFIX, SEQ_NAME, PAD_LENGTH, DATE_FORMAT, DESCRIPTION) VALUES ('OQC_REQ',     'OQ', 'SEQ_OQC_REQ',      4, 'YYMMDD', 'OQC 요청')
/
INSERT INTO SEQ_RULES (DOC_TYPE, PREFIX, SEQ_NAME, PAD_LENGTH, DATE_FORMAT, DESCRIPTION) VALUES ('MAT_REQ',     'MR', 'SEQ_MAT_REQ',      4, 'YYMMDD', '자재불출요청')
/
INSERT INTO SEQ_RULES (DOC_TYPE, PREFIX, SEQ_NAME, PAD_LENGTH, DATE_FORMAT, DESCRIPTION) VALUES ('ARRIVAL',     'AR', 'SEQ_ARRIVAL',      4, 'YYMMDD', '입하번호')
/
INSERT INTO SEQ_RULES (DOC_TYPE, PREFIX, SEQ_NAME, PAD_LENGTH, DATE_FORMAT, DESCRIPTION) VALUES ('SHIPMENT',    'SH', 'SEQ_SHIPMENT',     4, 'YYMMDD', '출하번호')
/
INSERT INTO SEQ_RULES (DOC_TYPE, PREFIX, SEQ_NAME, PAD_LENGTH, DATE_FORMAT, DESCRIPTION) VALUES ('SUBCON',      'SC', 'SEQ_SUBCON',       4, 'YYMMDD', '외주발주')
/
COMMIT
/
