/**
 * @file 메뉴 코드 유효성 검증 — 프론트 menuConfig.ts의 leaf 메뉴 코드와 동기화된 화이트리스트
 * @description 운영 정책상 신규 페이지 추가 시 개발자가 이 파일과 menuConfig.ts를 동시에 수정한다.
 *              자동 동기화 없이 명시적 등록을 유지한다.
 *
 * 초보자 가이드:
 * 1. 새 페이지 추가 시: menuConfig.ts에 leaf 추가 + KNOWN_LEAF_CODES에 코드 추가 (둘 다)
 * 2. menu-category-items API는 이 화이트리스트를 통과한 코드만 받아들임
 * 3. SYS_MENU_CATEGORY는 관리 화면 자체의 메뉴 코드
 */
const KNOWN_LEAF_CODES: ReadonlySet<string> = new Set<string>([
  // 단독 메뉴 (__ROOT__ 매핑 대상)
  'DASHBOARD', 'WORKFLOW',
  // MONITORING
  'MON_EQUIP_STATUS',
  // MASTER
  'MST_PART','MST_BOM','MST_PARTNER','EQUIP_MASTER','MST_PROCESS','MST_PROD_LINE',
  'MST_ROUTING','MST_WORK_CALENDAR','MST_WORKER','MST_WORK_INST','MST_WAREHOUSE',
  'MST_LABEL','MST_VENDOR_BARCODE','MST_PROCESS_CAPA','SYS_DOCUMENT',
  // INVENTORY
  'INV_MAT_STOCK','INV_TRANSACTION','INV_MAT_PHYSICAL_INV','INV_MAT_PHYSICAL_INV_HISTORY',
  'INV_ARRIVAL_STOCK','MAT_HOLD',
  // PRODUCT_INVENTORY
  'INV_PRODUCT_STOCK','INV_PRODUCT_PHYSICAL_INV','INV_PRODUCT_PHYSICAL_INV_HISTORY','PROD_HOLD',
  // PRODUCT_MGMT
  'PROD_RECEIVE','PROD_RECEIPT_CANCEL','PROD_ISSUE','PROD_ISSUE_CANCEL',
  // MATERIAL
  'MAT_ARRIVAL','MAT_RECEIVE_LABEL','MAT_RECEIVE','MAT_RECEIVE_HISTORY','MAT_REQUEST',
  'MAT_ISSUE','MAT_LOT','MAT_LOT_SPLIT','MAT_LOT_MERGE','MAT_SHELF_LIFE','MAT_SCRAP',
  'MAT_ADJUSTMENT','MAT_MISC_RECEIPT','MAT_RECEIPT_CANCEL',
  // PURCHASING
  'PUR_PO','PUR_PO_STATUS',
  // PRODUCTION
  'PROD_MONTHLY_PLAN','PROD_SIMULATION','PROD_ORDER','PROD_RESULT','PROD_PROGRESS',
  'PROD_INPUT_MANUAL','PROD_INPUT_MACHINE','PROD_INPUT_INSPECT','PROD_INPUT_EQUIP',
  'PROD_RESULT_SUMMARY','PROD_WIP_STOCK','QC_REWORK','QC_REWORK_HISTORY','PROD_REPAIR',
  // INSPECTION
  'INSP_RESULT','INSP_HISTORY','INSP_PROTOCOL',
  // QUALITY
  'QC_IQC_ITEM','QC_IQC','QC_IQC_HISTORY','QC_DEFECT','QC_REWORK_INSPECT','QC_INSPECT',
  'QC_SAMPLE_INSPECT','QC_OQC','QC_OQC_HISTORY','QC_TRACE','QC_CHANGE','QC_COMPLAINT',
  'QC_CAPA','QC_FAI','QC_PPAP','QC_SPC','QC_CONTROL_PLAN','QC_AUDIT','SYS_TRAINING',
  // EQUIPMENT
  'EQ_MOLD_MGMT','EQUIP_INSPECT_ITEM_MASTER','EQUIP_INSPECT_ITEM','EQUIP_INSPECT_CALENDAR',
  'EQUIP_DAILY','EQUIP_PERIODIC_CALENDAR','EQUIP_PERIODIC','EQUIP_HISTORY',
  'EQUIP_PM_PLAN','EQUIP_PM_CALENDAR','EQUIP_PM_RESULT',
  // GAUGE_MGMT
  'GAUGE_MASTER','GAUGE_CALIBRATION','GAUGE_CALIBRATION_HISTORY',
  // SHIPPING
  'SHIP_PACK_RESULT','SHIP_PACK','SHIP_PALLET','SHIP_CONFIRM','SHIP_ORDER','SHIP_HISTORY','SHIP_RETURN',
  // SALES
  'SALES_CUST_PO','SALES_CUST_PO_STATUS',
  // CUSTOMS
  'CUST_ENTRY','CUST_STOCK','CUST_USAGE',
  // CONSUMABLES
  'CONS_MASTER','CONS_LABEL','CONS_RECEIVING','CONS_ISSUING','CONS_STOCK','CONS_LIFE','CONS_MOUNT',
  // OUTSOURCING
  'OUT_VENDOR','OUT_ORDER','OUT_RECEIVE',
  // INTERFACE
  'IF_DASHBOARD','IF_LOG','IF_MANUAL',
  // SYSTEM
  'SYS_COMPANY','SYS_DEPT','SYS_USER','SYS_ROLE','SYS_PDA_ROLE','SYS_COMM','SYS_CONFIG',
  'SYS_CODE','SYS_SCHEDULER','SYS_MENU_CATEGORY','SYS_IMPR_REQ',
]);

export function isValidMenuCode(code: string): boolean {
  return KNOWN_LEAF_CODES.has(code);
}

export function listKnownMenuCodes(): string[] {
  return Array.from(KNOWN_LEAF_CODES);
}
