-- ============================================================================
-- HANES MES Oracle Schema Creation Script
-- For MYDBPDB / HNSMES user
-- ============================================================================

-- ============================================================================
-- 기준정보 그룹 (Master Data)
-- ============================================================================

-- 공통코드 테이블
CREATE TABLE COM_CODES (
  ID VARCHAR2(36) PRIMARY KEY,
  GROUP_CODE VARCHAR2(50) NOT NULL,
  DETAIL_CODE VARCHAR2(50) NOT NULL,
  PARENT_CODE VARCHAR2(50),
  CODE_NAME VARCHAR2(200) NOT NULL,
  CODE_DESC VARCHAR2(500),
  SORT_ORDER NUMBER DEFAULT 0,
  USE_YN VARCHAR2(1) DEFAULT 'Y',
  ATTR1 VARCHAR2(100),
  ATTR2 VARCHAR2(100),
  ATTR3 VARCHAR2(100),
  COMPANY VARCHAR2(50),
  PLANT_CD VARCHAR2(50),
  CREATED_BY VARCHAR2(50),
  UPDATED_BY VARCHAR2(50),
  CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  UPDATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  DELETED_AT TIMESTAMP WITH TIME ZONE,
  CONSTRAINT UK_COM_CODES UNIQUE (GROUP_CODE, DETAIL_CODE)
);

CREATE INDEX IDX_COM_CODES_GROUP ON COM_CODES(GROUP_CODE);
CREATE INDEX IDX_COM_CODES_PARENT ON COM_CODES(PARENT_CODE);

-- 공장/라인 테이블
CREATE TABLE PLANTS (
  ID VARCHAR2(36) PRIMARY KEY,
  PLANT_CODE VARCHAR2(50) NOT NULL,
  SHOP_CODE VARCHAR2(50),
  LINE_CODE VARCHAR2(50),
  CELL_CODE VARCHAR2(50),
  PLANT_NAME VARCHAR2(200) NOT NULL,
  PLANT_TYPE VARCHAR2(20),
  PARENT_ID VARCHAR2(36),
  SORT_ORDER NUMBER DEFAULT 0,
  USE_YN VARCHAR2(1) DEFAULT 'Y',
  COMPANY VARCHAR2(50),
  PLANT_CD VARCHAR2(50),
  CREATED_BY VARCHAR2(50),
  UPDATED_BY VARCHAR2(50),
  CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  UPDATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  DELETED_AT TIMESTAMP WITH TIME ZONE,
  CONSTRAINT UK_PLANTS UNIQUE (PLANT_CODE, SHOP_CODE, LINE_CODE, CELL_CODE),
  CONSTRAINT FK_PLANTS_PARENT FOREIGN KEY (PARENT_ID) REFERENCES PLANTS(ID)
);

CREATE INDEX IDX_PLANTS_TYPE ON PLANTS(PLANT_TYPE);
CREATE INDEX IDX_PLANTS_PARENT ON PLANTS(PARENT_ID);

-- 회사마스터 테이블
CREATE TABLE COMPANY_MASTERS (
  ID VARCHAR2(36) PRIMARY KEY,
  COMPANY_CODE VARCHAR2(50) UNIQUE NOT NULL,
  COMPANY_NAME VARCHAR2(200) NOT NULL,
  BIZ_NO VARCHAR2(20),
  CEO_NAME VARCHAR2(100),
  ADDRESS VARCHAR2(500),
  TEL VARCHAR2(50),
  FAX VARCHAR2(50),
  EMAIL VARCHAR2(100),
  REMARK VARCHAR2(1000),
  USE_YN VARCHAR2(1) DEFAULT 'Y',
  COMPANY VARCHAR2(50),
  PLANT_CD VARCHAR2(50),
  CREATED_BY VARCHAR2(50),
  UPDATED_BY VARCHAR2(50),
  CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  UPDATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  DELETED_AT TIMESTAMP WITH TIME ZONE
);

-- 품목마스터 테이블
CREATE TABLE PART_MASTERS (
  ID VARCHAR2(36) PRIMARY KEY,
  PART_CODE VARCHAR2(100) UNIQUE NOT NULL,
  PART_NAME VARCHAR2(200) NOT NULL,
  PART_NO VARCHAR2(100),
  CUST_PART_NO VARCHAR2(100),
  PART_TYPE VARCHAR2(20) NOT NULL,
  PRODUCT_TYPE VARCHAR2(50),
  SPEC VARCHAR2(500),
  REV VARCHAR2(20),
  UNIT VARCHAR2(20) DEFAULT 'EA',
  DRAW_NO VARCHAR2(100),
  CUSTOMER VARCHAR2(100),
  VENDOR VARCHAR2(100),
  LEAD_TIME NUMBER DEFAULT 0,
  SAFETY_STOCK NUMBER DEFAULT 0,
  LOT_UNIT_QTY NUMBER,
  BOX_QTY NUMBER DEFAULT 0,
  IQC_FLAG VARCHAR2(1) DEFAULT 'Y',
  TACT_TIME NUMBER DEFAULT 0,
  EXPIRY_DATE NUMBER DEFAULT 0,
  REMARKS VARCHAR2(1000),
  USE_YN VARCHAR2(1) DEFAULT 'Y',
  COMPANY VARCHAR2(50),
  PLANT_CD VARCHAR2(50),
  CREATED_BY VARCHAR2(50),
  UPDATED_BY VARCHAR2(50),
  CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  UPDATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  DELETED_AT TIMESTAMP WITH TIME ZONE
);

CREATE INDEX IDX_PART_MASTERS_TYPE ON PART_MASTERS(PART_TYPE);
CREATE INDEX IDX_PART_MASTERS_CUSTOMER ON PART_MASTERS(CUSTOMER);

-- BOM 테이블
CREATE TABLE BOM_MASTERS (
  ID VARCHAR2(36) PRIMARY KEY,
  PARENT_PART_ID VARCHAR2(36) NOT NULL,
  CHILD_PART_ID VARCHAR2(36) NOT NULL,
  QTY_PER NUMBER(10,4) NOT NULL,
  SEQ NUMBER DEFAULT 0,
  REVISION VARCHAR2(10) DEFAULT 'A',
  BOM_GRP VARCHAR2(50),
  OPER VARCHAR2(50),
  SIDE VARCHAR2(10),
  ECO_NO VARCHAR2(50),
  VALID_FROM DATE,
  VALID_TO DATE,
  REMARK VARCHAR2(1000),
  USE_YN VARCHAR2(1) DEFAULT 'Y',
  COMPANY VARCHAR2(50),
  PLANT_CD VARCHAR2(50),
  CREATED_BY VARCHAR2(50),
  UPDATED_BY VARCHAR2(50),
  CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  UPDATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  DELETED_AT TIMESTAMP WITH TIME ZONE,
  CONSTRAINT UK_BOM_MASTERS UNIQUE (PARENT_PART_ID, CHILD_PART_ID, REVISION)
);

CREATE INDEX IDX_BOM_PARENT ON BOM_MASTERS(PARENT_PART_ID);
CREATE INDEX IDX_BOM_CHILD ON BOM_MASTERS(CHILD_PART_ID);

-- 설비마스터 테이블
CREATE TABLE EQUIP_MASTERS (
  ID VARCHAR2(36) PRIMARY KEY,
  EQUIP_CODE VARCHAR2(50) UNIQUE NOT NULL,
  EQUIP_NAME VARCHAR2(200) NOT NULL,
  EQUIP_TYPE VARCHAR2(50),
  MODEL_NAME VARCHAR2(100),
  MAKER VARCHAR2(100),
  LINE_CODE VARCHAR2(50),
  IP_ADDRESS VARCHAR2(50),
  PORT NUMBER,
  COMM_TYPE VARCHAR2(20),
  COMM_CONFIG CLOB,
  INSTALL_DATE DATE,
  STATUS VARCHAR2(20) DEFAULT 'NORMAL',
  USE_YN VARCHAR2(1) DEFAULT 'Y',
  COMPANY VARCHAR2(50),
  PLANT_CD VARCHAR2(50),
  CREATED_BY VARCHAR2(50),
  UPDATED_BY VARCHAR2(50),
  CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  UPDATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  DELETED_AT TIMESTAMP WITH TIME ZONE
);

CREATE INDEX IDX_EQUIP_TYPE ON EQUIP_MASTERS(EQUIP_TYPE);
CREATE INDEX IDX_EQUIP_LINE ON EQUIP_MASTERS(LINE_CODE);

-- 소모품마스터 테이블
CREATE TABLE CONSUMABLE_MASTERS (
  ID VARCHAR2(36) PRIMARY KEY,
  CONSUMABLE_CODE VARCHAR2(50) UNIQUE NOT NULL,
  NAME VARCHAR2(200) NOT NULL,
  CATEGORY VARCHAR2(50),
  EXPECTED_LIFE NUMBER,
  CURRENT_COUNT NUMBER DEFAULT 0,
  STOCK_QTY NUMBER DEFAULT 0,
  SAFETY_STOCK NUMBER DEFAULT 0,
  WARNING_COUNT NUMBER,
  LOCATION VARCHAR2(200),
  LAST_REPLACE TIMESTAMP WITH TIME ZONE,
  NEXT_REPLACE TIMESTAMP WITH TIME ZONE,
  UNIT_PRICE NUMBER(12,2),
  VENDOR VARCHAR2(100),
  STATUS VARCHAR2(20) DEFAULT 'NORMAL',
  USE_YN VARCHAR2(1) DEFAULT 'Y',
  COMPANY VARCHAR2(50),
  PLANT_CD VARCHAR2(50),
  CREATED_BY VARCHAR2(50),
  UPDATED_BY VARCHAR2(50),
  CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  UPDATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  DELETED_AT TIMESTAMP WITH TIME ZONE
);

CREATE INDEX IDX_CONSUMABLE_CAT ON CONSUMABLE_MASTERS(CATEGORY);

-- ============================================================================
-- 생산/공정 그룹 (Production)
-- ============================================================================

-- 작업지시 테이블
CREATE TABLE JOB_ORDERS (
  ID VARCHAR2(36) PRIMARY KEY,
  ORDER_NO VARCHAR2(50) UNIQUE NOT NULL,
  PART_ID VARCHAR2(36) NOT NULL,
  LINE_CODE VARCHAR2(50),
  PLAN_QTY NUMBER NOT NULL,
  GOOD_QTY NUMBER DEFAULT 0,
  DEFECT_QTY NUMBER DEFAULT 0,
  PLAN_DATE DATE,
  START_TIME TIMESTAMP WITH TIME ZONE,
  END_TIME TIMESTAMP WITH TIME ZONE,
  PRIORITY NUMBER DEFAULT 5,
  STATUS VARCHAR2(20) DEFAULT 'WAITING',
  REMARK VARCHAR2(1000),
  ERP_SYNC_YN VARCHAR2(1) DEFAULT 'N',
  COMPANY VARCHAR2(50),
  PLANT_CD VARCHAR2(50),
  CREATED_BY VARCHAR2(50),
  UPDATED_BY VARCHAR2(50),
  CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  UPDATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  DELETED_AT TIMESTAMP WITH TIME ZONE
);

CREATE INDEX IDX_JOB_ORDERS_STATUS ON JOB_ORDERS(STATUS);
CREATE INDEX IDX_JOB_ORDERS_PLAN_DATE ON JOB_ORDERS(PLAN_DATE);
CREATE INDEX IDX_JOB_ORDERS_LINE ON JOB_ORDERS(LINE_CODE);

-- 생산실적 테이블
CREATE TABLE PROD_RESULTS (
  ID VARCHAR2(36) PRIMARY KEY,
  JOB_ORDER_ID VARCHAR2(36) NOT NULL,
  EQUIP_ID VARCHAR2(36),
  WORKER_ID VARCHAR2(36),
  LOT_NO VARCHAR2(50),
  PROCESS_CODE VARCHAR2(50),
  GOOD_QTY NUMBER DEFAULT 0,
  DEFECT_QTY NUMBER DEFAULT 0,
  START_TIME TIMESTAMP WITH TIME ZONE,
  END_TIME TIMESTAMP WITH TIME ZONE,
  CYCLE_TIME NUMBER(10,2),
  STATUS VARCHAR2(20) DEFAULT 'RUNNING',
  REMARK VARCHAR2(1000),
  COMPANY VARCHAR2(50),
  PLANT_CD VARCHAR2(50),
  CREATED_BY VARCHAR2(50),
  UPDATED_BY VARCHAR2(50),
  CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  UPDATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  DELETED_AT TIMESTAMP WITH TIME ZONE
);

CREATE INDEX IDX_PROD_RES_JOB_ORDER ON PROD_RESULTS(JOB_ORDER_ID);
CREATE INDEX IDX_PROD_RES_EQUIP ON PROD_RESULTS(EQUIP_ID);
CREATE INDEX IDX_PROD_RES_STATUS ON PROD_RESULTS(STATUS);

-- ============================================================================
-- 자재/재고 그룹 (Material & Inventory)
-- ============================================================================

-- 창고마스터 테이블
CREATE TABLE WAREHOUSES (
  ID VARCHAR2(36) PRIMARY KEY,
  WAREHOUSE_CODE VARCHAR2(50) UNIQUE NOT NULL,
  WAREHOUSE_NAME VARCHAR2(200) NOT NULL,
  WAREHOUSE_TYPE VARCHAR2(20) NOT NULL,
  PLANT_CODE VARCHAR2(50),
  LINE_CODE VARCHAR2(50),
  PROCESS_CODE VARCHAR2(50),
  VENDOR_ID VARCHAR2(36),
  IS_DEFAULT NUMBER(1) DEFAULT 0,
  USE_YN VARCHAR2(1) DEFAULT 'Y',
  COMPANY VARCHAR2(50),
  PLANT_CD VARCHAR2(50),
  CREATED_BY VARCHAR2(50),
  UPDATED_BY VARCHAR2(50),
  CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  UPDATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  DELETED_AT TIMESTAMP WITH TIME ZONE
);

CREATE INDEX IDX_WAREHOUSE_TYPE ON WAREHOUSES(WAREHOUSE_TYPE);
CREATE INDEX IDX_WAREHOUSE_PLANT ON WAREHOUSES(PLANT_CODE);

-- LOT 테이블
CREATE TABLE LOTS (
  ID VARCHAR2(36) PRIMARY KEY,
  LOT_NO VARCHAR2(50) UNIQUE NOT NULL,
  PART_ID VARCHAR2(36) NOT NULL,
  PART_TYPE VARCHAR2(20) NOT NULL,
  INIT_QTY NUMBER NOT NULL,
  CURRENT_QTY NUMBER NOT NULL,
  RECV_DATE DATE,
  EXPIRE_DATE DATE,
  ORIGIN VARCHAR2(100),
  VENDOR VARCHAR2(100),
  INVOICE_NO VARCHAR2(100),
  PO_NO VARCHAR2(50),
  JOB_ORDER_ID VARCHAR2(36),
  PARENT_LOT_ID VARCHAR2(36),
  IQC_STATUS VARCHAR2(20) DEFAULT 'PENDING',
  STATUS VARCHAR2(20) DEFAULT 'NORMAL',
  COMPANY VARCHAR2(50),
  PLANT_CD VARCHAR2(50),
  CREATED_BY VARCHAR2(50),
  UPDATED_BY VARCHAR2(50),
  CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  UPDATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  DELETED_AT TIMESTAMP WITH TIME ZONE
);

CREATE INDEX IDX_LOTS_PART ON LOTS(PART_ID);
CREATE INDEX IDX_LOTS_TYPE ON LOTS(PART_TYPE);
CREATE INDEX IDX_LOTS_STATUS ON LOTS(STATUS);
CREATE INDEX IDX_LOTS_IQC ON LOTS(IQC_STATUS);

-- 현재고 테이블
CREATE TABLE STOCKS (
  ID VARCHAR2(36) PRIMARY KEY,
  WAREHOUSE_ID VARCHAR2(36) NOT NULL,
  PART_ID VARCHAR2(36) NOT NULL,
  LOT_ID VARCHAR2(36),
  QTY NUMBER DEFAULT 0,
  RESERVED_QTY NUMBER DEFAULT 0,
  AVAILABLE_QTY NUMBER DEFAULT 0,
  LAST_TRANS_AT TIMESTAMP WITH TIME ZONE,
  LAST_COUNT_AT TIMESTAMP WITH TIME ZONE,
  COMPANY VARCHAR2(50),
  PLANT_CD VARCHAR2(50),
  CREATED_BY VARCHAR2(50),
  UPDATED_BY VARCHAR2(50),
  CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  UPDATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT UK_STOCKS UNIQUE (WAREHOUSE_ID, PART_ID, LOT_ID)
);

CREATE INDEX IDX_STOCKS_WAREHOUSE ON STOCKS(WAREHOUSE_ID);
CREATE INDEX IDX_STOCKS_PART ON STOCKS(PART_ID);
CREATE INDEX IDX_STOCKS_LOT ON STOCKS(LOT_ID);

-- 수불이력 테이블
CREATE TABLE STOCK_TRANSACTIONS (
  ID VARCHAR2(36) PRIMARY KEY,
  TRANS_NO VARCHAR2(50) UNIQUE NOT NULL,
  TRANS_TYPE VARCHAR2(50) NOT NULL,
  TRANS_DATE TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  FROM_WAREHOUSE_ID VARCHAR2(36),
  TO_WAREHOUSE_ID VARCHAR2(36),
  PART_ID VARCHAR2(36) NOT NULL,
  LOT_ID VARCHAR2(36),
  QTY NUMBER NOT NULL,
  UNIT_PRICE NUMBER(12,4),
  TOTAL_AMOUNT NUMBER(14,2),
  REF_TYPE VARCHAR2(50),
  REF_ID VARCHAR2(36),
  CANCEL_REF_ID VARCHAR2(36),
  WORKER_ID VARCHAR2(36),
  REMARK VARCHAR2(1000),
  STATUS VARCHAR2(20) DEFAULT 'DONE',
  COMPANY VARCHAR2(50),
  PLANT_CD VARCHAR2(50),
  CREATED_BY VARCHAR2(50),
  UPDATED_BY VARCHAR2(50),
  CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IDX_TRANS_TYPE ON STOCK_TRANSACTIONS(TRANS_TYPE);
CREATE INDEX IDX_TRANS_DATE ON STOCK_TRANSACTIONS(TRANS_DATE);
CREATE INDEX IDX_TRANS_PART ON STOCK_TRANSACTIONS(PART_ID);
CREATE INDEX IDX_TRANS_LOT ON STOCK_TRANSACTIONS(LOT_ID);
CREATE INDEX IDX_TRANS_REF ON STOCK_TRANSACTIONS(REF_TYPE, REF_ID);

-- ============================================================================
-- 품질/추적 그룹 (Quality & Traceability)
-- ============================================================================

-- 검사실적 테이블
CREATE TABLE INSPECT_RESULTS (
  ID VARCHAR2(36) PRIMARY KEY,
  PROD_RESULT_ID VARCHAR2(36) NOT NULL,
  SERIAL_NO VARCHAR2(50),
  INSPECT_TYPE VARCHAR2(50),
  PASS_YN VARCHAR2(1) DEFAULT 'Y',
  ERROR_CODE VARCHAR2(50),
  ERROR_DETAIL VARCHAR2(500),
  INSPECT_DATA CLOB,
  INSPECT_TIME TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  INSPECTOR_ID VARCHAR2(36),
  COMPANY VARCHAR2(50),
  PLANT_CD VARCHAR2(50),
  CREATED_BY VARCHAR2(50),
  UPDATED_BY VARCHAR2(50),
  CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IDX_INSPECT_RES_PROD ON INSPECT_RESULTS(PROD_RESULT_ID);
CREATE INDEX IDX_INSPECT_RES_PASS ON INSPECT_RESULTS(PASS_YN);
CREATE INDEX IDX_INSPECT_RES_SERIAL ON INSPECT_RESULTS(SERIAL_NO);

-- 불량로그 테이블
CREATE TABLE DEFECT_LOGS (
  ID VARCHAR2(36) PRIMARY KEY,
  PROD_RESULT_ID VARCHAR2(36) NOT NULL,
  DEFECT_CODE VARCHAR2(50) NOT NULL,
  DEFECT_NAME VARCHAR2(200),
  QTY NUMBER DEFAULT 1,
  STATUS VARCHAR2(20) DEFAULT 'WAIT',
  CAUSE VARCHAR2(500),
  OCCUR_TIME TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  IMAGE_URL VARCHAR2(500),
  COMPANY VARCHAR2(50),
  PLANT_CD VARCHAR2(50),
  CREATED_BY VARCHAR2(50),
  UPDATED_BY VARCHAR2(50),
  CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  UPDATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  DELETED_AT TIMESTAMP WITH TIME ZONE
);

CREATE INDEX IDX_DEFECT_PROD ON DEFECT_LOGS(PROD_RESULT_ID);
CREATE INDEX IDX_DEFECT_CODE ON DEFECT_LOGS(DEFECT_CODE);
CREATE INDEX IDX_DEFECT_STATUS ON DEFECT_LOGS(STATUS);

-- ============================================================================
-- 출하/포장 그룹 (Shipping)
-- ============================================================================

-- 박스마스터 테이블
CREATE TABLE BOX_MASTERS (
  ID VARCHAR2(36) PRIMARY KEY,
  BOX_NO VARCHAR2(50) UNIQUE NOT NULL,
  PART_ID VARCHAR2(36) NOT NULL,
  QTY NUMBER NOT NULL,
  SERIAL_LIST CLOB,
  PALLET_ID VARCHAR2(36),
  STATUS VARCHAR2(20) DEFAULT 'OPEN',
  CLOSE_TIME TIMESTAMP WITH TIME ZONE,
  COMPANY VARCHAR2(50),
  PLANT_CD VARCHAR2(50),
  CREATED_BY VARCHAR2(50),
  UPDATED_BY VARCHAR2(50),
  CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  UPDATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  DELETED_AT TIMESTAMP WITH TIME ZONE
);

CREATE INDEX IDX_BOX_PART ON BOX_MASTERS(PART_ID);
CREATE INDEX IDX_BOX_PALLET ON BOX_MASTERS(PALLET_ID);
CREATE INDEX IDX_BOX_STATUS ON BOX_MASTERS(STATUS);

-- 팔레트마스터 테이블
CREATE TABLE PALLET_MASTERS (
  ID VARCHAR2(36) PRIMARY KEY,
  PALLET_NO VARCHAR2(50) UNIQUE NOT NULL,
  BOX_COUNT NUMBER DEFAULT 0,
  TOTAL_QTY NUMBER DEFAULT 0,
  STATUS VARCHAR2(20) DEFAULT 'OPEN',
  CLOSE_TIME TIMESTAMP WITH TIME ZONE,
  SHIPMENT_ID VARCHAR2(36),
  COMPANY VARCHAR2(50),
  PLANT_CD VARCHAR2(50),
  CREATED_BY VARCHAR2(50),
  UPDATED_BY VARCHAR2(50),
  CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  UPDATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  DELETED_AT TIMESTAMP WITH TIME ZONE
);

CREATE INDEX IDX_PALLET_STATUS ON PALLET_MASTERS(STATUS);
CREATE INDEX IDX_PALLET_SHIPMENT ON PALLET_MASTERS(SHIPMENT_ID);

-- 출하이력 테이블
CREATE TABLE SHIPMENT_LOGS (
  ID VARCHAR2(36) PRIMARY KEY,
  SHIP_NO VARCHAR2(50) UNIQUE NOT NULL,
  SHIP_DATE DATE,
  SHIP_TIME TIMESTAMP WITH TIME ZONE,
  VEHICLE_NO VARCHAR2(50),
  DRIVER_NAME VARCHAR2(100),
  DESTINATION VARCHAR2(500),
  CUSTOMER VARCHAR2(100),
  PALLET_COUNT NUMBER DEFAULT 0,
  BOX_COUNT NUMBER DEFAULT 0,
  TOTAL_QTY NUMBER DEFAULT 0,
  STATUS VARCHAR2(20) DEFAULT 'PREPARING',
  REMARK VARCHAR2(1000),
  ERP_SYNC_YN VARCHAR2(1) DEFAULT 'N',
  COMPANY VARCHAR2(50),
  PLANT_CD VARCHAR2(50),
  CREATED_BY VARCHAR2(50),
  UPDATED_BY VARCHAR2(50),
  CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  UPDATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  DELETED_AT TIMESTAMP WITH TIME ZONE
);

CREATE INDEX IDX_SHIP_STATUS ON SHIPMENT_LOGS(STATUS);
CREATE INDEX IDX_SHIP_DATE ON SHIPMENT_LOGS(SHIP_DATE);
CREATE INDEX IDX_SHIP_CUSTOMER ON SHIPMENT_LOGS(CUSTOMER);

-- ============================================================================
-- 시스템/인터페이스 (System & Interface)
-- ============================================================================

-- 사용자 테이블
CREATE TABLE USERS (
  ID VARCHAR2(36) PRIMARY KEY,
  EMAIL VARCHAR2(200) UNIQUE NOT NULL,
  PASSWORD VARCHAR2(200) DEFAULT 'admin123',
  NAME VARCHAR2(100),
  EMP_NO VARCHAR2(50),
  DEPT VARCHAR2(100),
  ROLE VARCHAR2(20) DEFAULT 'OPERATOR',
  STATUS VARCHAR2(20) DEFAULT 'ACTIVE',
  LAST_LOGIN TIMESTAMP WITH TIME ZONE,
  COMPANY VARCHAR2(50),
  PLANT_CD VARCHAR2(50),
  CREATED_BY VARCHAR2(50),
  UPDATED_BY VARCHAR2(50),
  CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  UPDATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  DELETED_AT TIMESTAMP WITH TIME ZONE
);

CREATE INDEX IDX_USERS_ROLE ON USERS(ROLE);
CREATE INDEX IDX_USERS_STATUS ON USERS(STATUS);

-- 사용자권한 테이블
CREATE TABLE USER_AUTHS (
  ID VARCHAR2(36) PRIMARY KEY,
  USER_ID VARCHAR2(36) NOT NULL,
  MENU_CODE VARCHAR2(50) NOT NULL,
  CAN_READ NUMBER(1) DEFAULT 1,
  CAN_WRITE NUMBER(1) DEFAULT 0,
  CAN_DELETE NUMBER(1) DEFAULT 0,
  CAN_EXPORT NUMBER(1) DEFAULT 0,
  COMPANY VARCHAR2(50),
  PLANT_CD VARCHAR2(50),
  CREATED_BY VARCHAR2(50),
  UPDATED_BY VARCHAR2(50),
  CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  UPDATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT UK_USER_AUTHS UNIQUE (USER_ID, MENU_CODE)
);

CREATE INDEX IDX_USER_AUTHS_USER ON USER_AUTHS(USER_ID);

-- 통신설정 테이블
CREATE TABLE COMM_CONFIGS (
  ID VARCHAR2(36) PRIMARY KEY,
  CONFIG_NAME VARCHAR2(200) UNIQUE NOT NULL,
  COMM_TYPE VARCHAR2(50) NOT NULL,
  DESCRIPTION VARCHAR2(500),
  HOST VARCHAR2(200),
  PORT NUMBER,
  PORT_NAME VARCHAR2(50),
  BAUD_RATE NUMBER,
  DATA_BITS NUMBER,
  STOP_BITS VARCHAR2(10),
  PARITY VARCHAR2(20),
  FLOW_CONTROL VARCHAR2(20),
  EXTRA_CONFIG CLOB,
  USE_YN VARCHAR2(1) DEFAULT 'Y',
  COMPANY VARCHAR2(50),
  PLANT_CD VARCHAR2(50),
  CREATED_BY VARCHAR2(50),
  UPDATED_BY VARCHAR2(50),
  CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  UPDATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  DELETED_AT TIMESTAMP WITH TIME ZONE
);

CREATE INDEX IDX_COMM_CONFIG_TYPE ON COMM_CONFIGS(COMM_TYPE);

-- ============================================================================
-- 시퀀스 및 트리거
-- ============================================================================

-- 시퀀스 생성
CREATE SEQUENCE TRANS_NO_SEQ START WITH 1 INCREMENT BY 1;

-- 샘플 데이터 삽입 (테스트용)
INSERT INTO USERS (ID, EMAIL, NAME, ROLE, STATUS) 
VALUES (SYS_GUID(), 'admin@hanes.com', '관리자', 'ADMIN', 'ACTIVE');

INSERT INTO COMPANY_MASTERS (ID, COMPANY_CODE, COMPANY_NAME, USE_YN)
VALUES (SYS_GUID(), 'HNS', 'HANES MES', 'Y');

INSERT INTO COM_CODES (ID, GROUP_CODE, DETAIL_CODE, CODE_NAME, SORT_ORDER)
VALUES (SYS_GUID(), 'STATUS', 'ACTIVE', '활성', 1);

COMMIT;
